!/**
 * Highcharts JS v13.0.0 (2026-06-11)
 * @module highcharts/modules/data-sorting
 * @requires highcharts
 *
 * Data sorting module
 *
 * (c) 2025-2025 Torstein Honsi
 *
 * License: www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts):"function"==typeof define&&define.amd?define("highcharts/modules/data-sorting",["highcharts/highcharts"],function(t){return e(t)}):"object"==typeof exports?exports["highcharts/modules/data-sorting"]=e(t._Highcharts):t.Highcharts=e(t.Highcharts)}("u"<typeof window?this:window,t=>(()=>{"use strict";var e={944:e=>{e.exports=t}},n={};function r(t){var i=n[t];if(void 0!==i)return i.exports;var o=n[t]={exports:{}};return e[t](o,o.exports,r),o.exports}r.n=t=>{var e=t&&t.__esModule?()=>t.default:()=>t;return r.d(e,{a:e}),e},r.d=(t,e)=>{for(var n in e)r.o(e,n)&&!r.o(t,n)&&Object.defineProperty(t,n,{enumerable:!0,get:e[n]})},r.o=(t,e)=>Object.prototype.hasOwnProperty.call(t,e);var i={};r.d(i,{default:()=>h});var o=r(944),a=r.n(o);function s(t){t.series.concat().sort((t,e)=>t.linkedSeries.length||e.linkedSeries.length?e.linkedSeries.length-t.linkedSeries.length:0).forEach(t=>{t.points||t.data||!t.enabledDataSorting||t.setData(t.options.data,!1)})}function d(t){var e;(0,o.extend)(t,{requireSorting:!1,sorted:!1,enabledDataSorting:!0,allowDG:!1}),(e=t.options).pointRange??(e.pointRange=1)}let c=a();({compose:function(t,e){(0,o.wrap)(e.prototype,"setData",function(t,e,...n){if(this.options.dataSorting?.enabled){if(!this.chart.hasInitializedLinkedSeries)return this;Array.isArray(e)&&(e=function(t,e){let{sortKey:n="y"}=t.options.dataSorting||{},r=function(t,e){return(0,o.defined)(e)&&t.pointClass.prototype.optionsToObject.call({series:t},e)||{}};return e.forEach((n,i)=>{e[i]=r(t,n),e[i].index=i}),e.concat().sort((t,e)=>{let r=(0,o.getNestedProperty)(n,t),i=(0,o.getNestedProperty)(n,e);return i<r?-1:+(i>r)}).forEach((t,e)=>{t.x=e}),t.linkedSeries&&t.linkedSeries.forEach(t=>{let n=t.options,i=n.data;!n.dataSorting?.enabled&&i&&(i.forEach((n,o)=>{i[o]=r(t,n),e[o]&&(i[o].x=e[o].x,i[o].index=o)}),t.setData(i,!1))}),e}(this,e))}return t.apply(this,[e].concat(n))}),(0,o.addEvent)(t,"beforeRender",function(){s(this)}),(0,o.addEvent)(t,"afterLinkSeries",function(){this.series.forEach(t=>{t.linkedParent?.enabledDataSorting&&d(t)}),this.hasInitializedLinkedSeries=!0}),(0,o.addEvent)(t,"afterAddSeries",function({series:t}){t.enabledDataSorting&&t.setData(t.options.data,!1)}),(0,o.addEvent)(e,"afterUpdate",function(){s(this.chart)}),(0,o.addEvent)(e,"afterInit",function(){this.options.dataSorting?.enabled&&d(this)})}}).compose(c.Chart,c.Series);let h=a();return i.default})());