/*
 Highcharts JS v11.1.0 (2023-10-19)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/draggable-points",["highcharts"],function(p){b(p);b.Highcharts=p;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function p(b,l,t,A){b.hasOwnProperty(l)||(b[l]=A.apply(null,t),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:l,module:b[l]}})))}
b=b?b._modules:{};p(b,"Extensions/DraggablePoints/DragDropUtilities.js",[b["Core/Utilities.js"]],function(b){const {addEvent:l}=b;return{addEvents:function(b,A,w,p){const t=A.map(t=>l(b,t,w,p));return function(){for(const b of t)b()}},countProps:function(b){return Object.keys(b).length},getFirstProp:function(b){for(const t in b)if(Object.hasOwnProperty.call(b,t))return b[t]},getNormalizedEvent:function(b,l){return"undefined"===typeof b.chartX||"undefined"===typeof b.chartY?l.pointer.normalize(b):
b}}});p(b,"Extensions/DraggablePoints/DragDropDefaults.js",[],function(){return{dragSensitivity:2,dragHandle:{className:"highcharts-drag-handle",color:"#fff",lineColor:"rgba(0, 0, 0, 0.6)",lineWidth:1,zIndex:901},guideBox:{"default":{className:"highcharts-drag-box-default",lineWidth:1,lineColor:"#888",color:"rgba(0, 0, 0, 0.1)",cursor:"move",zIndex:900}}}});p(b,"Extensions/DraggablePoints/DraggableChart.js",[b["Core/Animation/AnimationUtilities.js"],b["Extensions/DraggablePoints/DragDropUtilities.js"],
b["Extensions/DraggablePoints/DragDropDefaults.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,l,t,p,L){function w(a){const c=a.container;G(a)&&(D(c,["mousedown","touchstart"],c=>{{c=m(c,a);const g=a.hoverPoint;var n=H(g&&g.series.options.dragDrop,g&&g.options.dragDrop),d=n.draggableX||!1;n=n.draggableY||!1;a.cancelClick=!1;if((d||n)&&!a.zoomOrPanKeyPressed(c)&&!a.hasDraggedAnnotation)if(a.dragDropData&&a.dragDropData.isDragging)B(c,a);else{if(d=g){{d=g.series;n=d.chart;const a=d.options.dragDrop||
{},c=g.options&&g.options.dragDrop,x=d.dragDropProps;let k,e,b;for(const a in x)k=x[a],"x"===k.axis&&k.move?e=!0:"y"===k.axis&&k.move&&(b=!0);d=(a.draggableX&&e||a.draggableY&&b)&&!(c&&!1===c.draggableX&&!1===c.draggableY)&&(!(!d.yAxis||!d.xAxis)||n.mapView)}}d&&(a.mouseIsDown=!1,z(c,g),g.firePointEvent("dragStart",c))}}}),D(c,["mousemove","touchmove"],c=>{y(m(c,a),a)},{passive:!1}),v(c,"mouseleave",c=>{B(m(c,a),a)}),a.unbindDragDropMouseUp=D(q,["mouseup","touchend"],c=>{B(m(c,a),a)},{passive:!1}),
a.hasAddedDragDropEvents=!0,v(a,"destroy",()=>{a.unbindDragDropMouseUp&&a.unbindDragDropMouseUp()}))}function A(){const a=this.dragHandles||{};for(const c of Object.keys(a))a[c].destroy&&a[c].destroy();delete this.dragHandles}function C(a,d){const c=this.dragGuideBox;d=H(t.guideBox,d);a=H(d["default"],d[a]);return c.attr({"class":a.className,stroke:a.lineColor,strokeWidth:a.lineWidth,fill:a.color,cursor:a.cursor,zIndex:a.zIndex}).css({pointerEvents:"none"})}function I(a){var c=this.options.chart||
{};c=c.panKey&&c.panKey+"Key";return a[this.zooming.key&&this.zooming.key+"Key"]||a[c]}function h(a){return{left:"right",right:"left",top:"bottom",bottom:"top"}[a]}function J(a){const c=a.series,d=c.options.data||[],k=c.options.dragDrop.groupBy;let e=[];if(c.boosted)for(let a=0,k=d.length;a<k;++a)e.push((new c.pointClass).init(c,d[a])),e[e.length-1].index=a;else e=c.points;return a.options[k]?e.filter(c=>c.options[k]===a.options[k]):[a]}function K(a,d){const c=a.point;var k=c.series;const e=k.chart;
k=H(k.options.dragDrop,c.options.dragDrop);const g={},n=a.updateProp,b={},f=c.series.dragDropProps;for(const a in f){const c=f[a];if(!n||n===a&&c.resize&&(!c.optionName||!1!==k[c.optionName]))if(n||c.move&&("x"===c.axis&&k.draggableX||"y"===c.axis&&k.draggableY))e.mapView?g["x"===a?"lon":"lat"]=c:g[a]=c}for(const k of n?[c]:a.groupedPoints)b[k.id]={point:k,newValues:k.getDropValues(a.origin,d,g)};return b}function E(a,d,e){var c=d.dragDropData.origin;d=c.chartX;c=c.chartY;const b=a.chartX;a=a.chartY;
return Math.sqrt((b-d)*(b-d)+(a-c)*(a-c))>e}function z(a,d){const c=J(d);var e=d.series;const b=e.chart;var g;r(e.options.dragDrop&&e.options.dragDrop.liveRedraw,!0)||(b.dragGuideBox=g=e.getGuideBox(c),b.setGuideBoxState("default",e.options.dragDrop.guideBox).add(e.group));e=g;e={chartX:a.chartX,chartY:a.chartY,guideBox:e&&{x:e.attr("x"),y:e.attr("y"),width:e.attr("width"),height:e.attr("height")},points:{}};for(const d of c){g=d.series.dragDropProps||{};const c={};for(const e of Object.keys(g)){const b=
d.series[g[e].axis+"Axis"];c[e]=d[e];c[e+"Offset"]=d.series.chart.mapView&&d.plotX&&d.plotY?"x"===e?d.plotX:d.plotY:b.toPixels(d[e])-(b.horiz?a.chartX:a.chartY)}c.point=d;e.points[d.id]=c}a=e;b.dragDropData={origin:a,point:d,groupedPoints:c,isDragging:!0}}function G(a){let d=a.series?a.series.length:0;if(a.hasCartesianSeries&&!a.polar||a.mapView)for(;d--;){var c;if(c=a.series[d].options.dragDrop)a:{var e=void 0;c=a.series[d];const b=["draggableX","draggableY"],g=c.dragDropProps||{};for(const a of Object.keys(g))e=
g[a],e.optionName&&b.push(e.optionName);for(e=b.length;e--;)if(c.options.dragDrop[b[e]]){c=!0;break a}c=void 0}if(c)return!0}return!1}function y(a,b){if(!b.zoomOrPanKeyPressed(a)){var c=b.dragDropData;var f=0;if(c&&c.isDragging&&c.point.series){var m=c.point;f=m.series.options.dragDrop;a.preventDefault();c.draggedPastSensitivity||(c.draggedPastSensitivity=E(a,b,r(m.options.dragDrop&&m.options.dragDrop.dragSensitivity,f&&f.dragSensitivity,t.dragSensitivity)));c.draggedPastSensitivity&&(c.newPoints=
K(c,a),b=c.newPoints,f=F(b),b=1===f?e(b):null,m.firePointEvent("drag",{origin:c.origin,newPoints:c.newPoints,newPoint:b&&b.newValues,newPointId:b&&b.point.id,numNewPoints:f,chartX:a.chartX,chartY:a.chartY},function(){{var c=m.series,e=c.chart,b=e.dragDropData,f=H(c.options.dragDrop,m.options.dragDrop),n=f.draggableX,k=f.draggableY;c=b.origin;var q=b.updateProp;b=a.chartX-c.chartX;let g=a.chartY-c.chartY;var v=b;e.inverted&&(b=-g,g=-v);if(r(f.liveRedraw,!0))d(e,!1),m.showDragHandles();else if(q){{k=
b;e=g;v=m.series;q=v.chart;f=q.dragDropData;n=v.dragDropProps[f.updateProp];const a=f.newPoints[m.id].newValues,c="function"===typeof n.resizeSide?n.resizeSide(a,m):n.resizeSide;n.beforeResize&&n.beforeResize(q.dragGuideBox,a,m);{q=q.dragGuideBox;v="x"===n.axis&&v.xAxis.reversed||"y"===n.axis&&v.yAxis.reversed?h(c):c;k="x"===n.axis?k-(f.origin.prevdX||0):0;e="y"===n.axis?e-(f.origin.prevdY||0):0;let a;switch(v){case "left":a={x:q.attr("x")+k,width:Math.max(1,q.attr("width")-k)};break;case "right":a=
{width:Math.max(1,q.attr("width")+k)};break;case "top":a={y:q.attr("y")+e,height:Math.max(1,q.attr("height")-e)};break;case "bottom":a={height:Math.max(1,q.attr("height")+e)}}q.attr(a)}}}else e.dragGuideBox.translate(n?b:0,k?g:0);c.prevdX=b;c.prevdY=g}}))}}}function B(a,b){const c=b.dragDropData;if(c&&c.isDragging&&c.draggedPastSensitivity&&c.point.series){const f=c.point,m=c.newPoints,g=F(m),q=1===g?e(m):null;b.dragHandles&&b.hideDragHandles();a.preventDefault();b.cancelClick=!0;f.firePointEvent("drop",
{origin:c.origin,chartX:a.chartX,chartY:a.chartY,newPoints:m,numNewPoints:g,newPoint:q&&q.newValues,newPointId:q&&q.point.id},function(){d(b)})}delete b.dragDropData;b.dragGuideBox&&(b.dragGuideBox.destroy(),delete b.dragGuideBox)}function a(){this.hasAddedDragDropEvents||w(this)}function d(a,d){const c=a.dragDropData.newPoints;d=f(d);a.isDragDropAnimating=!0;let e;for(const a of Object.keys(c))e=c[a],e.point.update(e.newValues,!1);a.redraw(d);setTimeout(()=>{delete a.isDragDropAnimating;a.hoverPoint&&
!a.dragHandles&&a.hoverPoint.showDragHandles()},d.duration)}const {animObject:f}=b,{addEvents:D,countProps:F,getFirstProp:e,getNormalizedEvent:m}=l,{doc:q}=p,{addEvent:v,merge:H,pick:r,pushUnique:O}=L,u=[];return{compose:function(c){if(O(u,c)){const d=c.prototype;d.hideDragHandles=A;d.setGuideBoxState=C;d.zoomOrPanKeyPressed=I;v(c,"render",a)}},flipResizeSide:h,initDragDrop:z}});p(b,"Extensions/DraggablePoints/DragDropProps.js",[b["Extensions/DraggablePoints/DraggableChart.js"],b["Core/Utilities.js"]],
function(b,l){function t(a){a=a.graphic?a.graphic.getBBox().width/2+1:4;return[["M",0-a,0],["a",a,a,0,1,0,2*a,0],["a",a,a,0,1,0,-2*a,0]]}function p(a){a=a.shapeArgs||a.graphic.getBBox();const d=a.r||0,b=a.height/2;return[["M",0,d],["L",0,b-5],["A",1,1,0,0,0,0,b+5],["A",1,1,0,0,0,0,b-5],["M",0,b+5],["L",0,a.height-d]]}function w(a,d){var b=a.series;const h=b.xAxis,l=b.yAxis,e=b.chart.inverted;b=b.columnMetrics?b.columnMetrics.offset:-a.shapeArgs.height/2;d=h.toPixels(a[d],!0);a=l.toPixels(a.y,!0);
e&&(d=h.len-d,a=l.len-a);return{x:Math.round(d),y:Math.round(a+b)}}const {flipResizeSide:M}=b,{isNumber:N,merge:C,pick:I}=l;b={x:{axis:"x",move:!0},y:{axis:"y",move:!0}};const h={x:{axis:"x",move:!0},y:{axis:"y",move:!1,resize:!0,beforeResize:(a,d,b)=>{const f=I(b.yBottom,b.series.translatedThreshold),h=a.attr("y"),e=N(b.stackY)?b.stackY-(b.y||0):b.series.options.threshold||0;d=e+d.y;(b.series.yAxis.reversed?d<e:d>=e)?(b=a.attr("height"),a.attr({height:Math.max(0,Math.round(b+(f?f-h-b:0)))})):a.attr({y:Math.round(h+
(f?f-h:0))})},resizeSide:(a,b)=>{const d=b.series.chart.dragHandles;a=a.y>=(b.series.options.threshold||0)?"top":"bottom";b=M(a);d&&d[b]&&(d[b].destroy(),delete d[b]);return a},handlePositioner:a=>{const b=a.shapeArgs||a.graphic&&a.graphic.getBBox()||{},f=a.series.yAxis.reversed,h=a.series.options.threshold||0;a=a.y||0;return{x:b.x||0,y:!f&&a>=h||f&&a<h?b.y||0:(b.y||0)+(b.height||0)}},handleFormatter:a=>{var b=a.shapeArgs||{};a=b.r||0;b=b.width||0;const f=b/2;return[["M",a,0],["L",f-5,0],["A",1,1,
0,0,0,f+5,0],["A",1,1,0,0,0,f-5,0],["M",f+5,0],["L",b-a,0]]}}};l={x:h.x,low:{optionName:"draggableLow",axis:"y",move:!0,resize:!0,resizeSide:"bottom",handlePositioner:a=>({x:a.shapeArgs.x||0,y:a.lowPlot}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.q1},q1:{optionName:"draggableQ1",axis:"y",move:!0,resize:!0,resizeSide:"bottom",handlePositioner:a=>({x:a.shapeArgs.x||0,y:a.q1Plot}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.median&&a>=b.low},median:{axis:"y",move:!0},
q3:{optionName:"draggableQ3",axis:"y",move:!0,resize:!0,resizeSide:"top",handlePositioner:a=>({x:a.shapeArgs.x||0,y:a.q3Plot}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.high&&a>=b.median},high:{optionName:"draggableHigh",axis:"y",move:!0,resize:!0,resizeSide:"top",handlePositioner:a=>({x:a.shapeArgs.x||0,y:a.highPlot}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a>=b.q3}};const J={x:h.x,y:h.y,target:{optionName:"draggableTarget",axis:"y",move:!0,resize:!0,resizeSide:"top",
handlePositioner:a=>{const b=a.targetGraphic.getBBox();return{x:a.barX,y:b.y+b.height/2}},handleFormatter:h.y.handleFormatter}},K={x:h.x,low:{optionName:"draggableLow",axis:"y",move:!0,resize:!0,resizeSide:"bottom",handlePositioner:a=>({x:a.shapeArgs.x,y:a.plotLow}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.open&&a<=b.close},high:{optionName:"draggableHigh",axis:"y",move:!0,resize:!0,resizeSide:"top",handlePositioner:a=>({x:a.shapeArgs.x,y:a.plotHigh}),handleFormatter:h.y.handleFormatter,
propValidate:(a,b)=>a>=b.open&&a>=b.close},open:{optionName:"draggableOpen",axis:"y",move:!0,resize:!0,resizeSide:a=>a.open>=a.close?"top":"bottom",handlePositioner:a=>({x:a.shapeArgs.x,y:a.plotOpen}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.high&&a>=b.low},close:{optionName:"draggableClose",axis:"y",move:!0,resize:!0,resizeSide:a=>a.open>=a.close?"bottom":"top",handlePositioner:a=>({x:a.shapeArgs.x,y:a.plotClose}),handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.high&&
a>=b.low}},E={x:h.x,y:C(h.y,{handleFormatter:a=>a.isSum||a.isIntermediateSum?null:h.y.handleFormatter(a)})},z={x:{axis:"x",move:!0},low:{optionName:"draggableLow",axis:"y",move:!0,resize:!0,resizeSide:"bottom",handlePositioner:a=>{a=a.shapeArgs||a.graphic.getBBox();return{x:a.x||0,y:(a.y||0)+(a.height||0)}},handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a<=b.high},high:{optionName:"draggableHigh",axis:"y",move:!0,resize:!0,resizeSide:"top",handlePositioner:a=>{a=a.shapeArgs||a.graphic.getBBox();
return{x:a.x||0,y:a.y||0}},handleFormatter:h.y.handleFormatter,propValidate:(a,b)=>a>=b.low}},G={x:z.x,low:{optionName:"draggableLow",axis:"y",move:!0,resize:!0,resizeSide:"bottom",handlePositioner:a=>(a=a.graphics&&a.graphics[0]&&a.graphics[0].getBBox())?{x:a.x+a.width/2,y:a.y+a.height/2}:{x:-999,y:-999},handleFormatter:t,propValidate:z.low.propValidate},high:{optionName:"draggableHigh",axis:"y",move:!0,resize:!0,resizeSide:"top",handlePositioner:a=>(a=a.graphics&&a.graphics[1]&&a.graphics[1].getBBox())?
{x:a.x+a.width/2,y:a.y+a.height/2}:{x:-999,y:-999},handleFormatter:t,propValidate:z.high.propValidate}},y={y:{axis:"y",move:!0},x:{optionName:"draggableX1",axis:"x",move:!0,resize:!0,resizeSide:"left",handlePositioner:a=>w(a,"x"),handleFormatter:p,propValidate:(a,b)=>a<=b.x2},x2:{optionName:"draggableX2",axis:"x",move:!0,resize:!0,resizeSide:"right",handlePositioner:a=>w(a,"x2"),handleFormatter:p,propValidate:(a,b)=>a>=b.x}},B={y:y.y,start:C(y.x,{optionName:"draggableStart",validateIndividualDrag:a=>
!a.milestone}),end:C(y.x2,{optionName:"draggableEnd",validateIndividualDrag:a=>!a.milestone})};return{arearange:G,boxplot:l,bullet:J,column:h,columnrange:z,flags:b,gantt:B,line:b,ohlc:K,waterfall:E,xrange:y}});p(b,"Extensions/DraggablePoints/DraggablePoints.js",[b["Extensions/DraggablePoints/DragDropUtilities.js"],b["Extensions/DraggablePoints/DraggableChart.js"],b["Extensions/DraggablePoints/DragDropDefaults.js"],b["Extensions/DraggablePoints/DragDropProps.js"],b["Core/Utilities.js"]],function(b,
l,p,A,L){function t(a){const b=a.series&&a.series.chart,e=b&&b.dragDropData;!b||!b.dragHandles||e&&(e.isDragging&&e.draggedPastSensitivity||e.isHoveringHandle===a.id)||b.hideDragHandles()}function w(){const a=this;setTimeout(()=>{a.series&&t(a)},10)}function C(){const a=this;setTimeout(()=>{{const b=a.series,e=b&&b.chart,d=e&&e.dragDropData,f=e&&e.is3d&&e.is3d();!e||d&&d.isDragging&&d.draggedPastSensitivity||e.isDragDropAnimating||!b.options.dragDrop||f||(e.dragHandles&&e.hideDragHandles(),a.showDragHandles())}},
12)}function I(){const a=this.series.chart,b=a.dragHandles;b&&b.point===this.id&&a.hideDragHandles()}function h(b,m,q){const e=this.series,h=e.chart,r=h.mapView,l=d(e.options.dragDrop,this.options.dragDrop),u={};b=b.points[this.id];const c=1===Object.keys(q).length,n=(a,b)=>{var c=e[b.toLowerCase()+"Axis"].categories?1:0;c=f(l["dragPrecision"+b],c);const d=f(l["dragMin"+b],-Infinity);b=f(l["dragMax"+b],Infinity);c&&(a=Math.round(a/c)*c);return B(a,d,b)},p=(a,b,c)=>{if(r){const g=f(l["dragPrecision"+
b],0);var e=r.pixelsToLonLat({x:0,y:0}),d=r.pixelsToLonLat({x:h.plotBox.width,y:h.plotBox.height});e=f(l["dragMin"+b],e&&e[c],-Infinity);b=f(l["dragMax"+b],d&&d[c],Infinity);d=a[c];if("Orthographic"===r.projection.options.name)return d;if("lat"===c){if(isNaN(e)||e>r.projection.maxLatitude)e=r.projection.maxLatitude;if(isNaN(b)||b<-1*r.projection.maxLatitude)b=-1*r.projection.maxLatitude;const a=b;b=e;e=a}r.projection.hasCoordinates||(a=r.pixelsToLonLat({x:a.chartX-h.plotLeft,y:h.plotHeight-a.chartY+
h.plotTop}))&&(d=a[c]);g&&(d=Math.round(d/g)*g);return B(d,e,b)}};for(const d of Object.keys(q)){const g=q[d],f=b.point[d];var k=e[g.axis+"Axis"];k=r?p(m,g.axis.toUpperCase(),d):n(k.toValue((k.horiz?m.chartX:m.chartY)+b[d+"Offset"]),g.axis.toUpperCase());!a(k)||c&&g.propValidate&&!g.propValidate(k,this)||"undefined"===typeof f||(u[d]=k)}return u}function J(){const a=this,b=a.series,f=b.chart,{inverted:h,renderer:l}=f,r=d(b.options.dragDrop,a.options.dragDrop),w=b.dragDropProps||{};let u=f.dragHandles;
for(const e of Object.keys(w)){const g=w[e];var c=d(p.dragHandle,g.handleOptions,r.dragHandle);const m={"class":c.className,"stroke-width":c.lineWidth,fill:c.color,stroke:c.lineColor};var n=c.pathFormatter||g.handleFormatter,x=g.handlePositioner,k=g.validateIndividualDrag?g.validateIndividualDrag(a):!0;if(g.resize&&k&&g.resizeSide&&n&&(r["draggable"+g.axis.toUpperCase()]||r[g.optionName])&&!1!==r[g.optionName]){u?u.point=a.id:u=f.dragHandles={group:l.g("drag-drop-handles").add(b.markerGroup||b.group),
point:a.id};x=x(a);m.d=n=n(a);k=a.series.xAxis.categories?-.5:0;if(!n||x.x<k||0>x.y)break;m.cursor=c.cursor||("x"===g.axis!==!!h?"ew-resize":"ns-resize");(c=u[g.optionName])||(c=u[g.optionName]=l.path().add(u.group));m.translateX=h?b.yAxis.len-x.y:x.x;m.translateY=h?b.xAxis.len-x.x:x.y;h&&(m.rotation=-90);c.attr(m);E(c.element,["touchstart","mousedown"],b=>{{b=z(b,f);var c=e;const d=a.series.chart;d.zoomOrPanKeyPressed(b)||(d.mouseIsDown=!1,G(b,a),d.dragDropData.updateProp=b.updateProp=c,a.firePointEvent("dragStart",
b),b.stopPropagation(),b.preventDefault())}},{passive:!1});y(u.group.element,"mouseover",()=>{f.dragDropData=f.dragDropData||{};f.dragDropData.isHoveringHandle=a.id});E(u.group.element,["touchend","mouseout"],()=>{{const b=a.series.chart;b.dragDropData&&a.id===b.dragDropData.isHoveringHandle&&delete b.dragDropData.isHoveringHandle;b.hoverPoint||t(a)}})}}}function K(b){const d=this.chart;let e=Infinity,f=-Infinity,h=Infinity,l=-Infinity;for(const d of b)if(b=d.graphic&&d.graphic.getBBox()||d.shapeArgs){let c;
var p=d.x2;a(p)&&(c=d.series.xAxis.translate(p,!1,!1,!1,!0));const m=!(b.width||b.height||b.x||b.y);p=!0;e=Math.min(d.plotX||0,c||0,m?Infinity:b.x||0,e);f=Math.max(d.plotX||0,c||0,(b.x||0)+(b.width||0),f);h=Math.min(d.plotY||0,m?Infinity:b.y||0,h);l=Math.max((b.y||0)+(b.height||0),l)}return p?d.renderer.rect(e,h,f-e,l-h):d.renderer.g()}const {addEvents:E,getNormalizedEvent:z}=b,{initDragDrop:G}=l,{addEvent:y,clamp:B,isNumber:a,merge:d,pick:f,pushUnique:D}=L,F=[];"";return{compose:function(a,b){const d=
b.prototype.pointClass,e=b.types;l.compose(a);D(F,d)&&(a=d.prototype,a.getDropValues=h,a.showDragHandles=J,y(d,"mouseOut",w),y(d,"mouseOver",C),y(d,"remove",I));D(F,b)&&(b=b.prototype,b.dragDropProps=A.line,b.getGuideBox=K);b="arearange boxplot bullet column columnrange flags gantt ohlc waterfall xrange".split(" ");for(var f of b)e[f]&&D(F,e[f])&&(e[f].prototype.dragDropProps=A[f]);f="bellcurve gauge histogram map mapline pareto pie sankey sma sunburst treemap vector windbarb wordcloud".split(" ");
for(const a of f)e[a]&&(e[a].prototype.dragDropProps=null)}}});p(b,"masters/modules/draggable-points.src.js",[b["Core/Globals.js"],b["Extensions/DraggablePoints/DraggablePoints.js"]],function(b,l){l.compose(b.Chart,b.Series)})});
//# sourceMappingURL=draggable-points.js.map