/*
 Highcharts JS v11.1.0 (2023-09-22)

 Exporting module

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';var g=g||{};g.scope={};g.ASSUME_ES5=!1;g.ASSUME_NO_NATIVE_MAP=!1;g.ASSUME_NO_NATIVE_SET=!1;g.SIMPLE_FROUND_POLYFILL=!1;g.ISOLATE_POLYFILLS=!1;g.defineProperty=g.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};
g.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};g.global=g.getGlobal(this);g.polyfills={};g.propertyToPolyfillSymbol={};g.POLYFILL_PREFIX="$jscp$";g.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
g.polyfill=function(a,c,d,b){c&&(g.ISOLATE_POLYFILLS?g.polyfillIsolated(a,c,d,b):g.polyfillUnisolated(a,c,d,b))};g.polyfillUnisolated=function(a,c){var d=g.global;a=a.split(".");for(var b=0;b<a.length-1;b++){var h=a[b];h in d||(d[h]={});d=d[h]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&g.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
g.polyfillIsolated=function(a,c,d){var b=a.split(".");a=1===b.length;var h=b[0];h=!a&&h in g.polyfills?g.polyfills:g.global;for(var x=0;x<b.length-1;x++){var m=b[x];m in h||(h[m]={});h=h[m]}b=b[b.length-1];d=g.IS_SYMBOL_NATIVE&&"es6"===d?h[b]:null;c=c(d);null!=c&&(a?g.defineProperty(g.polyfills,b,{configurable:!0,writable:!0,value:c}):c!==d&&(g.propertyToPolyfillSymbol[b]=g.IS_SYMBOL_NATIVE?g.global.Symbol(b):g.POLYFILL_PREFIX+b,b=g.propertyToPolyfillSymbol[b],g.defineProperty(h,b,{configurable:!0,
writable:!0,value:c})))};g.polyfill("Array.prototype.includes",function(a){return a?a:function(a,d){var b=this;b instanceof String&&(b=String(b));var h=b.length;d=d||0;for(0>d&&(d=Math.max(d+h,0));d<h;d++){var c=b[d];if(c===a||Object.is(c,a))return!0}return!1}},"es7","es3");
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/export-data",["highcharts","highcharts/modules/exporting"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,b,h,c){a.hasOwnProperty(b)||(a[b]=c.apply(null,h),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:b,module:a[b]}})))}
a=a?a._modules:{};c(a,"Extensions/ExportData/ExportDataDefaults.js",[],function(){"";return{exporting:{csv:{annotations:{itemDelimiter:"; ",join:!1},columnHeaderFormatter:null,dateFormat:"%Y-%m-%d %H:%M:%S",decimalPoint:null,itemDelimiter:null,lineDelimiter:"\n"},showTable:!1,useMultiLevelHeaders:!0,useRowspanHeaders:!0},lang:{downloadCSV:"Download CSV",downloadXLS:"Download XLS",exportData:{annotationHeader:"Annotations",categoryHeader:"Category",categoryDatetimeHeader:"DateTime"},viewData:"View data table",
hideData:"Hide data table"}}});c(a,"Extensions/DownloadURL.js",[a["Core/Globals.js"]],function(a){const {isSafari:b}=a,c=a.win,d=c.document,m=c.URL||c.webkitURL||c,F=a.dataURLtoBlob=function(a){if((a=a.replace(/filename=.*;/,"").match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/))&&3<a.length&&c.atob&&c.ArrayBuffer&&c.Uint8Array&&c.Blob&&m.createObjectURL){const d=c.atob(a[3]);var b=new c.ArrayBuffer(d.length);b=new c.Uint8Array(b);for(let a=0;a<b.length;++a)b[a]=d.charCodeAt(a);a=new c.Blob([b],{type:a[1]});
return m.createObjectURL(a)}};a=a.downloadURL=function(a,h){var f=c.navigator;const m=d.createElement("a");if("string"===typeof a||a instanceof String||!f.msSaveOrOpenBlob){a=`${a}`;f=/Edge\/\d+/.test(f.userAgent);if(b&&"string"===typeof a&&0===a.indexOf("data:application/pdf")||f||2E6<a.length)if(a=F(a)||"",!a)throw Error("Failed to convert to blob");if("undefined"!==typeof m.download)m.href=a,m.download=h,d.body.appendChild(m),m.click(),d.body.removeChild(m);else try{const b=c.open(a,"chart");if("undefined"===
typeof b||null===b)throw Error("Failed to open window");}catch(Q){c.location.href=a}}else f.msSaveOrOpenBlob(a,h)};return{dataURLtoBlob:F,downloadURL:a}});c(a,"Extensions/ExportData/ExportData.js",[a["Core/Renderer/HTML/AST.js"],a["Extensions/ExportData/ExportDataDefaults.js"],a["Core/Globals.js"],a["Core/Defaults.js"],a["Extensions/DownloadURL.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,c,h,x,m,F,f){function b(){const a=this.getCSV(!0);R(S(a,"text/csv")||"data:text/csv,\ufeff"+
encodeURIComponent(a),this.getFilename()+".csv")}function d(){const a='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head>\x3c!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Ark1</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--\x3e<style>td{border:none;font-family: Calibri, sans-serif;} .number{mso-number-format:"0.00";} .text{ mso-number-format:"@";}</style><meta name=ProgId content=Excel.Sheet><meta charset=UTF-8></head><body>'+
this.getTable(!0)+"</body></html>";R(S(a,"application/vnd.ms-excel")||"data:application/vnd.ms-excel;base64,"+t.btoa(unescape(encodeURIComponent(a))),this.getFilename()+".xls")}function X(a){let e="";const c=this.getDataRows(),b=this.options.exporting.csv,d=y(b.decimalPoint,","!==b.itemDelimiter&&a?(1.1).toLocaleString()[1]:"."),B=y(b.itemDelimiter,","===d?";":","),h=b.lineDelimiter;c.forEach((a,b)=>{let n,r=a.length;for(;r--;)n=a[r],"string"===typeof n&&(n='"'+n+'"'),"number"===typeof n&&"."!==d&&
(n=n.toString().replace(".",d)),a[r]=n;a.length=c.length?c[0].length:0;e+=a.join(B);b<c.length-1&&(e+=h)});return e}function Q(a){function c(a,b){const e=a.pointArrayMap||["y"];return a.data.some(a=>"undefined"!==typeof a.y&&a.name)&&b&&!b.categories&&"name"!==a.exportKey?["x",...e]:e}function b(a,b,e){const c={},d={};b.forEach(function(b){var k=(a.keyToAxis&&a.keyToAxis[b]||b)+"Axis";k=Y(e)?a.chart[k][e]:a[k];c[b]=k&&k.categories||[];d[b]=k&&k.dateTime});return{categoryMap:c,dateTimeValueAxisMap:d}}
function e(b,e,c){if(h.columnHeaderFormatter){const a=h.columnHeaderFormatter(b,e,c);if(!1!==a)return a}return b?b instanceof Z?a?{columnTitle:1<c?e:b.name,topLevelColumnTitle:b.name}:b.name+(1<c?" ("+e+")":""):b.options.title&&b.options.title.text||(b.dateTime?C:T):T}const d=this.hasParallelCoordinates,B=this.time,h=this.options.exporting&&this.options.exporting.csv||{},m=this.xAxis,p={},f=[],z=[],u=[];var v=this.options.lang.exportData;const T=v.categoryHeader,C=v.categoryDatetimeHeader,D=[];let l,
E,A=0;this.series.forEach(function(k){const n=k.xAxis,r=k.options.keys||c(k,n),v=r.length,l=!k.requireSorting&&{},J=m.indexOf(n);let I=b(k,r),C,f;if(!1!==k.options.includeInDataExport&&!k.options.isInternal&&!1!==k.visible){aa(D,function(a){return a[0]===J})||D.push([J,A]);for(f=0;f<v;)E=e(k,r[f],r.length),u.push(E.columnTitle||E),a&&z.push(E.topLevelColumnTitle||E),f++;C={chart:k.chart,autoIncrement:k.autoIncrement,options:k.options,pointArrayMap:k.pointArrayMap,index:k.index};const c=C.index;k.options.data.forEach(function(a,
e){var u;const z={series:C};let q;d&&(I=b(k,r,e));k.pointClass.prototype.applyOptions.apply(z,[a]);a=k.data[e]&&k.data[e].name;q=(null!==(u=z.x)&&void 0!==u?u:"")+","+a;K(p[q])&&p[q].seriesIndices.includes(c)&&(u=Object.keys(p).filter(a=>p[a].seriesIndices.includes(c)&&q).filter(a=>0===a.indexOf(String(q))),q=q+","+u.length);f=0;if(!n||"name"===k.exportKey||!d&&n&&n.hasNames&&a)q=a;l&&(l[q]&&(q+="|"+e),l[q]=!0);p[q]||(p[q]=[],p[q].xValues=[]);p[q].x=z.x;p[q].name=a;p[q].xValues[J]=z.x;K(p[q].seriesIndices)||
(p[q].seriesIndices=[]);for(p[q].seriesIndices=[...p[q].seriesIndices,c];f<v;)e=r[f],u=z[e],p[q][A+f]=y(I.categoryMap[e][u],I.dateTimeValueAxisMap[e]?B.dateFormat(h.dateFormat,u):null,u),f++});A+=f}});for(x in p)Object.hasOwnProperty.call(p,x)&&f.push(p[x]);let t,w;v=a?[z,u]:[u];for(A=D.length;A--;){t=D[A][0];w=D[A][1];l=m[t];f.sort(function(a,b){return a.xValues[t]-b.xValues[t]});var x=e(l);v[0].splice(w,0,x);a&&v[1]&&v[1].splice(w,0,x);f.forEach(function(a){let b=a.name;l&&!K(b)&&(l.dateTime?(a.x instanceof
Date&&(a.x=a.x.getTime()),b=B.dateFormat(h.dateFormat,a.x)):b=l.categories?y(l.names[a.x],l.categories[a.x],a.x):a.x);a.splice(w,0,b)})}v=v.concat(f);G(this,"exportData",{dataRows:v});return v}function ba(a){const b=a=>{if(!a.tagName||"#text"===a.tagName)return a.textContent||"";const e=a.attributes;let c=`<${a.tagName}`;e&&Object.keys(e).forEach(a=>{c+=` ${a}="${e[a]}"`});c+=">";c+=a.textContent||"";(a.children||[]).forEach(a=>{c+=b(a)});return c+=`</${a.tagName}>`};a=this.getTableAST(a);return b(a)}
function ca(a){function b(a,b,c,e){let d=y(e,"");b="highcharts-text"+(b?" "+b:"");"number"===typeof d?(d=d.toString(),","===f&&(d=d.replace(".",f)),b="highcharts-number"):e||(b="highcharts-empty");c=U({"class":b},c);return{tagName:a,attributes:c,textContent:d}}let c=0;var e=[];const d=this.options,f=a?(1.1).toLocaleString()[1]:".",h=y(d.exporting.useMultiLevelHeaders,!0);a=this.getDataRows(h);const m=h?a.shift():null,p=a.shift();!1!==d.exporting.tableCaption&&e.push({tagName:"caption",attributes:{"class":"highcharts-table-caption"},
textContent:y(d.exporting.tableCaption,d.title.text?d.title.text:"Chart")});for(let b=0,e=a.length;b<e;++b)a[b].length>c&&(c=a[b].length);e.push(function(a,c,e){const f=[];let n=0;e=e||c&&c.length;let p=0;var l;if(l=h&&a&&c){a:if(l=a.length,c.length===l){for(;l--;)if(a[l]!==c[l]){l=!1;break a}l=!0}else l=!1;l=!l}if(l){for(l=[];n<e;++n){var r=a[n];var m=a[n+1];r===m?++p:p?(l.push(b("th","highcharts-table-topheading",{scope:"col",colspan:p+1},r)),p=0):(r===c[n]?d.exporting.useRowspanHeaders?(m=2,delete c[n]):
(m=1,c[n]=""):m=1,r=b("th","highcharts-table-topheading",{scope:"col"},r),1<m&&r.attributes&&(r.attributes.valign="top",r.attributes.rowspan=m),l.push(r))}f.push({tagName:"tr",children:l})}if(c){a=[];n=0;for(e=c.length;n<e;++n)"undefined"!==typeof c[n]&&a.push(b("th",null,{scope:"col"},c[n]));f.push({tagName:"tr",children:a})}return{tagName:"thead",children:f}}(m,p,Math.max(c,p.length)));const t=[];a.forEach(function(a){const e=[];for(let d=0;d<c;d++)e.push(b(d?"td":"th",null,d?{}:{scope:"row"},a[d]));
t.push({tagName:"tr",children:e})});e.push({tagName:"tbody",children:t});e={tree:{tagName:"table",id:`highcharts-data-table-${this.index}`,children:e}};G(this,"aftergetTableAST",e);return e.tree}function da(){this.toggleDataTable(!1)}function ea(b){var c=(b=y(b,!this.isDataTableVisible))&&!this.dataTableDiv;c&&(this.dataTableDiv=fa.createElement("div"),this.dataTableDiv.className="highcharts-data-table",this.renderTo.parentNode.insertBefore(this.dataTableDiv,this.renderTo.nextSibling));if(this.dataTableDiv){var e=
this.dataTableDiv.style,d=e.display;e.display=b?"block":"none";b?(this.dataTableDiv.innerHTML=a.emptyHTML,(new a([this.getTableAST()])).addToDOM(this.dataTableDiv),G(this,"afterViewData",{element:this.dataTableDiv,wasHidden:c||d!==e.display})):G(this,"afterHideData")}this.isDataTableVisible=b;c=this.exportDivElements;d=(e=this.options.exporting)&&e.buttons&&e.buttons.contextButton.menuItems;b=this.options.lang;e&&e.menuItemDefinitions&&b&&b.viewData&&b.hideData&&d&&c&&(c=c[d.indexOf("viewData")])&&
a.setElementHTML(c,this.isDataTableVisible?b.hideData:b.viewData)}function ha(){this.toggleDataTable(!0)}function S(a,b){const c=t.navigator,e=-1<c.userAgent.indexOf("WebKit")&&0>c.userAgent.indexOf("Chrome"),d=t.URL||t.webkitURL||t;try{if(c.msSaveOrOpenBlob&&t.MSBlobBuilder){const b=new t.MSBlobBuilder;b.append(a);return b.getBlob("image/svg+xml")}if(!e)return d.createObjectURL(new t.Blob(["\ufeff"+a],{type:b}))}catch(B){}}function ia(){const a=this,b=a.dataTableDiv,c=(a,b)=>(c,e)=>{var d=(b?c:e).children[a].textContent;
c=(b?e:c).children[a].textContent;return""===d||""===c||isNaN(d)||isNaN(c)?d.toString().localeCompare(c):d-c};if(b&&a.options.exporting&&a.options.exporting.allowTableSorting){const e=b.querySelector("thead tr");e&&e.childNodes.forEach(e=>{const d=e.closest("table");e.addEventListener("click",function(){const f=[...b.querySelectorAll("tr:not(thead tr)")],h=[...e.parentNode.children];f.sort(c(h.indexOf(e),a.ascendingOrderInTable=!a.ascendingOrderInTable)).forEach(a=>{d.appendChild(a)});h.forEach(a=>
{["highcharts-sort-ascending","highcharts-sort-descending"].forEach(b=>{a.classList.contains(b)&&a.classList.remove(b)})});e.classList.add(a.ascendingOrderInTable?"highcharts-sort-ascending":"highcharts-sort-descending")})})}}function ja(){this.options&&this.options.exporting&&this.options.exporting.showTable&&!this.options.chart.forExport&&this.viewData()}const {doc:fa,win:t}=h,{getOptions:ka,setOptions:V}=x,{downloadURL:R}=m,{series:Z,seriesTypes:{arearange:L,gantt:H,map:M,mapbubble:N,treemap:O,
xrange:P}}=F,{addEvent:W,defined:K,extend:U,find:aa,fireEvent:G,isNumber:Y,pick:y}=f,w=[];"";return{compose:function(a){f.pushUnique(w,a)&&(W(a,"afterViewData",ia),W(a,"render",ja),a=a.prototype,a.downloadCSV=b,a.downloadXLS=d,a.getCSV=X,a.getDataRows=Q,a.getTable=ba,a.getTableAST=ca,a.hideData=da,a.toggleDataTable=ea,a.viewData=ha);if(f.pushUnique(w,V)){if(a=ka().exporting)U(a.menuItemDefinitions,{downloadCSV:{textKey:"downloadCSV",onclick:function(){this.downloadCSV()}},downloadXLS:{textKey:"downloadXLS",
onclick:function(){this.downloadXLS()}},viewData:{textKey:"viewData",onclick:function(){this.toggleDataTable()}}}),a.buttons&&a.buttons.contextButton.menuItems&&a.buttons.contextButton.menuItems.push("separator","downloadCSV","downloadXLS","viewData");V(c)}L&&f.pushUnique(w,L)&&(L.prototype.keyToAxis={low:"y",high:"y"});H&&f.pushUnique(w,H)&&(H.prototype.exportKey="name",H.prototype.keyToAxis={start:"x",end:"x"});P&&f.pushUnique(w,P)&&(P.prototype.keyToAxis={x2:"x"});M&&f.pushUnique(w,M)&&(M.prototype.exportKey=
"name");N&&f.pushUnique(w,N)&&(N.prototype.exportKey="name");O&&f.pushUnique(w,O)&&(O.prototype.exportKey="name")}}});c(a,"masters/modules/export-data.src.js",[a["Core/Globals.js"],a["Extensions/ExportData/ExportData.js"]],function(a,b){b.compose(a.Chart)})});
//# sourceMappingURL=export-data.js.map