!/**
 * Highcharts JS v13.0.0-modified (2026-08-14)
 * @module highcharts/modules/lollipop
 * @requires highcharts
 *
 * (c) 2009-2026 Highsoft AS
 * Author: Sebastian Bochan, Rafał Sebestjański
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry,e._Highcharts.Series):"function"==typeof define&&define.amd?define("highcharts/modules/lollipop",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry,e.Series)}):"object"==typeof exports?exports["highcharts/modules/lollipop"]=t(e._Highcharts,e._Highcharts.SeriesRegistry,e._Highcharts.Series):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry,e.Highcharts.Series)}("u"<typeof window?this:window,(e,t,r)=>(()=>{"use strict";var o={820(e){e.exports=r},512(e){e.exports=t},944(t){t.exports=e}};let s={};function i(e){let t=s[e];if(void 0!==t)return t.exports;let r=s[e]={exports:{}};return o[e](r,r.exports,i),r.exports}i.n=e=>{let t=e&&e.__esModule?()=>e.default:()=>e;return i.d(t,{a:t}),t},i.d=(e,t)=>{if(Array.isArray(t))for(var r=0;r<t.length;){var o=t[r++],s=t[r++];i.o(e,o)?0===s&&r++:0===s?Object.defineProperty(e,o,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,o,{enumerable:!0,get:s})}else for(var o in t)i.o(t,o)&&!i.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:t[o]})},i.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t);let a={};i.d(a,{default:()=>C});var n=i(944),l=i.n(n),p=i(512),d=i.n(p);let{series:{prototype:{pointClass:h}},seriesTypes:{scatter:{prototype:{pointClass:c}},dumbbell:{prototype:{pointClass:g}}}}=d();class u extends h{}(0,n.extend)(u.prototype,{destroy:g.prototype.destroy,pointSetState:c.prototype.setState,setState:g.prototype.setState});var y=i(820),f=i.n(y);let{seriesTypes:{column:{prototype:b},dumbbell:{prototype:x},scatter:m}}=d();class S extends f(){drawPoints(){let e=this.points.length,t=0,r;for(super.drawPoints.apply(this,arguments);t<e;)r=this.points[t],this.drawConnector(r),t++}translate(){for(let e of(b.translate.apply(this,arguments),this.points)){let{pointWidth:t,shapeArgs:r}=e;r?.x&&(r.x+=t/2,e.plotX=r.x||0)}}}S.defaultOptions=(0,n.merge)(f().defaultOptions,{threshold:0,connectorWidth:1,groupPadding:.2,pointPadding:.1,states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}},lineWidth:0,dataLabels:{align:void 0,verticalAlign:void 0},pointRange:1}),(0,n.extend)(S.prototype,{alignDataLabel:b.alignDataLabel,crispCol:b.crispCol,drawConnector:x.drawConnector,drawDataLabels:b.drawDataLabels,getColumnMetrics:b.getColumnMetrics,getConnectorAttribs:x.getConnectorAttribs,pointClass:u}),d().registerSeriesType("lollipop",S);let C=l();return a.default})());