/*
 Highcharts JS v11.1.0 (2023-10-06)

 Pictorial graph series type for Highcharts

 (c) 2010-2022 Torstein Honsi, Magdalena Gut

 License: www.highcharts.com/license
*/
'use strict';(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/pictorial",["highcharts"],function(n){c(n);c.Highcharts=n;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function n(c,f,l,e){c.hasOwnProperty(f)||(c[f]=e.apply(null,l),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:f,module:c[f]}})))}c=c?c._modules:
{};n(c,"Extensions/PatternFill.js",[c["Core/Animation/AnimationUtilities.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Defaults.js"],c["Core/Series/Point.js"],c["Core/Series/Series.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,f,l,e,w,k,v,m){function E(a,d){a=JSON.stringify(a);const b=a.length||0;let g=0,h=0;if(d){d=Math.max(Math.floor(b/500),1);for(let h=0;h<b;h+=d)g+=a.charCodeAt(h);g&=g}for(;h<b;++h)d=a.charCodeAt(h),g=(g<<5)-g+d,g&=g;return g.toString(16).replace("-",
"1")}const {animObject:p}=c,{getOptions:n}=e,{addEvent:q,defined:x,erase:B,merge:y,pick:r,removeEvent:C,wrap:D}=m,z=l.patterns=(()=>{const a=[],d=n().colors;["M 0 0 L 5 5 M 4.5 -0.5 L 5.5 0.5 M -0.5 4.5 L 0.5 5.5","M 0 5 L 5 0 M -0.5 0.5 L 0.5 -0.5 M 4.5 5.5 L 5.5 4.5","M 2 0 L 2 5 M 4 0 L 4 5","M 0 2 L 5 2 M 0 4 L 5 4","M 0 1.5 L 2.5 1.5 L 2.5 0 M 2.5 5 L 2.5 3.5 L 5 3.5"].forEach((b,g)=>{a.push({path:b,color:d[g],width:5,height:5,patternTransform:"scale(1.4 1.4)"})});["M 0 0 L 5 10 L 10 0","M 3 3 L 8 3 L 8 8 L 3 8 Z",
"M 5 5 m -4 0 a 4 4 0 1 1 8 0 a 4 4 0 1 1 -8 0","M 0 0 L 10 10 M 9 -1 L 11 1 M -1 9 L 1 11","M 0 10 L 10 0 M -1 1 L 1 -1 M 9 11 L 11 9"].forEach((b,g)=>{a.push({path:b,color:d[g+5],width:10,height:10})});return a})();w.prototype.calculatePatternDimensions=function(a){if(!a.width||!a.height){var d=this.graphic&&(this.graphic.getBBox&&this.graphic.getBBox(!0)||this.graphic.element&&this.graphic.element.getBBox())||{},b=this.shapeArgs;b&&(d.width=b.width||d.width,d.height=b.height||d.height,d.x=b.x||
d.x,d.y=b.y||d.y);if(a.image){if(!d.width||!d.height){a._width="defer";a._height="defer";d=this.series.chart.mapView&&this.series.chart.mapView.getSVGTransform().scaleY;x(d)&&0>d&&(a._inverted=!0);return}a.aspectRatio&&(d.aspectRatio=d.width/d.height,a.aspectRatio>d.aspectRatio?d.aspectWidth=d.height*a.aspectRatio:d.aspectHeight=d.width/a.aspectRatio);a._width=a.width||Math.ceil(d.aspectWidth||d.width);a._height=a.height||Math.ceil(d.aspectHeight||d.height)}a.width||(a._x=a.x||0,a._x+=d.x-Math.round(d.aspectWidth?
Math.abs(d.aspectWidth-d.width)/2:0));a.height||(a._y=a.y||0,a._y+=d.y-Math.round(d.aspectHeight?Math.abs(d.aspectHeight-d.height)/2:0))}};v.prototype.addPattern=function(a,d){function b(a){f.rect(0,0,c,t).attr({fill:a}).add(g)}let g;d=r(d,!0);let h=p(d);let c=a.width||a._width||32,t=a.height||a._height||32,l=a.color||"#343434",e=a.id,f=this,k;e||(this.idCounter=this.idCounter||0,e="highcharts-pattern-"+this.idCounter+"-"+(this.chartIndex||0),++this.idCounter);this.forExport&&(e+="-export");this.defIds=
this.defIds||[];if(!(-1<this.defIds.indexOf(e))){this.defIds.push(e);var u={id:e,patternUnits:"userSpaceOnUse",patternContentUnits:a.patternContentUnits||"userSpaceOnUse",width:c,height:t,x:a._x||a.x||0,y:a._y||a.y||0};a._inverted&&(u.patternTransform="scale(1, -1)",a.patternTransform&&(a.patternTransform+=" scale(1, -1)"));a.patternTransform&&(u.patternTransform=a.patternTransform);g=this.createElement("pattern").attr(u).add(this.defs);g.id=e;a.path?(u=m.isObject(a.path)?a.path:{d:a.path},a.backgroundColor&&
b(a.backgroundColor),k={d:u.d},this.styledMode||(k.stroke=u.stroke||l,k["stroke-width"]=r(u.strokeWidth,2),k.fill=u.fill||"none"),u.transform&&(k.transform=u.transform),this.createElement("path").attr(k).add(g),g.color=l):a.image&&(d?this.image(a.image,0,0,c,t,function(){this.animate({opacity:r(a.opacity,1)},h);C(this.element,"load")}).attr({opacity:0}).add(g):this.image(a.image,0,0,c,t).add(g));a.image&&d||"undefined"===typeof a.opacity||[].forEach.call(g.element.childNodes,function(b){b.setAttribute("opacity",
a.opacity)});this.patternElements=this.patternElements||{};return this.patternElements[e]=g}};D(k.prototype,"getColor",function(a){const d=this.options.color;d&&d.pattern&&!d.pattern.color?(delete this.options.color,a.apply(this,Array.prototype.slice.call(arguments,1)),d.pattern.color=this.color,this.color=this.options.color=d):a.apply(this,Array.prototype.slice.call(arguments,1))});q(k,"render",function(){const a=this.chart.isResizing;(this.isDirtyData||a||!this.chart.hasRendered)&&(this.points||
[]).forEach(function(d){const b=d.options&&d.options.color;b&&b.pattern&&(!a||d.shapeArgs&&d.shapeArgs.width&&d.shapeArgs.height?d.calculatePatternDimensions(b.pattern):(b.pattern._width="defer",b.pattern._height="defer"))})});q(w,"afterInit",function(){const a=this.options.color;a&&a.pattern&&("string"===typeof a.pattern.path&&(a.pattern.path={d:a.pattern.path}),this.color=this.options.color=y(this.series.options.color,a))});q(v,"complexColor",function(a){const d=a.args[0],b=a.args[1];a=a.args[2];
const g=this.chartIndex||0;let h=d.pattern,c="#343434";"undefined"!==typeof d.patternIndex&&z&&(h=z[d.patternIndex]);if(!h)return!0;if(h.image||"string"===typeof h.path||h.path&&h.path.d){let b=a.parentNode&&a.parentNode.getAttribute("class");b=b&&-1<b.indexOf("highcharts-legend");"defer"!==h._width&&"defer"!==h._height||w.prototype.calculatePatternDimensions.call({graphic:{element:a}},h);if(b||!h.id)h=y({},h),h.id="highcharts-pattern-"+g+"-"+E(h)+E(h,!0);this.addPattern(h,!this.forExport&&r(h.animation,
this.globalAnimation,{duration:100}));c=`url(${this.url}#${h.id+(this.forExport?"-export":"")})`}else c=h.color||c;a.setAttribute(b,c);d.toString=function(){return c};return!1});q(f,"endResize",function(){(this.renderer&&this.renderer.defIds||[]).filter(function(a){return a&&a.indexOf&&0===a.indexOf("highcharts-pattern-")}).length&&(this.series.forEach(function(a){a.visible&&a.points.forEach(function(a){(a=a.options&&a.options.color)&&a.pattern&&(a.pattern._width="defer",a.pattern._height="defer")})}),
this.redraw(!1))});q(f,"redraw",function(){const a={},d=this.renderer,b=(d.defIds||[]).filter(function(a){return a.indexOf&&0===a.indexOf("highcharts-pattern-")});b.length&&([].forEach.call(this.renderTo.querySelectorAll('[color^="url("], [fill^="url("], [stroke^="url("]'),function(b){if(b=b.getAttribute("fill")||b.getAttribute("color")||b.getAttribute("stroke"))b=b.replace(d.url,"").replace("url(#","").replace(")",""),a[b]=!0}),b.forEach(function(b){a[b]||(B(d.defIds,b),d.patternElements[b]&&(d.patternElements[b].destroy(),
delete d.patternElements[b]))}))});""});n(c,"Series/Pictorial/PictorialUtilities.js",[c["Core/Utilities.js"]],function(c){const {defined:f}=c;return{rescalePatternFill:function(c,e,f,k,v=1){var m=c&&c.attr("fill");if(m=m&&m.match(/url\(([^)]+)\)/))if(m=document.querySelector(`${m[1]} path`)){let p=m.getBBox();if(0===p.width){var l=m.parentElement;c.renderer.box.appendChild(m);p=m.getBBox();l.appendChild(m)}c=1/(p.width+v);k=e/k/p.height;l=p.width/p.height;e=f/e;const q=-p.width/2;l<e&&(c=c*l/e);m.setAttribute("stroke-width",
v/(f*c));m.setAttribute("transform","translate(0.5, 0)"+`scale(${c} ${k}) `+`translate(${q+v*c/2}, ${-p.y})`)}},invertShadowGroup:function(c,e){(e=e.chart.inverted)&&c.attr({rotation:e?90:0,scaleX:e?-1:1})},getStackMetrics:function(c,e){let l=c.len,k=0;e&&f(e.max)&&(k=c.toPixels(e.max,!0),l=c.len-k);return{height:l,y:k}}}});n(c,"Series/Pictorial/PictorialPoint.js",[c["Core/Series/SeriesRegistry.js"],c["Series/Pictorial/PictorialUtilities.js"]],function(c,f){c=c.seriesTypes.column.prototype.pointClass;
const {rescalePatternFill:l,getStackMetrics:e}=f;class n extends c{constructor(){super(...arguments);this.pathDef=this.series=this.options=void 0}setState(){super.setState.apply(this,arguments);const c=this.series,f=c.options.paths;this.graphic&&this.shapeArgs&&f&&l(this.graphic,e(c.yAxis,f[this.index%f.length]).height,this.shapeArgs.width||0,this.shapeArgs.height||Infinity,this.series.options.borderWidth||0)}}return n});n(c,"Series/Pictorial/PictorialSeries.js",[c["Core/Animation/AnimationUtilities.js"],
c["Core/Chart/Chart.js"],c["Series/Pictorial/PictorialPoint.js"],c["Series/Pictorial/PictorialUtilities.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Axis/Stacking/StackItem.js"],c["Core/Utilities.js"]],function(c,f,l,e,n,k,v){function m(b){var d=Object.keys(b.points).filter(b=>1<b.split(",").length);const c=b.axis.chart.series;let e=-1;d.map(b=>parseFloat(b.split(",")[0])).forEach(b=>{c[b]&&c[b].visible&&(e=b)});if((d=b.axis.chart.series[e])&&d.is("pictorial")&&b.axis.hasData()&&d.xAxis.hasData()){const c=
d.xAxis;var t=b.axis.options;const g=b.axis.chart,h=b.shadow;var f=c.toPixels(b.x,!0);f=g.inverted?c.len-f:f;var k=d.options.paths||[],l=k[b.x%k.length];k=d.getColumnMetrics&&d.getColumnMetrics().width;const {height:e,y:A}=x(d.yAxis,l);var m=t.stackShadow;t=a(m&&m.borderWidth,d.options.borderWidth,1);!h&&m&&m.enabled&&l?(b.shadowGroup||(b.shadowGroup=g.renderer.g("shadow-group").add()),b.shadowGroup.attr({translateX:g.inverted?b.axis.pos:c.pos,translateY:g.inverted?c.pos:b.axis.pos}),b.shadow=g.renderer.rect(f,
A,k,e).attr({fill:{pattern:{path:{d:l.definition,fill:m.color||"#dedede",strokeWidth:t,stroke:m.borderColor||"transparent"},x:f,y:A,width:k,height:e,patternContentUnits:"objectBoundingBox",backgroundColor:"none",color:"#dedede"}}}).add(b.shadowGroup),B(b.shadowGroup,b.axis),y(b.shadow,e,k,e,t),b.setOffset(d.pointXOffset||0,d.barW||0)):h&&b.shadowGroup&&(h.animate({x:f,y:A,width:k,height:e}),l=/url\(([^)]+)\)/,(l=(m=h.attr("fill"))&&m.match(l))&&g.renderer.patternElements&&g.renderer.patternElements[l[1].slice(1)].animate({x:f,
y:A,width:k,height:e}),b.shadowGroup.animate({translateX:g.inverted?b.axis.pos:c.pos,translateY:g.inverted?c.pos:b.axis.pos}),B(b.shadowGroup,b.axis),y(h,e,k,e,t),b.setOffset(d.pointXOffset||0,d.barW||0))}else b.shadow&&b.shadowGroup&&(b.shadow.destroy(),b.shadow=void 0,b.shadowGroup.destroy(),b.shadowGroup=void 0)}function q(b,a){b.axes&&b.axes.forEach(function(b){b.stacking&&z(b.stacking.stacks,function(b){z(b,function(b){a(b)})})})}function p(b){q(b,function(b){b.shadow&&b.shadowGroup&&(b.shadow.destroy(),
b.shadowGroup.destroy(),delete b.shadow,delete b.shadowGroup)})}const w=n.seriesTypes.column,{animObject:F}=c,{getStackMetrics:x,invertShadowGroup:B,rescalePatternFill:y}=e,{addEvent:r,defined:C,merge:D,objectEach:z,pick:a}=v;class d extends w{constructor(){super(...arguments);this.points=this.options=this.data=this.paths=void 0}animate(b){const {chart:a,group:d}=this;var c=F(this.options.animation),e=[this.getSharedClipKey(),c.duration,c.easing,c.defer].join();let f=a.sharedClips[e];b&&d?(c=this.getClipBox(),
f||(c.y=c.height,c.height=0,f=a.renderer.clipRect(c),a.sharedClips[e]=f),d.clip(f)):f&&!f.hasClass("highcharts-animating")&&(e=this.getClipBox(),f.addClass("highcharts-animating").animate(e,c))}animateDrilldown(){}animateDrillupFrom(){}pointAttribs(b){const a=super.pointAttribs.apply(this,arguments);var c=this.options.paths;if(b&&b.shapeArgs&&c){c=c[b.index%c.length];const {y:d,height:e}=x(this.yAxis,c);c=c.definition;c!==b.pathDef?(b.pathDef=c,a.fill={pattern:{path:{d:c,fill:a.fill,strokeWidth:a["stroke-width"],
stroke:a.stroke},x:b.shapeArgs.x,y:d,width:b.shapeArgs.width||0,height:e,patternContentUnits:"objectBoundingBox",backgroundColor:"none",color:"#ff0000"}}):b.pathDef&&b.graphic&&delete a.fill}delete a.stroke;delete a.strokeWidth;return a}getExtremes(){const b=super.getExtremes.apply(this,arguments),a=this.options.paths;a&&a.forEach(function(a){C(a.max)&&C(b.dataMax)&&a.max>b.dataMax&&(b.dataMax=a.max)});return b}}d.defaultOptions=D(w.defaultOptions,{borderWidth:0});r(d,"afterRender",function(){const b=
this,a=b.options.paths,c=/url\(([^)]+)\)/;b.points.forEach(function(d){if(d.graphic&&d.shapeArgs&&a){const f=a[d.index%a.length];var e=d.graphic.attr("fill");e=e&&e.match(c);const {y:g,height:h}=x(b.yAxis,f);e&&b.chart.renderer.patternElements&&(e=b.chart.renderer.patternElements[e[1].slice(1)])&&e.animate({x:d.shapeArgs.x,y:g,width:d.shapeArgs.width||0,height:h});y(d.graphic,x(b.yAxis,f).height,d.shapeArgs.width||0,d.shapeArgs.height||Infinity,b.options.borderWidth||0)}})});r(f,"render",function(){q(this,
m)});r(k,"afterSetOffset",function(a){if(this.shadow){const {chart:b,len:c}=this.axis,{xOffset:d,width:e}=a;this.shadow.attr({translateX:b.inverted?d-b.xAxis[0].len:d,translateY:b.inverted?-c:0});this.shadow.animate({width:e})}});r(f,"afterDrilldown",function(){p(this)});r(f,"afterDrillUp",function(){p(this)});d.prototype.pointClass=l;n.registerSeriesType("pictorial",d);"";return d});n(c,"masters/modules/pictorial.src.js",[],function(){})});
//# sourceMappingURL=pictorial.js.map