/*
 Highcharts JS v11.1.0 (2023-10-06)

 (c) 2016-2021 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
'use strict';var m=m||{};m.scope={};m.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};m.arrayIterator=function(a){return{next:m.arrayIteratorImpl(a)}};m.ASSUME_ES5=!1;m.ASSUME_NO_NATIVE_MAP=!1;m.ASSUME_NO_NATIVE_SET=!1;m.SIMPLE_FROUND_POLYFILL=!1;m.ISOLATE_POLYFILLS=!1;
m.defineProperty=m.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};m.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};m.global=m.getGlobal(this);
m.SYMBOL_PREFIX="jscomp_symbol_";m.initSymbol=function(){m.initSymbol=function(){};m.global.Symbol||(m.global.Symbol=m.Symbol)};m.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;m.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};m.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
m.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new m.SymbolClass(m.SYMBOL_PREFIX+(d||"")+"_"+c++,d)}var c=0;return a}();
m.initSymbolIterator=function(){m.initSymbol();var a=m.global.Symbol.iterator;a||(a=m.global.Symbol.iterator=m.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&m.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m.iteratorPrototype(m.arrayIteratorImpl(this))}});m.initSymbolIterator=function(){}};
m.initSymbolAsyncIterator=function(){m.initSymbol();var a=m.global.Symbol.asyncIterator;a||(a=m.global.Symbol.asyncIterator=m.global.Symbol("Symbol.asyncIterator"));m.initSymbolAsyncIterator=function(){}};m.iteratorPrototype=function(a){m.initSymbolIterator();a={next:a};a[m.global.Symbol.iterator]=function(){return this};return a};
m.iteratorFromArray=function(a,c){m.initSymbolIterator();a instanceof String&&(a+="");var d=0,b={next:function(){if(d<a.length){var e=d++;return{value:c(e,a[e]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};m.polyfills={};m.propertyToPolyfillSymbol={};m.POLYFILL_PREFIX="$jscp$";m.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
m.polyfill=function(a,c,d,b){c&&(m.ISOLATE_POLYFILLS?m.polyfillIsolated(a,c,d,b):m.polyfillUnisolated(a,c,d,b))};m.polyfillUnisolated=function(a,c){var d=m.global;a=a.split(".");for(var b=0;b<a.length-1;b++){var e=a[b];e in d||(d[e]={});d=d[e]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&m.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
m.polyfillIsolated=function(a,c,d){var b=a.split(".");a=1===b.length;var e=b[0];e=!a&&e in m.polyfills?m.polyfills:m.global;for(var v=0;v<b.length-1;v++){var t=b[v];t in e||(e[t]={});e=e[t]}b=b[b.length-1];d=m.IS_SYMBOL_NATIVE&&"es6"===d?e[b]:null;c=c(d);null!=c&&(a?m.defineProperty(m.polyfills,b,{configurable:!0,writable:!0,value:c}):c!==d&&(m.propertyToPolyfillSymbol[b]=m.IS_SYMBOL_NATIVE?m.global.Symbol(b):m.POLYFILL_PREFIX+b,b=m.propertyToPolyfillSymbol[b],m.defineProperty(e,b,{configurable:!0,
writable:!0,value:c})))};m.polyfill("Array.prototype.values",function(a){return a?a:function(){return m.iteratorFromArray(this,function(a,d){return d})}},"es8","es3");
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,b,c,v){a.hasOwnProperty(b)||(a[b]=v.apply(null,c),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:b,module:a[b]}})))}a=a?a._modules:{};c(a,
"Series/ColorMapComposition.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b){const {column:{prototype:d}}=a.seriesTypes,{addEvent:c,defined:t}=b;var q;(function(a){function h(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})}const e=[];a.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};a.seriesMembers=
{colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(a){const g={};!t(a.color)||a.state&&"normal"!==a.state||(g[this.colorProp||"fill"]=a.color);return g},pointAttribs:d.pointAttribs};a.compose=function(a){const g=a.prototype.pointClass;b.pushUnique(e,g)&&c(g,"afterSetState",h);return a}})(q||(q={}));return q});c(a,"Series/Treemap/TreemapAlgorithmGroup.js",[],
function(){class a{constructor(a,d,c,t){this.height=a;this.width=d;this.plot=t;this.startDirection=this.direction=c;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,b){return Math.max(a/b,b/a)}}}addElement(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=
this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)}reset(){this.lW=this.nW=0;this.elArr=[];this.total=0}}return a});c(a,"Series/DrawPointUtilities.js",[a["Core/Utilities.js"]],function(){return{draw:function(a,b){const {animatableAttribs:d,onComplete:c,
css:t,renderer:q}=b,l=a.series&&a.series.chart.hasRendered?void 0:a.series&&a.series.options.animation;let h=a.graphic;b.attribs=Object.assign(Object.assign({},b.attribs),{"class":a.getClassName()})||{};if(a.shouldDraw())h||(h="text"===b.shapeType?q.text():"image"===b.shapeType?q.image(b.imageUrl||"").attr(b.shapeArgs||{}):q[b.shapeType](b.shapeArgs||{}),a.graphic=h,h.add(b.group)),t&&h.css(t),h.attr(b.attribs).animate(d,b.isNew?!1:l,c);else if(h){const b=()=>{a.graphic=h=h&&h.destroy();"function"===
typeof c&&c()};Object.keys(d).length?h.animate(d,void 0,()=>b()):b()}}}});c(a,"Series/Treemap/TreemapPoint.js",[a["Series/DrawPointUtilities.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b,c){const {series:{prototype:{pointClass:d}},seriesTypes:{pie:{prototype:{pointClass:e}},scatter:{prototype:{pointClass:q}}}}=b,{extend:l,isNumber:h,pick:y}=c;class g extends q{constructor(){super(...arguments);this.series=this.options=this.node=this.name=void 0;this.shapeType="rect";
this.value=void 0}draw(g){a.draw(this,g)}getClassName(){let a=d.prototype.getClassName.call(this),g=this.series,b=g.options;this.node.level<=g.nodeMap[g.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||y(b.interactByLeaf,!b.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a}isValid(){return!(!this.id&&!h(this.value))}setState(a){d.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===
a?1:0})}shouldDraw(){return h(this.plotY)&&null!==this.y}}l(g.prototype,{setVisible:e.prototype.setVisible});return g});c(a,"Series/Treemap/TreemapUtilities.js",[a["Core/Utilities.js"]],function(a){const {objectEach:b}=a;var d;(function(a){function d(a,b,c=this){a=b.call(c,a);!1!==a&&d(a,b,c)}a.AXIS_MAX=100;a.isBoolean=function(a){return"boolean"===typeof a};a.eachObject=function(a,d,c){c=c||this;b(a,function(b,g){d.call(c,b,g,a)})};a.recursive=d})(d||(d={}));return d});c(a,"Series/TreeUtilities.js",
[a["Core/Color/Color.js"],a["Core/Utilities.js"]],function(a,b){function d(a,b){var g=b.before;const p=b.idRoot,h=b.mapIdToNode[p],l=b.points[a.i],e=l&&l.options||{},t=[];let C=0;a.levelDynamic=a.level-(!1!==b.levelIsConstant?0:h.level);a.name=y(l&&l.name,"");a.visible=p===a.id||!0===b.visible;"function"===typeof g&&(a=g(a,b));a.children.forEach((g,p)=>{const E=c({},b);c(E,{index:p,siblings:a.children.length,visible:a.visible});g=d(g,E);t.push(g);g.visible&&(C+=g.val)});g=y(e.value,C);a.visible=0<=
g&&(0<C||a.visible);a.children=t;a.childrenTotal=C;a.isLeaf=a.visible&&!C;a.val=g;return a}const {extend:c,isArray:t,isNumber:q,isObject:l,merge:h,pick:y}=b;return{getColor:function(b,d){const g=d.index;var c=d.mapOptionsToLevel;const l=d.parentColor,h=d.parentColorIndex,p=d.series;var e=d.colors;const t=d.siblings;var z=p.points,q=p.chart.options.chart;let E;var u;let K;if(b){z=z[b.i];b=c[b.level]||{};if(c=z&&b.colorByPoint){E=z.index%(e?e.length:q.colorCount);var G=e&&e[E]}if(!p.chart.styledMode){e=
z&&z.options.color;q=b&&b.color;if(u=l)u=(u=b&&b.colorVariation)&&"brightness"===u.key&&g&&t?a.parse(l).brighten(g/t*u.to).get():l;u=y(e,q,G,u,p.color)}K=y(z&&z.options.colorIndex,b&&b.colorIndex,E,h,d.colorIndex)}return{color:u,colorIndex:K}},getLevelOptions:function(a){let b={},d,c,g;if(l(a)){g=q(a.from)?a.from:1;var e=a.levels;c={};d=l(a.defaults)?a.defaults:{};t(e)&&(c=e.reduce((a,b)=>{let c,e;l(b)&&q(b.level)&&(e=h({},b),c=y(e.levelIsConstant,d.levelIsConstant),delete e.levelIsConstant,delete e.level,
b=b.level+(c?0:g-1),l(a[b])?h(!0,a[b],e):a[b]=e);return a},{}));e=q(a.to)?a.to:1;for(a=0;a<=e;a++)b[a]=h({},d,l(c[a])?c[a]:{})}return b},setTreeValues:d,updateRootId:function(a){if(l(a)){var b=l(a.options)?a.options:{};b=y(a.rootNode,b.rootId,"");l(a.userOptions)&&(a.userOptions.rootId=b);a.rootNode=b}return b}}});c(a,"Extensions/Breadcrumbs/BreadcrumbsDefaults.js",[],function(){return{lang:{mainBreadcrumb:"Main"},options:{buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},
style:{color:"#334eff"}},buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",rtl:!1,position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666",fontSize:"0.8em"}},showFullPath:!0,style:{},useHTML:!1,zIndex:7}}});c(a,"Extensions/Breadcrumbs/Breadcrumbs.js",[a["Extensions/Breadcrumbs/BreadcrumbsDefaults.js"],a["Core/Chart/Chart.js"],a["Core/Templating.js"],a["Core/Utilities.js"]],function(a,b,c,v){function d(){if(this.breadcrumbs){const a=this.resetZoomButton&&
this.resetZoomButton.getBBox(),b=this.breadcrumbs.options;a&&"right"===b.position.align&&"plotBox"===b.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-a.width-b.buttonSpacing)}}function e(){this.breadcrumbs&&(this.breadcrumbs.destroy(),this.breadcrumbs=void 0)}function l(){const a=this.breadcrumbs;if(a&&!a.options.floating&&a.level){var b=a.options,d=b.buttonTheme;d=(d.height||0)+2*(d.padding||0)+b.buttonSpacing;b=b.position.verticalAlign;"bottom"===b?(this.marginBottom=(this.marginBottom||0)+
d,a.yOffset=d):"middle"!==b?(this.plotTop+=d,a.yOffset=-d):a.yOffset=void 0}}function h(){this.breadcrumbs&&this.breadcrumbs.redraw()}function y(a){!0===a.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}const {format:g}=c,{addEvent:p,defined:P,extend:Q,fireEvent:J,isString:N,merge:I,objectEach:M,pick:C}=v,z=[];class D{static compose(c,u){v.pushUnique(z,c)&&(p(b,"destroy",e),p(b,"afterShowResetZoom",d),p(b,"getMargins",l),p(b,"redraw",h),p(b,"selection",y));v.pushUnique(z,
u)&&Q(u.lang,a.lang)}constructor(a,b){this.elementList={};this.isDirty=!0;this.level=0;this.list=[];b=I(a.options.drilldown&&a.options.drilldown.drillUpButton,D.defaultOptions,a.options.navigation&&a.options.navigation.breadcrumbs,b);this.chart=a;this.options=b||{}}updateProperties(a){this.setList(a);this.setLevel();this.isDirty=!0}setList(a){this.list=a}setLevel(){this.level=this.list.length&&this.list.length-1}getLevel(){return this.level}getButtonText(a){const b=this.chart,d=this.options;var c=
b.options.lang;const e=C(d.format,d.showFullPath?"{level.name}":"\u2190 {level.name}");c=c&&C(c.drillUpText,c.mainBreadcrumb);a=d.formatter&&d.formatter(a)||g(e,{level:a.levelOptions},b)||"";(N(a)&&!a.length||"\u2190 "===a)&&P(c)&&(a=d.showFullPath?c:"\u2190 "+c);return a}redraw(){this.isDirty&&this.render();this.group&&this.group.align();this.isDirty=!1}render(){const a=this.chart,b=this.options;!this.group&&b&&(this.group=a.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:b.zIndex}).add());
b.showFullPath?this.renderFullPathButtons():this.renderSingleButton();this.alignBreadcrumbsGroup()}renderFullPathButtons(){this.destroySingleButton();this.resetElementListState();this.updateListElements();this.destroyListElements()}renderSingleButton(){const a=this.chart;var b=this.list;const d=this.options.buttonSpacing;this.destroyListElements();const c=this.group?this.group.getBBox().width:d;b=b[b.length-2];!a.drillUpButton&&0<this.level?a.drillUpButton=this.renderButton(b,c,d):a.drillUpButton&&
(0<this.level?this.updateSingleButton():this.destroySingleButton())}alignBreadcrumbsGroup(a){if(this.group){var b=this.options;const c=b.buttonTheme,g=b.position,e="chart"===b.relativeTo||"spacingBox"===b.relativeTo?void 0:"scrollablePlotBox";var d=this.group.getBBox();b=2*(c.padding||0)+b.buttonSpacing;g.width=d.width+b;g.height=d.height+b;d=I(g);a&&(d.x+=a);this.options.rtl&&(d.x+=g.width);d.y=C(d.y,this.yOffset,0);this.group.align(d,!0,e)}}renderButton(a,b,d){const c=this,g=this.chart,e=c.options,
l=I(e.buttonTheme);b=g.renderer.button(c.getButtonText(a),b,d,function(b){const d=e.events&&e.events.click;let n;d&&(n=d.call(c,b,a));!1!==n&&(b.newLevel=e.showFullPath?a.level:c.level-1,J(c,"up",b))},l).addClass("highcharts-breadcrumbs-button").add(c.group);g.styledMode||b.attr(e.style);return b}renderSeparator(a,b){const d=this.chart,c=this.options.separator;a=d.renderer.label(c.text,a,b,void 0,void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);d.styledMode||a.css(c.style);
return a}update(a){I(!0,this.options,a);this.destroy();this.isDirty=!0}updateSingleButton(){const a=this.chart,b=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(b)})}destroy(){this.destroySingleButton();this.destroyListElements(!0);this.group&&this.group.destroy();this.group=void 0}destroyListElements(a){const b=this.elementList;M(b,(d,c)=>{if(a||!b[c].updated)d=b[c],d.button&&d.button.destroy(),d.separator&&d.separator.destroy(),delete d.button,delete d.separator,
delete b[c]});a&&(this.elementList={})}destroySingleButton(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)}resetElementListState(){M(this.elementList,a=>{a.updated=!1})}updateListElements(){function a(a,b,f){a.translate(b-a.getBBox().width,f)}function b(a,b){return l*a.getBBox().width+l*b}const d=this.elementList,c=this.options.buttonSpacing,g=this.list,e=this.options.rtl,l=e?-1:1;let h=this.group?b(this.group,c):c,p,n;for(let B=0,F=g.length;B<F;++B){const f=
B===F-1;let r,k;n=g[B];d[n.level]?(p=d[n.level],r=p.button,p.separator||f?p.separator&&f&&(p.separator.destroy(),delete p.separator):(h+=l*c,p.separator=this.renderSeparator(h,c),e&&a(p.separator,h,c),h+=b(p.separator,c)),d[n.level].updated=!0):(r=this.renderButton(n,h,c),e&&a(r,h,c),h+=b(r,c),f||(k=this.renderSeparator(h,c),e&&a(k,h,c),h+=b(k,c)),d[n.level]={button:r,separator:k,updated:!0});r&&r.setState(f?2:0)}}}D.defaultOptions=a.options;"";return D});c(a,"Series/Treemap/TreemapComposition.js",
[a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapUtilities.js"],a["Core/Utilities.js"]],function(a,b,c){({series:a}=a);const {addEvent:d,extend:e}=c;let q=!1;d(a,"afterBindAxes",function(){let a=this.xAxis,d=this.yAxis,c;a&&d&&(this.is("treemap")?(c={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,minPadding:0,max:b.AXIS_MAX,maxPadding:0,startOnTick:!1,title:void 0,tickPositions:[]},e(d.options,c),e(a.options,c),q=!0):q&&(d.setOptions(d.userOptions),a.setOptions(a.userOptions),q=!1))})});
c(a,"Series/Treemap/TreemapNode.js",[],function(){class a{constructor(){this.childrenTotal=0;this.visible=!1}init(a,d,c,t,q,l,h){this.id=a;this.i=d;this.children=c;this.height=t;this.level=q;this.series=l;this.parent=h;return this}}return a});c(a,"Series/Treemap/TreemapSeries.js",[a["Core/Color/Color.js"],a["Series/ColorMapComposition.js"],a["Core/Globals.js"],a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapAlgorithmGroup.js"],a["Series/Treemap/TreemapPoint.js"],a["Series/Treemap/TreemapUtilities.js"],
a["Series/TreeUtilities.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"],a["Core/Utilities.js"],a["Series/Treemap/TreemapNode.js"]],function(a,b,c,v,t,q,l,h,y,g,p){const {parse:d}=a;({noop:a}=c);const {series:e,seriesTypes:{column:J,heatmap:N,scatter:I}}=v,{getColor:M,getLevelOptions:C,updateRootId:z}=h,{addEvent:D,correctFloat:E,defined:u,error:K,extend:G,fireEvent:R,isArray:L,isObject:S,isString:O,merge:x,pick:n,stableSort:B}=g;class F extends I{constructor(){super(...arguments);this.level=this.tree=
this.rootNode=this.points=this.options=this.nodeList=this.nodeMap=this.mapOptionsToLevel=this.data=this.axisRatio=void 0}algorithmCalcPoints(a,b,k,d){let f,r,c,n,A=k.lW,e=k.lH,g=k.plot,h,l=0,p=k.elArr.length-1;b?(A=k.nW,e=k.nH):h=k.elArr[k.elArr.length-1];k.elArr.forEach(function(a){if(b||l<p)0===k.direction?(f=g.x,r=g.y,c=A,n=a/c):(f=g.x,r=g.y,n=e,c=a/n),d.push({x:f,y:r,width:c,height:E(n)}),0===k.direction?g.y+=n:g.x+=c;l+=1});k.reset();0===k.direction?k.width-=A:k.height-=e;g.y=g.parent.y+(g.parent.height-
k.height);g.x=g.parent.x+(g.parent.width-k.width);a&&(k.direction=1-k.direction);b||k.addElement(h)}algorithmFill(a,b,k){let f=[],r,c=b.direction,d=b.x,n=b.y,g=b.width,e=b.height,h,l,p,B;k.forEach(function(k){r=k.val/b.val*b.height*b.width;h=d;l=n;0===c?(B=e,p=r/B,g-=p,d+=p):(p=g,B=r/p,e-=B,n+=B);f.push({x:h,y:l,width:p,height:B});a&&(c=1-c)});return f}algorithmLowAspectRatio(a,b,c){let f=[],d=this,k,r={x:b.x,y:b.y,parent:b},n=0,g=c.length-1,e=new t(b.height,b.width,b.direction,r);c.forEach(function(c){k=
c.val/b.val*b.height*b.width;e.addElement(k);e.lP.nR>e.lP.lR&&d.algorithmCalcPoints(a,!1,e,f,r);n===g&&d.algorithmCalcPoints(a,!0,e,f,r);n+=1});return f}alignDataLabel(a,b,c){const f=c.style;f&&!u(f.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:f.width+="px"});J.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})}calculateChildrenAreas(a,b){let f=this,c=f.options,d=f.mapOptionsToLevel[a.level+
1],r=n(f[d&&d.layoutAlgorithm]&&d.layoutAlgorithm,c.layoutAlgorithm),g=c.alternateStartingDirection,e=[];a=a.children.filter(function(a){return!a.ignore});d&&d.layoutStartingDirection&&(b.direction="vertical"===d.layoutStartingDirection?0:1);e=f[r](b,a);a.forEach(function(a,c){c=e[c];a.values=x(c,{val:a.childrenTotal,direction:g?1-b.direction:b.direction});a.pointValues=x(c,{x:c.x/f.axisRatio,y:l.AXIS_MAX-c.y-c.height,width:c.width/f.axisRatio});a.children.length&&f.calculateChildrenAreas(a,a.values)})}createList(a){var b=
this.chart;const f=[];if(b.breadcrumbs){let c=0;f.push({level:c,levelOptions:b.series[0]});b=a.target.nodeMap[a.newRootId];const d=[];for(;b.parent||""===b.parent;)d.push(b),b=a.target.nodeMap[b.parent];d.reverse().forEach(function(a){f.push({level:++c,levelOptions:a})});1>=f.length&&(f.length=0)}return f}drawDataLabels(){let a=this,b=a.mapOptionsToLevel,c,d;a.points.filter(function(a){return a.node.visible}).forEach(function(f){d=b[f.node.level];c={style:{}};f.node.isLeaf||(c.enabled=!1);d&&d.dataLabels&&
(c=x(c,d.dataLabels),a.hasDataLabels=()=>!0);f.shapeArgs&&(c.style.width=f.shapeArgs.width,f.dataLabel&&f.dataLabel.css({width:f.shapeArgs.width+"px"}));f.dlOptions=x(c,f.options.dataLabels)});e.prototype.drawDataLabels.call(this)}drawPoints(a=this.points){const b=this,f=b.chart,c=f.renderer,d=f.styledMode,n=b.options,g=d?{}:n.shadow,e=n.borderRadius,h=f.pointCount<n.animationLimit,p=n.allowTraversingTree;a.forEach(function(a){const f=a.node.levelDynamic,k={},r={},H={},A="level-group-"+a.node.level,
T=!!a.graphic,l=h&&T,U=a.shapeArgs;a.shouldDraw()&&(a.isInside=!0,e&&(r.r=e),x(!0,l?k:r,T?U:{},d?{}:b.pointAttribs(a,a.selected?"select":void 0)),b.colorAttribs&&d&&G(H,b.colorAttribs(a)),b[A]||(b[A]=c.g(A).attr({zIndex:1E3-(f||0)}).add(b.group),b[A].survive=!0));a.draw({animatableAttribs:k,attribs:r,css:H,group:b[A],imageUrl:a.imageUrl,renderer:c,shadow:g,shapeArgs:U,shapeType:a.shapeType});p&&a.graphic&&(a.drillId=n.interactByLeaf?b.drillToByLeaf(a):b.drillToByGroup(a))})}drillToByGroup(a){let b=
!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b}drillToByLeaf(a){let b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b}drillToNode(a,b){K(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)}drillUp(){const a=this.nodeMap[this.rootNode];a&&O(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})}getExtremes(){const {dataMin:a,
dataMax:b}=e.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=a;this.valueMax=b;return e.prototype.getExtremes.call(this)}getListOfParents(a,b){a=L(a)?a:[];const f=L(b)?b:[];b=a.reduce(function(a,b,f){b=n(b.parent,"");"undefined"===typeof a[b]&&(a[b]=[]);a[b].push(f);return a},{"":[]});l.eachObject(b,function(a,b,c){""!==b&&-1===f.indexOf(b)&&(a.forEach(function(a){c[""].push(a)}),delete c[b])});return b}getTree(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,
a);this.nodeMap={};this.nodeList=[];return this.buildTree("",-1,0,a)}buildTree(a,b,c,d,n){let f=this,k=[],g=f.points[b],e=0,r,A;(d[a]||[]).forEach(function(b){A=f.buildTree(f.points[b].id,b,c+1,d,a);e=Math.max(A.height+1,e);k.push(A)});r=(new f.NodeClass).init(a,b,k,e,c,f,n);k.forEach(a=>{a.parentNode=r});f.nodeMap[r.id]=r;f.nodeList.push(r);g&&(g.node=r,r.point=g);return r}hasData(){return!!this.processedXData.length}init(a,b){const f=this,c=x(b.drillUpButton,b.breadcrumbs);let d;d=D(f,"setOptions",
function(a){a=a.userOptions;u(a.allowDrillToNode)&&!u(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);u(a.drillUpButton)&&!u(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});e.prototype.init.call(f,a,b);delete f.opacity;f.eventsToUnbind.push(d);f.options.allowTraversingTree&&(f.eventsToUnbind.push(D(f,"click",f.onClickDrillToNode)),f.eventsToUnbind.push(D(f,"setRootNode",function(a){const b=f.chart;b.breadcrumbs&&b.breadcrumbs.updateProperties(f.createList(a))})),
f.eventsToUnbind.push(D(f,"update",function(a){const b=this.chart.breadcrumbs;b&&a.options.breadcrumbs&&b.update(a.options.breadcrumbs)})),f.eventsToUnbind.push(D(f,"destroy",function(a){const b=this.chart;b.breadcrumbs&&!a.keepEventsForUpdate&&(b.breadcrumbs.destroy(),b.breadcrumbs=void 0)})));a.breadcrumbs||(a.breadcrumbs=new y(a,c));f.eventsToUnbind.push(D(a.breadcrumbs,"up",function(a){a=this.level-a.newLevel;for(let b=0;b<a;b++)f.drillUp()}))}onClickDrillToNode(a){const b=(a=a.point)&&a.drillId;
O(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))}pointAttribs(a,b){var c=S(this.mapOptionsToLevel)?this.mapOptionsToLevel:{};let f=a&&c[a.node.level]||{};c=this.options;let g=b&&c.states&&c.states[b]||{},e=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||f.borderColor||g.borderColor||c.borderColor,"stroke-width":n(a&&a.borderWidth,f.borderWidth,g.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||f.borderDashStyle||g.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};
-1!==e.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==e.indexOf("highcharts-internal-node-interactive")?(b=n(g.opacity,c.opacity),a.fill=d(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==e.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=d(a.fill).brighten(g.brightness).get());return a}setColorRecursive(a,b,c,d,n){let f=this;var g=f&&f.chart;g=g&&g.options&&g.options.colors;let e;if(a){e=M(a,{colors:g,index:d,mapOptionsToLevel:f.mapOptionsToLevel,parentColor:b,
parentColorIndex:c,series:f,siblings:n});if(b=f.points[a.i])b.color=e.color,b.colorIndex=e.colorIndex;(a.children||[]).forEach(function(b,c){f.setColorRecursive(b,e.color,e.colorIndex,c,a.children.length)})}}setPointValues(){const a=this,{points:b,xAxis:c,yAxis:d}=a,n=a.chart.styledMode;b.forEach(function(b){const {pointValues:f,visible:g}=b.node;if(f&&g){const {height:g,width:r,x:h,y:p}=f;var e=n?0:(a.pointAttribs(b)["stroke-width"]||0)%2/2,k=Math.round(c.toPixels(h,!0))-e;const A=Math.round(c.toPixels(h+
r,!0))-e,l=Math.round(d.toPixels(p,!0))-e;e=Math.round(d.toPixels(p+g,!0))-e;k={x:Math.min(k,A),y:Math.min(l,e),width:Math.abs(A-k),height:Math.abs(e-l)};b.plotX=k.x+k.width/2;b.plotY=k.y+k.height/2;b.shapeArgs=k}else delete b.plotX,delete b.plotY})}setRootNode(a,b,c){a=G({newRootId:a,previousRootId:this.rootNode,redraw:n(b,!0),series:this},c);R(this,"setRootNode",a,function(a){const b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})}setState(a){this.options.inactiveOtherPoints=
!0;e.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1}setTreeValues(a){let b=this;var c=b.options;let d=b.nodeMap[b.rootNode];c=l.isBoolean(c.levelIsConstant)?c.levelIsConstant:!0;let f=0,e=[],g,h=b.points[a.i];a.children.forEach(function(a){a=b.setTreeValues(a);e.push(a);a.ignore||(f+=a.val)});B(e,function(a,b){return(a.sortIndex||0)-(b.sortIndex||0)});g=n(h&&h.options.value,f);h&&(h.value=g);G(a,{children:e,childrenTotal:f,ignore:!(n(h&&h.visible,!0)&&0<g),isLeaf:a.visible&&
!f,levelDynamic:a.level-(c?0:d.level),name:n(h&&h.name,""),sortIndex:n(h&&h.sortIndex,-g),val:g});return a}sliceAndDice(a,b){return this.algorithmFill(!0,a,b)}squarified(a,b){return this.algorithmLowAspectRatio(!0,a,b)}strip(a,b){return this.algorithmLowAspectRatio(!1,a,b)}stripes(a,b){return this.algorithmFill(!1,a,b)}translate(){let a=this;var b=a.options,c=z(a);let d,g;e.prototype.translate.call(a);g=a.tree=a.getTree();d=a.nodeMap[c];""===c||d&&d.children.length||(a.setRootNode("",!1),c=a.rootNode,
d=a.nodeMap[c]);a.mapOptionsToLevel=C({from:d.level+1,levels:b.levels,to:g.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});l.recursive(a.nodeMap[a.rootNode],function(b){let c=!1,d=b.parent;b.visible=!0;if(d||""===d)c=a.nodeMap[d];return c});l.recursive(a.nodeMap[a.rootNode].children,function(a){let b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(g);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=
c={x:0,y:0,width:l.AXIS_MAX,height:l.AXIS_MAX};a.nodeMap[""].values=c=x(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:g.val});a.calculateChildrenAreas(g,c);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=d.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()}}F.defaultOptions=x(I.defaultOptions,{allowTraversingTree:!1,animationLimit:250,
borderRadius:0,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){const a=this&&this.point?this.point:{};return O(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",
borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",brightness:N?0:.1,halo:!1,opacity:.75,shadow:!1}},legendSymbol:"rectangle"});G(F.prototype,{buildKDTree:a,colorAttribs:b.seriesMembers.colorAttribs,colorKey:"colorValue",directTouch:!0,getExtremesFromAll:!0,getSymbol:a,optionalAxis:"colorAxis",parallelArrays:["x","y","value","colorValue"],pointArrayMap:["value"],pointClass:q,NodeClass:p,trackerGroups:["group","dataLabelsGroup"],utils:{recursive:l.recursive}});b.compose(F);
v.registerSeriesType("treemap",F);"";return F});c(a,"Series/Sunburst/SunburstPoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b){const {series:{prototype:{pointClass:c}},seriesTypes:{treemap:{prototype:{pointClass:d}}}}=a,{correctFloat:t,extend:q,pInt:l}=b;class h extends d{constructor(){super(...arguments);this.shapeType=this.shapeExisting=this.series=this.options=this.node=void 0}getDataLabelPath(a){var b;let c=this.series.chart.renderer,d=this.shapeExisting,e=d.start,
h=d.end;var q=e+(h-e)/2;q=0>q&&q>-Math.PI||q>Math.PI;a=d.r+l((null===(b=a.options)||void 0===b?void 0:b.distance)||0);let v;e===-Math.PI/2&&t(h)===t(1.5*Math.PI)&&(e=-Math.PI+Math.PI/360,h=-Math.PI/360,q=!0);h-e>Math.PI&&(q=!1,v=!0,h-e>2*Math.PI-.01&&(e+=.01,h-=.01));this.dataLabelPath&&(this.dataLabelPath=this.dataLabelPath.destroy());return this.dataLabelPath=c.arc({open:!0,longArc:v?1:0}).attr({start:q?e:h,end:q?h:e,clockwise:+q,x:d.x,y:d.y,r:(a+d.innerR)/2}).add(c.defs)}isValid(){return!0}}q(h.prototype,
{getClassName:c.prototype.getClassName,haloPath:c.prototype.haloPath,setState:c.prototype.setState});return h});c(a,"Series/Sunburst/SunburstUtilities.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b){const {seriesTypes:{treemap:c}}=a,{isNumber:d,isObject:t,merge:q}=b;var l;(function(a){function b(a,b){let c=[];if(d(a)&&d(b)&&a<=b)for(;a<=b;a++)c.push(a);return c}a.recursive=c.prototype.utils.recursive;a.calculateLevelSizes=function(a,c){let e;c=t(c)?c:{};let g=0,h,l,p,
v;t(a)&&(e=q({},a),a=d(c.from)?c.from:0,v=d(c.to)?c.to:0,l=b(a,v),a=Object.keys(e).filter(function(a){return-1===l.indexOf(+a)}),h=p=d(c.diffRadius)?c.diffRadius:0,l.forEach(function(a){a=e[a];const b=a.levelSize.unit,c=a.levelSize.value;"weight"===b?g+=c:"percentage"===b?(a.levelSize={unit:"pixels",value:c/100*h},p-=a.levelSize.value):"pixels"===b&&(p-=c)}),l.forEach(function(a){var b=e[a];"weight"===b.levelSize.unit&&(b=b.levelSize.value,e[a].levelSize={unit:"pixels",value:b/g*p})}),a.forEach(function(a){e[a].levelSize=
{value:0,unit:"pixels"}}));return e};a.getLevelFromAndTo=function({level:a,height:b}){return{from:0<a?a:1,to:a+b}};a.range=b})(l||(l={}));return l});c(a,"Series/Sunburst/SunburstNode.js",[a["Series/Treemap/TreemapNode.js"]],function(a){class b extends a{}return b});c(a,"Series/Sunburst/SunburstSeries.js",[a["Series/CenteredUtilities.js"],a["Core/Globals.js"],a["Core/Series/SeriesRegistry.js"],a["Series/Sunburst/SunburstPoint.js"],a["Series/Sunburst/SunburstUtilities.js"],a["Series/TreeUtilities.js"],
a["Core/Utilities.js"],a["Series/Sunburst/SunburstNode.js"]],function(a,b,c,v,t,q,l,h){function d(a,b){var c=b.mapIdToNode,d=a.parent;d=d?c[d]:void 0;const e=b.series,n=e.chart;c=e.points[a.i];d=N(a,{colors:e.options.colors||n&&n.options.colors,colorIndex:e.colorIndex,index:b.index,mapOptionsToLevel:b.mapOptionsToLevel,parentColor:d&&d.color,parentColorIndex:d&&d.colorIndex,series:b.series,siblings:b.siblings});a.color=d.color;a.colorIndex=d.colorIndex;c&&(c.color=a.color,c.colorIndex=a.colorIndex,
a.sliced=a.id!==b.idRoot?c.sliced:!1);return a}const {getCenter:e,getStartAndEndRadians:p}=a;({noop:a}=b);const {series:P,seriesTypes:{column:Q,treemap:J}}=c,{getColor:N,getLevelOptions:I,setTreeValues:M,updateRootId:C}=q,{defined:z,error:D,extend:E,fireEvent:u,isNumber:K,isObject:G,isString:R,merge:L,splat:S}=l,O=180/Math.PI;class x extends J{constructor(){super(...arguments);this.tree=this.startAndEndRadians=this.shapeRoot=this.points=this.options=this.nodeMap=this.mapOptionsToLevel=this.data=this.center=
void 0}alignDataLabel(a,b,c){if(!c.textPath||!c.textPath.enabled)return super.alignDataLabel.apply(this,arguments)}animate(a){var b=this.chart;let c=[b.plotWidth/2,b.plotHeight/2],d=b.plotLeft,e=b.plotTop;b=this.group;a?(a={translateX:c[0]+d,translateY:c[1]+e,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},b.attr(a)):(a={translateX:d,translateY:e,scaleX:1,scaleY:1,rotation:0,opacity:1},b.animate(a,this.options.animation))}drawPoints(){let a=this,b=a.mapOptionsToLevel,c=a.shapeRoot,d=a.group,e=a.hasRendered,
g=a.rootNode,h=a.idPreviousRoot,l=a.nodeMap;var p=l[h];let q=p&&p.shapeArgs;p=a.points;let t=a.startAndEndRadians,v=a.chart;var u=v&&v.options&&v.options.chart||{};let C="boolean"===typeof u.animation?u.animation:!0,x=a.center[3]/2,y=a.chart.renderer,D,I=!1,J=!1;if(u=!!(C&&e&&g!==h&&a.dataLabelsGroup))a.dataLabelsGroup.attr({opacity:0}),D=function(){I=!0;a.dataLabelsGroup&&a.dataLabelsGroup.animate({opacity:1,visibility:"inherit"})};p.forEach(function(f){var n=f.node,k=b[n.level];var p=f.shapeExisting||
{};let r=n.shapeArgs||{},A,B=!(!n.visible||!n.shapeArgs);r.borderRadius=a.options.borderRadius;if(e&&C){var F={};var u={end:r.end,start:r.start,innerR:r.innerR,r:r.r,x:r.x,y:r.y};B?!f.graphic&&q&&(F=g===f.id?{start:t.start,end:t.end}:q.end<=r.start?{start:t.end,end:t.end}:{start:t.start,end:t.start},F.innerR=F.r=x):f.graphic&&(h===f.id?u={innerR:x,r:x}:c&&(u=c.end<=p.start?{innerR:x,r:x,start:t.end,end:t.end}:{innerR:x,r:x,start:t.start,end:t.start}));p=F}else u=r,p={};F=[r.plotX,r.plotY];if(!f.node.isLeaf)if(g===
f.id){var w=l[g];w=w.parent}else w=f.id;E(f,{shapeExisting:r,tooltipPos:F,drillId:w,name:""+(f.name||f.id||f.index),plotX:r.plotX,plotY:r.plotY,value:n.val,isInside:B,isNull:!B});w=f.options;n=G(r)?r:{};w=G(w)?w.dataLabels:{};k=S(G(k)?k.dataLabels:{})[0];k=L({style:{}},k,w);w=k.rotationMode;if(!K(k.rotation)){if("auto"===w||"circular"===w)if(k.useHTML&&"circular"===w&&(w="auto"),1>f.innerArcLength&&f.outerArcLength>n.radius){var H=0;f.dataLabelPath&&"circular"===w&&(k.textPath={enabled:!0})}else 1<
f.innerArcLength&&f.outerArcLength>1.5*n.radius?"circular"===w?k.textPath={enabled:!0,attributes:{dy:5}}:w="parallel":(f.dataLabel&&f.dataLabel.textPath&&"circular"===w&&(k.textPath={enabled:!1}),w="perpendicular");"auto"!==w&&"circular"!==w&&(f.dataLabel&&f.dataLabel.textPath&&(k.textPath={enabled:!1}),H=n.end-(n.end-n.start)/2);"parallel"===w?k.style.width=Math.min(2.5*n.radius,(f.outerArcLength+f.innerArcLength)/2):!z(k.style.width)&&n.radius&&(k.style.width=1===f.node.level?2*n.radius:n.radius);
"perpendicular"===w&&16>f.outerArcLength&&(k.style.width=1);k.style.width=Math.max(k.style.width-2*(k.padding||0),1);H=H*O%180;"parallel"===w&&(H-=90);90<H?H-=180:-90>H&&(H+=180);k.rotation=H}k.textPath&&(0===f.shapeExisting.innerR&&k.textPath.enabled?(k.rotation=0,k.textPath.enabled=!1,k.style.width=Math.max(2*f.shapeExisting.r-2*(k.padding||0),1)):f.dlOptions&&f.dlOptions.textPath&&!f.dlOptions.textPath.enabled&&"circular"===w&&(k.textPath.enabled=!0),k.textPath.enabled&&(k.rotation=0,k.style.width=
Math.max((f.outerArcLength+f.innerArcLength)/2-2*(k.padding||0),1)));0===k.rotation&&(k.rotation=.001);H=k;f.dlOptions=H;!J&&B&&(J=!0,A=D);f.draw({animatableAttribs:u,attribs:E(p,!v.styledMode&&a.pointAttribs(f,f.selected&&"select")),onComplete:A,group:d,renderer:y,shapeType:"arc",shapeArgs:r})});u&&J?(a.hasRendered=!1,a.options.dataLabels.defer=!0,P.prototype.drawDataLabels.call(a),a.hasRendered=!0,I&&D()):P.prototype.drawDataLabels.call(a);a.idPreviousRoot=g}layoutAlgorithm(a,b,c){let d=a.start,
e=a.end-d,g=a.val,n=a.x,h=a.y,l=c&&G(c.levelSize)&&K(c.levelSize.value)?c.levelSize.value:0,p=a.r,q=p+l,t=c&&K(c.slicedOffset)?c.slicedOffset:0;return(b||[]).reduce(function(a,b){const c=1/g*b.val*e;var f=d+c/2,k=n+Math.cos(f)*t;f=h+Math.sin(f)*t;b={x:b.sliced?k:n,y:b.sliced?f:h,innerR:p,r:q,radius:l,start:d,end:d+c};a.push(b);d=b.end;return a},[])}setRootNode(a,b,c){if(1===this.nodeMap[a].level&&1===this.nodeList.filter(a=>1===a.level).length){if(""===this.idPreviousRoot)return;a=""}super.setRootNode(a,
b,c)}setShapeArgs(a,b,c){let d=[],e=c[a.level+1];a=a.children.filter(function(a){return a.visible});d=this.layoutAlgorithm(b,a,e);a.forEach(function(a,b){b=d[b];const f=b.start+(b.end-b.start)/2;var e=b.innerR+(b.r-b.innerR)/2;const g=b.end-b.start;e=0===b.innerR&&6.28<g?{x:b.x,y:b.y}:{x:b.x+Math.cos(f)*e,y:b.y+Math.sin(f)*e};const k=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=g*b.innerR,this.points[a.i].outerArcLength=g*b.r);
a.shapeArgs=L(b,{plotX:e.x,plotY:e.y+4*Math.abs(Math.cos(f))});a.values=L(b,{val:k});a.children.length&&this.setShapeArgs(a,a.values,c)},this)}translate(){let a=this;var b=a.options;let c=a.center=a.getCenter(),e=a.startAndEndRadians=p(b.startAngle,b.endAngle),g=c[3]/2,k=c[2]/2-g,h=C(a),l=a.nodeMap;let q=l&&l[h],v,x,z={};a.shapeRoot=q&&q.shapeArgs;this.processedXData||this.processData();this.generatePoints();u(this,"afterTranslate");x=a.tree=a.getTree();l=a.nodeMap;q=l[h];var y=R(q.parent)?q.parent:
"";v=l[y];const {from:E,to:G}=t.getLevelFromAndTo(q);y=I({from:E,levels:a.options.levels,to:G,defaults:{colorByPoint:b.colorByPoint,dataLabels:b.dataLabels,levelIsConstant:b.levelIsConstant,levelSize:b.levelSize,slicedOffset:b.slicedOffset}});y=t.calculateLevelSizes(y,{diffRadius:k,from:E,to:G});M(x,{before:d,idRoot:h,levelIsConstant:b.levelIsConstant,mapOptionsToLevel:y,mapIdToNode:l,points:a.points,series:a});b=l[""].shapeArgs={end:e.end,r:g,start:e.start,val:q.val,x:c[0],y:c[1]};this.setShapeArgs(v,
b,y);a.mapOptionsToLevel=y;a.data.forEach(function(b){z[b.id]&&D(31,!1,a.chart);z[b.id]=!0});z={}}}x.defaultOptions=L(J.defaultOptions,{center:["50%","50%"],clip:!1,colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"circular",style:{textOverflow:"ellipsis"}},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10});E(x.prototype,{axisTypes:[],drawDataLabels:a,getCenter:e,isCartesian:!1,onPointSupported:!0,pointAttribs:Q.prototype.pointAttribs,pointClass:v,
NodeClass:h,utils:t});c.registerSeriesType("sunburst",x);"";return x});c(a,"masters/modules/sunburst.src.js",[a["Core/Globals.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"]],function(a,b){a.Breadcrumbs=b;b.compose(a.Chart,a.defaultOptions)})});
//# sourceMappingURL=sunburst.js.map