/*
 Highcharts JS v11.1.0 (2023-10-12)

 Timeline series

 (c) 2010-2021 Highsoft AS
 Author: Daniel Studencki

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/timeline",["highcharts"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,m,e,t){a.hasOwnProperty(m)||(a[m]=t.apply(null,e),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:m,module:a[m]}})))}a=a?a._modules:
{};e(a,"Series/Timeline/TimelinePoint.js",[a["Core/Series/Point.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,e,r){const {series:m,seriesTypes:{pie:{prototype:{pointClass:q}}}}=e,{defined:x,isNumber:n,merge:k,objectEach:u,pick:p}=r;class v extends m.prototype.pointClass{constructor(){super(...arguments);this.series=this.options=void 0}alignConnector(){let a=this.series,d=this.dataLabel,f=d.connector,g=d.options||{};var b=g.connectorWidth||0;let c=this.series.chart;var l=
f.getBBox(),h=l.x+d.translateX;l=l.y+d.translateY;c.inverted?l-=b/2:h+=b/2;b=c.isInsidePlot(h,l);f[b?"animate":"attr"]({d:this.getConnectorPath()});f.addClass(`highcharts-color-${this.colorIndex}`);a.chart.styledMode||f.attr({stroke:g.connectorColor||this.color,"stroke-width":g.connectorWidth,opacity:d[x(d.newOpacity)?"newOpacity":"opacity"]})}drawConnector(){const {dataLabel:a,series:d}=this;a&&(a.connector||(a.connector=d.chart.renderer.path(this.getConnectorPath()).attr({zIndex:-1}).add(a)),this.series.chart.isInsidePlot(a.x||
0,a.y||0)&&this.alignConnector())}getConnectorPath(){var a;let d=this.series.chart,f=this.series.xAxis.len,g=d.inverted,b=g?"x2":"y2",c=this.dataLabel,l=c.targetPosition,h={x1:this.plotX,y1:this.plotY,x2:this.plotX,y2:n(l.y)?l.y:c.y},y=(c.alignAttr||c)[b[0]]<this.series.yAxis.len/2;g&&(h={x1:this.plotY,y1:f-this.plotX,x2:l.x||c.x,y2:f-this.plotX});y&&(h[b]+=c[g?"width":"height"]);u(h,function(b,a){h[a]-=(c.alignAttr||c)[a[0]]});return d.renderer.crispLine([["M",h.x1,h.y1],["L",h.x2,h.y2]],(null===
(a=c.options)||void 0===a?void 0:a.connectorWidth)||0)}init(){const a=super.init.apply(this,arguments);a.name=p(a.name,"Event");a.y=1;return a}isValid(){return null!==this.options.y}setState(){const a=super.setState;this.isNull||a.apply(this,arguments)}setVisible(a,d){const f=this.series;d=p(d,f.options.ignoreHiddenPoint);q.prototype.setVisible.call(this,a,!1);f.processData();d&&f.chart.redraw()}applyOptions(e,d){e=a.prototype.optionsToObject.call(this,e);this.userDLOptions=k(this.userDLOptions,e.dataLabels);
return super.applyOptions(e,d)}}return v});e(a,"Series/Timeline/TimelineSeriesDefaults.js",[],function(){"";return{colorByPoint:!0,stickyTracking:!1,ignoreHiddenPoint:!0,legendType:"point",lineWidth:4,tooltip:{headerFormat:'<span style="color:{point.color}">\u25cf</span> <span style="font-size: 0.8em"> {point.key}</span><br/>',pointFormat:"{point.description}"},states:{hover:{lineWidthPlus:0}},dataLabels:{enabled:!0,allowOverlap:!0,alternate:!0,backgroundColor:"#ffffff",borderWidth:1,borderColor:"#999999",
borderRadius:3,color:"#333333",connectorWidth:1,distance:100,formatter:function(){let a;a=this.series.chart.styledMode?'<span class="highcharts-color-'+this.point.colorIndex+'">\u25cf </span>':'<span style="color:'+this.point.color+'">\u25cf </span>';return a+='<span class="highcharts-strong">'+(this.key||"")+"</span><br/>"+(this.point.label||"")},style:{textOutline:"none",fontWeight:"normal",fontSize:"0.8em"},shadow:!1,verticalAlign:"middle"},marker:{enabledThreshold:0,symbol:"square",radius:6,lineWidth:2,
height:15},showInLegend:!1,colorKey:"x",legendSymbol:"rectangle"}});e(a,"Series/Timeline/TimelineSeries.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Series/Timeline/TimelinePoint.js"],a["Series/Timeline/TimelineSeriesDefaults.js"],a["Core/Utilities.js"]],function(a,e,r,t,w){const {seriesTypes:{column:m,line:n}}=a,{addEvent:k,arrayMax:u,arrayMin:p,defined:v,extend:q,merge:d,pick:f}=w;class g extends n{constructor(){super(...arguments);this.visibilityMap=this.userOptions=
this.points=this.options=this.data=void 0}alignDataLabel(b,a,l,h){var c=this.chart.inverted,d=this.visibilityMap.filter(function(b){return b}),e=this.visiblePointsCount,f=d.indexOf(b);d=this.options.dataLabels;let g=b.userDLOptions||{};f=d.alternate?f&&f!==e-1?2:1.5:1;let m;e=Math.floor(this.xAxis.len/e);let k=a.padding;b.visible&&(m=Math.abs(g.x||b.options.dataLabels.x),c?(c=2*(m-k)-b.itemHeight/2,c={width:c+"px",textOverflow:a.width/c*a.height/2>e*f?"ellipsis":"none"}):c={width:(g.width||d.width||
e*f-2*k)+"px"},a.css(c),this.chart.styledMode||a.shadow(d.shadow));super.alignDataLabel.apply(this,arguments)}bindAxes(){const b=this;super.bindAxes.call(b);["xAxis","yAxis"].forEach(function(a){"xAxis"!==a||b[a].userOptions.type||(b[a].categories=b[a].hasNames=!0)})}distributeDL(){const b=this,a=b.options.dataLabels;let l=1;if(a){const c=a.distance||0;b.points.forEach(h=>{h.options.dataLabels=d({[b.chart.inverted?"x":"y"]:a.alternate&&l%2?-c:c},h.userDLOptions);l++})}}generatePoints(){const a=this;
super.generatePoints.apply(a);a.points.forEach(function(b,l){b.applyOptions({x:a.xData[l]},a.xData[l])})}getVisibilityMap(){return(this.data.length?this.data:this.userOptions.data).map(function(a){return a&&!1!==a.visible&&!a.isNull?a:!1})}getXExtremes(a){const b=this;a=a.filter(function(a,c){return b.points[c].isValid()&&b.points[c].visible});return{min:p(a),max:u(a)}}init(){const a=this;super.init.apply(a,arguments);a.eventsToUnbind.push(k(a,"afterTranslate",function(){let c,b=Number.MAX_VALUE;
a.points.forEach(function(a){a.isInside=a.isInside&&a.visible;a.visible&&!a.isNull&&(v(c)&&(b=Math.min(b,Math.abs(a.plotX-c))),c=a.plotX)});a.closestPointRangePx=b}));a.eventsToUnbind.push(k(a,"drawDataLabels",function(){a.distributeDL()}));a.eventsToUnbind.push(k(a,"afterDrawDataLabels",function(){let b;a.points.forEach(function(a){if(b=a.dataLabel)return b.animate=function(a){this.targetPosition&&(this.targetPosition=a);return e.prototype.animate.apply(this,arguments)},b.targetPosition||(b.targetPosition=
{}),a.drawConnector()})}));a.eventsToUnbind.push(k(a.chart,"afterHideOverlappingLabel",function(){a.points.forEach(a=>{a.dataLabel&&a.dataLabel.connector&&a.dataLabel.oldOpacity!==a.dataLabel.newOpacity&&a.alignConnector()})}))}markerAttribs(a,c){var b=this.options.marker;let d=a.marker||{},e=d.symbol||b.symbol,g=f(d.width,b.width,this.closestPointRangePx),m=f(d.height,b.height),k=0;if(this.xAxis.dateTime)return super.markerAttribs.call(this,a,c);c&&(b=b.states[c]||{},c=d.states&&d.states[c]||{},
k=f(c.radius,b.radius,k+(b.radiusPlus||0)));a.hasImage=e&&0===e.indexOf("url");a={x:Math.floor(a.plotX)-g/2-k/2,y:a.plotY-m/2-k/2,width:g+k,height:m+k};return this.chart.inverted?{y:a.x&&a.width&&this.xAxis.len-a.x-a.width,x:a.y&&a.y,width:a.height,height:a.width}:a}processData(){let a=0,c;this.visibilityMap=this.getVisibilityMap();this.visibilityMap.forEach(function(b){b&&a++});this.visiblePointsCount=a;for(c=0;c<this.xData.length;c++)this.yData[c]=1;super.processData.call(this,arguments)}}g.defaultOptions=
d(n.defaultOptions,t);q(g.prototype,{drawTracker:m.prototype.drawTracker,pointClass:r,trackerGroups:["markerGroup","dataLabelsGroup"]});a.registerSeriesType("timeline",g);"";return g});e(a,"masters/modules/timeline.src.js",[],function(){})});
//# sourceMappingURL=timeline.js.map