/*
 Highcharts Gantt JS v11.1.0 (2023-10-06)

 Tree Grid

 (c) 2016-2021 Jon Arild Nygard

 License: www.highcharts.com/license
*/
'use strict';(function(g){"object"===typeof module&&module.exports?(g["default"]=g,module.exports=g):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(F){g(F);g.Highcharts=F;return g}):g("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(g){function F(g,v,u,N){g.hasOwnProperty(v)||(g[v]=N.apply(null,u),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:v,module:g[v]}})))}g=g?g._modules:
{};F(g,"Core/Axis/BrokenAxis.js",[g["Core/Axis/Stacking/StackItem.js"],g["Core/Utilities.js"]],function(g,v){const {addEvent:u,find:H,fireEvent:G,isArray:A,isNumber:p,pick:w}=v;var x;(function(a){function z(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)}function D(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)}function r(){const k=this.brokenAxis;if(k&&k.hasBreaks){const b=this.tickPositions,a=this.tickPositions.info,e=[];for(let a=
0;a<b.length;a++)k.isInAnyBreak(b[a])||e.push(b[a]);this.tickPositions=e;this.tickPositions.info=a}}function c(){this.brokenAxis||(this.brokenAxis=new E(this))}function I(){const {isDirty:k,options:{connectNulls:b},points:a,xAxis:e,yAxis:c}=this;if(k){let d=a.length;for(;d--;){const k=a[d],C=!(null===k.y&&!1===b)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(k.x,!0)||c&&c.brokenAxis&&c.brokenAxis.isInAnyBreak(k.y,!0));k.visible=C?!1:!1!==k.options.visible}}}function q(){this.drawBreaks(this.xAxis,
["x"]);this.drawBreaks(this.yAxis,w(this.pointArrayMap,["y"]))}function f(k,a){const b=this,e=b.points;let c,d,m,t;if(k&&k.brokenAxis&&k.brokenAxis.hasBreaks){const C=k.brokenAxis;a.forEach(function(a){c=C&&C.breakArray||[];d=k.isXAxis?k.min:w(b.options.threshold,k.min);e.forEach(function(e){t=w(e["stack"+a.toUpperCase()],e[a]);c.forEach(function(a){if(p(d)&&p(t)){m=!1;if(d<a.from&&t>a.to||d>a.from&&t<a.from)m="pointBreak";else if(d<a.from&&t>a.from&&t<a.to||d>a.from&&t>a.to&&t<a.from)m="pointInBreak";
m&&G(k,m,{point:e,brk:a})}})})})}}function l(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.points.slice();const c=this.yAxis;let e=this.options.gapSize,f=a.length-1;var d;if(e&&0<f)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),b&&b>e&&b>=this.basePointRange&&(e=b);f--;)d&&!1!==d.visible||(d=a[f+1]),b=a[f],!1!==d.visible&&!1!==b.visible&&(d.x-b.x>e&&(d=(b.x+d.x)/2,a.splice(f+1,0,{isNull:!0,x:d}),c.stacking&&this.options.stacking&&(d=c.stacking.stacks[this.stackKey][d]=new g(c,
c.options.stackLabels,!1,d,this.stack),d.total=0)),d=b);return this.getGraphPath(a)}const n=[];a.compose=function(a,b){v.pushUnique(n,a)&&(a.keepProps.push("brokenAxis"),u(a,"init",c),u(a,"afterInit",z),u(a,"afterSetTickPositions",r),u(a,"afterSetOptions",D));if(v.pushUnique(n,b)){const a=b.prototype;a.drawBreaks=f;a.gappedPath=l;u(b,"afterGeneratePoints",I);u(b,"afterRender",q)}return a};class E{static isInBreak(a,b){const c=a.repeat||Infinity,e=a.from,k=a.to-a.from;b=b>=e?(b-e)%c:c-(e-b)%c;return a.inclusive?
b<=k:b<k&&0!==b}static lin2Val(a){var b=this.brokenAxis;b=b&&b.breakArray;if(!b||!p(a))return a;let c,e;for(e=0;e<b.length&&!(c=b[e],c.from>=a);e++)c.to<a?a+=c.len:E.isInBreak(c,a)&&(a+=c.len);return a}static val2Lin(a){var b=this.brokenAxis;b=b&&b.breakArray;if(!b||!p(a))return a;let c=a,e,f;for(f=0;f<b.length;f++)if(e=b[f],e.to<=a)c-=e.len;else if(e.from>=a)break;else if(E.isInBreak(e,a)){c-=a-e.from;break}return c}constructor(a){this.hasBreaks=!1;this.axis=a}findBreakAt(a,b){return H(b,function(b){return b.from<
a&&a<b.to})}isInAnyBreak(a,b){const c=this.axis,e=c.options.breaks||[];let f=e.length,d,m,t;if(f&&p(a)){for(;f--;)E.isInBreak(e[f],a)&&(d=!0,m||(m=w(e[f].showPoints,!c.isXAxis)));t=d&&b?d&&!m:d}return t}setBreaks(a,b){const c=this,e=c.axis,f=A(a)&&!!a.length;e.isDirty=c.hasBreaks!==f;c.hasBreaks=f;a!==e.options.breaks&&(e.options.breaks=e.userOptions.breaks=a);e.forceRedraw=!0;e.series.forEach(function(a){a.isDirty=!0});f||e.val2lin!==E.val2Lin||(delete e.val2lin,delete e.lin2val);f&&(e.userOptions.ordinal=
!1,e.lin2val=E.lin2Val,e.val2lin=E.val2Lin,e.setExtremes=function(a,b,f,l,B){if(c.hasBreaks){const e=this.options.breaks||[];let d;for(;d=c.findBreakAt(a,e);)a=d.to;for(;d=c.findBreakAt(b,e);)b=d.from;b<a&&(b=a)}e.constructor.prototype.setExtremes.call(this,a,b,f,l,B)},e.setAxisTranslation=function(){e.constructor.prototype.setAxisTranslation.call(this);c.unitLength=void 0;if(c.hasBreaks){const a=e.options.breaks||[],b=[],f=[],l=w(e.pointRangePadding,0);let B=0,r,n,k=e.userMin||e.min,q=e.userMax||
e.max,h,y;a.forEach(function(h){n=h.repeat||Infinity;p(k)&&p(q)&&(E.isInBreak(h,k)&&(k+=h.to%n-k%n),E.isInBreak(h,q)&&(q-=q%n-h.from%n))});a.forEach(function(a){h=a.from;n=a.repeat||Infinity;if(p(k)&&p(q)){for(;h-n>k;)h-=n;for(;h<k;)h+=n;for(y=h;y<q;y+=n)b.push({value:y,move:"in"}),b.push({value:y+a.to-a.from,move:"out",size:a.breakSize})}});b.sort(function(h,a){return h.value===a.value?("in"===h.move?0:1)-("in"===a.move?0:1):h.value-a.value});r=0;h=k;b.forEach(function(a){r+="in"===a.move?1:-1;1===
r&&"in"===a.move&&(h=a.value);0===r&&p(h)&&(f.push({from:h,to:a.value,len:a.value-h-(a.size||0)}),B+=a.value-h-(a.size||0))});c.breakArray=f;p(k)&&p(q)&&p(e.min)&&(c.unitLength=q-k-B+l,G(e,"afterBreaks"),e.staticScale?e.transA=e.staticScale:c.unitLength&&(e.transA*=(q-e.min+l)/c.unitLength),l&&(e.minPixelPadding=e.transA*(e.minPointOffset||0)),e.min=k,e.max=q)}});w(b,!0)&&e.chart.redraw()}}a.Additions=E})(x||(x={}));return x});F(g,"Core/Axis/GridAxis.js",[g["Core/Axis/Axis.js"],g["Core/Globals.js"],
g["Core/Utilities.js"]],function(g,v,u){function H(a,y){const h={width:0,height:0};y.forEach(function(y){y=a[y];let c,b;u.isObject(y,!0)&&(b=u.isObject(y.label,!0)?y.label:{},y=b.getBBox?b.getBBox().height:0,b.textStr&&!m(b.textPxLength)&&(b.textPxLength=b.getBBox().width),c=m(b.textPxLength)?Math.round(b.textPxLength):0,b.textStr&&(c=Math.round(b.getBBox().width)),h.height=Math.max(y,h.height),h.width=Math.max(c,h.width))});"treegrid"===this.options.type&&this.treeGrid&&this.treeGrid.mapOfPosToGridNode&&
(h.width+=this.options.labels.indentation*((this.treeGrid.mapOfPosToGridNode[-1].height||0)-1));return h}function G(){const {grid:a}=this;(a&&a.columns||[]).forEach(function(a){a.getOffset()})}function A(a){if(!0===(this.options.grid||{}).enabled){const {axisTitle:b,height:c,horiz:y,left:e,offset:d,opposite:f,options:m,top:B,width:l}=this;var h=this.tickSize();const n=b&&b.getBBox().width,k=m.title.x,t=m.title.y,q=K(m.title.margin,y?5:10),r=b?this.chart.renderer.fontMetrics(b).f:0;h=(y?B+c:e)+(y?
1:-1)*(f?-1:1)*(h?h[0]/2:0)+(this.side===J.bottom?r:0);a.titlePosition.x=y?e-(n||0)/2-q+k:h+(f?l:0)+d+k;a.titlePosition.y=y?h-(f?c:0)+(f?r:-r)/2+d+t:B-q+t}}function p(){const {chart:a,options:{grid:b={}},userOptions:c}=this;if(b.enabled){var d=this.options;d.labels.align=K(d.labels.align,"center");this.categories||(d.showLastLabel=!1);this.labelRotation=0;d.labels.rotation=0}if(b.columns){d=this.grid.columns=[];let h=this.grid.columnIndex=0;for(;++h<b.columns.length;){var f=t(c,b.columns[b.columns.length-
h-1],{isInternal:!0,linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete f.grid.columns;f=new g(this.chart,f,"yAxis");f.grid.isColumn=!0;f.grid.columnIndex=h;e(a.axes,f);e(a[this.coll]||[],f);d.push(f)}}}function w(){var a=this.grid,b=this.options;if(!0===(b.grid||{}).enabled){var c=this.min||0;const h=this.max||0;this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine){var e=
b.lineWidth;if(e){e=this.getLinePath(e);var d=e[0],f=e[1],m=((this.tickSize("tick")||[1])[0]-1)*(this.side===J.top||this.side===J.left?-1:1);"M"===d[0]&&"L"===f[0]&&(this.horiz?(d[2]+=m,f[2]+=m):(d[1]+=m,f[1]+=m));!this.horiz&&this.chart.marginRight&&(d=[d,["L",this.left,d[2]||0]],m=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(h+this.tickmarkOffset)],f=[["M",f[1]||0,this.toPixels(h+this.tickmarkOffset)],m],this.grid.upperBorder||0===c%1||(this.grid.upperBorder=this.grid.renderBorder(d)),
this.grid.upperBorder&&(this.grid.upperBorder.attr({stroke:b.lineColor,"stroke-width":b.lineWidth}),this.grid.upperBorder.animate({d})),this.grid.lowerBorder||0===h%1||(this.grid.lowerBorder=this.grid.renderBorder(f)),this.grid.lowerBorder&&(this.grid.lowerBorder.attr({stroke:b.lineColor,"stroke-width":b.lineWidth}),this.grid.lowerBorder.animate({d:f})));this.grid.axisLineExtra?(this.grid.axisLineExtra.attr({stroke:b.lineColor,"stroke-width":b.lineWidth}),this.grid.axisLineExtra.animate({d:e})):this.grid.axisLineExtra=
this.grid.renderBorder(e);this.axisLine[this.showAxis?"show":"hide"]()}}(a&&a.columns||[]).forEach(a=>a.render());if(!this.horiz&&this.chart.hasRendered&&(this.scrollbar||this.linkedParent&&this.linkedParent.scrollbar)){a=this.tickmarkOffset;b=this.tickPositions[this.tickPositions.length-1];e=this.tickPositions[0];let d,f;for(;(d=this.hiddenLabels.pop())&&d.element;)d.show();for(;(f=this.hiddenMarks.pop())&&f.element;)f.show();(d=this.ticks[e].label)&&(c-e>a?this.hiddenLabels.push(d.hide()):d.show());
(d=this.ticks[b].label)&&(b-h>a?this.hiddenLabels.push(d.hide()):d.show());(c=this.ticks[b].mark)&&b-h<a&&0<b-h&&this.ticks[b].isLast&&this.hiddenMarks.push(c.hide())}}}function x(){const a=this.tickPositions&&this.tickPositions.info,b=this.options,d=this.userOptions.labels||{};(b.grid||{}).enabled&&(this.horiz?(this.series.forEach(a=>{a.options.pointRange=0}),a&&b.dateTimeLabelFormats&&b.labels&&!C(d.align)&&(!1===b.dateTimeLabelFormats[a.unitName].range||1<a.count)&&(b.labels.align="left",C(d.x)||
(b.labels.x=3))):"treegrid"!==this.options.type&&this.grid&&this.grid.columns&&(this.minPointOffset=this.tickInterval))}function a(a){const h=this.options;a=a.userOptions;const b=h&&u.isObject(h.grid,!0)?h.grid:{};let d;!0===b.enabled&&(d=t(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"0.9em"}},
margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a),"xAxis"===this.coll&&(C(a.linkedTo)&&!C(a.tickPixelInterval)&&(d.tickPixelInterval=350),C(a.tickPixelInterval)||!C(a.linkedTo)||C(a.tickPositioner)||C(a.tickInterval)||(d.tickPositioner=function(a,h){var b=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var c=
d.units||[];let f;var e=1;let y="year";for(let a=0;a<c.length;a++){const h=c[a];if(h&&h[0]===b.unitName){f=a;break}}(c=m(f)&&c[f+1])?(y=c[0]||"year",e=(e=c[1])&&e[0]||1):"year"===b.unitName&&(e=10*b.count);b=B[y];this.tickInterval=b*e;return this.chart.time.getTimeTicks({unitRange:b,count:e,unitName:y},a,h,this.options.startOfWeek)}})),t(!0,this.options,d),this.horiz&&(h.minPadding=K(a.minPadding,0),h.maxPadding=K(a.maxPadding,0)),m(h.grid.borderWidth)&&(h.tickWidth=h.lineWidth=b.borderWidth))}function z(a){a=
(a=a.userOptions)&&a.grid||{};const h=a.columns;a.enabled&&h&&t(!0,this.options,h[h.length-1])}function D(){(this.grid.columns||[]).forEach(a=>a.setScale())}function r(a){const {horiz:h,maxLabelDimensions:b,options:{grid:c={}}}=this;if(c.enabled&&b){var e=2*this.options.labels.distance;e=h?c.cellHeight||e+b.height:e+b.width;d(a.tickSize)?a.tickSize[0]=e:a.tickSize=[e,0]}}function c(){this.axes.forEach(a=>{(a.grid&&a.grid.columns||[]).forEach(a=>{a.setAxisSize();a.setAxisTranslation()})})}function I(a){const {grid:h}=
this;(h.columns||[]).forEach(h=>h.destroy(a.keepEvents));h.columns=void 0}function q(a){a=a.userOptions||{};const h=a.grid||{};h.enabled&&C(h.borderColor)&&(a.tickColor=a.lineColor=h.borderColor);this.grid||(this.grid=new P(this));this.hiddenLabels=[];this.hiddenMarks=[]}function f(a){var h=this.label;const b=this.axis;var c=b.reversed,d=b.chart,e=b.options.grid||{};const f=b.options.labels,B=f.align;var l=J[b.side],k=a.tickmarkOffset,n=b.tickPositions;const r=this.pos-k;n=m(n[a.index+1])?n[a.index+
1]-k:(b.max||0)+k;var t=b.tickSize("tick");k=t?t[0]:0;t=t?t[1]/2:0;if(!0===e.enabled){let m;"top"===l?(e=b.top+b.offset,m=e-k):"bottom"===l?(m=d.chartHeight-b.bottom+b.offset,e=m+k):(e=b.top+b.len-(b.translate(c?n:r)||0),m=b.top+b.len-(b.translate(c?r:n)||0));"right"===l?(l=d.chartWidth-b.right+b.offset,c=l+k):"left"===l?(c=b.left+b.offset,l=c-k):(l=Math.round(b.left+(b.translate(c?n:r)||0))-t,c=Math.min(Math.round(b.left+(b.translate(c?r:n)||0))-t,b.left+b.len));this.slotWidth=c-l;a.pos.x="left"===
B?l:"right"===B?c:l+(c-l)/2;a.pos.y=m+(e-m)/2;h&&(d=d.renderer.fontMetrics(h),h=h.getBBox().height,a.pos.y=f.useHTML?a.pos.y+(d.b+-(h/2)):a.pos.y+((d.b-(d.h-d.f))/2+-((Math.round(h/d.h)-1)*d.h/2)));a.pos.x+=b.horiz&&f.x||0}}function l(a){const {axis:b,value:h}=a;if(b.options.grid&&b.options.grid.enabled){var c=b.tickPositions;const d=(b.linkedParent||b).series[0],e=h===c[0];c=h===c[c.length-1];const f=d&&F(d.options.data,function(a){return a[b.isXAxis?"x":"y"]===h});let m;f&&d.is("gantt")&&(m=t(f),
v.seriesTypes.gantt.prototype.pointClass.setGanttPointAliases(m));a.isFirst=e;a.isLast=c;a.point=m}}function n(){const a=this.options,b=this.categories,c=this.tickPositions,d=c[0],e=c[c.length-1],f=this.linkedParent&&this.linkedParent.min||this.min,m=this.linkedParent&&this.linkedParent.max||this.max,l=this.tickInterval;!0!==(a.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(d<f&&d+l>f&&!a.startOnTick&&(c[0]=f),e>m&&e-l<m&&!a.endOnTick&&(c[c.length-1]=m))}function E(a){const {options:{grid:b=
{}}}=this;return!0===b.enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))}const {dateFormats:k}=v,{addEvent:b,defined:C,erase:e,find:F,isArray:d,isNumber:m,merge:t,pick:K,timeUnits:B,wrap:O}=u;var J;(function(a){a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(J||(J={}));const L=[];class P{constructor(a){this.axis=a}isOuterAxis(){const a=this.axis,b=a.grid.columnIndex,c=a.linkedParent&&a.linkedParent.grid.columns||a.grid.columns,
d=b?a.linkedParent:a;let e=-1,f=0;(a.chart[a.coll]||[]).forEach((b,c)=>{b.side!==a.side||b.options.isInternal||(f=c,b===d&&(e=c))});return f===e&&(m(b)?c.length===b:!0)}renderBorder(a){const b=this.axis,c=b.chart.renderer,d=b.options;a=c.path(a).addClass("highcharts-axis-line").add(b.axisBorder);c.styledMode||a.attr({stroke:d.lineColor,"stroke-width":d.lineWidth,zIndex:7});return a}}k.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};k.W=function(a){const b=this,c=new this.Date(a);["Hours",
"Milliseconds","Minutes","Seconds"].forEach(function(a){b.set(a,c,0)});var d=(this.get("Day",c)+6)%7;a=new this.Date(c.valueOf());this.set("Date",a,this.get("Date",c)-d+3);d=new this.Date(this.get("FullYear",a),0,1);4!==this.get("Day",d)&&(this.set("Month",c,0),this.set("Date",c,1+(11-this.get("Day",d))%7));return(1+Math.floor((a.valueOf()-d.valueOf())/6048E5)).toString()};"";return{compose:function(d,e,m){u.pushUnique(L,d)&&(d.keepProps.push("grid"),d.prototype.getMaxLabelDimensions=H,O(d.prototype,
"unsquish",E),b(d,"init",q),b(d,"afterGetOffset",G),b(d,"afterGetTitlePosition",A),b(d,"afterInit",p),b(d,"afterRender",w),b(d,"afterSetAxisTranslation",x),b(d,"afterSetOptions",a),b(d,"afterSetOptions",z),b(d,"afterSetScale",D),b(d,"afterTickSize",r),b(d,"trimTicks",n),b(d,"destroy",I));u.pushUnique(L,e)&&b(e,"afterSetChartSize",c);u.pushUnique(L,m)&&(b(m,"afterGetLabelPosition",f),b(m,"labelFormat",l));return d}}});F(g,"Gantt/Tree.js",[g["Core/Utilities.js"]],function(g){function v(g,w,x,a,z,D){let r=
0,c=0,I=D&&D.after;var q=D&&D.before;w={data:a,depth:x-1,id:g,level:x,parent:w};let f,l;"function"===typeof q&&q(w,D);q=(z[g]||[]).map(function(a){const n=v(a.id,g,x+1,a,z,D),k=a.start;a=!0===a.milestone?k:a.end;f=!G(f)||k<f?k:f;l=!G(l)||a>l?a:l;r=r+1+n.descendants;c=Math.max(n.height+1,c);return n});a&&(a.start=A(a.start,f),a.end=A(a.end,l));H(w,{children:q,descendants:r,height:c});"function"===typeof I&&I(w,D);return w}function u(g,w){const p=g.reduce(function(a,g){const p=A(g.parent,"");"undefined"===
typeof a[p]&&(a[p]=[]);a[p].push(g);return a},{});Object.keys(p).forEach(function(a,g){const z=p[a];""!==a&&-1===w.indexOf(a)&&(z.forEach(function(a){g[""].push(a)}),delete g[a])});return p}const {extend:H,isNumber:G,pick:A}=g;return{getListOfParents:u,getNode:v,getTree:function(g,w){const p=g.map(function(a){return a.id});g=u(g,p);return v("",null,1,null,g,w)}}});F(g,"Core/Axis/TreeGrid/TreeGridTick.js",[g["Core/Utilities.js"]],function(g){function v(){this.treeGrid||(this.treeGrid=new D(this))}
function u(a,c){a=a.treeGrid;const g=!a.labelIcon,q=c.renderer;var f=c.xy;const l=c.options,n=l.width||0,r=l.height||0;var k=f.x-n/2-(l.padding||0);f=f.y-r/2;const b=c.collapsed?90:180,p=c.show&&w(f);let e=a.labelIcon;e||(a.labelIcon=e=q.path(q.symbols[l.type](l.x||0,l.y||0,n,r)).addClass("highcharts-label-icon").add(c.group));e[p?"show":"hide"]();q.styledMode||e.attr({cursor:"pointer",fill:x(c.color,"#666666"),"stroke-width":1,stroke:l.lineColor,strokeWidth:l.lineWidth||0});e[g?"attr":"animate"]({translateX:k,
translateY:f,rotation:b})}function H(a,c,g,q,f,l,n,z,k){var b=x(this.options&&this.options.labels,l);l=this.pos;var r=this.axis;const e="treegrid"===r.options.type;a=a.apply(this,[c,g,q,f,b,n,z,k]);e&&(c=b&&p(b.symbol,!0)?b.symbol:{},b=b&&w(b.indentation)?b.indentation:0,l=(l=(r=r.treeGrid.mapOfPosToGridNode)&&r[l])&&l.depth||1,a.x+=(c.width||0)+2*(c.padding||0)+(l-1)*b);return a}function G(a){const c=this;var g=c.pos,q=c.axis;const f=c.label;var l=q.treeGrid.mapOfPosToGridNode,n=q.options;const r=
x(c.options&&c.options.labels,n&&n.labels);var k=r&&p(r.symbol,!0)?r.symbol:{};const b=(l=l&&l[g])&&l.depth;n="treegrid"===n.type;const z=-1<q.tickPositions.indexOf(g);g=q.chart.styledMode;n&&l&&f&&f.element&&f.addClass("highcharts-treegrid-node-level-"+b);a.apply(c,Array.prototype.slice.call(arguments,1));n&&f&&f.element&&l&&l.descendants&&0<l.descendants&&(q=q.treeGrid.isCollapsed(l),u(c,{color:!g&&f.styles&&f.styles.color||"",collapsed:q,group:f.parentGroup,options:k,renderer:f.renderer,show:z,
xy:f.xy}),k="highcharts-treegrid-node-"+(q?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(q?"collapsed":"expanded")).removeClass(k),g||f.css({cursor:"pointer"}),[f,c.treeGrid.labelIcon].forEach(a=>{a&&!a.attachedTreeGridEvents&&(A(a.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),A(a.element,"mouseout",function(){{const a=p(r.style)?r.style:{};f.removeClass("highcharts-treegrid-node-active");
f.renderer.styledMode||f.css({textDecoration:a.textDecoration})}}),A(a.element,"click",function(){c.treeGrid.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}const {addEvent:A,isObject:p,isNumber:w,pick:x,wrap:a}=g,z=[];class D{static compose(r){g.pushUnique(z,r)&&(A(r,"init",v),a(r.prototype,"getLabelPosition",H),a(r.prototype,"renderLabel",G),r.prototype.collapse=function(a){this.treeGrid.collapse(a)},r.prototype.expand=function(a){this.treeGrid.expand(a)},r.prototype.toggleCollapse=function(a){this.treeGrid.toggleCollapse(a)})}constructor(a){this.tick=
a}collapse(a){var c=this.tick;const g=c.axis,q=g.brokenAxis;q&&g.treeGrid.mapOfPosToGridNode&&(c=g.treeGrid.collapse(g.treeGrid.mapOfPosToGridNode[c.pos]),q.setBreaks(c,x(a,!0)))}destroy(){this.labelIcon&&this.labelIcon.destroy()}expand(a){var c=this.tick;const g=c.axis,q=g.brokenAxis;q&&g.treeGrid.mapOfPosToGridNode&&(c=g.treeGrid.expand(g.treeGrid.mapOfPosToGridNode[c.pos]),q.setBreaks(c,x(a,!0)))}toggleCollapse(a){var c=this.tick;const g=c.axis,q=g.brokenAxis;q&&g.treeGrid.mapOfPosToGridNode&&
(c=g.treeGrid.toggleCollapse(g.treeGrid.mapOfPosToGridNode[c.pos]),q.setBreaks(c,x(a,!0)))}}return D});F(g,"Series/TreeUtilities.js",[g["Core/Color/Color.js"],g["Core/Utilities.js"]],function(g,v){function u(a,g){var p=g.before;const r=g.idRoot,c=g.mapIdToNode[r],z=g.points[a.i],q=z&&z.options||{},f=[];let l=0;a.levelDynamic=a.level-(!1!==g.levelIsConstant?0:c.level);a.name=x(z&&z.name,"");a.visible=r===a.id||!0===g.visible;"function"===typeof p&&(a=p(a,g));a.children.forEach((c,q)=>{const k=H({},
g);H(k,{index:q,siblings:a.children.length,visible:a.visible});c=u(c,k);f.push(c);c.visible&&(l+=c.val)});p=x(q.value,l);a.visible=0<=p&&(0<l||a.visible);a.children=f;a.childrenTotal=l;a.isLeaf=a.visible&&!l;a.val=p;return a}const {extend:H,isArray:G,isNumber:A,isObject:p,merge:w,pick:x}=v;return{getColor:function(a,p){const z=p.index;var r=p.mapOptionsToLevel;const c=p.parentColor,w=p.parentColorIndex,q=p.series;var f=p.colors;const l=p.siblings;var n=q.points,u=q.chart.options.chart;let k;var b;
let v;if(a){n=n[a.i];a=r[a.level]||{};if(r=n&&a.colorByPoint){k=n.index%(f?f.length:u.colorCount);var e=f&&f[k]}if(!q.chart.styledMode){f=n&&n.options.color;u=a&&a.color;if(b=c)b=(b=a&&a.colorVariation)&&"brightness"===b.key&&z&&l?g.parse(c).brighten(z/l*b.to).get():c;b=x(f,u,e,b,q.color)}v=x(n&&n.options.colorIndex,a&&a.colorIndex,k,w,p.colorIndex)}return{color:b,colorIndex:v}},getLevelOptions:function(a){let g={},u,r,c;if(p(a)){c=A(a.from)?a.from:1;var v=a.levels;r={};u=p(a.defaults)?a.defaults:
{};G(v)&&(r=v.reduce((a,f)=>{let g,n;p(f)&&A(f.level)&&(n=w({},f),g=x(n.levelIsConstant,u.levelIsConstant),delete n.levelIsConstant,delete n.level,f=f.level+(g?0:c-1),p(a[f])?w(!0,a[f],n):a[f]=n);return a},{}));v=A(a.to)?a.to:1;for(a=0;a<=v;a++)g[a]=w({},u,p(r[a])?r[a]:{})}return g},setTreeValues:u,updateRootId:function(a){if(p(a)){var g=p(a.options)?a.options:{};g=x(a.rootNode,g.rootId,"");p(a.userOptions)&&(a.userOptions.rootId=g);a.rootNode=g}return g}}});F(g,"Core/Axis/TreeGrid/TreeGridAxis.js",
[g["Core/Axis/BrokenAxis.js"],g["Core/Axis/GridAxis.js"],g["Gantt/Tree.js"],g["Core/Axis/TreeGrid/TreeGridTick.js"],g["Series/TreeUtilities.js"],g["Core/Utilities.js"]],function(g,v,u,F,G,A){function p(a,b){const d=a.collapseEnd||0;a=a.collapseStart||0;d>=b&&(a-=.5);return{from:a,to:d,showPoints:!1}}function w(a,b,c){const d=[],e=[],f={},g="boolean"===typeof b?b:!1;let m={},k=-1;a=u.getTree(a,{after:function(a){a=m[a.pos];let b=0,d=0;a.children.forEach(function(a){d+=(a.descendants||0)+1;b=Math.max((a.height||
0)+1,b)});a.descendants=d;a.height=b;a.collapsed&&e.push(a)},before:function(a){function b(a){return a.name===e}const c=l(a.data,!0)?a.data:{},e=n(c.name)?c.name:"";var h=f[a.parent];h=l(h,!0)?m[h.pos]:null;let B,t;g&&l(h,!0)&&(B=H(h.children,b))?(t=B.pos,B.nodes.push(a)):t=k++;m[t]||(m[t]=B={depth:h?h.depth+1:0,name:e,id:c.id,nodes:[a],children:[],pos:t},-1!==t&&d.push(e),l(h,!0)&&h.children.push(B));n(a.id)&&(f[a.id]=a);B&&!0===c.collapsed&&(B.collapsed=!0);a.pos=t}});m=function(a,b){function c(a,
d,e){let f=d+(-1===d?0:b-1);const g=(f-d)/2,h=d+g;a.nodes.forEach(function(a){const b=a.data;l(b,!0)&&(b.y=d+(b.seriesIndex||0),delete b.seriesIndex);a.pos=h});e[h]=a;a.pos=h;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,e);f=(a.collapseEnd||0)-.5});a.collapseEnd=f+.5;return e}return c(a["-1"],-1,{})}(m,c);return{categories:d,mapOfIdToNode:f,mapOfPosToGridNode:m,collapsedNodes:e,tree:a}}function x(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var c=
b.options||{};const d=c.labels,e=c.uniqueNames;c=c.max;let g=0,m;if(!b.treeGrid.mapOfPosToGridNode||b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){m=b.series.reduce(function(a,b){b.visible&&((b.options.data||[]).forEach(function(c){b.options.keys&&b.options.keys.length&&(c=b.pointClass.prototype.optionsToObject.call({series:b},c),b.pointClass.setGanttPointAliases(c));l(c,!0)&&(c.seriesIndex=g,a.push(c))}),!0===e&&g++);return a},[]);if(c&&m.length<c)for(let a=m.length;a<=
c;a++)m.push({name:a+"\u200b"});c=w(m,e||!1,!0===e?g:1);b.categories=c.categories;b.treeGrid.mapOfPosToGridNode=c.mapOfPosToGridNode;b.hasNames=!0;b.treeGrid.tree=c.tree;b.series.forEach(function(a){const b=(a.options.data||[]).map(function(b){f(b)&&a.options.keys&&a.options.keys.length&&m.forEach(function(a){0<=b.indexOf(a.x)&&0<=b.indexOf(a.x2)&&(b=a)});return l(b,!0)?E(b):b});a.visible&&a.setData(b,!1)});b.treeGrid.mapOptionsToLevel=r({defaults:d,from:1,levels:d&&d.levels,to:b.treeGrid.tree&&b.treeGrid.tree.height});
"beforeRender"===a.type&&(b.treeGrid.collapsedNodes=c.collapsedNodes)}})}function a(a,b){var c=this.treeGrid.mapOptionsToLevel||{};const d=this.ticks;let f=d[b],g,m;"treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode?(m=this.treeGrid.mapOfPosToGridNode[b],(c=c[m.depth])&&(g={labels:c}),!f&&e?d[b]=new e(this,b,void 0,void 0,{category:m.name,tickmarkOffset:m.tickmarkOffset,options:g}):(f.parameters.category=m.name,f.options=g,f.addLabel())):a.apply(this,Array.prototype.slice.call(arguments,
1))}function z(a,b,e,f){const d=this,g="treegrid"===e.type;d.treeGrid||(d.treeGrid=new M(d));g&&(c(b,"beforeRender",x),c(b,"beforeRedraw",x),c(b,"addSeries",function(a){a.options.data&&(a=w(a.options.data,e.uniqueNames||!1,1),d.treeGrid.collapsedNodes=(d.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),c(d,"foundExtremes",function(){d.treeGrid.collapsedNodes&&d.treeGrid.collapsedNodes.forEach(function(a){const b=d.treeGrid.collapse(a);d.brokenAxis&&(d.brokenAxis.setBreaks(b,!1),d.treeGrid.collapsedNodes&&
(d.treeGrid.collapsedNodes=d.treeGrid.collapsedNodes.filter(b=>a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd)))})}),c(d,"afterBreaks",function(){"yAxis"===d.coll&&!d.staticScale&&d.chart.options.chart.height&&(d.isDirty=!0)}),e=E({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},e,{reversed:!0,grid:{columns:void 0}}));a.apply(d,[b,e,f]);g&&(d.hasNames=
!0,d.options.showLastLabel=!0)}function D(a){const b=this.options;"treegrid"===b.type?(this.min=k(this.userMin,b.min,this.dataMin),this.max=k(this.userMax,b.max,this.dataMax),q(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}const {getLevelOptions:r}=G,{addEvent:c,find:H,fireEvent:q,isArray:f,isObject:l,isString:n,
merge:E,pick:k,wrap:b}=A,C=[];let e;class M{static compose(c,f,l,k){if(A.pushUnique(C,c)){-1===c.keepProps.indexOf("treeGrid")&&c.keepProps.push("treeGrid");const d=c.prototype;b(d,"generateTick",a);b(d,"init",z);b(d,"setTickInterval",D);d.utils={getNode:u.getNode}}A.pushUnique(C,k)&&(e||(e=k));v.compose(c,f,k);g.compose(c,l);F.compose(k);return c}constructor(a){this.axis=a}setCollapsedStatus(a){const b=this.axis,c=b.chart;b.series.forEach(function(b){const d=b.options.data;if(a.id&&d){const e=c.get(a.id);
b=d[b.data.indexOf(e)];e&&b&&(e.collapsed=a.collapsed,b.collapsed=a.collapsed)}})}collapse(a){const b=this.axis,c=b.options.breaks||[],d=p(a,b.max);c.push(d);a.collapsed=!0;b.treeGrid.setCollapsedStatus(a);return c}expand(a){const b=this.axis,c=b.options.breaks||[],d=p(a,b.max);a.collapsed=!1;b.treeGrid.setCollapsedStatus(a);return c.reduce(function(a,b){b.to===d.to&&b.from===d.from||a.push(b);return a},[])}getTickPositions(){const a=this.axis,b=Math.floor(a.min/a.tickInterval)*a.tickInterval,c=Math.ceil(a.max/
a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(d,e){e=+e;!(e>=b&&e<=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(e)||d.push(e);return d},[])}isCollapsed(a){const b=this.axis,c=b.options.breaks||[],d=p(a,b.max);return c.some(function(a){return a.from===d.from&&a.to===d.to})}toggleCollapse(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)}}return M});F(g,"masters/modules/treegrid.src.js",[g["Core/Globals.js"],g["Core/Axis/TreeGrid/TreeGridAxis.js"]],
function(g,v){v.compose(g.Axis,g.Chart,g.Series,g.Tick)})});
//# sourceMappingURL=treegrid.js.map