!/**
 * Highcharts JS v13.0.0-modified (2026-08-14)
 * @module highcharts/modules/vector
 * @requires highcharts
 *
 * Vector plot series module
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Torstein Hønsi
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts,t._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/modules/vector",["highcharts/highcharts"],function(t){return e(t,t.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/modules/vector"]=e(t._Highcharts,t._Highcharts.SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,(t,e)=>(()=>{"use strict";var r={512(t){t.exports=e},944(e){e.exports=t}};let i={};function o(t){let e=i[t];if(void 0!==e)return e.exports;let s=i[t]={exports:{}};return r[t](s,s.exports,o),s.exports}o.n=t=>{let e=t&&t.__esModule?()=>t.default:()=>t;return o.d(e,{a:e}),e},o.d=(t,e)=>{if(Array.isArray(e))for(var r=0;r<e.length;){var i=e[r++],s=e[r++];o.o(t,i)?0===s&&r++:0===s?Object.defineProperty(t,i,{enumerable:!0,value:e[r++]}):Object.defineProperty(t,i,{enumerable:!0,get:s})}else for(var i in e)o.o(e,i)&&!o.o(t,i)&&Object.defineProperty(t,i,{enumerable:!0,get:e[i]})},o.o=(t,e)=>Object.prototype.hasOwnProperty.call(t,e);let s={};o.d(s,{default:()=>g});var n=o(944),a=o.n(n),h=o(512),l=o.n(h);let{series:p,seriesTypes:{scatter:c}}=l();class d extends c{animate(t){t?this.markerGroup.attr({opacity:.01}):this.markerGroup.animate({opacity:1},(0,n.animObject)(this.options.animation))}arrow(t){let e=t.length/this.lengthMax*this.options.vectorLength/20,r={start:10*e,center:0,end:-10*e}[this.options.rotationOrigin]||0;return[["M",0,7*e+r],["L",-1.5*e,7*e+r],["L",0,10*e+r],["L",1.5*e,7*e+r],["L",0,7*e+r],["L",0,-10*e+r]]}drawPoints(){let t=this.chart;for(let e of this.points){let r=e.plotX,i=e.plotY;!1===this.options.clip||t.isInsidePlot(r,i,{inverted:t.inverted})?(e.graphic||(e.graphic=this.chart.renderer.path().add(this.markerGroup).addClass("highcharts-point highcharts-color-"+(e.colorIndex??e.series.colorIndex))),e.graphic.attr({d:this.arrow(e),translateX:r,translateY:i,rotation:e.direction}),this.chart.styledMode||e.graphic.attr(this.pointAttribs(e))):e.graphic&&(e.graphic=e.graphic.destroy())}}pointAttribs(t,e){let r=this.options,i=t?.color||this.color,o=this.options.lineWidth;return e&&(i=r.states?.[e]?.color||i,o=(r.states?.[e]?.lineWidthPlus||0)+(r.states?.[e]?.lineWidth||o||0)),{stroke:i,"stroke-width":o}}translate(){p.prototype.translate.call(this),this.lengthMax=(0,n.arrayMax)(this.getColumn("length"))}}d.defaultOptions=(0,n.merge)(c.defaultOptions,{lineWidth:2,marker:void 0,rotationOrigin:"center",states:{hover:{lineWidthPlus:1}},tooltip:{pointFormat:"<b>[{point.x}, {point.y}]</b><br/>Length: <b>{point.length}</b><br/>Direction: <b>{point.direction}\xb0</b><br/>"},vectorLength:20}),(0,n.extend)(d.prototype,{drawGraph:a().noop,getSymbol:a().noop,markerAttribs:a().noop,parallelArrays:["x","y","length","direction"],pointArrayMap:["y","length","direction"]}),l().registerSeriesType("vector",d);let g=a();return s.default})());