/* *
 *
 *  (c) 2026 Highsoft AS
 *  Authors:
 *  - Paweł Fus
 *  - Jedrzej Ruta
 *
 *  License: www.highcharts.com/license
 *
 *  DO NOT EDIT THIS FILE! This file is created by 'gulp scripts-icons' task.
 *
 * */
'use strict';
// Auto-generated SVG JSON
/* eslint-disable max-len */
/**
 * Helper function to generate SVG icon prefix with given viewBox size.
 * @internal
 */
var baseFormIconPrefix = function (viewBox) {
    return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n        <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 ".concat(viewBox, " ").concat(viewBox, "\">");
};
/**
 * Constants
 */
var baseIconFillColor = '#4B4B4D';
export default {
    'close.svg': "".concat(baseFormIconPrefix(32), "\n<polygon fill=\"").concat(baseIconFillColor, "\" points=\"24.308,8.756 23.248,7.695 16.002,14.941 8.757,7.695 7.695,8.754 14.941,16.001 7.696,23.246\n    8.755,24.308 16.002,17.061 23.247,24.307 24.308,23.248 17.062,16.001\"/>\n</svg>\n"),
    'destroy.svg': "".concat(baseFormIconPrefix(32), "\n<g>\n    <rect x=\"12.75\" y=\"14\" fill=\"").concat(baseIconFillColor, "\" width=\"1.5\" height=\"10\"/>\n    <rect x=\"17.75\" y=\"14\" fill=\"").concat(baseIconFillColor, "\" width=\"1.5\" height=\"10\"/>\n    <path fill=\"").concat(baseIconFillColor, "\" d=\"M25.25,10.5c0-1.517-1.233-2.75-2.75-2.75h-3.25V7c0-1.24-1.01-2.25-2.25-2.25h-2\n        c-1.24,0-2.25,1.01-2.25,2.25v0.75H9.5c-1.517,0-2.75,1.233-2.75,2.75v1.751h2V27.25h14.5V12.251h2V10.5z M14.25,7\n        c0-0.413,0.337-0.75,0.75-0.75h2c0.413,0,0.75,0.337,0.75,0.75v0.75h-3.5V7z M21.75,25.75h-11.5V12.251h11.5V25.75z M23.75,10.751\n        H8.25V10.5c0-0.689,0.561-1.25,1.25-1.25h13c0.689,0,1.25,0.561,1.25,1.25V10.751z\"/>\n</g>\n</svg>\n"),
    'edit.svg': "".concat(baseFormIconPrefix(32), "\n<path fill=\"").concat(baseIconFillColor, "\" d=\"M22.125,3.814L5.817,20.122l-1.818,7.879l7.879-1.818L28.186,9.875L22.125,3.814z M26.064,9.875\n    l-1.439,1.439l-3.939-3.939l1.439-1.439L26.064,9.875z M10.186,22.875l9.939-9.939l1.439,1.439l-9.939,9.939L10.186,22.875z\n     M7.686,20.375l9.939-9.939l1.439,1.439l-9.939,9.939L7.686,20.375z M18.686,9.375l0.939-0.939l3.939,3.939l-0.939,0.939\n    L18.686,9.375z M6.974,21.784l3.242,3.242l-4.215,0.973L6.974,21.784z\"/>\n</svg>\n")
};
