/**
* @license Highcharts JS v12.3.0 (2025-06-21)
* @module highcharts/i18n/fr-FR
* @requires highcharts
*
* fr-FR language pack
*
* (c) 2009-2025 Torstein Honsi
*
* License: www.highcharts.com/license
*
* **Do not edit this file!** This file is generated using the 'gulp lang-build' task.
*/
import D from '../../Core/Defaults.js';
export default D;
