/**
 * @license Highcharts JS v13.0.0 (2026-06-11)
 * @module highcharts/i18n/fr-FR
 * @requires highcharts
 *
 * fr-FR language pack
 *
 * (c) 2009-2026 Highsoft AS
 *
 * Integration of this software requires a license:
 * - For commercial use, see www.highcharts.com/license
 * - For non-commercial, see www.highcharts.com/license-eula
 *
 * **Do not edit this file!** This file is generated using the 'gulp lang-build' task.
 */
import D from '../../Core/Defaults.js';
export default D;
