/**
* @license Highcharts JS v12.5.0 (2026-01-12)
* @module highcharts/i18n/nb-NO
* @requires highcharts
*
* nb-NO language pack
*
* (c) 2009-2026 Highsoft AS
*
* A commercial license may be required depending on use.
* See www.highcharts.com/license
*
* **Do not edit this file!** This file is generated using the 'gulp lang-build' task.
*/
import D from '../../Core/Defaults.js';
export default D;
