/**
* @license Highcharts JS v12.4.0-modified (2025-11-17)
* @module highcharts/i18n/zh-CN
* @requires highcharts
*
* zh-CN language pack
*
* (c) 2009-2025 Highsoft AS
*
* License: www.highcharts.com/license
*
* **Do not edit this file!** This file is generated using the 'gulp lang-build' task.
*/
import D from '../../Core/Defaults.js';
export default D;
