/*
 Highcharts JS v11.1.0 (2023-09-22)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(D){a(D);a.Highcharts=D;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function D(a,z,t,C){a.hasOwnProperty(z)||(a[z]=C.apply(null,t),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:z,module:a[z]}})))}a=a?a._modules:
{};D(a,"Core/Math3D.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,z){function t(n,g,e,b){var c=g.options.chart.options3d,a=B(b,e?g.inverted:!1),m={x:g.plotWidth/2,y:g.plotHeight/2,z:c.depth/2,vd:B(c.depth,1)*B(c.viewDistance,0)},p=g.scale3d||1;b=l*c.beta*(a?-1:1);c=l*c.alpha*(a?-1:1);var k=Math.cos(c),y=Math.cos(-b),w=Math.sin(c),x=Math.sin(-b);e||(m.x+=g.plotLeft,m.y+=g.plotTop);return n.map(function(c){var b=(a?c.y:c.x)-m.x;var g=(a?c.x:c.y)-m.y;c=(c.z||0)-m.z;b={x:y*b-x*c,y:-w*x*
b+k*g-y*w*c,z:k*x*b+w*g+k*y*c};g=A(b,m,m.vd);g.x=g.x*p+m.x;g.y=g.y*p+m.y;g.z=b.z*p+m.z;return{x:a?g.y:g.x,y:a?g.x:g.y,z:g.z}})}function A(a,g,e){g=0<e&&e<Number.POSITIVE_INFINITY?e/(a.z+g.z+e):1;return{x:a.x*g,y:a.y*g}}function n(a){var g=0,e;for(e=0;e<a.length;e++){var b=(e+1)%a.length;g+=a[e].x*a[b].y-a[b].x*a[e].y}return g/2}var l=a.deg2rad,B=z.pick;return{perspective:t,perspective3D:A,pointCameraDistance:function(a,g){var e=g.options.chart.options3d,b=g.plotWidth/2;g=g.plotHeight/2;e=B(e.depth,
1)*B(e.viewDistance,0)+e.depth;return Math.sqrt(Math.pow(b-B(a.plotX,a.x),2)+Math.pow(g-B(a.plotY,a.y),2)+Math.pow(e-B(a.plotZ,a.z),2))},shapeArea:n,shapeArea3D:function(a,g,e){return n(t(a,g,e))}}});D(a,"Core/Renderer/SVG/SVGElement3D.js",[a["Core/Color/Color.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Utilities.js"]],function(a,z,t){var A=a.parse,n=t.defined;a=t.merge;var l=t.objectEach,B=t.pick,y={base:{initArgs:function(g){var a=this,b=a.renderer,c=b[a.pathType+"Path"](g),n=c.zIndexes;a.parts.forEach(function(g){var m=
{"class":"highcharts-3d-"+g,zIndex:n[g]||0};b.styledMode&&("top"===g?m.filter="url(#highcharts-brighter)":"side"===g&&(m.filter="url(#highcharts-darker)"));a[g]=b.path(c[g]).attr(m).add(a)});a.attr({"stroke-linejoin":"round",zIndex:n.group});a.originalDestroy=a.destroy;a.destroy=a.destroyParts;a.forcedSides=c.forcedSides},singleSetterForParts:function(g,a,b,c,n,m){var e={};c=[null,null,c||"attr",n,m];var k=b&&b.zIndexes;b?(k&&k.group&&this.attr({zIndex:k.group}),l(b,function(c,a){e[a]={};e[a][g]=
c;k&&(e[a].zIndex=b.zIndexes[a]||0)}),c[1]=e):(e[g]=a,c[0]=e);return this.processParts.apply(this,c)},processParts:function(g,a,b,c,n){var m=this;m.parts.forEach(function(e){a&&(g=B(a[e],!1));if(!1!==g)m[e][b](g,c,n)});return m},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}}};y.cuboid=a(y.base,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,e,b,c){if("string"===typeof a&&"undefined"!==typeof e){var g=a;a={};a[g]=e}return a.shapeArgs||
n(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):z.prototype.attr.call(this,a,void 0,b,c)},animate:function(a,e,b){if(n(a.x)&&n(a.y)){a=this.renderer[this.pathType+"Path"](a);var c=a.forcedSides;this.singleSetterForParts("d",null,a,"animate",e,b);this.attr({zIndex:a.zIndexes.group});c!==this.forcedSides&&(this.forcedSides=c,this.renderer.styledMode||y.cuboid.fillSetter.call(this,this.fill))}else z.prototype.animate.call(this,a,e,b);return this},fillSetter:function(a){this.forcedSides=
this.forcedSides||[];this.singleSetterForParts("fill",null,{front:a,top:A(a).brighten(0<=this.forcedSides.indexOf("top")?0:.1).get(),side:A(a).brighten(0<=this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=a;return this}});return y});D(a,"Core/Renderer/SVG/SVGRenderer3D.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Math3D.js"],a["Core/Renderer/SVG/SVGElement.js"],a["Core/Renderer/SVG/SVGElement3D.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Utilities.js"]],function(a,z,t,C,n,l,B,y){var g=this&&this.__extends||function(){function a(h,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var v in f)Object.prototype.hasOwnProperty.call(f,v)&&(a[v]=f[v])};return a(h,c)}return function(h,c){function b(){this.constructor=h}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(h,c);h.prototype=null===c?Object.create(c):
(b.prototype=c.prototype,new b)}}(),e=a.animObject,b=z.parse,c=t.charts,E=t.deg2rad,m=C.perspective,p=C.shapeArea,k=y.defined,F=y.extend,w=y.merge,x=y.pick,A=Math.cos,H=Math.sin,J=Math.PI,L=4*(Math.sqrt(2)-1)/3/(J/2);return function(a){function h(){return null!==a&&a.apply(this,arguments)||this}g(h,a);h.compose=function(a){a=a.prototype;var c=h.prototype;a.elements3d=l;a.arc3d=c.arc3d;a.arc3dPath=c.arc3dPath;a.cuboid=c.cuboid;a.cuboidPath=c.cuboidPath;a.element3d=c.element3d;a.face3d=c.face3d;a.polyhedron=
c.polyhedron;a.toLinePath=c.toLinePath;a.toLineSegments=c.toLineSegments};h.curveTo=function(a,c,f,v,d,u,G,q){var h=[],b=u-d;return u>d&&u-d>Math.PI/2+1E-4?(h=h.concat(this.curveTo(a,c,f,v,d,d+Math.PI/2,G,q)),h=h.concat(this.curveTo(a,c,f,v,d+Math.PI/2,u,G,q))):u<d&&d-u>Math.PI/2+1E-4?(h=h.concat(this.curveTo(a,c,f,v,d,d-Math.PI/2,G,q)),h=h.concat(this.curveTo(a,c,f,v,d-Math.PI/2,u,G,q))):[["C",a+f*Math.cos(d)-f*L*b*Math.sin(d)+G,c+v*Math.sin(d)+v*L*b*Math.cos(d)+q,a+f*Math.cos(u)+f*L*b*Math.sin(u)+
G,c+v*Math.sin(u)-v*L*b*Math.cos(u)+q,a+f*Math.cos(u)+G,c+v*Math.sin(u)+q]]};h.prototype.toLinePath=function(a,c){var f=[];a.forEach(function(a){f.push(["L",a.x,a.y])});a.length&&(f[0][0]="M",c&&f.push(["Z"]));return f};h.prototype.toLineSegments=function(a){var c=[],f=!0;a.forEach(function(a){c.push(f?["M",a.x,a.y]:["L",a.x,a.y]);f=!f});return c};h.prototype.face3d=function(a){var h=this,f=this.createElement("path");f.vertexes=[];f.insidePlotArea=!1;f.enabled=!0;f.attr=function(f){if("object"===
typeof f&&(k(f.enabled)||k(f.vertexes)||k(f.insidePlotArea))){this.enabled=x(f.enabled,this.enabled);this.vertexes=x(f.vertexes,this.vertexes);this.insidePlotArea=x(f.insidePlotArea,this.insidePlotArea);delete f.enabled;delete f.vertexes;delete f.insidePlotArea;var d=m(this.vertexes,c[h.chartIndex],this.insidePlotArea),a=h.toLinePath(d,!0);d=p(d);f.d=a;f.visibility=this.enabled&&0<d?"inherit":"hidden"}return n.prototype.attr.apply(this,arguments)};f.animate=function(f){if("object"===typeof f&&(k(f.enabled)||
k(f.vertexes)||k(f.insidePlotArea))){this.enabled=x(f.enabled,this.enabled);this.vertexes=x(f.vertexes,this.vertexes);this.insidePlotArea=x(f.insidePlotArea,this.insidePlotArea);delete f.enabled;delete f.vertexes;delete f.insidePlotArea;var d=m(this.vertexes,c[h.chartIndex],this.insidePlotArea),a=h.toLinePath(d,!0);d=p(d);d=this.enabled&&0<d?"visible":"hidden";f.d=a;this.attr("visibility",d)}return n.prototype.animate.apply(this,arguments)};return f.attr(a)};h.prototype.polyhedron=function(a){var c=
this,f=this.g(),h=f.destroy;this.styledMode||f.attr({"stroke-linejoin":"round"});f.faces=[];f.destroy=function(){for(var d=0;d<f.faces.length;d++)f.faces[d].destroy();return h.call(this)};f.attr=function(d,a,h,q){if("object"===typeof d&&k(d.faces)){for(;f.faces.length>d.faces.length;)f.faces.pop().destroy();for(;f.faces.length<d.faces.length;)f.faces.push(c.face3d().add(f));for(var u=0;u<d.faces.length;u++)c.styledMode&&delete d.faces[u].fill,f.faces[u].attr(d.faces[u],null,h,q);delete d.faces}return n.prototype.attr.apply(this,
arguments)};f.animate=function(d,a,h){if(d&&d.faces){for(;f.faces.length>d.faces.length;)f.faces.pop().destroy();for(;f.faces.length<d.faces.length;)f.faces.push(c.face3d().add(f));for(var q=0;q<d.faces.length;q++)f.faces[q].animate(d.faces[q],a,h);delete d.faces}return n.prototype.animate.apply(this,arguments)};return f.attr(a)};h.prototype.element3d=function(a,c){var f=this.g();F(f,this.elements3d[a]);f.initArgs(c);return f};h.prototype.cuboid=function(a){return this.element3d("cuboid",a)};h.prototype.cuboidPath=
function(a){function h(f){return 0===G&&1<f&&6>f?{x:r[f].x,y:r[f].y+10,z:r[f].z}:r[0].x===r[7].x&&4<=f?{x:r[f].x+10,y:r[f].y,z:r[f].z}:0===b&&2>f||5<f?{x:r[f].x,y:r[f].y,z:r[f].z+10}:r[f]}function f(f){return r[f]}var v=a.x||0,d=a.y||0,u=a.z||0,G=a.height||0,q=a.width||0,b=a.depth||0,g=c[this.chartIndex],e=g.options.chart.options3d.alpha,k=0,r=[{x:v,y:d,z:u},{x:v+q,y:d,z:u},{x:v+q,y:d+G,z:u},{x:v,y:d+G,z:u},{x:v,y:d+G,z:u+b},{x:v+q,y:d+G,z:u+b},{x:v+q,y:d,z:u+b},{x:v,y:d,z:u+b}],n=[];r=m(r,g,a.insidePlotArea);
var I=function(d,a,q){var c=[[],-1],u=d.map(f),G=a.map(f);d=d.map(h);a=a.map(h);0>p(u)?c=[u,0]:0>p(G)?c=[G,1]:q&&(n.push(q),c=0>p(d)?[u,0]:0>p(a)?[G,1]:[u,0]);return c};var l=I([3,2,1,0],[7,6,5,4],"front");a=l[0];var x=l[1];l=I([1,6,7,0],[4,5,2,3],"top");q=l[0];var w=l[1];l=I([1,2,5,6],[0,7,4,3],"side");I=l[0];l=l[1];1===l?k+=1E6*(g.plotWidth-v):l||(k+=1E6*v);k+=10*(!w||0<=e&&180>=e||360>e&&357.5<e?g.plotHeight-d:10+d);1===x?k+=100*u:x||(k+=100*(1E3-u));return{front:this.toLinePath(a,!0),top:this.toLinePath(q,
!0),side:this.toLinePath(I,!0),zIndexes:{group:Math.round(k)},forcedSides:n,isFront:x,isTop:w}};h.prototype.arc3d=function(a){function c(f){var a=!1,c={},h;f=w(f);for(h in f)-1!==d.indexOf(h)&&(c[h]=f[h],delete f[h],a=!0);return a?[c,f]:!1}var f=this.g(),h=f.renderer,d="x y r innerR start end depth".split(" ");a=w(a);a.alpha=(a.alpha||0)*E;a.beta=(a.beta||0)*E;f.top=h.path();f.side1=h.path();f.side2=h.path();f.inn=h.path();f.out=h.path();f.onAdd=function(){var d=f.parentGroup,a=f.attr("class");f.top.add(f);
["out","inn","side1","side2"].forEach(function(c){f[c].attr({"class":a+" highcharts-3d-side"}).add(d)})};["addClass","removeClass"].forEach(function(d){f[d]=function(){var a=arguments;["top","out","inn","side1","side2"].forEach(function(c){f[c][d].apply(f[c],a)})}});f.setPaths=function(d){var a=f.renderer.arc3dPath(d),c=100*a.zTop;f.attribs=d;f.top.attr({d:a.top,zIndex:a.zTop});f.inn.attr({d:a.inn,zIndex:a.zInn});f.out.attr({d:a.out,zIndex:a.zOut});f.side1.attr({d:a.side1,zIndex:a.zSide1});f.side2.attr({d:a.side2,
zIndex:a.zSide2});f.zIndex=c;f.attr({zIndex:c});d.center&&(f.top.setRadialReference(d.center),delete d.center)};f.setPaths(a);f.fillSetter=function(f){var d=b(f).brighten(-.1).get();this.fill=f;this.side1.attr({fill:d});this.side2.attr({fill:d});this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:f});return this};["opacity","translateX","translateY","visibility"].forEach(function(d){f[d+"Setter"]=function(d,a){f[a]=d;["out","inn","side1","side2","top"].forEach(function(c){f[c].attr(a,
d)})}});f.attr=function(d){var a;if("object"===typeof d&&(a=c(d))){var h=a[0];arguments[0]=a[1];F(f.attribs,h);f.setPaths(f.attribs)}return n.prototype.attr.apply(f,arguments)};f.animate=function(d,a,h){var q=this.attribs,u="data-"+Math.random().toString(26).substring(2,9);delete d.center;delete d.z;delete d.alpha;delete d.beta;var v=e(x(a,this.renderer.globalAnimation));if(v.duration){a=c(d);f[u]=0;d[u]=1;f[u+"Setter"]=t.noop;if(a){var b=a[0];v.step=function(d,f){function a(d){return q[d]+(x(b[d],
q[d])-q[d])*f.pos}f.prop===u&&f.elem.setPaths(w(q,{x:a("x"),y:a("y"),r:a("r"),innerR:a("innerR"),start:a("start"),end:a("end"),depth:a("depth")}))}}a=v}return n.prototype.animate.call(this,d,a,h)};f.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return n.prototype.destroy.call(this)};f.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};f.show=function(d){this.top.show(d);this.out.show(d);
this.inn.show(d);this.side1.show(d);this.side2.show(d)};return f};h.prototype.arc3dPath=function(a){function c(d){d%=2*Math.PI;d>Math.PI&&(d=2*Math.PI-d);return d}var f=a.x||0,v=a.y||0,d=a.start||0,u=(a.end||0)-1E-5,b=a.r||0,q=a.innerR||0,g=a.depth||0,e=a.alpha||0,m=a.beta||0,k=Math.cos(d),r=Math.sin(d);a=Math.cos(u);var n=Math.sin(u),p=b*Math.cos(m);b*=Math.cos(e);var l=q*Math.cos(m),x=q*Math.cos(e);q=g*Math.sin(m);var w=g*Math.sin(e);g=[["M",f+p*k,v+b*r]];g=g.concat(h.curveTo(f,v,p,b,d,u,0,0));
g.push(["L",f+l*a,v+x*n]);g=g.concat(h.curveTo(f,v,l,x,u,d,0,0));g.push(["Z"]);var E=0<m?Math.PI/2:0;m=0<e?0:Math.PI/2;E=d>-E?d:u>-E?-E:d;var y=u<J-m?u:d<J-m?J-m:u,F=2*J-m;e=[["M",f+p*A(E),v+b*H(E)]];e=e.concat(h.curveTo(f,v,p,b,E,y,0,0));u>F&&d<F?(e.push(["L",f+p*A(y)+q,v+b*H(y)+w]),e=e.concat(h.curveTo(f,v,p,b,y,F,q,w)),e.push(["L",f+p*A(F),v+b*H(F)]),e=e.concat(h.curveTo(f,v,p,b,F,u,0,0)),e.push(["L",f+p*A(u)+q,v+b*H(u)+w]),e=e.concat(h.curveTo(f,v,p,b,u,F,q,w)),e.push(["L",f+p*A(F),v+b*H(F)]),
e=e.concat(h.curveTo(f,v,p,b,F,y,0,0))):u>J-m&&d<J-m&&(e.push(["L",f+p*Math.cos(y)+q,v+b*Math.sin(y)+w]),e=e.concat(h.curveTo(f,v,p,b,y,u,q,w)),e.push(["L",f+p*Math.cos(u),v+b*Math.sin(u)]),e=e.concat(h.curveTo(f,v,p,b,u,y,0,0)));e.push(["L",f+p*Math.cos(y)+q,v+b*Math.sin(y)+w]);e=e.concat(h.curveTo(f,v,p,b,y,E,q,w));e.push(["Z"]);m=[["M",f+l*k,v+x*r]];m=m.concat(h.curveTo(f,v,l,x,d,u,0,0));m.push(["L",f+l*Math.cos(u)+q,v+x*Math.sin(u)+w]);m=m.concat(h.curveTo(f,v,l,x,u,d,q,w));m.push(["Z"]);k=[["M",
f+p*k,v+b*r],["L",f+p*k+q,v+b*r+w],["L",f+l*k+q,v+x*r+w],["L",f+l*k,v+x*r],["Z"]];f=[["M",f+p*a,v+b*n],["L",f+p*a+q,v+b*n+w],["L",f+l*a+q,v+x*n+w],["L",f+l*a,v+x*n],["Z"]];n=Math.atan2(w,-q);v=Math.abs(u+n);a=Math.abs(d+n);d=Math.abs((d+u)/2+n);v=c(v);a=c(a);d=c(d);d*=1E5;u=1E5*a;v*=1E5;return{top:g,zTop:1E5*Math.PI+1,out:e,zOut:Math.max(d,u,v),inn:m,zInn:Math.max(d,u,v),side1:k,zSide1:.99*v,side2:f,zSide2:.99*u}};return h}(B)});D(a,"Core/Chart/Chart3D.js",[a["Core/Color/Color.js"],a["Core/Defaults.js"],
a["Core/Math3D.js"],a["Core/Utilities.js"]],function(a,z,t,C){var n=a.parse,l=z.defaultOptions,A=t.perspective,y=t.shapeArea3D,g=C.addEvent,e=C.isArray,b=C.merge,c=C.pick,E=C.wrap,m;(function(a){function m(a){this.is3d()&&"scatter"===a.options.type&&(a.options.type="scatter3d")}function p(){if(this.chart3d&&this.is3d()){var a=this.renderer,c=this.options.chart.options3d,d=this.chart3d.get3dFrame(),h=this.plotLeft,b=this.plotLeft+this.plotWidth,q=this.plotTop,e=this.plotTop+this.plotHeight;c=c.depth;
var m=h-(d.left.visible?d.left.size:0),g=b+(d.right.visible?d.right.size:0),k=q-(d.top.visible?d.top.size:0),r=e+(d.bottom.visible?d.bottom.size:0),p=0-(d.front.visible?d.front.size:0),l=c+(d.back.visible?d.back.size:0),w=this.hasRendered?"animate":"attr";this.chart3d.frame3d=d;this.frameShapes||(this.frameShapes={bottom:a.polyhedron().add(),top:a.polyhedron().add(),left:a.polyhedron().add(),right:a.polyhedron().add(),back:a.polyhedron().add(),front:a.polyhedron().add()});this.frameShapes.bottom[w]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",
zIndex:d.bottom.frontFacing?-1E3:1E3,faces:[{fill:n(d.bottom.color).brighten(.1).get(),vertexes:[{x:m,y:r,z:p},{x:g,y:r,z:p},{x:g,y:r,z:l},{x:m,y:r,z:l}],enabled:d.bottom.visible},{fill:n(d.bottom.color).brighten(.1).get(),vertexes:[{x:h,y:e,z:c},{x:b,y:e,z:c},{x:b,y:e,z:0},{x:h,y:e,z:0}],enabled:d.bottom.visible},{fill:n(d.bottom.color).brighten(-.1).get(),vertexes:[{x:m,y:r,z:p},{x:m,y:r,z:l},{x:h,y:e,z:c},{x:h,y:e,z:0}],enabled:d.bottom.visible&&!d.left.visible},{fill:n(d.bottom.color).brighten(-.1).get(),
vertexes:[{x:g,y:r,z:l},{x:g,y:r,z:p},{x:b,y:e,z:0},{x:b,y:e,z:c}],enabled:d.bottom.visible&&!d.right.visible},{fill:n(d.bottom.color).get(),vertexes:[{x:g,y:r,z:p},{x:m,y:r,z:p},{x:h,y:e,z:0},{x:b,y:e,z:0}],enabled:d.bottom.visible&&!d.front.visible},{fill:n(d.bottom.color).get(),vertexes:[{x:m,y:r,z:l},{x:g,y:r,z:l},{x:b,y:e,z:c},{x:h,y:e,z:c}],enabled:d.bottom.visible&&!d.back.visible}]});this.frameShapes.top[w]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:d.top.frontFacing?-1E3:
1E3,faces:[{fill:n(d.top.color).brighten(.1).get(),vertexes:[{x:m,y:k,z:l},{x:g,y:k,z:l},{x:g,y:k,z:p},{x:m,y:k,z:p}],enabled:d.top.visible},{fill:n(d.top.color).brighten(.1).get(),vertexes:[{x:h,y:q,z:0},{x:b,y:q,z:0},{x:b,y:q,z:c},{x:h,y:q,z:c}],enabled:d.top.visible},{fill:n(d.top.color).brighten(-.1).get(),vertexes:[{x:m,y:k,z:l},{x:m,y:k,z:p},{x:h,y:q,z:0},{x:h,y:q,z:c}],enabled:d.top.visible&&!d.left.visible},{fill:n(d.top.color).brighten(-.1).get(),vertexes:[{x:g,y:k,z:p},{x:g,y:k,z:l},{x:b,
y:q,z:c},{x:b,y:q,z:0}],enabled:d.top.visible&&!d.right.visible},{fill:n(d.top.color).get(),vertexes:[{x:m,y:k,z:p},{x:g,y:k,z:p},{x:b,y:q,z:0},{x:h,y:q,z:0}],enabled:d.top.visible&&!d.front.visible},{fill:n(d.top.color).get(),vertexes:[{x:g,y:k,z:l},{x:m,y:k,z:l},{x:h,y:q,z:c},{x:b,y:q,z:c}],enabled:d.top.visible&&!d.back.visible}]});this.frameShapes.left[w]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:d.left.frontFacing?-1E3:1E3,faces:[{fill:n(d.left.color).brighten(.1).get(),
vertexes:[{x:m,y:r,z:p},{x:h,y:e,z:0},{x:h,y:e,z:c},{x:m,y:r,z:l}],enabled:d.left.visible&&!d.bottom.visible},{fill:n(d.left.color).brighten(.1).get(),vertexes:[{x:m,y:k,z:l},{x:h,y:q,z:c},{x:h,y:q,z:0},{x:m,y:k,z:p}],enabled:d.left.visible&&!d.top.visible},{fill:n(d.left.color).brighten(-.1).get(),vertexes:[{x:m,y:r,z:l},{x:m,y:k,z:l},{x:m,y:k,z:p},{x:m,y:r,z:p}],enabled:d.left.visible},{fill:n(d.left.color).brighten(-.1).get(),vertexes:[{x:h,y:q,z:c},{x:h,y:e,z:c},{x:h,y:e,z:0},{x:h,y:q,z:0}],enabled:d.left.visible},
{fill:n(d.left.color).get(),vertexes:[{x:m,y:r,z:p},{x:m,y:k,z:p},{x:h,y:q,z:0},{x:h,y:e,z:0}],enabled:d.left.visible&&!d.front.visible},{fill:n(d.left.color).get(),vertexes:[{x:m,y:k,z:l},{x:m,y:r,z:l},{x:h,y:e,z:c},{x:h,y:q,z:c}],enabled:d.left.visible&&!d.back.visible}]});this.frameShapes.right[w]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:d.right.frontFacing?-1E3:1E3,faces:[{fill:n(d.right.color).brighten(.1).get(),vertexes:[{x:g,y:r,z:l},{x:b,y:e,z:c},{x:b,y:e,z:0},{x:g,
y:r,z:p}],enabled:d.right.visible&&!d.bottom.visible},{fill:n(d.right.color).brighten(.1).get(),vertexes:[{x:g,y:k,z:p},{x:b,y:q,z:0},{x:b,y:q,z:c},{x:g,y:k,z:l}],enabled:d.right.visible&&!d.top.visible},{fill:n(d.right.color).brighten(-.1).get(),vertexes:[{x:b,y:q,z:0},{x:b,y:e,z:0},{x:b,y:e,z:c},{x:b,y:q,z:c}],enabled:d.right.visible},{fill:n(d.right.color).brighten(-.1).get(),vertexes:[{x:g,y:r,z:p},{x:g,y:k,z:p},{x:g,y:k,z:l},{x:g,y:r,z:l}],enabled:d.right.visible},{fill:n(d.right.color).get(),
vertexes:[{x:g,y:k,z:p},{x:g,y:r,z:p},{x:b,y:e,z:0},{x:b,y:q,z:0}],enabled:d.right.visible&&!d.front.visible},{fill:n(d.right.color).get(),vertexes:[{x:g,y:r,z:l},{x:g,y:k,z:l},{x:b,y:q,z:c},{x:b,y:e,z:c}],enabled:d.right.visible&&!d.back.visible}]});this.frameShapes.back[w]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:d.back.frontFacing?-1E3:1E3,faces:[{fill:n(d.back.color).brighten(.1).get(),vertexes:[{x:g,y:r,z:l},{x:m,y:r,z:l},{x:h,y:e,z:c},{x:b,y:e,z:c}],enabled:d.back.visible&&
!d.bottom.visible},{fill:n(d.back.color).brighten(.1).get(),vertexes:[{x:m,y:k,z:l},{x:g,y:k,z:l},{x:b,y:q,z:c},{x:h,y:q,z:c}],enabled:d.back.visible&&!d.top.visible},{fill:n(d.back.color).brighten(-.1).get(),vertexes:[{x:m,y:r,z:l},{x:m,y:k,z:l},{x:h,y:q,z:c},{x:h,y:e,z:c}],enabled:d.back.visible&&!d.left.visible},{fill:n(d.back.color).brighten(-.1).get(),vertexes:[{x:g,y:k,z:l},{x:g,y:r,z:l},{x:b,y:e,z:c},{x:b,y:q,z:c}],enabled:d.back.visible&&!d.right.visible},{fill:n(d.back.color).get(),vertexes:[{x:h,
y:q,z:c},{x:b,y:q,z:c},{x:b,y:e,z:c},{x:h,y:e,z:c}],enabled:d.back.visible},{fill:n(d.back.color).get(),vertexes:[{x:m,y:r,z:l},{x:g,y:r,z:l},{x:g,y:k,z:l},{x:m,y:k,z:l}],enabled:d.back.visible}]});this.frameShapes.front[w]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:d.front.frontFacing?-1E3:1E3,faces:[{fill:n(d.front.color).brighten(.1).get(),vertexes:[{x:m,y:r,z:p},{x:g,y:r,z:p},{x:b,y:e,z:0},{x:h,y:e,z:0}],enabled:d.front.visible&&!d.bottom.visible},{fill:n(d.front.color).brighten(.1).get(),
vertexes:[{x:g,y:k,z:p},{x:m,y:k,z:p},{x:h,y:q,z:0},{x:b,y:q,z:0}],enabled:d.front.visible&&!d.top.visible},{fill:n(d.front.color).brighten(-.1).get(),vertexes:[{x:m,y:k,z:p},{x:m,y:r,z:p},{x:h,y:e,z:0},{x:h,y:q,z:0}],enabled:d.front.visible&&!d.left.visible},{fill:n(d.front.color).brighten(-.1).get(),vertexes:[{x:g,y:r,z:p},{x:g,y:k,z:p},{x:b,y:q,z:0},{x:b,y:e,z:0}],enabled:d.front.visible&&!d.right.visible},{fill:n(d.front.color).get(),vertexes:[{x:b,y:q,z:0},{x:h,y:q,z:0},{x:h,y:e,z:0},{x:b,y:e,
z:0}],enabled:d.front.visible},{fill:n(d.front.color).get(),vertexes:[{x:g,y:r,z:p},{x:m,y:r,z:p},{x:m,y:k,z:p},{x:g,y:k,z:p}],enabled:d.front.visible}]})}}function w(){this.styledMode&&[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(a){this.renderer.definition({tagName:"filter",attributes:{id:"highcharts-"+a.name},children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",attributes:{type:"linear",slope:a.slope}},{tagName:"feFuncG",attributes:{type:"linear",slope:a.slope}},
{tagName:"feFuncB",attributes:{type:"linear",slope:a.slope}}]}]})},this)}function x(){var a=this.options;this.is3d()&&(a.series||[]).forEach(function(f){"scatter"===(f.type||a.chart.type||a.chart.defaultSeriesType)&&(f.type="scatter3d")})}function t(){var a=this.options.chart.options3d;if(this.chart3d&&this.is3d()){a&&(a.alpha=a.alpha%360+(0<=a.alpha?0:360),a.beta=a.beta%360+(0<=a.beta?0:360));var c=this.inverted,d=this.clipBox,h=this.margin;d[c?"y":"x"]=-(h[3]||0);d[c?"x":"y"]=-(h[0]||0);d[c?"height":
"width"]=this.chartWidth+(h[3]||0)+(h[1]||0);d[c?"width":"height"]=this.chartHeight+(h[0]||0)+(h[2]||0);this.scale3d=1;!0===a.fitToPlot&&(this.scale3d=this.chart3d.getScale(a.depth));this.chart3d.frame3d=this.chart3d.get3dFrame()}}function B(){this.is3d()&&(this.isDirtyBox=!0)}function z(){this.chart3d&&this.is3d()&&(this.chart3d.frame3d=this.chart3d.get3dFrame())}function C(){this.chart3d||(this.chart3d=new K(this))}function M(a){return this.is3d()||a.apply(this,[].slice.call(arguments,1))}function h(a){var f=
this.series.length;if(this.is3d())for(;f--;)a=this.series[f],a.translate(),a.render();else a.call(this)}function I(a){a.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")}var K=function(){function a(a){this.frame3d=void 0;this.chart=a}a.prototype.get3dFrame=function(){function a(a,d,f){for(var b=["size","color","visible"],h={},e=0;e<b.length;e++)for(var m=b[e],g=0;g<a.length;g++)if("object"===typeof a[g]){var k=a[g][m];if("undefined"!==typeof k&&
null!==k){h[m]=k;break}}a=f;!0===h.visible||!1===h.visible?a=h.visible:"auto"===h.visible&&(a=0<d);return{size:c(h.size,1),color:c(h.color,"none"),frontFacing:0<d,visible:a}}function d(a){a=y(a,f);return.5<a?1:-.5>a?-1:0}var f=this.chart,h=f.options.chart.options3d,b=h.frame,e=f.plotLeft,m=f.plotLeft+f.plotWidth,g=f.plotTop,k=f.plotTop+f.plotHeight,p=h.depth,l=d([{x:e,y:k,z:p},{x:m,y:k,z:p},{x:m,y:k,z:0},{x:e,y:k,z:0}]),n=d([{x:e,y:g,z:0},{x:m,y:g,z:0},{x:m,y:g,z:p},{x:e,y:g,z:p}]),w=d([{x:e,y:g,
z:0},{x:e,y:g,z:p},{x:e,y:k,z:p},{x:e,y:k,z:0}]),x=d([{x:m,y:g,z:p},{x:m,y:g,z:0},{x:m,y:k,z:0},{x:m,y:k,z:p}]),E=d([{x:e,y:k,z:0},{x:m,y:k,z:0},{x:m,y:g,z:0},{x:e,y:g,z:0}]),F=d([{x:e,y:g,z:p},{x:m,y:g,z:p},{x:m,y:k,z:p},{x:e,y:k,z:p}]),t=!1,I=!1,K=!1,B=!1;[].concat(f.xAxis,f.yAxis,f.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?I=!0:t=!0:a.opposite?B=!0:K=!0)});b={axes:{},bottom:a([b.bottom,b.top,b],l,t),top:a([b.top,b.bottom,b],n,I),left:a([b.left,b.right,b.side,b],w,K),right:a([b.right,b.left,
b.side,b],x,B),back:a([b.back,b.front,b],F,!0),front:a([b.front,b.back,b],E,!1)};"auto"===h.axisLabelPosition?(x=function(a,d){return a.visible!==d.visible||a.visible&&d.visible&&a.frontFacing!==d.frontFacing},h=[],x(b.left,b.front)&&h.push({y:(g+k)/2,x:e,z:0,xDir:{x:1,y:0,z:0}}),x(b.left,b.back)&&h.push({y:(g+k)/2,x:e,z:p,xDir:{x:0,y:0,z:-1}}),x(b.right,b.front)&&h.push({y:(g+k)/2,x:m,z:0,xDir:{x:0,y:0,z:1}}),x(b.right,b.back)&&h.push({y:(g+k)/2,x:m,z:p,xDir:{x:-1,y:0,z:0}}),l=[],x(b.bottom,b.front)&&
l.push({x:(e+m)/2,y:k,z:0,xDir:{x:1,y:0,z:0}}),x(b.bottom,b.back)&&l.push({x:(e+m)/2,y:k,z:p,xDir:{x:-1,y:0,z:0}}),n=[],x(b.top,b.front)&&n.push({x:(e+m)/2,y:g,z:0,xDir:{x:1,y:0,z:0}}),x(b.top,b.back)&&n.push({x:(e+m)/2,y:g,z:p,xDir:{x:-1,y:0,z:0}}),w=[],x(b.bottom,b.left)&&w.push({z:(0+p)/2,y:k,x:e,xDir:{x:0,y:0,z:-1}}),x(b.bottom,b.right)&&w.push({z:(0+p)/2,y:k,x:m,xDir:{x:0,y:0,z:1}}),k=[],x(b.top,b.left)&&k.push({z:(0+p)/2,y:g,x:e,xDir:{x:0,y:0,z:-1}}),x(b.top,b.right)&&k.push({z:(0+p)/2,y:g,
x:m,xDir:{x:0,y:0,z:1}}),e=function(a,d,c){if(0===a.length)return null;if(1===a.length)return a[0];for(var h=A(a,f,!1),b=0,e=1;e<h.length;e++)c*h[e][d]>c*h[b][d]?b=e:c*h[e][d]===c*h[b][d]&&h[e].z<h[b].z&&(b=e);return a[b]},b.axes={y:{left:e(h,"x",-1),right:e(h,"x",1)},x:{top:e(n,"y",-1),bottom:e(l,"y",1)},z:{top:e(k,"y",-1),bottom:e(w,"y",1)}}):b.axes={y:{left:{x:e,z:0,xDir:{x:1,y:0,z:0}},right:{x:m,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:g,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:k,z:0,xDir:{x:1,y:0,z:0}}},
z:{top:{x:K?m:e,y:g,xDir:K?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:K?m:e,y:k,xDir:K?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return b};a.prototype.getScale=function(a){var d=this.chart,f=d.plotLeft,h=d.plotWidth+f,b=d.plotTop,c=d.plotHeight+b,e=f+d.plotWidth/2,m=b+d.plotHeight/2,g=Number.MAX_VALUE,k=-Number.MAX_VALUE,p=Number.MAX_VALUE,l=-Number.MAX_VALUE,n=1;var x=[{x:f,y:b,z:0},{x:f,y:b,z:a}];[0,1].forEach(function(a){x.push({x:h,y:x[a].y,z:x[a].z})});[0,1,2,3].forEach(function(a){x.push({x:x[a].x,y:c,z:x[a].z})});
x=A(x,d,!1);x.forEach(function(a){g=Math.min(g,a.x);k=Math.max(k,a.x);p=Math.min(p,a.y);l=Math.max(l,a.y)});f>g&&(n=Math.min(n,1-Math.abs((f+e)/(g+e))%1));h<k&&(n=Math.min(n,(h-e)/(k-e)));b>p&&(n=0>p?Math.min(n,(b+m)/(-p+b+m)):Math.min(n,1-(b+m)/(p+m)%1));c<l&&(n=Math.min(n,Math.abs((c-m)/(l-m))));return n};return a}();a.Composition=K;a.defaultOptions={chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},
top:{},left:{},right:{},back:{},front:{}}}}};a.compose=function(f,c){var d=f.prototype;c=c.prototype;d.is3d=function(){return!(!this.options.chart.options3d||!this.options.chart.options3d.enabled)};d.propsRequireDirtyBox.push("chart.options3d");d.propsRequireUpdateSeries.push("chart.options3d");c.matrixSetter=function(){if(1>this.pos&&(e(this.start)||e(this.end))){var a=this.start||[1,0,0,1,0,0],d=this.end||[1,0,0,1,0,0];var f=[];for(var b=0;6>b;b++)f.push(this.pos*d[b]+(1-this.pos)*a[b])}else f=
this.end;this.elem.attr(this.prop,f,null,!0)};b(!0,l,a.defaultOptions);g(f,"init",C);g(f,"addSeries",m);g(f,"afterDrawChartBox",p);g(f,"afterGetContainer",w);g(f,"afterInit",x);g(f,"afterSetChartSize",t);g(f,"beforeRedraw",B);g(f,"beforeRender",z);E(d,"isInsidePlot",M);E(d,"renderSeries",h);E(d,"setClassName",I)}})(m||(m={}));"";return m});D(a,"Core/Axis/ZAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,z){function t(a){return new b(this,a)}function A(){var a=this,b=this.options.zAxis=
g(this.options.zAxis||{});this.is3d()&&(this.zAxis=[],b.forEach(function(b){a.addZAxis(b).setScale()}))}var n=this&&this.__extends||function(){function a(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function e(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");
a(b,c);b.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),l=z.addEvent,B=z.merge,y=z.pick,g=z.splat,e=[],b=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.isZAxis=!0;return b}n(b,a);b.compose=function(a){z.pushUnique(e,a)&&(l(a,"afterGetAxes",A),a=a.prototype,a.addZAxis=t,a.collectionsWithInit.zAxis=[a.addZAxis],a.collectionsWithUpdate.push("zAxis"))};b.prototype.init=function(b,c){this.isZAxis=!0;a.prototype.init.call(this,b,c,"zAxis")};b.prototype.getSeriesExtremes=
function(){var a=this,b=this.chart;this.hasVisibleSeries=!1;this.dataMin=this.dataMax=this.ignoreMinPadding=this.ignoreMaxPadding=void 0;this.stacking&&this.stacking.buildStacks();this.series.forEach(function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries)a.hasVisibleSeries=!0,c=c.zData,c.length&&(a.dataMin=Math.min(y(a.dataMin,c[0]),Math.min.apply(null,c)),a.dataMax=Math.max(y(a.dataMax,c[0]),Math.max.apply(null,c)))})};b.prototype.setAxisSize=function(){var b=this.chart;a.prototype.setAxisSize.call(this);
this.width=this.len=b.options.chart.options3d&&b.options.chart.options3d.depth||0;this.right=b.chartWidth-this.width-this.left};b.prototype.setOptions=function(b){b=B({offset:0,lineWidth:0},b);a.prototype.setOptions.call(this,b)};return b}(a);return b});D(a,"Core/Axis/Axis3DDefaults.js",[],function(){return{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}}});D(a,"Core/Axis/Tick3DComposition.js",[a["Core/Utilities.js"]],function(a){function A(a){var g=this.axis.axis3D;g&&
n(a.pos,g.fix3dPosition(a.pos))}function t(a){var g=this.axis.axis3D,e=a.apply(this,[].slice.call(arguments,1));if(g){var b=e[0],c=e[1];if("M"===b[0]&&"L"===c[0])return g=[g.fix3dPosition({x:b[1],y:b[2],z:0}),g.fix3dPosition({x:c[1],y:c[2],z:0})],this.axis.chart.renderer.toLineSegments(g)}return e}var C=a.addEvent,n=a.extend,l=a.wrap,B=[];return{compose:function(n){a.pushUnique(B,n)&&(C(n,"afterGetLabelPosition",A),l(n.prototype,"getMarkPath",t))}}});D(a,"Core/Axis/Axis3DComposition.js",[a["Core/Axis/Axis3DDefaults.js"],
a["Core/Globals.js"],a["Core/Math3D.js"],a["Core/Axis/Tick3DComposition.js"],a["Core/Utilities.js"]],function(a,z,t,C,n){function l(){var a=this.chart,b=this.options;a.is3d&&a.is3d()&&"colorAxis"!==this.coll&&(b.tickWidth=A(b.tickWidth,0),b.gridLineWidth=A(b.gridLineWidth,1))}function B(a){this.chart.is3d()&&"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)}function y(){this.axis3D||(this.axis3D=new L(this))}function g(a){return this.chart.is3d()&&
"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))}function e(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var b=arguments,c=b[2],e=[];b=this.getPlotLinePath({value:b[1]});c=this.getPlotLinePath({value:c});if(b&&c)for(var f=0;f<b.length;f+=2){var g=b[f],d=b[f+1],k=c[f],m=c[f+1];"M"===g[0]&&"L"===d[0]&&"M"===k[0]&&"L"===m[0]&&e.push(g,d,m,["L",k[1],k[2]],["Z"])}return e}function b(a){var b=this.axis3D,c=this.chart,e=a.apply(this,
[].slice.call(arguments,1));if("colorAxis"===this.coll||!c.chart3d||!c.is3d()||null===e)return e;var f=c.options.chart.options3d,g=this.isZAxis?c.plotWidth:f.depth;f=c.chart3d.frame3d;var d=e[0],k=e[1];e=[];"M"===d[0]&&"L"===k[0]&&(b=[b.swapZ({x:d[1],y:d[2],z:0}),b.swapZ({x:d[1],y:d[2],z:g}),b.swapZ({x:k[1],y:k[2],z:0}),b.swapZ({x:k[1],y:k[2],z:g})],this.horiz?(this.isZAxis?(f.left.visible&&e.push(b[0],b[2]),f.right.visible&&e.push(b[1],b[3])):(f.front.visible&&e.push(b[0],b[2]),f.back.visible&&e.push(b[1],
b[3])),f.top.visible&&e.push(b[0],b[1]),f.bottom.visible&&e.push(b[2],b[3])):(f.front.visible&&e.push(b[0],b[2]),f.back.visible&&e.push(b[1],b[3]),f.left.visible&&e.push(b[0],b[1]),f.right.visible&&e.push(b[2],b[3])),e=p(e,this.chart,!1));return c.renderer.toLineSegments(e)}function c(a,b){var c=this.chart,e=this.ticks,f=this.gridGroup;if(this.categories&&c.frameShapes&&c.is3d()&&f&&b&&b.label){f=f.element.childNodes[0].getBBox();var h=c.frameShapes.left.getBBox(),d=c.options.chart.options3d;c={x:c.plotWidth/
2,y:c.plotHeight/2,z:d.depth/2,vd:A(d.depth,1)*A(d.viewDistance,0)};d=b.pos;var g=e[d-1],m=e[d+1],p=e=void 0;0!==d&&g&&g.label&&g.label.xy&&(e=k({x:g.label.xy.x,y:g.label.xy.y,z:null},c,c.vd));m&&m.label&&m.label.xy&&(p=k({x:m.label.xy.x,y:m.label.xy.y,z:null},c,c.vd));d={x:b.label.xy.x,y:b.label.xy.y,z:null};d=k(d,c,c.vd);return Math.abs(e?d.x-e.x:p?p.x-d.x:f.x-h.x)}return a.apply(this,[].slice.call(arguments,1))}function E(a){var b=a.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(b,
!0):b}var m=z.deg2rad,p=t.perspective,k=t.perspective3D,F=t.shapeArea,w=n.addEvent,x=n.merge,A=n.pick,H=n.wrap,J=[],L=function(){function k(a){this.axis=a}k.compose=function(h,k){C.compose(k);n.pushUnique(J,h)&&(x(!0,h.defaultOptions,a),h.keepProps.push("axis3D"),w(h,"init",y),w(h,"afterSetOptions",l),w(h,"drawCrosshair",B),h=h.prototype,H(h,"getLinePath",g),H(h,"getPlotBandPath",e),H(h,"getPlotLinePath",b),H(h,"getSlotWidth",c),H(h,"getTitlePosition",E))};k.prototype.fix3dPosition=function(a,b){var c=
this.axis,f=c.chart;if("colorAxis"===c.coll||!f.chart3d||!f.is3d())return a;var e=m*f.options.chart.options3d.alpha,d=m*f.options.chart.options3d.beta,g=A(b&&c.options.title.position3d,c.options.labels.position3d);b=A(b&&c.options.title.skew3d,c.options.labels.skew3d);var k=f.chart3d.frame3d,h=f.plotLeft,l=f.plotWidth+h,n=f.plotTop,x=f.plotHeight+n,w=f=0,r={x:0,y:1,z:0},y=!1;a=c.axis3D.swapZ({x:a.x,y:a.y,z:0});if(c.isZAxis)if(c.opposite){if(null===k.axes.z.top)return{};w=a.y-n;a.x=k.axes.z.top.x;
a.y=k.axes.z.top.y;h=k.axes.z.top.xDir;y=!k.top.frontFacing}else{if(null===k.axes.z.bottom)return{};w=a.y-x;a.x=k.axes.z.bottom.x;a.y=k.axes.z.bottom.y;h=k.axes.z.bottom.xDir;y=!k.bottom.frontFacing}else if(c.horiz)if(c.opposite){if(null===k.axes.x.top)return{};w=a.y-n;a.y=k.axes.x.top.y;a.z=k.axes.x.top.z;h=k.axes.x.top.xDir;y=!k.top.frontFacing}else{if(null===k.axes.x.bottom)return{};w=a.y-x;a.y=k.axes.x.bottom.y;a.z=k.axes.x.bottom.z;h=k.axes.x.bottom.xDir;y=!k.bottom.frontFacing}else if(c.opposite){if(null===
k.axes.y.right)return{};f=a.x-l;a.x=k.axes.y.right.x;a.z=k.axes.y.right.z;h=k.axes.y.right.xDir;h={x:h.z,y:h.y,z:-h.x}}else{if(null===k.axes.y.left)return{};f=a.x-h;a.x=k.axes.y.left.x;a.z=k.axes.y.left.z;h=k.axes.y.left.xDir}"chart"!==g&&("flap"===g?c.horiz?(d=Math.sin(e),e=Math.cos(e),c.opposite&&(d=-d),y&&(d=-d),r={x:h.z*d,y:e,z:-h.x*d}):h={x:Math.cos(d),y:0,z:Math.sin(d)}:"ortho"===g?c.horiz?(r=Math.cos(e),g=Math.sin(d)*r,e=-Math.sin(e),d=-r*Math.cos(d),r={x:h.y*d-h.z*e,y:h.z*g-h.x*d,z:h.x*e-
h.y*g},e=1/Math.sqrt(r.x*r.x+r.y*r.y+r.z*r.z),y&&(e=-e),r={x:e*r.x,y:e*r.y,z:e*r.z}):h={x:Math.cos(d),y:0,z:Math.sin(d)}:c.horiz?r={x:Math.sin(d)*Math.sin(e),y:Math.cos(e),z:-Math.cos(d)*Math.sin(e)}:h={x:Math.cos(d),y:0,z:Math.sin(d)});a.x+=f*h.x+w*r.x;a.y+=f*h.y+w*r.y;a.z+=f*h.z+w*r.z;f=p([a],c.chart)[0];b&&(0>F(p([a,{x:a.x+h.x,y:a.y+h.y,z:a.z+h.z},{x:a.x+r.x,y:a.y+r.y,z:a.z+r.z}],c.chart))&&(h={x:-h.x,y:-h.y,z:-h.z}),a=p([{x:a.x,y:a.y,z:a.z},{x:a.x+h.x,y:a.y+h.y,z:a.z+h.z},{x:a.x+r.x,y:a.y+r.y,
z:a.z+r.z}],c.chart),f.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,f.x,f.y],f.matrix[4]-=f.x*f.matrix[0]+f.y*f.matrix[2],f.matrix[5]-=f.x*f.matrix[1]+f.y*f.matrix[3]);return f};k.prototype.swapZ=function(a,b){var c=this.axis;return c.isZAxis?(b=b?0:c.chart.plotLeft,{x:b+a.z,y:a.y,z:a.x-b}):a};return k}();return L});D(a,"Core/Series/Series3D.js",[a["Core/Math3D.js"],a["Core/Series/Series.js"],a["Core/Utilities.js"]],function(a,z,t){var A=this&&this.__extends||function(){function a(b,
c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)}return function(b,c){function e(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),n=a.perspective;a=t.addEvent;var l=t.extend,B=t.merge,y=t.pick,
g=t.isNumber;t=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}A(b,a);b.prototype.translate=function(){a.prototype.translate.apply(this,arguments);this.chart.is3d()&&this.translate3dPoints()};b.prototype.translate3dPoints=function(){var a=this.options,b=this.chart,e=y(this.zAxis,b.options.zAxis[0]),p=[],k,l=[];this.zPadding=(a.stacking?g(a.stack)?a.stack:0:this.index||0)*(a.depth||0+(a.groupZPadding||1));for(k=0;k<this.data.length;k++){a=this.data[k];if(e&&e.translate){var w=
e.logarithmic&&e.val2lin?e.val2lin(a.z):a.z;a.plotZ=e.translate(w);a.isInside=a.isInside?w>=e.min&&w<=e.max:!1}else a.plotZ=this.zPadding;a.axisXpos=a.plotX;a.axisYpos=a.plotY;a.axisZpos=a.plotZ;p.push({x:a.plotX,y:a.plotY,z:a.plotZ});l.push(a.plotX||0)}this.rawPointsX=l;b=n(p,b,!0);for(k=0;k<this.data.length;k++)a=this.data[k],e=b[k],a.plotX=e.x,a.plotY=e.y,a.plotZ=e.z};b.defaultOptions=B(z.defaultOptions);return b}(z);a(z,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});
l(z.prototype,{translate3dPoints:t.prototype.translate3dPoints});return t});D(a,"Series/Area3D/Area3DSeries.js",[a["Core/Math3D.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,z,t){function A(a){var e=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d())return e;var b=l.getGraphPath,c=this.options,g=Math.round(this.yAxis.getThreshold(c.threshold)),m=[];if(this.rawPointsX)for(var p=0;p<this.points.length;p++)m.push({x:this.rawPointsX[p],y:c.stacking?this.points[p].yBottom:
g,z:this.zPadding});c=this.chart.options.chart.options3d;m=n(m,this.chart,!0).map(function(a){return{plotX:a.x,plotY:a.y,plotZ:a.z}});this.group&&c&&c.depth&&c.beta&&(this.markerGroup&&(this.markerGroup.add(this.group),this.markerGroup.attr({translateX:0,translateY:0})),this.group.attr({zIndex:Math.max(1,270<c.beta||90>c.beta?c.depth-Math.round(this.zPadding||0):Math.round(this.zPadding||0))}));m.reversed=!0;b=b.call(this,m,!0,!0);b[0]&&"M"===b[0][0]&&(b[0]=["L",b[0][1],b[0][2]]);this.areaPath&&(b=
this.areaPath.splice(0,this.areaPath.length/2).concat(b),b.xMap=this.areaPath.xMap,this.areaPath=b);return e}var n=a.perspective,l=z.seriesTypes.line.prototype,B=t.wrap,y=[];return{compose:function(a){t.pushUnique(y,a)&&B(a.prototype,"getGraphPath",A)}}});D(a,"Series/Column3D/Column3DComposition.js",[a["Series/Column/ColumnSeries.js"],a["Core/Series/Series.js"],a["Core/Math3D.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Axis/Stacking/StackItem.js"],a["Core/Utilities.js"]],function(a,z,t,C,n,l){function B(a,
b){var c=a.series,e={totalStacks:0},g,k=1;c.forEach(function(a){g=m(a.options.stack,b?0:c.length-1-a.index);e[g]?e[g].series.push(a):(e[g]={series:[a],position:k},k++)});e.totalStacks=k+1;return e}function y(a){var b=a.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(b.stroke=this.options.edgeColor||b.fill,b["stroke-width"]=m(this.options.edgeWidth,1));return b}function g(a,b,c){var e=this.chart.is3d&&this.chart.is3d();e&&(this.options.inactiveOtherPoints=!0);a.call(this,
b,c);e&&(this.options.inactiveOtherPoints=!1)}function e(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:a.apply(this,b)}var b=a.prototype,c=t.perspective;t=l.addEvent;var A=l.extend,m=l.pick;l=l.wrap;l(b,"translate",function(a){a.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});l(z.prototype,"justifyDataLabel",function(a){return arguments[2].outside3dPlot?!1:a.apply(this,
[].slice.call(arguments,1))});b.translate3dPoints=function(){};b.translate3dShapes=function(){var a=this,b=a.chart,e=a.options,g=e.depth,m=(e.stacking?e.stack||0:a.index)*(g+(e.groupZPadding||1)),l=a.borderWidth%2?.5:0,n;b.inverted&&!a.yAxis.reversed&&(l*=-1);!1!==e.grouping&&(m=0);m+=e.groupZPadding||1;a.data.forEach(function(e){e.outside3dPlot=null;if(null!==e.y){var k=A({x:0,y:0,width:0,height:0},e.shapeArgs||{}),p=e.tooltipPos,h;[["x","width"],["y","height"]].forEach(function(b){h=k[b[0]]-l;0>
h&&(k[b[1]]+=k[b[0]]+l,k[b[0]]=-l,h=0);h+k[b[1]]>a[b[0]+"Axis"].len&&0!==k[b[1]]&&(k[b[1]]=a[b[0]+"Axis"].len-k[b[0]]);if(0!==k[b[1]]&&(k[b[0]]>=a[b[0]+"Axis"].len||k[b[0]]+k[b[1]]<=l)){for(var c in k)k[c]="y"===c?-9999:0;e.outside3dPlot=!0}});"roundedRect"===e.shapeType&&(e.shapeType="cuboid");e.shapeArgs=A(k,{z:m,depth:g,insidePlotArea:!0});n={x:k.x+k.width/2,y:k.y,z:m+g/2};b.inverted&&(n.x=k.height,n.y=e.clientX||0);e.plot3d=c([n],b,!0,!1)[0];p&&(p=c([{x:p[0],y:p[1],z:m+g/2}],b,!0,!1)[0],e.tooltipPos=
[p.x,p.y])}});a.z=m};l(b,"animate",function(a){if(this.chart.is3d()){var b=this.yAxis,c=this,e=this.yAxis.reversed;arguments[1]?c.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,e||(a.shapeArgs.y=a.stackY?a.plotY+b.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(c.data.forEach(function(a){if(null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic))a.graphic[a.outside3dPlot?"attr":"animate"](a.shapeArgs,
c.options.animation)}),this.drawDataLabels())}else a.apply(this,[].slice.call(arguments,1))});l(b,"plotGroup",function(a,b,c,e,g,m){"dataLabelsGroup"!==b&&"markerGroup"!==b&&this.chart.is3d()&&(this[b]&&delete this[b],m&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(m)),this[b]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[b].survive=!0,"group"===b&&(arguments[3]="visible")));return a.apply(this,Array.prototype.slice.call(arguments,
1))});l(b,"setVisible",function(a,b){var c=this;c.chart.is3d()&&c.data.forEach(function(a){a.visible=a.options.visible=b="undefined"===typeof b?!m(c.visible,a.visible):b;c.options.data[c.data.indexOf(a)]=a.options;a.graphic&&a.graphic.attr({visibility:b?"visible":"hidden"})});a.apply(this,Array.prototype.slice.call(arguments,1))});t(a,"afterInit",function(){if(this.chart.is3d()){var a=this.options,b=a.grouping,c=a.stacking,e=this.yAxis.options.reversedStacks,g=0;if("undefined"===typeof b||b){b=B(this.chart,
c);g=a.stack||0;for(c=0;c<b[g].series.length&&b[g].series[c]!==this;c++);g=10*(b.totalStacks-b[g].position)+(e?c:-c);this.xAxis.reversed||(g=10*b.totalStacks-g)}a.depth=a.depth||25;this.z=this.z||0;a.zIndex=g}});l(b,"pointAttribs",y);l(b,"setState",g);l(b.pointClass.prototype,"hasNewShapeType",e);C.seriesTypes.columnRange&&(t=C.seriesTypes.columnrange.prototype,l(t,"pointAttribs",y),l(t,"setState",g),l(t.pointClass.prototype,"hasNewShapeType",e),t.plotGroup=b.plotGroup,t.setVisible=b.setVisible);
l(z.prototype,"alignDataLabel",function(a,b,e,g,l){var k=this.chart;g.outside3dPlot=b.outside3dPlot;if(k.is3d()&&this.is("column")){var n=this.options,p=m(g.inside,!!this.options.stacking),w=k.options.chart.options3d,y=b.pointWidth/2||0;n={x:l.x+y,y:l.y,z:this.z+n.depth/2};k.inverted&&(p&&(l.width=0,n.x+=b.shapeArgs.height/2),90<=w.alpha&&270>=w.alpha&&(n.y+=b.shapeArgs.width));n=c([n],k,!0,!1)[0];l.x=n.x-y;l.y=b.outside3dPlot?-9E9:n.y}a.apply(this,[].slice.call(arguments,1))});l(n.prototype,"getStackBox",
function(a,b){var e=a.apply(this,[].slice.call(arguments,1)),g=this.axis.chart,k=b.width;if(g.is3d()&&this.base){var m=+this.base.split(",")[0],l=g.series[m];m=g.options.chart.options3d;l&&l instanceof C.seriesTypes.column&&(l={x:e.x+(g.inverted?e.height:k/2),y:e.y,z:l.options.depth/2},g.inverted&&(e.width=0,90<=m.alpha&&270>=m.alpha&&(l.y+=k)),l=c([l],g,!0,!1)[0],e.x=l.x-k/2,e.y=l.y)}return e});"";return a});D(a,"Series/Pie3D/Pie3DPoint.js",[a["Core/Series/SeriesRegistry.js"]],function(a){var A=
this&&this.__extends||function(){function a(n,l){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,l){a.__proto__=l}||function(a,l){for(var g in l)Object.prototype.hasOwnProperty.call(l,g)&&(a[g]=l[g])};return a(n,l)}return function(n,l){function t(){this.constructor=n}if("function"!==typeof l&&null!==l)throw new TypeError("Class extends value "+String(l)+" is not a constructor or null");a(n,l);n.prototype=null===l?Object.create(l):(t.prototype=l.prototype,new t)}}();a=a.seriesTypes.pie.prototype.pointClass;
var t=a.prototype.haloPath;return function(a){function n(){var l=null!==a&&a.apply(this,arguments)||this;l.series=void 0;return l}A(n,a);n.prototype.haloPath=function(){var a;return(null===(a=this.series)||void 0===a?0:a.chart.is3d())?[]:t.apply(this,arguments)};return n}(a)});D(a,"Series/Pie3D/Pie3DSeries.js",[a["Core/Globals.js"],a["Series/Pie3D/Pie3DPoint.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,z,t,C){var n=this&&this.__extends||function(){function a(g,e){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)Object.prototype.hasOwnProperty.call(c,b)&&(a[b]=c[b])};return a(g,e)}return function(g,e){function b(){this.constructor=g}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");a(g,e);g.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),l=a.deg2rad;a=C.extend;var A=C.pick;t=function(a){function g(){return null!==a&&a.apply(this,
arguments)||this}n(g,a);g.prototype.addPoint=function(){a.prototype.addPoint.apply(this,arguments);this.chart.is3d()&&this.update(this.userOptions,!0)};g.prototype.animate=function(e){if(this.chart.is3d()){var b=this.options.animation;var c=this.center;var g=this.group,m=this.markerGroup;!0===b&&(b={});e?(g.oldtranslateX=A(g.oldtranslateX,g.translateX),g.oldtranslateY=A(g.oldtranslateY,g.translateY),c={translateX:c[0],translateY:c[1],scaleX:.001,scaleY:.001},g.attr(c),m&&(m.attrSetters=g.attrSetters,
m.attr(c))):(c={translateX:g.oldtranslateX,translateY:g.oldtranslateY,scaleX:1,scaleY:1},g.animate(c,b),m&&m.animate(c,b))}else a.prototype.animate.apply(this,arguments)};g.prototype.getDataLabelPosition=function(e,b){b=a.prototype.getDataLabelPosition.call(this,e,b);if(this.chart.is3d()){var c=this.chart.options.chart.options3d;e=e.shapeArgs;var g=e.r,m=(e.start+e.end)/2,n=b.connectorPosition,k=-g*(1-Math.cos((e.alpha||(null===c||void 0===c?NaN:c.alpha))*l))*Math.sin(m),t=g*(Math.cos((e.beta||(null===
c||void 0===c?NaN:c.beta))*l)-1)*Math.cos(m);[null===b||void 0===b?void 0:b.natural,n.breakAt,n.touchingSliceAt].forEach(function(a){a.x+=t;a.y+=k})}return b};g.prototype.pointAttribs=function(e){var b=a.prototype.pointAttribs.apply(this,arguments),c=this.options;this.chart.is3d()&&!this.chart.styledMode&&(b.stroke=c.edgeColor||e.color||this.color,b["stroke-width"]=A(c.edgeWidth,1));return b};g.prototype.translate=function(){a.prototype.translate.apply(this,arguments);if(this.chart.is3d()){var e=
this,b=e.options,c=b.depth||0,g=e.chart.options.chart.options3d,m=g.alpha,n=g.beta,k=b.stacking?(b.stack||0)*c:e._i*c;k+=c/2;!1!==b.grouping&&(k=0);e.data.forEach(function(a){var g=a.shapeArgs;a.shapeType="arc3d";g.z=k;g.depth=.75*c;g.alpha=m;g.beta=n;g.center=e.center;g=(g.end+g.start)/2;a.slicedTranslation={translateX:Math.round(Math.cos(g)*b.slicedOffset*Math.cos(m*l)),translateY:Math.round(Math.sin(g)*b.slicedOffset*Math.cos(m*l))}})}};g.prototype.drawTracker=function(){a.prototype.drawTracker.apply(this,
arguments);this.chart.is3d()&&this.points.forEach(function(a){a.graphic&&["out","inn","side1","side2"].forEach(function(b){a.graphic&&(a.graphic[b].element.point=a)})})};return g}(t.seriesTypes.pie);a(t.prototype,{pointClass:z});"";return t});D(a,"Series/Pie3D/Pie3DComposition.js",[a["Series/Pie3D/Pie3DPoint.js"],a["Series/Pie3D/Pie3DSeries.js"],a["Core/Series/SeriesRegistry.js"]],function(a,z,t){t.seriesTypes.pie.prototype.pointClass.prototype.haloPath=a.prototype.haloPath;t.seriesTypes.pie=z});
D(a,"Series/Scatter3D/Scatter3DPoint.js",[a["Series/Scatter/ScatterSeries.js"],a["Core/Utilities.js"]],function(a,z){var t=this&&this.__extends||function(){function a(l,n){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var e in g)Object.prototype.hasOwnProperty.call(g,e)&&(a[e]=g[e])};return a(l,n)}return function(l,n){function t(){this.constructor=l}if("function"!==typeof n&&null!==n)throw new TypeError("Class extends value "+String(n)+" is not a constructor or null");
a(l,n);l.prototype=null===n?Object.create(n):(t.prototype=n.prototype,new t)}}(),A=z.defined;return function(a){function l(){var l=null!==a&&a.apply(this,arguments)||this;l.options=void 0;l.series=void 0;return l}t(l,a);l.prototype.applyOptions=function(){a.prototype.applyOptions.apply(this,arguments);A(this.z)||(this.z=0);return this};return l}(a.prototype.pointClass)});D(a,"Series/Scatter3D/Scatter3DSeries.js",[a["Core/Math3D.js"],a["Series/Scatter3D/Scatter3DPoint.js"],a["Series/Scatter/ScatterSeries.js"],
a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,z,t,C,n){var l=this&&this.__extends||function(){function a(e,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(e,b)}return function(e,b){function c(){this.constructor=e}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");a(e,b);
e.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)}}(),A=a.pointCameraDistance;a=n.extend;var y=n.merge;n=function(a){function e(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}l(e,a);e.prototype.pointAttribs=function(b){var c=a.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&b&&(c.zIndex=A(b,this.chart));return c};e.defaultOptions=y(t.defaultOptions,{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}});
return e}(t);a(n.prototype,{axisTypes:["xAxis","yAxis","zAxis"],directTouch:!0,parallelArrays:["x","y","z"],pointArrayMap:["x","y","z"],pointClass:z});C.registerSeriesType("scatter3d",n);"";return n});D(a,"masters/highcharts-3d.src.js",[a["Core/Globals.js"],a["Core/Renderer/SVG/SVGRenderer3D.js"],a["Core/Chart/Chart3D.js"],a["Core/Axis/ZAxis.js"],a["Core/Axis/Axis3DComposition.js"],a["Series/Area3D/Area3DSeries.js"]],function(a,z,t,C,n,l){z.compose(a.SVGRenderer);t.compose(a.Chart,a.Fx);C.compose(a.Chart);
n.compose(a.Axis,a.Tick);l.compose(a.seriesTypes.area)})});
//# sourceMappingURL=highcharts-3d.js.map