/**
 * Dependencies for the autoload feature.
 *
 * DO NOT EDIT THIS FILE. This file is generated using the
 * 'gulp dependency-mapping' task.
 */
declare const DependencyMapping: Record<string, Array<string>>;
export default DependencyMapping;
