!/**
 * Highstock JS v13.1.0 (2026-09-18)
 * @module highcharts/indicators/ao
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Wojciech Chmiel
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts.SeriesRegistry,t._Highcharts):"function"==typeof define&&define.amd?define("highcharts/indicators/ao",["highcharts/highcharts"],function(t){return e(t.SeriesRegistry,t)}):"object"==typeof exports?exports["highcharts/indicators/ao"]=e(t._Highcharts.SeriesRegistry,t._Highcharts):t.Highcharts=e(t.Highcharts.SeriesRegistry,t.Highcharts)}("u"<typeof window?this:window,(t,e)=>(()=>{"use strict";var r={512(e){e.exports=t},944(t){t.exports=e}};let o={};function s(t){let e=o[t];if(void 0!==e)return e.exports;let a=o[t]={exports:{}};return r[t](a,a.exports,s),a.exports}s.n=t=>{let e=t&&t.__esModule?()=>t.default:()=>t;return s.d(e,{a:e}),e},s.d=(t,e)=>{for(var r in e)s.o(e,r)&&!s.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},s.o=(t,e)=>Object.prototype.hasOwnProperty.call(t,e);let a={};s.d(a,{default:()=>u});var i=s(944),l=s.n(i),c=s(512),n=s.n(c);let{noop:h}=l(),{column:{prototype:p},sma:d}=n().seriesTypes;class g extends d{drawGraph(){let t,e=this.options,r=this.points,o=this.userOptions.color,s=e.greaterBarColor,a=e.lowerBarColor,i=r[0];if(!o&&i)for(i.color=s,t=1;t<r.length;t++)r[t].y>r[t-1].y?r[t].color=s:r[t].y<r[t-1].y?r[t].color=a:r[t].color=r[t-1].color}getValues(t){let e=t.xData||[],r=t.yData||[],o=r.length,s=[],a=[],l=[],c,n,h,p,d,g,u,f,y=0,x=0;if(!(e.length<=34)&&(0,i.isArray)(r[0])&&4===r[0].length){for(u=0;u<33;u++)g=(r[u][1]+r[u][2])/2,u>=29&&(x=(0,i.correctFloat)(x+g)),y=(0,i.correctFloat)(y+g);for(f=33;f<o;f++)g=(r[f][1]+r[f][2])/2,x=(0,i.correctFloat)(x+g),y=(0,i.correctFloat)(y+g),c=x/5,n=y/34,h=(0,i.correctFloat)(c-n),s.push([e[f],h]),a.push(e[f]),l.push(h),p=f+1-5,d=f+1-34,x=(0,i.correctFloat)(x-(r[p][1]+r[p][2])/2),y=(0,i.correctFloat)(y-(r[d][1]+r[d][2])/2);return{values:s,xData:a,yData:l}}}}g.defaultOptions=(0,i.merge)(d.defaultOptions,{params:{index:void 0,period:void 0},greaterBarColor:"var(--highcharts-positive-color)",lowerBarColor:"var(--highcharts-negative-color)",threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}}),(0,i.extend)(g.prototype,{nameBase:"AO",nameComponents:void 0,markerAttribs:h,getColumnMetrics:p.getColumnMetrics,crispCol:p.crispCol,translate:p.translate,drawPoints:p.drawPoints}),n().registerSeriesType("ao",g);let u=l();return a.default})());