/*
 Highstock JS v9.0.1 (2021-03-13)

 All technical indicators for Highstock

 (c) 2010-2021 Pawel Fus

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(u){d(u);d.Highcharts=u;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function u(d,f,g,h){d.hasOwnProperty(f)||(d[f]=h.apply(null,g))}d=d?d._modules:{};u(d,"Mixins/IndicatorRequired.js",[d["Core/Utilities.js"]],function(d){var f=d.error;return{isParentLoaded:function(g,
d,m,p,t){if(g)return p?p(g):!0;f(t||this.generateMessage(m,d));return!1},generateMessage:function(f,d){return'Error: "'+f+'" indicator type requires "'+d+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+f}}});u(d,"Stock/Indicators/SMA/SMAComposition.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=d.series,h=d.seriesTypes.ohlc.prototype;d=f.addEvent;var m=f.extend;d(g,"init",function(f){f=f.options;f.useOhlcData&&"highcharts-navigator-series"!==
f.id&&m(this,{pointValKey:h.pointValKey,keys:h.keys,pointArrayMap:h.pointArrayMap,toYData:h.toYData})});d(g,"afterSetOptions",function(f){f=f.options;var g=f.dataGrouping;g&&f.useOhlcData&&"highcharts-navigator-series"!==f.id&&(g.approximation="ohlc")})});u(d,"Stock/Indicators/SMA/SMAIndicator.js",[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return a(c,k)};return function(c,k){function b(){this.constructor=c}a(c,k);c.prototype=null===k?Object.create(k):(b.prototype=k.prototype,new b)}}(),m=f.seriesTypes.line,p=g.addEvent,t=g.error,l=g.extend,e=g.isArray,b=g.merge,a=g.pick,c=g.splat,k=d.generateMessage;d=function(y){function v(){var a=null!==y&&y.apply(this,arguments)||this;a.data=void 0;a.dataEventsToUnbind=void 0;a.linkedParent=void 0;
a.options=void 0;a.points=void 0;return a}h(v,y);v.prototype.destroy=function(){this.dataEventsToUnbind.forEach(function(a){a()});y.prototype.destroy.apply(this,arguments)};v.prototype.getName=function(){var c=this.name,k=[];c||((this.nameComponents||[]).forEach(function(c,b){k.push(this.options.params[c]+a(this.nameSuffixes[b],""))},this),c=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+k.join(", ")+")":""));return c};v.prototype.getValues=function(a,c){var k=c.period,b=a.xData;
a=a.yData;var y=a.length,v=0,B=0,l=[],f=[],g=[],F=-1;if(!(b.length<k)){for(e(a[0])&&(F=c.index?c.index:0);v<k-1;)B+=0>F?a[v]:a[v][F],v++;for(c=v;c<y;c++){B+=0>F?a[c]:a[c][F];var d=[b[c],B/k];l.push(d);f.push(d[0]);g.push(d[1]);B-=0>F?a[c-v]:a[c-v][F]}return{values:l,xData:f,yData:g}}};v.prototype.init=function(a,b){function e(){var a=v.points||[],k=(v.xData||[]).length,b=v.getValues(v.linkedParent,v.options.params)||{values:[],xData:[],yData:[]},e=[],y=!0;if(k&&!v.hasGroupedData&&v.visible&&v.points)if(v.cropped){if(v.xAxis){var n=
v.xAxis.min;var x=v.xAxis.max}k=v.cropData(b.xData,b.yData,n,x);for(n=0;n<k.xData.length;n++)e.push([k.xData[n]].concat(c(k.yData[n])));k=b.xData.indexOf(v.xData[0]);n=b.xData.indexOf(v.xData[v.xData.length-1]);-1===k&&n===b.xData.length-2&&e[0][0]===a[0].x&&e.shift();v.updateData(e)}else b.xData.length!==k-1&&b.xData.length!==k+1&&(y=!1,v.updateData(b.values));y&&(v.xData=b.xData,v.yData=b.yData,v.options.data=b.values);!1===v.bindTo.series&&(delete v.processedXData,v.isDirty=!0,v.redraw());v.isDirtyData=
!1}var v=this,n=v.requireIndicators();if(!n.allLoaded)return t(k(v.type,n.needed));y.prototype.init.call(v,a,b);a.linkSeries();v.dataEventsToUnbind=[];if(!v.linkedParent)return t("Series "+v.options.linkedTo+" not found! Check `linkedTo`.",!1,a);v.dataEventsToUnbind.push(p(v.bindTo.series?v.linkedParent:v.linkedParent.xAxis,v.bindTo.eventName,e));if("init"===v.calculateOn)e();else var x=p(v.chart,v.calculateOn,function(){e();x()})};v.prototype.processData=function(){var a=this.options.compareToMain,
c=this.linkedParent;y.prototype.processData.apply(this,arguments);c&&c.compareValue&&a&&(this.compareValue=c.compareValue)};v.prototype.requireIndicators=function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){f.seriesTypes[c]?f.seriesTypes[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=c)});return a};v.defaultOptions=b(m.defaultOptions,{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}});return v}(m);l(d.prototype,{bindTo:{series:!0,
eventName:"updatedData"},calculateOn:"init",hasDerivedData:!0,nameComponents:["period"],nameSuffixes:[],requiredIndicators:[],useCommonDataGrouping:!0});f.registerSeriesType("sma",d);"";return d});u(d,"Stock/Indicators/AD/ADIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var l=function(e,b){l=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&
(a[k]=c[k])};return l(e,b)};return function(e,b){function a(){this.constructor=e}l(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.error,p=f.extend,t=f.merge;f=function(l){function e(){var b=null!==l&&l.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,l);e.populateAverage=function(b,a,c,k,e){e=a[k][1];var y=a[k][2];a=a[k][3];c=c[k];return[b[k],a===e&&a===y||e===y?0:(2*a-y-e)/(e-y)*c]};e.prototype.getValues=
function(b,a){var c=a.period,k=b.xData,y=b.yData,v=a.volumeSeriesID,B=b.chart.get(v);a=B&&B.yData;var l=y?y.length:0,f=[],r=[],n=[];if(!(k.length<=c&&l&&4!==y[0].length)){if(B){for(v=c;v<l;v++)b=f.length,B=e.populateAverage(k,y,a,v,c),0<b&&(B[1]+=f[b-1][1]),f.push(B),r.push(B[0]),n.push(B[1]);return{values:f,xData:r,yData:n}}m("Series "+v+" not found! Check `volumeSeriesID`.",!0,b.chart)}};e.defaultOptions=t(h.defaultOptions,{params:{volumeSeriesID:"volume"}});return e}(h);p(f.prototype,{nameComponents:!1,
nameBase:"Accumulation/Distribution"});d.registerSeriesType("ad",f);"";return f});u(d,"Stock/Indicators/AO/AOIndicator.js",[d["Core/Globals.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return a(c,k)};return function(c,k){function b(){this.constructor=c}a(c,
k);c.prototype=null===k?Object.create(k):(b.prototype=k.prototype,new b)}}();d=d.noop;var m=f.seriesTypes,p=m.sma;m=m.column;var t=g.extend,l=g.merge,e=g.correctFloat,b=g.isArray;g=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}h(c,a);c.prototype.drawGraph=function(){var a=this.options,c=this.points,b=a.greaterBarColor;a=a.lowerBarColor;var e=c[0];if(!this.userOptions.color&&e)for(e.color=b,e=1;e<c.length;e++)c[e].color=
c[e].y>c[e-1].y?b:c[e].y<c[e-1].y?a:c[e-1].color};c.prototype.getValues=function(c){var a=c.xData||[];c=c.yData||[];var k=c.length,B=[],f=[],l=[],r=0,n=0,x;if(!(34>=a.length)&&b(c[0])&&4===c[0].length){for(x=0;33>x;x++){var q=(c[x][1]+c[x][2])/2;29<=x&&(r=e(r+q));n=e(n+q)}for(x=33;x<k;x++){q=(c[x][1]+c[x][2])/2;r=e(r+q);n=e(n+q);q=r/5;var A=n/34;q=e(q-A);B.push([a[x],q]);f.push(a[x]);l.push(q);q=x+1-5;A=x+1-34;r=e(r-(c[q][1]+c[q][2])/2);n=e(n-(c[A][1]+c[A][2])/2)}return{values:B,xData:f,yData:l}}};
c.defaultOptions=l(p.defaultOptions,{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}});return c}(p);t(g.prototype,{nameBase:"AO",nameComponents:!1,markerAttribs:d,getColumnMetrics:m.prototype.getColumnMetrics,crispCol:m.prototype.crispCol,translate:m.prototype.translate,drawPoints:m.prototype.drawPoints});f.registerSeriesType("ao",g);"";return g});u(d,"Mixins/MultipleLines.js",[d["Core/Globals.js"],d["Core/Utilities.js"]],
function(d,f){var g=f.defined,h=f.error,m=f.merge,p=d.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(f){var l=[];(this.pointArrayMap||[]).forEach(function(e){e!==f&&l.push("plot"+e.charAt(0).toUpperCase()+e.slice(1))});return l},toYData:function(f){var l=[];(this.pointArrayMap||[]).forEach(function(e){l.push(f[e])});return l},translate:function(){var f=this,l=f.pointArrayMap,e=[],b;e=f.getTranslatedLinesNames();
p.prototype.translate.apply(f,arguments);f.points.forEach(function(a){l.forEach(function(c,k){b=a[c];null!==b&&(a[e[k]]=f.yAxis.toPixels(b,!0))})})},drawGraph:function(){var f=this,l=f.linesApiNames,e=f.points,b=e.length,a=f.options,c=f.graph,k={options:{gapSize:a.gapSize}},y=[],v;f.getTranslatedLinesNames(f.pointValKey).forEach(function(c,a){for(y[a]=[];b--;)v=e[b],y[a].push({x:v.x,plotX:v.plotX,plotY:v[c],isNull:!g(v[c])});b=e.length});l.forEach(function(c,b){y[b]?(f.points=y[b],a[c]?f.options=
m(a[c].styles,k):h('Error: "There is no '+c+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),f.graph=f["graph"+c],p.prototype.drawGraph.call(f),f["graph"+c]=f.graph):h('Error: "'+c+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});f.points=e;f.options=a;f.graph=c;p.prototype.drawGraph.call(f)}}});u(d,"Stock/Indicators/Aroon/AroonIndicator.js",[d["Mixins/MultipleLines.js"],
d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){function h(b,a){var c=b[0],k=0,e;for(e=1;e<b.length;e++)if("max"===a&&b[e]>=c||"min"===a&&b[e]<=c)c=b[e],k=e;return k}var m=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&(c[k]=a[k])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):
(k.prototype=c.prototype,new k)}}(),p=f.seriesTypes.sma,t=g.extend,l=g.merge,e=g.pick;g=function(b){function a(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}m(a,b);a.prototype.getValues=function(c,a){a=a.period;var k=c.xData,b=(c=c.yData)?c.length:0,f=[],l=[],g=[],r;for(r=a-1;r<b;r++){var n=c.slice(r-a+1,r+2);var x=h(n.map(function(c){return e(c[2],c)}),"min");n=h(n.map(function(c){return e(c[1],c)}),"max");n=n/a*100;x=x/a*100;k[r+1]&&(f.push([k[r+
1],n,x]),l.push(k[r+1]),g.push([n,x]))}return{values:f,xData:l,yData:g}};a.defaultOptions=l(p.defaultOptions,{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}});return a}(p);t(g.prototype,{linesApiNames:["aroonDown"],nameBase:"Aroon",pointArrayMap:["y","aroonDown"],
pointValKey:"y",drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,toYData:d.toYData,translate:d.translate});f.registerSeriesType("aroon",g);"";return g});u(d,"Stock/Indicators/AroonOscillator/AroonOscillatorIndicator.js",[d["Mixins/MultipleLines.js"],d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g,h){var m=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,
a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&(c[k]=a[k])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),p=g.seriesTypes.aroon,t=h.extend,l=h.merge,e=g.seriesTypes.aroon;h=function(b){function a(){var c=null!==b&&b.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}m(a,b);a.prototype.getValues=function(c,a){var k=[],b=[],f=[];c=e.prototype.getValues.call(this,
c,a);for(a=0;a<c.yData.length;a++){var l=c.yData[a][0];var g=c.yData[a][1];l-=g;k.push([c.xData[a],l]);b.push(c.xData[a]);f.push(l)}return{values:k,xData:b,yData:f}};a.prototype.init=function(){var c=arguments,a=this;f.isParentLoaded(e,"aroon",a.type,function(k){k.prototype.init.apply(a,c)})};a.defaultOptions=l(p.defaultOptions,{params:{period:25},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}});return a}(p);t(h.prototype,l(d,{nameBase:"Aroon Oscillator",
pointArrayMap:["y"],pointValKey:"y",linesApiNames:[]}));g.registerSeriesType("aroonoscillator",h);"";return h});u(d,"Stock/Indicators/ATR/ATRIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){function g(f,e){return Math.max(f[1]-f[2],"undefined"===typeof e?0:Math.abs(f[1]-e[3]),"undefined"===typeof e?0:Math.abs(f[2]-e[3]))}var h=this&&this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=
c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return f(e,b)};return function(e,b){function a(){this.constructor=e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),m=d.seriesTypes.sma,p=f.isArray,t=f.merge;f=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}h(e,f);e.prototype.getValues=function(b,a){a=a.period;var c=b.xData,k=(b=b.yData)?b.length:0,e=1,v=0,f=0,l=[],d=[],
r=[],n;var x=[[c[0],b[0]]];if(!(c.length<=a)&&p(b[0])&&4===b[0].length){for(n=1;n<=k;n++)if(x.push([c[n],b[n]]),a<e){var q=a;var A=c[n-1],h=g(b[n-1],b[n-2]);q=[A,(v*(q-1)+h)/q];v=q[1];l.push(q);d.push(q[0]);r.push(q[1])}else a===e?(v=f/(n-1),l.push([c[n-1],v]),d.push(c[n-1]),r.push(v)):f+=g(b[n-1],b[n-2]),e++;return{values:l,xData:d,yData:r}}};e.defaultOptions=t(m.defaultOptions,{params:{period:14}});return e}(m);d.registerSeriesType("atr",f);"";return f});u(d,"Stock/Indicators/BB/BBIndicator.js",
[d["Mixins/MultipleLines.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var k in a)a.hasOwnProperty(k)&&(c[k]=a[k])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.sma,p=g.extend,t=g.isArray,
l=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=l({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};b.prototype.getValues=function(a,c){var k=c.period,b=c.standardDeviation,e=a.xData,l=(a=a.yData)?a.length:0,g=[],d=[],r=[],n;if(!(e.length<k)){var x=t(a[0]);
for(n=k;n<=l;n++){var q=e.slice(n-k,n);var A=a.slice(n-k,n);var h=f.seriesTypes.sma.prototype.getValues.call(this,{xData:q,yData:A},c);q=h.xData[0];h=h.yData[0];for(var m=0,w=A.length,p=0;p<w;p++){var z=(x?A[p][c.index]:A[p])-h;m+=z*z}z=Math.sqrt(m/(w-1));A=h+b*z;z=h-b*z;g.push([q,A,h,z]);d.push(q);r.push([A,h,z])}return{values:g,xData:d,yData:r}}};b.defaultOptions=l(m.defaultOptions,{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,
lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}});return b}(m);p(g.prototype,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,translate:d.translate,
toYData:d.toYData});f.registerSeriesType("bb",g);"";return g});u(d,"Stock/Indicators/CCI/CCIIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){function g(f){return f.reduce(function(e,b){return e+b},0)}var h=this&&this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return f(e,b)};return function(e,b){function a(){this.constructor=
e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),m=d.seriesTypes.sma,p=f.isArray,t=f.merge;f=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}h(e,f);e.prototype.getValues=function(b,a){a=a.period;var c=b.xData,k=(b=b.yData)?b.length:0,e=[],v=1,f=[],l=[],d=[];if(!(c.length<=a)&&p(b[0])&&4===b[0].length){for(;v<a;){var r=b[v-1];e.push((r[1]+r[2]+r[3])/3);v++}for(v=a;v<=k;v++){r=b[v-1];r=(r[1]+
r[2]+r[3])/3;var n=e.push(r);var x=e.slice(n-a);n=g(x)/a;var q,A=x.length,h=0;for(q=0;q<A;q++)h+=Math.abs(n-x[q]);x=h/a;r=(r-n)/(.015*x);f.push([c[v-1],r]);l.push(c[v-1]);d.push(r)}return{values:f,xData:l,yData:d}}};e.defaultOptions=t(m.defaultOptions,{params:{period:14}});return e}(m);d.registerSeriesType("cci",f);"";return f});u(d,"Stock/Indicators/CMF/CMFIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var f=function(d,
l){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,b){e.__proto__=b}||function(e,b){for(var a in b)b.hasOwnProperty(a)&&(e[a]=b[a])};return f(d,l)};return function(d,l){function e(){this.constructor=d}f(d,l);d.prototype=null===l?Object.create(l):(e.prototype=l.prototype,new e)}}(),h=d.seriesTypes.sma,m=f.merge;f=function(f){function d(){var l=null!==f&&f.apply(this,arguments)||this;l.data=void 0;l.options=void 0;l.points=void 0;l.volumeSeries=void 0;l.linkedParent=void 0;l.yData=
void 0;l.nameBase="Chaikin Money Flow";return l}g(d,f);d.prototype.isValid=function(){var f=this.chart,e=this.options,b=this.linkedParent;f=this.volumeSeries||(this.volumeSeries=f.get(e.params.volumeSeriesID));var a=b&&b.yData&&4===b.yData[0].length;return!!(b&&f&&b.xData&&b.xData.length>=e.params.period&&f.xData&&f.xData.length>=e.params.period&&a)};d.prototype.getValues=function(f,e){if(this.isValid())return this.getMoneyFlow(f.xData,f.yData,this.volumeSeries.yData,e.period)};d.prototype.getMoneyFlow=
function(f,e,b,a){function c(a,c){var k=a[1],b=a[2];a=a[3];return null!==c&&null!==k&&null!==b&&null!==a&&k!==b?(a-b-(k-a))/(k-b)*c:(x=n,null)}var k=e.length,y=[],v=0,d=0,l=[],g=[],r=[],n,x=-1;if(0<a&&a<=k){for(n=0;n<a;n++)y[n]=c(e[n],b[n]),v+=b[n],d+=y[n];l.push(f[n-1]);g.push(n-x>=a&&0!==v?d/v:null);for(r.push([l[0],g[0]]);n<k;n++){y[n]=c(e[n],b[n]);v-=b[n-a];v+=b[n];d-=y[n-a];d+=y[n];var q=[f[n],n-x>=a?d/v:null];l.push(q[0]);g.push(q[1]);r.push([q[0],q[1]])}}return{values:r,xData:l,yData:g}};d.defaultOptions=
m(h.defaultOptions,{params:{period:14,volumeSeriesID:"volume"}});return d}(h);d.registerSeriesType("cmf",f);"";return f});u(d,"Stock/Indicators/DPO/DPOIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){function g(b,a,c,k,f){a=e(a[c][k],a[c]);return f?l(b-a):l(b+a)}var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=
c[k])};return b(a,c)};return function(a,c){function k(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(k.prototype=c.prototype,new k)}}(),m=d.seriesTypes.sma,p=f.extend,t=f.merge,l=f.correctFloat,e=f.pick;f=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.options=void 0;a.data=void 0;a.points=void 0;return a}h(a,b);a.prototype.getValues=function(a,k){var c=k.period;k=k.index;var b=c+Math.floor(c/2+1),f=a.xData||[];a=a.yData||[];var d=a.length,l=[],r=[],n=
[],x=0,q,A;if(!(f.length<=b)){for(q=0;q<c-1;q++)x=g(x,a,q,k);for(A=0;A<=d-b;A++){var h=A+c-1;q=A+b-1;x=g(x,a,h,k);h=e(a[q][k],a[q]);h-=x/c;x=g(x,a,A,k,!0);l.push([f[q],h]);r.push(f[q]);n.push(h)}return{values:l,xData:r,yData:n}}};a.defaultOptions=t(m.defaultOptions,{params:{period:21}});return a}(m);p(f.prototype,{nameBase:"DPO"});d.registerSeriesType("dpo",f);"";return f});u(d,"Stock/Indicators/EMA/EMAIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&
this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return f(e,b)};return function(e,b){function a(){this.constructor=e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.correctFloat,p=f.isArray,t=f.merge;f=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.options=
void 0;b.points=void 0;return b}g(e,f);e.prototype.accumulatePeriodPoints=function(b,a,c){for(var k=0,e=0,f;e<b;)f=0>a?c[e]:c[e][a],k+=f,e++;return k};e.prototype.calculateEma=function(b,a,c,k,e,f,d){b=b[c-1];a=0>f?a[c-1]:a[c-1][f];k="undefined"===typeof e?d:m(a*k+e*(1-k));return[b,k]};e.prototype.getValues=function(b,a){var c=a.period,k=b.xData,e=(b=b.yData)?b.length:0,f=2/(c+1),d=[],l=[],g=[],r=-1;if(!(e<c)){p(b[0])&&(r=a.index?a.index:0);a=this.accumulatePeriodPoints(c,r,b);for(a/=c;c<e+1;c++){var n=
this.calculateEma(k,b,c,f,n,r,a);d.push(n);l.push(n[0]);g.push(n[1]);n=n[1]}return{values:d,xData:l,yData:g}}};e.defaultOptions=t(h.defaultOptions,{params:{index:3,period:9}});return e}(h);d.registerSeriesType("ema",f);"";return f});u(d,"Stock/Indicators/Chaikin/ChaikinIndicator.js",[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var a=function(c,k){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,c){a.__proto__=c}||function(a,c){for(var k in c)c.hasOwnProperty(k)&&(a[k]=c[k])};return a(c,k)};return function(c,k){function b(){this.constructor=c}a(c,k);c.prototype=null===k?Object.create(k):(b.prototype=k.prototype,new b)}}(),m=f.seriesTypes,p=m.ad,t=m.ema,l=g.correctFloat;m=g.extend;var e=g.merge,b=g.error;g=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}h(c,a);c.prototype.init=function(){var a=
arguments,c=this;d.isParentLoaded(t,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};c.prototype.getValues=function(a,c){var k=c.periods,e=c.period,f=[],y=[],d=[],n;if(2!==k.length||k[1]<=k[0])b('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(c=p.prototype.getValues.call(this,a,{volumeSeriesID:c.volumeSeriesID,period:e}))if(a=t.prototype.getValues.call(this,c,{period:k[0]}),c=t.prototype.getValues.call(this,c,{period:k[1]}),a&&c){k=
k[1]-k[0];for(n=0;n<c.yData.length;n++)e=l(a.yData[n+k]-c.yData[n]),f.push([c.xData[n],e]),y.push(c.xData[n]),d.push(e);return{values:f,xData:y,yData:d}}};c.defaultOptions=e(t.defaultOptions,{params:{volumeSeriesID:"volume",periods:[3,10]}});return c}(t);m(g.prototype,{nameBase:"Chaikin Osc",nameComponents:["periods"]});f.registerSeriesType("chaikin",g);"";return g});u(d,"Stock/Indicators/DEMA/DEMAIndicator.js",[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],
function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,k){a.__proto__=k}||function(a,k){for(var c in k)k.hasOwnProperty(c)&&(a[c]=k[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.ema,p=g.correctFloat,t=g.isArray,l=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||
this;a.EMApercent=void 0;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(m,"ema",c.type,function(k){k.prototype.init.apply(c,a)})};b.prototype.getEMA=function(a,c,k,b,e,f){return m.prototype.calculateEma(f||[],a,"undefined"===typeof e?1:e,this.EMApercent,c,"undefined"===typeof b?-1:b,k)};b.prototype.getValues=function(a,c){var b=c.period,e=2*b,f=a.xData,d=(a=a.yData)?a.length:0,l=-1,g=[],r=[],n=[],x=0,q=[],A;this.EMApercent=
2/(b+1);if(!(d<2*b-1)){t(a[0])&&(l=c.index?c.index:0);c=m.prototype.accumulatePeriodPoints(b,l,a);var h=c/b;c=0;for(A=b;A<d+2;A++){A<d+1&&(x=this.getEMA(a,z,h,l,A)[1],q.push(x));var z=x;if(A<e)c+=x;else{A===e&&(h=c/b);x=q[A-b-1];var w=this.getEMA([x],w,h)[1];var O=[f[A-2],p(2*x-w)];g.push(O);r.push(O[0]);n.push(O[1])}}return{values:g,xData:r,yData:n}}};b.defaultOptions=l(m.defaultOptions);return b}(m);f.registerSeriesType("dema",g);"";return g});u(d,"Stock/Indicators/TEMA/TEMAIndicator.js",[d["Mixins/IndicatorRequired.js"],
d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.ema,p=g.correctFloat,t=g.isArray,l=g.merge;g=function(e){function b(){var a=
null!==e&&e.apply(this,arguments)||this;a.EMApercent=void 0;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(m,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};b.prototype.getEMA=function(a,c,b,e,f,d){return m.prototype.calculateEma(d||[],a,"undefined"===typeof f?1:f,this.EMApercent,c,"undefined"===typeof e?-1:e,b)};b.prototype.getTemaPoint=function(a,c,b,e){return[a[e-3],p(3*b.level1-3*b.level2+b.level3)]};b.prototype.getValues=
function(a,c){var b=c.period,e=2*b,f=3*b,d=a.xData,l=(a=a.yData)?a.length:0,g=-1,r=[],n=[],x=[],q=[],A=[],h,p,w={};this.EMApercent=2/(b+1);if(!(l<3*b-2)){t(a[0])&&(g=c.index?c.index:0);c=m.prototype.accumulatePeriodPoints(b,g,a);var z=c/b;c=0;for(h=b;h<l+3;h++){h<l+1&&(w.level1=this.getEMA(a,Q,z,g,h)[1],q.push(w.level1));var Q=w.level1;if(h<e)c+=w.level1;else{h===e&&(z=c/b,c=0);w.level1=q[h-b-1];w.level2=this.getEMA([w.level1],C,z)[1];A.push(w.level2);var C=w.level2;if(h<f)c+=w.level2;else{h===f&&
(z=c/b);h===l+1&&(w.level1=q[h-b-1],w.level2=this.getEMA([w.level1],C,z)[1],A.push(w.level2));w.level1=q[h-b-2];w.level2=A[h-2*b-1];w.level3=this.getEMA([w.level2],w.prevLevel3,z)[1];if(p=this.getTemaPoint(d,f,w,h))r.push(p),n.push(p[0]),x.push(p[1]);w.prevLevel3=w.level3}}}return{values:r,xData:n,yData:x}}};b.defaultOptions=l(m.defaultOptions);return b}(m);f.registerSeriesType("tema",g);"";return g});u(d,"Stock/Indicators/TRIX/TRIXIndicator.js",[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],
d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return f(e,b)};return function(e,b){function a(){this.constructor=e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),m=f.seriesTypes.tema,p=g.correctFloat,t=g.merge;g=function(l){function e(){var b=null!==l&&l.apply(this,
arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}h(e,l);e.prototype.init=function(){var b=arguments,a=this;d.isParentLoaded(f.seriesTypes.tema,"tema",a.type,function(c){c.prototype.init.apply(a,b)})};e.prototype.getTemaPoint=function(b,a,c,k){if(k>a)var e=[b[k-3],0!==c.prevLevel3?p(c.level3-c.prevLevel3)/c.prevLevel3*100:null];return e};e.defaultOptions=t(m.defaultOptions);return e}(m);f.registerSeriesType("trix",g);"";return g});u(d,"Stock/Indicators/APO/APOIndicator.js",
[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.ema,p=g.extend,t=g.merge,
l=g.error;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,c){var b=c.periods,e=c.index;c=[];var f=[],d=[],g;if(2!==b.length||b[1]<=b[0])l('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var h=m.prototype.getValues.call(this,a,{index:e,period:b[0]});a=m.prototype.getValues.call(this,a,{index:e,period:b[1]});if(h&&a){b=b[1]-b[0];
for(g=0;g<a.yData.length;g++)e=h.yData[g+b]-a.yData[g],c.push([a.xData[g],e]),f.push(a.xData[g]),d.push(e);return{values:c,xData:f,yData:d}}}};b.prototype.init=function(){var a=arguments,c=this;d.isParentLoaded(m,"ema",c.type,function(b){b.prototype.init.apply(c,a)})};b.defaultOptions=t(m.defaultOptions,{params:{periods:[10,20]}});return b}(m);p(g.prototype,{nameBase:"APO",nameComponents:["periods"]});f.registerSeriesType("apo",g);"";return g});u(d,"Stock/Indicators/IKH/IKHIndicator.js",[d["Core/Color/Color.js"],
d["Core/Globals.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g,h){function m(a){return a.reduce(function(a,c){return Math.max(a,c[1])},-Infinity)}function p(a){return a.reduce(function(a,c){return Math.min(a,c[2])},Infinity)}function t(a){return{high:m(a),low:p(a)}}function l(a){var c,b,k,e,f;a.series.forEach(function(a){if(a.xData)for(e=a.xData,f=b=a.xIncrement?1:e.length-1;0<f;f--)if(k=e[f]-e[f-1],"undefined"===typeof c||k<c)c=k});return c}function e(a,c,b,k){if(a&&
c&&b&&k){var e=c.plotX-a.plotX;c=c.plotY-a.plotY;var f=k.plotX-b.plotX;k=k.plotY-b.plotY;var v=a.plotX-b.plotX,n=a.plotY-b.plotY;b=(-c*v+e*n)/(-f*c+e*k);f=(f*n-k*v)/(-f*c+e*k);if(0<=b&&1>=b&&0<=f&&1>=f)return{plotX:a.plotX+f*e,plotY:a.plotY+f*c}}return!1}function b(a){var c=a.indicator;c.points=a.points;c.nextPoints=a.nextPoints;c.color=a.color;c.options=F(a.options.senkouSpan.styles,a.gap);c.graph=a.graph;c.fillGraph=!0;g.seriesTypes.sma.prototype.drawGraph.call(c)}var a=this&&this.__extends||function(){var a=
function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),c=d.parse,k=g.seriesTypes.sma,y=h.defined;d=h.extend;var v=h.isArray,B=h.isNumber,F=h.merge,K=h.objectEach;f.approximations["ichimoku-averages"]=function(){var a=[],c;[].forEach.call(arguments,
function(b,k){a.push(f.approximations.average(b));c=!c&&"undefined"===typeof a[k]});return c?void 0:a};h=function(f){function d(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.graphCollection=void 0;a.graphsenkouSpan=void 0;a.ikhMap=void 0;a.nextPoints=void 0;return a}a(d,f);d.prototype.init=function(){g.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=F({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},
chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:c(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:c(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:c(this.color).setOpacity(.2).get()}}},this.options)};d.prototype.toYData=function(a){return[a.tenkanSen,a.kijunSen,a.chikouSpan,a.senkouSpanA,a.senkouSpanB]};d.prototype.translate=function(){var a=this;g.seriesTypes.sma.prototype.translate.apply(a);a.points.forEach(function(c){a.pointArrayMap.forEach(function(b){var k=
c[b];B(k)&&(c["plot"+b]=a.yAxis.toPixels(k,!0),c.plotY=c["plot"+b],c.tooltipPos=[c.plotX,c["plot"+b]],c.isNull=!1)})})};d.prototype.drawGraph=function(){var a=this,c=a.points,k=c.length,f=a.options,v=a.graph,d=a.color,n={options:{gapSize:f.gapSize}},l=a.pointArrayMap.length,h=[[],[],[],[],[],[]],r={tenkanLine:h[0],kijunLine:h[1],chikouLine:h[2],senkouSpanA:h[3],senkouSpanB:h[4],senkouSpan:h[5]},B=[],m=a.options.senkouSpan,t=m.color||m.styles.fill,p=m.negativeColor,z=[[],[]],u=[[],[]],N=0,J,P,M;for(a.ikhMap=
r;k--;){var D=c[k];for(J=0;J<l;J++)m=a.pointArrayMap[J],y(D[m])&&h[J].push({plotX:D.plotX,plotY:D["plot"+m],isNull:!1});p&&k!==c.length-1&&(m=r.senkouSpanB.length-1,D=e(r.senkouSpanA[m-1],r.senkouSpanA[m],r.senkouSpanB[m-1],r.senkouSpanB[m]),J={plotX:D.plotX,plotY:D.plotY,isNull:!1,intersectPoint:!0},D&&(r.senkouSpanA.splice(m,0,J),r.senkouSpanB.splice(m,0,J),B.push(m)))}K(r,function(c,b){f[b]&&"senkouSpan"!==b&&(a.points=h[N],a.options=F(f[b].styles,n),a.graph=a["graph"+b],a.fillGraph=!1,a.color=
d,g.seriesTypes.sma.prototype.drawGraph.call(a),a["graph"+b]=a.graph);N++});a.graphCollection&&a.graphCollection.forEach(function(c){a[c].destroy();delete a[c]});a.graphCollection=[];if(p&&r.senkouSpanA[0]&&r.senkouSpanB[0]){B.unshift(0);B.push(r.senkouSpanA.length-1);for(l=0;l<B.length-1;l++){m=B[l];D=B[l+1];k=r.senkouSpanB.slice(m,D+1);m=r.senkouSpanA.slice(m,D+1);if(1<=Math.floor(k.length/2))if(D=Math.floor(k.length/2),k[D].plotY===m[D].plotY){for(M=J=D=0;M<k.length;M++)D+=k[M].plotY,J+=m[M].plotY;
D=D>J?0:1}else D=k[D].plotY>m[D].plotY?0:1;else D=k[0].plotY>m[0].plotY?0:1;z[D]=z[D].concat(k);u[D]=u[D].concat(m)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(c,k){z[k].length&&u[k].length&&(P=0===k?t:p,b({indicator:a,points:z[k],nextPoints:u[k],color:P,options:f,gap:n,graph:a[c]}),a[c]=a.graph,a.graphCollection.push(c))})}else b({indicator:a,points:r.senkouSpanB,nextPoints:r.senkouSpanA,color:t,options:f,gap:n,graph:a.graphsenkouSpan}),a.graphsenkouSpan=a.graph;delete a.nextPoints;
delete a.fillGraph;a.points=c;a.options=f;a.graph=v;a.color=d};d.prototype.getGraphPath=function(a){var c=[],b;a=a||this.points;if(this.fillGraph&&this.nextPoints){if((b=g.seriesTypes.sma.prototype.getGraphPath.call(this,this.nextPoints))&&b.length){b[0][0]="L";c=g.seriesTypes.sma.prototype.getGraphPath.call(this,a);b=b.slice(0,c.length);for(var k=b.length-1;0<=k;k--)c.push(b[k])}}else c=g.seriesTypes.sma.prototype.getGraphPath.apply(this,arguments);return c};d.prototype.getValues=function(a,c){var b=
c.period,k=c.periodTenkan;c=c.periodSenkouSpanB;var e=a.xData,f=a.yData,d=f&&f.length||0;a=l(a.xAxis);var n=[],y=[],g;if(!(e.length<=b)&&v(f[0])&&4===f[0].length){var r=e[0]-b*a;for(g=0;g<b;g++)y.push(r+g*a);for(g=0;g<d;g++){if(g>=k){var h=f.slice(g-k,g);h=t(h);h=(h.high+h.low)/2}if(g>=b){var B=f.slice(g-b,g);B=t(B);B=(B.high+B.low)/2;var q=(h+B)/2}if(g>=c){var x=f.slice(g-c,g);x=t(x);x=(x.high+x.low)/2}r=f[g][3];var m=e[g];"undefined"===typeof n[g]&&(n[g]=[]);"undefined"===typeof n[g+b]&&(n[g+b]=
[]);n[g+b][0]=h;n[g+b][1]=B;n[g+b][2]=void 0;n[g][2]=r;g<=b&&(n[g+b][3]=void 0,n[g+b][4]=void 0);"undefined"===typeof n[g+2*b]&&(n[g+2*b]=[]);n[g+2*b][3]=q;n[g+2*b][4]=x;y.push(m)}for(g=1;g<=b;g++)y.push(m+g*a);return{values:n,xData:y,yData:n}}};d.defaultOptions=F(k.defaultOptions,{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},
tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}});return d}(k);d(h.prototype,{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB",
"period","periodTenkan"]});g.registerSeriesType("ikh",h);"";return h});u(d,"Stock/Indicators/KeltnerChannels/KeltnerChannelsIndicator.js",[d["Mixins/MultipleLines.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=
b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.sma,p=g.correctFloat,t=g.extend,l=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=l({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};b.prototype.getValues=function(a,
c){var b=c.period,e=c.periodATR,d=c.multiplierATR,g=a.yData;g=g?g.length:0;var l=[];c=f.seriesTypes.ema.prototype.getValues(a,{period:b,index:c.index});var h=f.seriesTypes.atr.prototype.getValues(a,{period:e}),r=[],n=[],x;if(!(g<b)){for(x=b;x<=g;x++){var q=c.values[x-b];var m=h.values[x-e];var t=q[0];a=p(q[1]+d*m[1]);m=p(q[1]-d*m[1]);q=q[1];l.push([t,a,q,m]);r.push(t);n.push([a,q,m])}return{values:l,xData:r,yData:n}}};b.defaultOptions=l(m.defaultOptions,{params:{period:20,periodATR:10,multiplierATR:2},
bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1});return b}(m);t(g.prototype,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",
nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,translate:d.translate,toYData:d.toYData});f.registerSeriesType("keltnerchannels",g);"";return g});u(d,"Stock/Indicators/MACD/MACDIndicator.js",[d["Core/Globals.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),m=d.noop,p=f.seriesTypes.sma,t=g.extend,l=g.correctFloat,e=g.defined,b=g.merge;g=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;c.currentLineZone=void 0;c.graphmacd=
void 0;c.graphsignal=void 0;c.macdZones=void 0;c.signalZones=void 0;return c}h(c,a);c.prototype.init=function(){f.seriesTypes.sma.prototype.init.apply(this,arguments);this.options&&(this.options=b({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length},this.resetZones=!0)};
c.prototype.toYData=function(a){return[a.y,a.signal,a.MACD]};c.prototype.translate=function(){var a=this,c=["plotSignal","plotMACD"];d.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(b){[b.signal,b.MACD].forEach(function(k,e){null!==k&&(b[c[e]]=a.yAxis.toPixels(k,!0))})})};c.prototype.destroy=function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();f.seriesTypes.sma.prototype.destroy.apply(this,
arguments)};c.prototype.drawGraph=function(){for(var a=this,c=a.points,d=c.length,g=a.options,l=a.zones,h={options:{gapSize:g.gapSize}},r=[[],[]],n;d--;)n=c[d],e(n.plotMACD)&&r[0].push({plotX:n.plotX,plotY:n.plotMACD,isNull:!e(n.plotMACD)}),e(n.plotSignal)&&r[1].push({plotX:n.plotX,plotY:n.plotSignal,isNull:!e(n.plotMACD)});["macd","signal"].forEach(function(c,k){a.points=r[k];a.options=b(g[c+"Line"].styles,h);a.graph=a["graph"+c];a.currentLineZone=c+"Zones";a.zones=a[a.currentLineZone].zones;f.seriesTypes.sma.prototype.drawGraph.call(a);
a["graph"+c]=a.graph});a.points=c;a.options=g;a.zones=l;a.currentLineZone=null};c.prototype.getZonesGraphs=function(c){var b=a.prototype.getZonesGraphs.call(this,c),k=b;this.currentLineZone&&(k=b.splice(this[this.currentLineZone].startIndex+1),k.length?k.splice(0,0,c[0]):k=[c[0]]);return k};c.prototype.applyZones=function(){var a=this.zones;this.zones=this.signalZones.zones;f.seriesTypes.sma.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();
this.zones=a};c.prototype.getValues=function(a,c){var b=c.longPeriod-c.shortPeriod,k=0,d=[],g=[],y=[];if(!(a.xData.length<c.longPeriod+c.signalPeriod)){var n=f.seriesTypes.ema.prototype.getValues(a,{period:c.shortPeriod,index:c.index});var h=f.seriesTypes.ema.prototype.getValues(a,{period:c.longPeriod,index:c.index});n=n.values;h=h.values;for(a=0;a<=n.length;a++)e(h[a])&&e(h[a][1])&&e(n[a+b])&&e(n[a+b][0])&&d.push([n[a+b][0],0,null,n[a+b][1]-h[a][1]]);for(a=0;a<d.length;a++)g.push(d[a][0]),y.push([0,
null,d[a][3]]);c=f.seriesTypes.ema.prototype.getValues({xData:g,yData:y},{period:c.signalPeriod,index:2});c=c.values;for(a=0;a<d.length;a++)d[a][0]>=c[0][0]&&(d[a][2]=c[k][1],y[a]=[0,c[k][1],d[a][3]],null===d[a][3]?(d[a][1]=0,y[a][0]=0):(d[a][1]=l(d[a][3]-c[k][1]),y[a][0]=l(d[a][3]-c[k][1])),k++);return{values:d,xData:g,yData:y}}};c.defaultOptions=b(p.defaultOptions,{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],
styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,crisp:!1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0});return c}(p);t(g.prototype,{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],
parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:m,getColumnMetrics:d.seriesTypes.column.prototype.getColumnMetrics,crispCol:d.seriesTypes.column.prototype.crispCol,drawPoints:d.seriesTypes.column.prototype.drawPoints});f.registerSeriesType("macd",g);"";return g});u(d,"Stock/Indicators/MFI/MFIIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){function g(a){return a.reduce(function(a,b){return a+b})}function h(a){return(a[1]+a[2]+a[3])/3}var m=
this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),p=d.seriesTypes.sma,t=f.extend,l=f.merge,e=f.error,b=f.isArray;f=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;
c.options=void 0;c.points=void 0;return c}m(c,a);c.prototype.getValues=function(a,c){var k=c.period,f=a.xData,d=a.yData,l=d?d.length:0,r=c.decimals,n=1,y=a.chart.get(c.volumeSeriesID),q=y&&y.yData,m=[],t=[],p=[],w=[],z=[];if(!y)e("Series "+c.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,a.chart);else if(!(f.length<=k)&&b(d[0])&&4===d[0].length&&q){for(a=h(d[n]);n<k+1;)c=a,a=h(d[n]),c=a>=c,y=a*q[n],w.push(c?y:0),z.push(c?0:y),n++;for(k=n-1;k<l;k++)k>n-1&&(w.shift(),z.shift(),c=a,a=h(d[k]),
c=a>c,y=a*q[k],w.push(c?y:0),z.push(c?0:y)),c=g(z),y=g(w),c=y/c,c=parseFloat((100-100/(1+c)).toFixed(r)),m.push([f[k],c]),t.push(f[k]),p.push(c);return{values:m,xData:t,yData:p}}};c.defaultOptions=l(p.defaultOptions,{params:{period:14,volumeSeriesID:"volume",decimals:4}});return c}(p);t(f.prototype,{nameBase:"Money Flow Index"});d.registerSeriesType("mfi",f);"";return f});u(d,"Stock/Indicators/Momentum/MomentumIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){function g(e,
b,a,c,k){a=a[c-1][3]-a[c-k-1][3];b=b[c-1];e.shift();return[b,a]}var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=d.seriesTypes.sma,p=f.extend,t=f.isArray,l=f.merge;f=function(e){function b(){var a=
null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,c){c=c.period;var b=a.xData,e=(a=a.yData)?a.length:0,f=b[0],d=[],l=[],h=[];if(!(b.length<=c)&&t(a[0])){var r=a[0][3];r=[[f,r]];for(f=c+1;f<e;f++){var n=g(r,b,a,f,c,void 0);d.push(n);l.push(n[0]);h.push(n[1])}n=g(r,b,a,f,c,void 0);d.push(n);l.push(n[0]);h.push(n[1]);return{values:d,xData:l,yData:h}}};b.defaultOptions=l(m.defaultOptions,{params:{period:14}});return b}(m);
p(f.prototype,{nameBase:"Momentum"});d.registerSeriesType("momentum",f);"";return f});u(d,"Stock/Indicators/NATR/NATRIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var f=function(d,e){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return f(d,e)};return function(d,e){function b(){this.constructor=d}f(d,e);d.prototype=
null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=d.seriesTypes.atr,m=f.merge;f=f.extend;var p=function(f){function d(){var e=null!==f&&f.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(d,f);d.prototype.getValues=function(e,b){var a=h.prototype.getValues.apply(this,arguments),c=a.values.length,k=b.period-1,f=e.yData,d=0;if(a){for(;d<c;d++)a.yData[d]=a.values[d][1]/f[k][3]*100,a.values[d][1]=a.yData[d],k++;return a}};d.defaultOptions=m(h.defaultOptions,
{tooltip:{valueSuffix:"%"}});return d}(h);f(p.prototype,{requiredIndicators:["atr"]});d.registerSeriesType("natr",p);"";return p});u(d,"Stock/Indicators/PivotPoints/PivotPointsPoint.js",[d["Core/Series/SeriesRegistry.js"]],function(d){function f(f,g){var h=f.series.pointArrayMap,m=h.length;for(d.seriesTypes.sma.prototype.pointClass.prototype[g].call(f);m--;)g="dataLabel"+h[m],f[g]&&f[g].element&&f[g].destroy(),f[g]=null}var g=this&&this.__extends||function(){var f=function(d,g){f=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(f,d){f.__proto__=d}||function(f,d){for(var e in d)d.hasOwnProperty(e)&&(f[e]=d[e])};return f(d,g)};return function(d,g){function h(){this.constructor=d}f(d,g);d.prototype=null===g?Object.create(g):(h.prototype=g.prototype,new h)}}();return function(d){function h(){var f=null!==d&&d.apply(this,arguments)||this;f.P=void 0;f.pivotLine=void 0;f.series=void 0;return f}g(h,d);h.prototype.destroyElements=function(){f(this,"destroyElements")};h.prototype.destroy=function(){f(this,
"destroyElements")};return h}(d.seriesTypes.sma.prototype.pointClass)});u(d,"Stock/Indicators/PivotPoints/PivotPointsIndicator.js",[d["Stock/Indicators/PivotPoints/PivotPointsPoint.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,
c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),m=f.seriesTypes.sma,p=g.merge,t=g.extend,l=g.defined,e=g.isArray;g=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;a.endPoint=void 0;a.plotEndPoint=void 0;return a}h(a,b);a.prototype.toYData=function(a){return[a.P]};a.prototype.translate=function(){var a=this;f.seriesTypes.sma.prototype.translate.apply(a);a.points.forEach(function(c){a.pointArrayMap.forEach(function(b){l(c[b])&&
(c["plot"+b]=a.yAxis.toPixels(c[b],!0))})});a.plotEndPoint=a.xAxis.toPixels(a.endPoint,!0)};a.prototype.getGraphPath=function(a){for(var c=this,b=a.length,e=[[],[],[],[],[],[],[],[],[]],d=[],g=c.plotEndPoint,h=c.pointArrayMap.length,r,n,m;b--;){n=a[b];for(m=0;m<h;m++)r=c.pointArrayMap[m],l(n[r])&&e[m].push({plotX:n.plotX,plotY:n["plot"+r],isNull:!1},{plotX:g,plotY:n["plot"+r],isNull:!1},{plotX:g,plotY:null,isNull:!0});g=n.plotX}e.forEach(function(a){d=d.concat(f.seriesTypes.sma.prototype.getGraphPath.call(c,
a))});return d};a.prototype.drawDataLabels=function(){var a=this,b=a.pointArrayMap,e,d,g;if(a.options.dataLabels.enabled){var l=a.points.length;b.concat([!1]).forEach(function(c,k){for(g=l;g--;)d=a.points[g],c?(d.y=d[c],d.pivotLine=c,d.plotY=d["plot"+c],e=d["dataLabel"+c],k&&(d["dataLabel"+b[k-1]]=d.dataLabel),d.dataLabels||(d.dataLabels=[]),d.dataLabels[0]=d.dataLabel=e=e&&e.element?e:null):d["dataLabel"+b[k-1]]=d.dataLabel;f.seriesTypes.sma.prototype.drawDataLabels.apply(a,arguments)})}};a.prototype.getValues=
function(a,b){var c=b.period,k=a.xData,f=(a=a.yData)?a.length:0;b=this[b.algorithm+"Placement"];var d=[],g=[],l=[],n;if(!(k.length<c)&&e(a[0])&&4===a[0].length){for(n=c+1;n<=f+c;n+=c){var h=k.slice(n-c-1,n);var q=a.slice(n-c-1,n);var m=h.length;var t=h[m-1];q=this.getPivotAndHLC(q);q=b(q);q=d.push([t].concat(q));g.push(t);l.push(d[q-1].slice(1))}this.endPoint=h[0]+(t-h[0])/m*c;return{values:d,xData:g,yData:l}}};a.prototype.getPivotAndHLC=function(a){var c=-Infinity,b=Infinity,e=a[a.length-1][3];a.forEach(function(a){c=
Math.max(c,a[1]);b=Math.min(b,a[2])});return[(c+b+e)/3,c,b,e]};a.prototype.standardPlacement=function(a){var c=a[1]-a[2];return[null,null,a[0]+c,2*a[0]-a[2],a[0],2*a[0]-a[1],a[0]-c,null,null]};a.prototype.camarillaPlacement=function(a){var c=a[1]-a[2];return[a[3]+1.5*c,a[3]+1.25*c,a[3]+1.1666*c,a[3]+1.0833*c,a[0],a[3]-1.0833*c,a[3]-1.1666*c,a[3]-1.25*c,a[3]-1.5*c]};a.prototype.fibonacciPlacement=function(a){var c=a[1]-a[2];return[null,a[0]+c,a[0]+.618*c,a[0]+.382*c,a[0],a[0]-.382*c,a[0]-.618*c,a[0]-
c,null]};a.defaultOptions=p(m.defaultOptions,{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}});return a}(m);t(g.prototype,{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",pointClass:d});f.registerSeriesType("pivotpoints",g);"";return g});u(d,"Stock/Indicators/PPO/PPOIndicator.js",[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],
d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),m=f.seriesTypes.ema,p=g.correctFloat,t=g.extend,l=g.merge,e=g.error;g=function(b){function a(){var a=null!==
b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(a,b);a.prototype.init=function(){var a=arguments,b=this;d.isParentLoaded(m,"ema",b.type,function(c){c.prototype.init.apply(b,a)})};a.prototype.getValues=function(a,b){var c=b.periods,f=b.index;b=[];var k=[],d=[],g;if(2!==c.length||c[1]<=c[0])e('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');else{var l=m.prototype.getValues.call(this,a,{index:f,period:c[0]});a=
m.prototype.getValues.call(this,a,{index:f,period:c[1]});if(l&&a){c=c[1]-c[0];for(g=0;g<a.yData.length;g++)f=p((l.yData[g+c]-a.yData[g])/a.yData[g]*100),b.push([a.xData[g],f]),k.push(a.xData[g]),d.push(f);return{values:b,xData:k,yData:d}}}};a.defaultOptions=l(m.defaultOptions,{params:{periods:[12,26]}});return a}(m);t(g.prototype,{nameBase:"PPO",nameComponents:["periods"]});f.registerSeriesType("ppo",g);"";return g});u(d,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(d,f){return d.reduce(function(d,
h){return Math.min(d,h[f])},Number.MAX_VALUE)},maxInArray:function(d,f){return d.reduce(function(d,h){return Math.max(d,h[f])},-Number.MAX_VALUE)},getArrayExtremes:function(d,f,g){return d.reduce(function(d,m){return[Math.min(d[0],m[f]),Math.max(d[1],m[g])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});u(d,"Stock/Indicators/PC/PCIndicator.js",[d["Core/Color/Palette.js"],d["Mixins/MultipleLines.js"],d["Mixins/ReduceArray.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g,h,
z){var m=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),t=h.seriesTypes.sma,l=z.merge;z=z.extend;var e=g.getArrayExtremes;g=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=
void 0;a.options=void 0;a.points=void 0;return a}m(a,b);a.prototype.getValues=function(a,b){b=b.period;var c=a.xData,f=(a=a.yData)?a.length:0,k=[],d=[],g=[],l;if(!(f<b)){for(l=b;l<=f;l++){var n=c[l-1];var h=a.slice(l-b,l);var q=e(h,2,1);h=q[1];var m=q[0];q=(h+m)/2;k.push([n,h,q,m]);d.push(n);g.push([h,q,m])}return{values:k,xData:d,yData:g}}};a.defaultOptions=l(t.defaultOptions,{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:d.colors[2],lineWidth:1}},bottomLine:{styles:{lineColor:d.colors[8],
lineWidth:1}},dataGrouping:{approximation:"averages"}});return a}(t);z(g.prototype,{getTranslatedLinesNames:f.getTranslatedLinesNames,drawGraph:f.drawGraph,toYData:f.toYData,pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],translate:f.translate});h.registerSeriesType("pc",g);"";return g});u(d,"Stock/Indicators/PriceEnvelopes/PriceEnvelopesIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],
function(d,f){var g=this&&this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return f(e,b)};return function(e,b){function a(){this.constructor=e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.extend,p=f.isArray,t=f.merge;f=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=
void 0;b.options=void 0;b.points=void 0;return b}g(e,f);e.prototype.init=function(){d.seriesTypes.sma.prototype.init.apply(this,arguments);this.options=t({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)};e.prototype.toYData=function(b){return[b.top,b.middle,b.bottom]};e.prototype.translate=function(){var b=this,a=["plotTop","plotMiddle","plotBottom"];d.seriesTypes.sma.prototype.translate.apply(b);b.points.forEach(function(c){[c.top,c.middle,c.bottom].forEach(function(e,
f){null!==e&&(c[a[f]]=b.yAxis.toPixels(e,!0))})})};e.prototype.drawGraph=function(){for(var b=this,a=b.points,c=a.length,e=b.options,f=b.graph,g={options:{gapSize:e.gapSize}},l=[[],[]],h;c--;)h=a[c],l[0].push({plotX:h.plotX,plotY:h.plotTop,isNull:h.isNull}),l[1].push({plotX:h.plotX,plotY:h.plotBottom,isNull:h.isNull});["topLine","bottomLine"].forEach(function(a,c){b.points=l[c];b.options=t(e[a].styles,g);b.graph=b["graph"+a];d.seriesTypes.sma.prototype.drawGraph.call(b);b["graph"+a]=b.graph});b.points=
a;b.options=e;b.graph=f;d.seriesTypes.sma.prototype.drawGraph.call(b)};e.prototype.getValues=function(b,a){var c=a.period,e=a.topBand,f=a.bottomBand,g=b.xData,l=(b=b.yData)?b.length:0,h=[],m=[],r=[],n;if(!(g.length<c)&&p(b[0])&&4===b[0].length){for(n=c;n<=l;n++){var x=g.slice(n-c,n);var q=b.slice(n-c,n);q=d.seriesTypes.sma.prototype.getValues.call(this,{xData:x,yData:q},a);x=q.xData[0];q=q.yData[0];var A=q*(1+e);var t=q*(1-f);h.push([x,A,q,t]);m.push(x);r.push([A,q,t])}return{values:h,xData:m,yData:r}}};
e.defaultOptions=t(h.defaultOptions,{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}});return e}(h);m(f.prototype,{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",
pointArrayMap:["top","middle","bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle"});d.registerSeriesType("priceenvelopes",f);"";return f});u(d,"Stock/Indicators/PSAR/PSARIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var f=function(d,e){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return f(d,e)};
return function(d,e){function b(){this.constructor=d}f(d,e);d.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=d.seriesTypes.sma,m=f.merge;f=f.extend;var p=function(f){function d(){var e=null!==f&&f.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(d,f);d.prototype.getValues=function(e,b){var a=e.xData;e=e.yData;var c=e[0][1],f=b.maxAccelerationFactor,d=b.increment,g=b.initialAccelerationFactor,l=e[0][2],h=b.decimals,m=b.index,r=[],n=[],
x=[],q=1,A;if(!(m>=e.length)){for(A=0;A<m;A++)c=Math.max(e[A][1],c),l=Math.min(e[A][2],parseFloat(l.toFixed(h)));var t=e[A][1]>l?1:-1;b=b.initialAccelerationFactor;var p=b*(c-l);r.push([a[m],l]);n.push(a[m]);x.push(parseFloat(l.toFixed(h)));for(A=m+1;A<e.length;A++){m=e[A-1][2];var w=e[A-2][2];var z=e[A-1][1];var u=e[A-2][1];var C=e[A][1];var L=e[A][2];null!==w&&null!==u&&null!==m&&null!==z&&null!==C&&null!==L&&(l=t===q?1===t?l+p<Math.min(w,m)?l+p:Math.min(w,m):l+p>Math.max(u,z)?l+p:Math.max(u,z):
c,m=1===t?C>c?C:c:L<c?L:c,C=1===q&&L>l||-1===q&&C>l?1:-1,q=C,p=m,L=d,w=f,z=g,b=q===t?1===q&&p>c?b===w?w:parseFloat((b+L).toFixed(2)):-1===q&&p<c?b===w?w:parseFloat((b+L).toFixed(2)):b:z,c=m-l,p=b*c,r.push([a[A],parseFloat(l.toFixed(h))]),n.push(a[A]),x.push(parseFloat(l.toFixed(h))),q=t,t=C,c=m)}return{values:r,xData:n,yData:x}}};d.defaultOptions=m(h.defaultOptions,{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,
index:2,decimals:4}});return d}(h);f(p.prototype,{nameComponents:!1});d.registerSeriesType("psar",p);"";return p});u(d,"Stock/Indicators/ROC/ROCIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return f(e,b)};return function(e,b){function a(){this.constructor=
e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.isArray,p=f.merge;f=f.extend;var t=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,f);e.prototype.getValues=function(b,a){var c=a.period,e=b.xData,f=(b=b.yData)?b.length:0,d=[],g=[],l=[],h=-1;if(!(e.length<=c)){m(b[0])&&(h=a.index);for(a=c;a<f;a++){var r=0>h?(r=b[a-c])?(b[a]-r)/r*100:null:(r=b[a-c][h])?(b[a][h]-
r)/r*100:null;r=[e[a],r];d.push(r);g.push(r[0]);l.push(r[1])}return{values:d,xData:g,yData:l}}};e.defaultOptions=p(h.defaultOptions,{params:{index:3,period:9}});return e}(h);f(t.prototype,{nameBase:"Rate of Change"});d.registerSeriesType("roc",t);"";return t});u(d,"Stock/Indicators/RSI/RSIIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var f=function(d,e){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,
a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return f(d,e)};return function(d,e){function b(){this.constructor=d}f(d,e);d.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=d.seriesTypes.sma,m=f.isNumber,p=f.merge;f=function(f){function d(){var e=null!==f&&f.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(d,f);d.prototype.getValues=function(e,b){var a=b.period,c=e.xData,f=e.yData;e=f?f.length:0;var d=
b.decimals,g=1,h=[],l=[],p=[],r=b.index,n=b=0,x;if(!(c.length<a)){if(m(f[0]))var q=f;else r=Math.min(r,f[0].length-1),q=f.map(function(a){return a[r]});for(;g<a;){var A=parseFloat((q[g]-q[g-1]).toFixed(d));0<A?b+=A:n+=Math.abs(A);g++}f=parseFloat((b/(a-1)).toFixed(d));for(x=parseFloat((n/(a-1)).toFixed(d));g<e;g++)A=parseFloat((q[g]-q[g-1]).toFixed(d)),0<A?(b=A,n=0):(b=0,n=Math.abs(A)),f=parseFloat(((f*(a-1)+b)/a).toFixed(d)),x=parseFloat(((x*(a-1)+n)/a).toFixed(d)),b=0===x?100:0===f?0:parseFloat((100-
100/(1+f/x)).toFixed(d)),h.push([c[g],b]),l.push(c[g]),p.push(b);return{values:h,xData:l,yData:p}}};d.defaultOptions=p(h.defaultOptions,{params:{period:14,decimals:4,index:3}});return d}(h);d.registerSeriesType("rsi",f);"";return f});u(d,"Stock/Indicators/Stochastic/StochasticIndicator.js",[d["Mixins/MultipleLines.js"],d["Mixins/ReduceArray.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g,h){var m=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),p=g.seriesTypes.sma,t=h.extend,l=h.isArray,e=h.merge;h=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}m(a,b);a.prototype.init=function(){g.seriesTypes.sma.prototype.init.apply(this,
arguments);this.options=e({smoothedLine:{styles:{lineColor:this.color}}},this.options)};a.prototype.getValues=function(a,b){var c=b.periods[0];b=b.periods[1];var e=a.xData,d=(a=a.yData)?a.length:0,k=[],h=[],m=[],n=null,x;if(!(d<c)&&l(a[0])&&4===a[0].length){for(x=c-1;x<d;x++){var q=a.slice(x-c+1,x+1);var A=f.getArrayExtremes(q,2,1);var p=A[0];q=a[x][3]-p;p=A[1]-p;q=q/p*100;h.push(e[x]);m.push([q,null]);x>=c-1+(b-1)&&(n=g.seriesTypes.sma.prototype.getValues.call(this,{xData:h.slice(-b),yData:m.slice(-b)},
{period:b}),n=n.yData[0]);k.push([e[x],q,n]);m[m.length-1][1]=n}return{values:k,xData:h,yData:m}}};a.defaultOptions=e(p.defaultOptions,{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}});return a}(p);t(h.prototype,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y",
"smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,translate:d.translate,toYData:d.toYData});g.registerSeriesType("stochastic",h);"";return h});u(d,"Stock/Indicators/SlowStochastic/SlowStochasticIndicator.js",[d["Mixins/IndicatorRequired.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.stochastic,p=f.seriesTypes,t=g.extend,l=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.init=function(){var a=
arguments,c=this;d.isParentLoaded(p.stochastic,"stochastic",c.type,function(b){b.prototype.init.apply(c,a)})};b.prototype.getValues=function(a,c){var b=c.periods,e=p.stochastic.prototype.getValues.call(this,a,c);a={values:[],xData:[],yData:[]};c=0;if(e){a.xData=e.xData.slice(b[1]-1);e=e.yData.slice(b[1]-1);var f=p.sma.prototype.getValues.call(this,{xData:a.xData,yData:e},{index:1,period:b[2]});if(f){for(var d=a.xData.length;c<d;c++)a.yData[c]=[e[c][1],f.yData[c-b[2]+1]||null],a.values[c]=[a.xData[c],
e[c][1],f.yData[c-b[2]+1]||null];return a}}};b.defaultOptions=l(m.defaultOptions,{params:{periods:[14,3,3]}});return b}(m);t(g.prototype,{nameBase:"Slow Stochastic"});f.registerSeriesType("slowstochastic",g);"";return g});u(d,"Stock/Indicators/Supertrend/SupertrendIndicator.js",[d["Core/Color/Palette.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){function h(a,c,b){return{index:c,close:a.yData[c][b],x:a.xData[c]}}var m=this&&this.__extends||function(){var a=function(c,
b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function e(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),p=f.seriesTypes,t=p.atr,l=p.sma,e=g.correctFloat,b=g.isArray;p=g.extend;var a=g.merge,c=g.objectEach;g=function(f){function k(){var a=null!==f&&f.apply(this,arguments)||this;a.data=void 0;a.linkedParent=
void 0;a.options=void 0;a.points=void 0;return a}m(k,f);k.prototype.init=function(){l.prototype.init.apply(this,arguments);var a=this.options;a.cropThreshold=this.linkedParent.options.cropThreshold-(a.params.period-1)};k.prototype.drawGraph=function(){var b=this,e=b.options,f=b.linkedParent,d=f?f.points:[],k=b.points,g=b.graph,m=k.length,q=d.length-m;q=0<q?q:0;for(var A={options:{gapSize:e.gapSize}},p={top:[],bottom:[],intersect:[]},t={top:{styles:{lineWidth:e.lineWidth,lineColor:e.fallingTrendColor||
e.color,dashStyle:e.dashStyle}},bottom:{styles:{lineWidth:e.lineWidth,lineColor:e.risingTrendColor||e.color,dashStyle:e.dashStyle}},intersect:e.changeTrendLine},w,y,u,C,z,G,H,I;m--;)w=k[m],y=k[m-1],u=d[m-1+q],C=d[m-2+q],z=d[m+q],G=d[m+q+1],H=w.options.color,I={x:w.x,plotX:w.plotX,plotY:w.plotY,isNull:!1},!C&&u&&f.yData[u.index-1]&&(C=h(f,u.index-1,3)),!G&&z&&f.yData[z.index+1]&&(G=h(f,z.index+1,3)),!u&&C&&f.yData[C.index+1]?u=h(f,C.index+1,3):!u&&z&&f.yData[z.index-1]&&(u=h(f,z.index-1,3)),w&&u&&
z&&C&&w.x!==u.x&&(w.x===z.x?(C=u,u=z):w.x===C.x?(u=C,C={close:f.yData[u.index-1][3],x:f.xData[u.index-1]}):G&&w.x===G.x&&(u=G,C=z)),y&&C&&u?(z={x:y.x,plotX:y.plotX,plotY:y.plotY,isNull:!1},w.y>=u.close&&y.y>=C.close?(w.color=H||e.fallingTrendColor||e.color,p.top.push(I)):w.y<u.close&&y.y<C.close?(w.color=H||e.risingTrendColor||e.color,p.bottom.push(I)):(p.intersect.push(I),p.intersect.push(z),p.intersect.push(a(z,{isNull:!0})),w.y>=u.close&&y.y<C.close?(w.color=H||e.fallingTrendColor||e.color,y.color=
H||e.risingTrendColor||e.color,p.top.push(I),p.top.push(a(z,{isNull:!0}))):w.y<u.close&&y.y>=C.close&&(w.color=H||e.risingTrendColor||e.color,y.color=H||e.fallingTrendColor||e.color,p.bottom.push(I),p.bottom.push(a(z,{isNull:!0}))))):u&&(w.y>=u.close?(w.color=H||e.fallingTrendColor||e.color,p.top.push(I)):(w.color=H||e.risingTrendColor||e.color,p.bottom.push(I)));c(p,function(c,e){b.points=c;b.options=a(t[e].styles,A);b.graph=b["graph"+e+"Line"];l.prototype.drawGraph.call(b);b["graph"+e+"Line"]=b.graph});
b.points=k;b.options=e;b.graph=g};k.prototype.getValues=function(a,c){var f=c.period;c=c.multiplier;var d=a.xData,k=a.yData,g=[],h=[],l=[],m=0===f?0:f-1,p=[],v=[],w;if(!(d.length<=f||!b(k[0])||4!==k[0].length||0>f)){a=t.prototype.getValues.call(this,a,{period:f}).yData;for(w=0;w<a.length;w++){var y=k[m+w];var B=k[m+w-1]||[];var u=p[w-1];var z=v[w-1];var G=l[w-1];0===w&&(u=z=G=0);f=e((y[1]+y[2])/2+c*a[w]);var H=e((y[1]+y[2])/2-c*a[w]);p[w]=f<u||B[3]>u?f:u;v[w]=H>z||B[3]<z?H:z;if(G===u&&y[3]<p[w]||
G===z&&y[3]<v[w])var I=p[w];else if(G===u&&y[3]>p[w]||G===z&&y[3]>v[w])I=v[w];g.push([d[m+w],I]);h.push(d[m+w]);l.push(I)}return{values:g,xData:h,yData:l}}};k.defaultOptions=a(l.defaultOptions,{params:{multiplier:3,period:10},risingTrendColor:d.indicatorPositiveLine,fallingTrendColor:d.indicatorNegativeLine,changeTrendLine:{styles:{lineWidth:1,lineColor:d.neutralColor80,dashStyle:"LongDash"}}});return k}(l);p(g.prototype,{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"]});
f.registerSeriesType("supertrend",g);"";return g});u(d,"Stock/Indicators/VBP/VBPIndicator.js",[d["Core/Animation/AnimationUtilities.js"],d["Core/Globals.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g,h){var m=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,b)};return function(c,b){function e(){this.constructor=
c}a(c,b);c.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}(),p=d.animObject;d=f.noop;var t=g.seriesTypes.sma,l=h.addEvent,e=h.arrayMax,b=h.arrayMin,a=h.correctFloat,c=h.error,k=h.extend,y=h.isArray,v=h.merge,B=Math.abs,u=g.seriesTypes.column.prototype;h=function(d){function g(){var a=null!==d&&d.apply(this,arguments)||this;a.data=void 0;a.negWidths=void 0;a.options=void 0;a.points=void 0;a.posWidths=void 0;a.priceZones=void 0;a.rangeStep=void 0;a.volumeDataArray=void 0;a.zoneStarts=
void 0;a.zoneLinesSVG=void 0;return a}m(g,d);g.prototype.init=function(a){f.seriesTypes.sma.prototype.init.apply(this,arguments);var c=this.options.params;var b=this.linkedParent;c=a.get(c.volumeSeriesID);this.addCustomEvents(b,c);return this};g.prototype.addCustomEvents=function(a,c){function b(){e.chart.redraw();e.setData([]);e.zoneStarts=[];e.zoneLinesSVG&&(e.zoneLinesSVG=e.zoneLinesSVG.destroy())}var e=this;e.dataEventsToUnbind.push(l(a,"remove",function(){b()}));c&&e.dataEventsToUnbind.push(l(c,
"remove",function(){b()}));return e};g.prototype.animate=function(a){var c=this,b=c.chart.inverted,e=c.group,f={};!a&&e&&(a=b?c.yAxis.top:c.xAxis.left,b?(e["forceAnimate:translateY"]=!0,f.translateY=a):(e["forceAnimate:translateX"]=!0,f.translateX=a),e.animate(f,k(p(c.options.animation),{step:function(a,b){c.group.attr({scaleX:Math.max(.001,b.pos)})}})))};g.prototype.drawPoints=function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,!0),u.drawPoints.apply(this,arguments),this.posNegVolume(!1,
!1));u.drawPoints.apply(this,arguments)};g.prototype.posNegVolume=function(a,c){var b=c?["positive","negative"]:["negative","positive"],e=this.options.volumeDivision,f=this.points.length,d=[],k=[],g=0,h;a?(this.posWidths=d,this.negWidths=k):(d=this.posWidths,k=this.negWidths);for(;g<f;g++){var l=this.points[g];l[b[0]+"Graphic"]=l.graphic;l.graphic=l[b[1]+"Graphic"];if(a){var n=l.shapeArgs.width;var m=this.priceZones[g];(h=m.wholeVolumeData)?(d.push(n/h*m.positiveVolumeData),k.push(n/h*m.negativeVolumeData)):
(d.push(0),k.push(0))}l.color=c?e.styles.positiveColor:e.styles.negativeColor;l.shapeArgs.width=c?this.posWidths[g]:this.negWidths[g];l.shapeArgs.x=c?l.shapeArgs.x:this.posWidths[g]}};g.prototype.translate=function(){var c=this,b=c.options,f=c.chart,d=c.yAxis,k=d.min,g=c.options.zoneLines,h=c.priceZones,l=0,m,r,p;u.translate.apply(c);var v=c.points;if(v.length){var t=.5>b.pointPadding?b.pointPadding:.1;b=c.volumeDataArray;var y=e(b);var z=f.plotWidth/2;var F=f.plotTop;var K=B(d.toPixels(k)-d.toPixels(k+
c.rangeStep));var N=B(d.toPixels(k)-d.toPixels(k+c.rangeStep));t&&(k=B(K*(1-2*t)),l=B((K-k)/2),K=B(k));v.forEach(function(b,e){r=b.barX=b.plotX=0;p=b.plotY=d.toPixels(h[e].start)-F-(d.reversed?K-N:K)-l;m=a(z*h[e].wholeVolumeData/y);b.pointWidth=m;b.shapeArgs=c.crispCol.apply(c,[r,p,m,K]);b.volumeNeg=h[e].negativeVolumeData;b.volumePos=h[e].positiveVolumeData;b.volumeAll=h[e].wholeVolumeData});g.enabled&&c.drawZones(f,d,c.zoneStarts,g.styles)}};g.prototype.getValues=function(a,b){var e=a.processedXData,
f=a.processedYData,d=this.chart,k=b.ranges,g=[],h=[],l=[],n;if(a.chart)if(n=d.get(b.volumeSeriesID))if((b=y(f[0]))&&4!==f[0].length)c("Type of "+a.name+" series is different than line, OHLC or candlestick.",!0,d);else return(this.priceZones=this.specifyZones(b,e,f,k,n)).forEach(function(a,c){g.push([a.x,a.end]);h.push(g[c][0]);l.push(g[c][1])}),{values:g,xData:h,yData:l};else c("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,d);else c("Base series not found! In case it has been removed, add a new one.",
!0,d)};g.prototype.specifyZones=function(c,f,d,k,g){if(c){var h=d.length;for(var l=d[0][3],n=l,m=1,q;m<h;m++)q=d[m][3],q<l&&(l=q),q>n&&(n=q);h={min:l,max:n}}else h=!1;h=(l=h)?l.min:b(d);q=l?l.max:e(d);l=this.zoneStarts=[];n=[];var r=0;m=1;if(!h||!q)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG&&(this.zoneLinesSVG=this.zoneLinesSVG.destroy())),[];var p=this.rangeStep=a(q-h)/k;for(l.push(h);r<k-1;r++)l.push(a(l[r]+p));l.push(q);for(k=l.length;m<k;m++)n.push({index:m-
1,x:f[0],start:l[m-1],end:l[m]});return this.volumePerZone(c,n,g,f,d)};g.prototype.volumePerZone=function(a,c,b,e,f){var d=this,k=b.processedXData,g=b.processedYData,l=c.length-1,h=f.length;b=g.length;var n,m,q,r,p;B(h-b)&&(e[0]!==k[0]&&g.unshift(0),e[h-1]!==k[b-1]&&g.push(0));d.volumeDataArray=[];c.forEach(function(c){c.wholeVolumeData=0;c.positiveVolumeData=0;for(p=c.negativeVolumeData=0;p<h;p++)q=m=!1,r=a?f[p][3]:f[p],n=p?a?f[p-1][3]:f[p-1]:r,r<=c.start&&0===c.index&&(m=!0),r>=c.end&&c.index===
l&&(q=!0),(r>c.start||m)&&(r<c.end||q)&&(c.wholeVolumeData+=g[p],n>r?c.negativeVolumeData+=g[p]:c.positiveVolumeData+=g[p]);d.volumeDataArray.push(c.wholeVolumeData)});return c};g.prototype.drawZones=function(a,c,b,e){var f=a.renderer,d=this.zoneLinesSVG,k=[],g=a.plotWidth,h=a.plotTop,l;b.forEach(function(b){l=c.toPixels(b)-h;k=k.concat(a.renderer.crispLine([["M",0,l],["L",g,l]],e.lineWidth))});d?d.animate({d:k}):d=this.zoneLinesSVG=f.path(k).attr({"stroke-width":e.lineWidth,stroke:e.color,dashstyle:e.dashStyle,
zIndex:this.group.zIndex+.1}).add(this.group)};g.defaultOptions=v(t.defaultOptions,{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",
padding:0,style:{fontSize:"7px"},verticalAlign:"top"}});return g}(t);k(h.prototype,{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:d,drawGraph:d,getColumnMetrics:u.getColumnMetrics,crispCol:u.crispCol});g.registerSeriesType("vbp",h);"";return h});u(d,"Stock/Indicators/VWAP/VWAPIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var f=function(e,b){f=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return f(e,b)};return function(e,b){function a(){this.constructor=e}f(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.error,p=f.isArray,t=f.merge;f=function(f){function e(){var b=null!==f&&f.apply(this,arguments)||this;b.data=void 0;b.points=void 0;b.options=void 0;return b}g(e,f);e.prototype.getValues=function(b,a){var c=
b.chart,e=b.xData;b=b.yData;var f=a.period,d=!0,g;if(g=c.get(a.volumeSeriesID))return p(b[0])||(d=!1),this.calculateVWAPValues(d,e,b,g,f);m("Series "+a.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,c)};e.prototype.calculateVWAPValues=function(b,a,c,e,f){var d=e.yData,k=e.xData.length,g=a.length;e=[];var h=[],l=[],m=[],p=[],q;k=g<=k?g:k;for(q=g=0;g<k;g++){var t=b?(c[g][1]+c[g][2]+c[g][3])/3:c[g];t*=d[g];t=q?e[g-1]+t:t;var y=q?h[g-1]+d[g]:d[g];e.push(t);h.push(y);p.push([a[g],t/y]);l.push(p[g][0]);
m.push(p[g][1]);q++;q===f&&(q=0)}return{values:p,xData:l,yData:m}};e.defaultOptions=t(h.defaultOptions,{params:{period:30,volumeSeriesID:"volume"}});return e}(h);d.registerSeriesType("vwap",f);"";return f});u(d,"Stock/Indicators/WilliamsR/WilliamsRIndicator.js",[d["Mixins/ReduceArray.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f,g){var h=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=
b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=d.getArrayExtremes,p=f.seriesTypes.sma;d=g.extend;var t=g.isArray,l=g.merge;g=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}h(b,e);b.prototype.getValues=function(a,c){c=c.period;var b=a.xData,e=(a=a.yData)?
a.length:0,f=[],d=[],g=[],h;if(!(b.length<c)&&t(a[0])&&4===a[0].length){for(h=c-1;h<e;h++){var l=a.slice(h-c+1,h+1);var n=m(l,2,1);l=n[0];n=n[1];var p=a[h][3];l=(n-p)/(n-l)*-100;b[h]&&(f.push([b[h],l]),d.push(b[h]),g.push(l))}return{values:f,xData:d,yData:g}}};b.defaultOptions=l(p.defaultOptions,{params:{period:14}});return b}(p);d(g.prototype,{nameBase:"Williams %R"});f.registerSeriesType("williamsr",g);"";return g});u(d,"Stock/Indicators/WMA/WMAIndicator.js",[d["Core/Series/SeriesRegistry.js"],
d["Core/Utilities.js"]],function(d,f){function g(e,b){b*=(b+1)/2;return e.reduce(function(a,c,b){return[null,a[1]+c[1]*(b+1)]})[1]/b}function h(e,b,a,c){a=g(e,e.length);b=b[c-1];e.shift();return[b,a]}var m=this&&this.__extends||function(){var e=function(b,a){e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return e(b,a)};return function(b,a){function c(){this.constructor=b}e(b,a);b.prototype=null===
a?Object.create(a):(c.prototype=a.prototype,new c)}}(),p=d.seriesTypes.sma,t=f.isArray,l=f.merge;f=function(e){function b(){var a=null!==e&&e.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.points=void 0;return a}m(b,e);b.prototype.getValues=function(a,c){var b=c.period,e=a.xData,f=(a=a.yData)?a.length:0,d=1,g=e[0],l=a[0],m=[],n=[],p=[],q=-1;if(!(e.length<b)){t(a[0])&&(q=c.index,l=a[0][q]);for(c=[[g,l]];d!==b;)c.push([e[d],0>q?a[d]:a[d][q]]),d++;for(b=d;b<f;b++)d=h(c,e,a,b),m.push(d),
n.push(d[0]),p.push(d[1]),c.push([e[b],0>q?a[b]:a[b][q]]);d=h(c,e,a,b);m.push(d);n.push(d[0]);p.push(d[1]);return{values:m,xData:n,yData:p}}};b.defaultOptions=l(p.defaultOptions,{params:{index:3,period:9}});return b}(p);d.registerSeriesType("wma",f);"";return f});u(d,"Stock/Indicators/Zigzag/ZigzagIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&
function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=d.seriesTypes.sma,m=f.merge;f=f.extend;var p=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.points=void 0;e.options=void 0;return e}g(f,d);f.prototype.getValues=function(e,b){var a=b.lowIndex,c=b.highIndex,d=b.deviation/
100;b=1+d;var f=1-d;d=e.xData;var g=e.yData;e=g?g.length:0;var h=[],l=[],m=[],p,n,t=!1,q=!1;if(!(!d||1>=d.length||e&&("undefined"===typeof g[0][a]||"undefined"===typeof g[0][c]))){var u=g[0][a];var z=g[0][c];for(p=1;p<e;p++){if(g[p][a]<=z*f){h.push([d[0],z]);var E=[d[p],g[p][a]];t=n=!0}else g[p][c]>=u*b&&(h.push([d[0],u]),E=[d[p],g[p][c]],n=!1,t=!0);if(t){l.push(h[0][0]);m.push(h[0][1]);var w=p++;p=e}}for(p=w;p<e;p++)n?(g[p][a]<=E[1]&&(E=[d[p],g[p][a]]),g[p][c]>=E[1]*b&&(q=c)):(g[p][c]>=E[1]&&(E=
[d[p],g[p][c]]),g[p][a]<=E[1]*f&&(q=a)),!1!==q&&(h.push(E),l.push(E[0]),m.push(E[1]),E=[d[p],g[p][q]],n=!n,q=!1);a=h.length;0!==a&&h[a-1][0]<d[e-1]&&(h.push(E),l.push(E[0]),m.push(E[1]));return{values:h,xData:l,yData:m}}};f.defaultOptions=m(h.defaultOptions,{params:{lowIndex:2,highIndex:1,deviation:1}});return f}(h);f(p.prototype,{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag"});d.registerSeriesType("zigzag",p);"";return p});u(d,"Stock/Indicators/LinearRegression/LinearRegression.js",
[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.isArray,p=f.extend,t=f.merge;f=function(d){function e(){var b=
null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.getRegressionLineParameters=function(b,a){var c=this.options.params.index,e=function(a,b){return m(a)?a[b]:a},d=b.reduce(function(a,b){return b+a},0),f=a.reduce(function(a,b){return e(b,c)+a},0);d/=b.length;f/=a.length;var g=0,h=0,l;for(l=0;l<b.length;l++){var p=b[l]-d;var n=e(a[l],c)-f;g+=p*n;h+=Math.pow(p,2)}b=h?g/h:0;return{slope:b,intercept:f-b*d}};e.prototype.getEndPointY=function(b,
a){return b.slope*a+b.intercept};e.prototype.transformXData=function(b,a){var c=b[0];return b.map(function(b){return(b-c)/a})};e.prototype.findClosestDistance=function(b){var a,c;for(c=1;c<b.length-1;c++){var e=b[c]-b[c-1];0<e&&("undefined"===typeof a||e<a)&&(a=e)}return a};e.prototype.getValues=function(b,a){var c=b.xData;b=b.yData;a=a.period;var e,d={xData:[],yData:[],values:[]},f=this.options.params.xAxisUnit||this.findClosestDistance(c);for(e=a-1;e<=c.length-1;e++){var g=e-a+1;var h=e+1;var l=
c[e];var m=c.slice(g,h);g=b.slice(g,h);h=this.transformXData(m,f);m=this.getRegressionLineParameters(h,g);g=this.getEndPointY(m,h[h.length-1]);d.values.push({regressionLineParameters:m,x:l,y:g});d.xData.push(l);d.yData.push(g)}return d};e.defaultOptions=t(h.defaultOptions,{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}});return e}(h);p(f.prototype,{nameBase:"Linear Regression Indicator"});d.registerSeriesType("linearRegression",f);"";return f});u(d,"Stock/Indicators/LinearRegressionSlopes/LinearRegressionSlopes.js",
[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=d.seriesTypes.linearRegression,m=f.extend,p=f.merge;f=function(d){function f(){var e=
null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.options=void 0;e.points=void 0;return e}g(f,d);f.prototype.getEndPointY=function(e){return e.slope};f.defaultOptions=p(h.defaultOptions);return f}(h);m(f.prototype,{nameBase:"Linear Regression Slope Indicator"});d.registerSeriesType("linearRegressionSlope",f);"";return f});u(d,"Stock/Indicators/LinearRegressionIntercept/LinearRegressionIntercept.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||
function(){var d=function(f,e){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return d(f,e)};return function(f,e){function b(){this.constructor=f}d(f,e);f.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),h=d.seriesTypes.linearRegression,m=f.extend,p=f.merge;f=function(d){function f(){var e=null!==d&&d.apply(this,arguments)||this;e.data=void 0;e.options=void 0;e.points=void 0;
return e}g(f,d);f.prototype.getEndPointY=function(d){return d.intercept};f.defaultOptions=p(h.defaultOptions);return f}(h);m(f.prototype,{nameBase:"Linear Regression Intercept Indicator"});d.registerSeriesType("linearRegressionIntercept",f);"";return f});u(d,"Stock/Indicators/LinearRegressionAngle/LinearRegressionAngle.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes,m=h.sma,p=f.extend,t=f.merge;f=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.slopeToAngle=function(b){return 180/Math.PI*Math.atan(b)};e.prototype.getEndPointY=
function(b){return this.slopeToAngle(b.slope)};e.defaultOptions=t(m.defaultOptions,{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}});return e}(h.linearRegression);p(f.prototype,{nameBase:"Linear Regression Angle Indicator"});d.registerSeriesType("linearRegressionAngle",f);"";return f});u(d,"Stock/Indicators/ABands/ABandsIndicator.js",[d["Mixins/MultipleLines.js"],d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,
f,g){var h=this&&this.__extends||function(){var d=function(b,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(b,a)};return function(b,a){function c(){this.constructor=b}d(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),m=f.seriesTypes.sma,p=g.correctFloat,t=g.extend,l=g.merge;g=function(d){function b(){var a=null!==d&&d.apply(this,arguments)||this;a.data=
void 0;a.options=void 0;a.points=void 0;return a}h(b,d);b.prototype.getValues=function(a,b){var c=b.period,e=b.factor;b=b.index;var f=a.xData,g=(a=a.yData)?a.length:0,h=[],l=[],m=[],n=[],t=[],q;if(!(g<c)){for(q=0;q<=g;q++){if(q<g){var u=a[q][2];var z=a[q][1];var E=e;u=p(z-u)/(p(z+u)/2)*1E3*E;h.push(a[q][1]*p(1+2*u));l.push(a[q][2]*p(1-2*u))}if(q>=c){u=f.slice(q-c,q);var w=a.slice(q-c,q);E=d.prototype.getValues.call(this,{xData:u,yData:h.slice(q-c,q)},{period:c});z=d.prototype.getValues.call(this,
{xData:u,yData:l.slice(q-c,q)},{period:c});w=d.prototype.getValues.call(this,{xData:u,yData:w},{period:c,index:b});u=w.xData[0];E=E.yData[0];z=z.yData[0];w=w.yData[0];m.push([u,E,w,z]);n.push(u);t.push([E,w,z])}}return{values:m,xData:n,yData:t}}};b.defaultOptions=l(m.defaultOptions,{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}});return b}(m);t(g.prototype,{drawGraph:d.drawGraph,getTranslatedLinesNames:d.getTranslatedLinesNames,
linesApiNames:["topLine","bottomLine"],nameBase:"Acceleration Bands",nameComponents:["period","factor"],pointArrayMap:["top","middle","bottom"],pointValKey:"middle",toYData:d.toYData,translate:d.translate});f.registerSeriesType("abands",g);"";return g});u(d,"Stock/Indicators/TrendLine/TrendLineIndicator.js",[d["Core/Series/SeriesRegistry.js"],d["Core/Utilities.js"]],function(d,f){var g=this&&this.__extends||function(){var d=function(e,b){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,
b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(e,b)};return function(e,b){function a(){this.constructor=e}d(e,b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),h=d.seriesTypes.sma,m=f.extend,p=f.merge,t=f.isArray;f=function(d){function e(){var b=null!==d&&d.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}g(e,d);e.prototype.getValues=function(b,a){var c=b.xData,d=b.yData;b=[];var e=[],f=[],g=
0,h=0,l=0,m=0,n=c.length,p=a.index;for(a=0;a<n;a++){var q=c[a];var u=t(d[a])?d[a][p]:d[a];g+=q;h+=u;l+=q*u;m+=q*q}d=(n*l-g*h)/(n*m-g*g);isNaN(d)&&(d=0);g=(h-d*g)/n;for(a=0;a<n;a++)q=c[a],u=d*q+g,b[a]=[q,u],e[a]=q,f[a]=u;return{xData:e,yData:f,values:b}};e.defaultOptions=p(h.defaultOptions,{params:{index:3}});return e}(h);m(f.prototype,{nameBase:"Trendline",nameComponents:!1});d.registerSeriesType("trendline",f);"";return f});u(d,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map