!/**
 * Highstock JS v12.0.1 (2024-11-28)
 * @module highcharts/indicators/psar
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Parabolic SAR Indicator for Highcharts Stock
 *
 * (c) 2010-2024 Grzegorz Blachliński
 *
 * License: www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("highcharts"),require("highcharts").SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/psar",[["highcharts/highcharts"],["highcharts/highcharts","SeriesRegistry"]],t):"object"==typeof exports?exports["highcharts/psar"]=t(require("highcharts"),require("highcharts").SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}(this,(e,t)=>(()=>{"use strict";var r={512:e=>{e.exports=t},944:t=>{t.exports=e}},a={};function i(e){var t=a[e];if(void 0!==t)return t.exports;var s=a[e]={exports:{}};return r[e](s,s.exports,i),s.exports}i.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return i.d(t,{a:t}),t},i.d=(e,t)=>{for(var r in t)i.o(t,r)&&!i.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},i.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t);var s={};i.d(s,{default:()=>f});var n=i(944),o=/*#__PURE__*/i.n(n),h=i(512),c=/*#__PURE__*/i.n(h);let{sma:l}=c().seriesTypes,{merge:u}=o();function p(e,t){return parseFloat(e.toFixed(t))}class d extends l{constructor(){super(...arguments),this.nameComponents=void 0}getValues(e,t){let r=e.xData,a=e.yData,i=t.maxAccelerationFactor,s=t.increment,n=t.initialAccelerationFactor,o=t.decimals,h=t.index,c=[],l=[],u=[],d=t.initialAccelerationFactor,f,g=a[0][1],m,x,y,v=1,F,b,M,A,j=a[0][2],O,S,q,D;if(!(h>=a.length)){for(D=0;D<h;D++)g=Math.max(a[D][1],g),j=Math.min(a[D][2],p(j,o));for(f=a[D][1]>j?1:-1,m=g-j,x=(d=t.initialAccelerationFactor)*m,c.push([r[h],j]),l.push(r[h]),u.push(p(j,o)),D=h+1;D<a.length;D++)if(F=a[D-1][2],b=a[D-2][2],M=a[D-1][1],A=a[D-2][1],S=a[D][1],q=a[D][2],null!==b&&null!==A&&null!==F&&null!==M&&null!==S&&null!==q){var R,H,P,T,W,_,k,w,C,V,z,B,E;W=f,_=v,k=j,w=x,C=g,j=W===_?1===W?k+w<Math.min(b,F)?k+w:Math.min(b,F):k+w>Math.max(A,M)?k+w:Math.max(A,M):C,R=f,H=g,O=1===R?S>H?S:H:q<H?q:H,P=v,T=j,V=y=1===P&&q>T||-1===P&&S>T?1:-1,z=f,B=g,E=d,x=(d=V===z?1===V&&O>B||-1===V&&O<B?E===i?i:p(E+s,2):E:n)*(m=O-j),c.push([r[D],p(j,o)]),l.push(r[D]),u.push(p(j,o)),v=f,f=y,g=O}return{values:c,xData:l,yData:u}}}}d.defaultOptions=u(l.defaultOptions,{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{period:void 0,initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}}),c().registerSeriesType("psar",d);let f=o();return s.default})());