!/**
 * Highstock JS v12.6.0 (2026-04-13)
 * @module highcharts/indicators/trendline
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Sebastian Bochan
 *
 * A commercial license may be required depending on use.
 * See www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/trendline",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/trendline"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,(e,t)=>(()=>{"use strict";var r={512:e=>{e.exports=t},944:t=>{t.exports=e}},o={};function n(e){var t=o[e];if(void 0!==t)return t.exports;var i=o[e]={exports:{}};return r[e](i,i.exports,n),i.exports}n.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return n.d(t,{a:t}),t},n.d=(e,t)=>{for(var r in t)n.o(t,r)&&!n.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},n.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t);var i={};n.d(i,{default:()=>x});var s=n(944),a=n.n(s),l=n(512),c=n.n(l);let{doc:p,win:u}=a();function h(e){return d(e)&&"number"==typeof e.nodeType}function f(e){let t=Object.prototype.toString.call(e);return"[object Array]"===t||"[object Array Iterator]"===t}function d(e,t){return!!e&&"object"==typeof e&&(!t||!f(e))}Array.prototype.find;let{sma:y}=c().seriesTypes;class g extends y{constructor(){super(...arguments),this.updateAllPoints=!0}getValues(e,t){let r=e.xData,o=e.yData,n=[],i=[],s=[],a=[],l=t.index,c=0,p=0,u=0,h=0,d=0;for(let e=0;e<r.length;e++)(0===e||r[e]!==r[e-1])&&d++,n.push(d);for(let e=0;e<n.length;e++)u+=n[e],h+=f(o[e])?o[e][l]:o[e];let y=u/n.length,g=h/o.length;for(let e=0;e<n.length;e++){let t=f(o[e])?o[e][l]:o[e];c+=(n[e]-y)*(t-g),p+=Math.pow(n[e]-y,2)}for(let e=0;e<n.length;e++){if(r[e]===s[s.length-1])continue;let t=r[e],o=g+c/p*(n[e]-y);i.push([t,o]),s.push(t),a.push(o)}return{xData:s,yData:a,values:i}}}g.defaultOptions=function(e,...t){let r,o=[e,...t],n={},i=function(e,t){return"object"!=typeof e&&(e={}),function(e,t,r){for(let r in e)Object.hasOwnProperty.call(e,r)&&t.call((0,e[r]),e[r],r,e)}(t,function(r,o){if("__proto__"!==o&&"constructor"!==o){let n;!d(r,!0)||(n=r?.constructor,d(r,!0)&&!h(r)&&n?.name&&"Object"!==n.name)||h(r)?e[o]=t[o]:e[o]=i(e[o]||{},r)}}),e};!0===e&&(n=o[1],o=Array.prototype.slice.call(o,2));let s=o.length;for(r=0;r<s;r++)n=i(n,o[r]);return n}(y.defaultOptions,{params:{period:void 0,index:3}}),function(e,t){let r;for(r in e||(e={}),t)e[r]=t[r]}(g.prototype,{nameBase:"Trendline",nameComponents:void 0}),c().registerSeriesType("trendline",g);let x=a();return i.default})());