!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/zigzag
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Kacper Madej
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/zigzag",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/zigzag"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,(e,t)=>(()=>{"use strict";var r={512(e){e.exports=t},944(t){t.exports=e}};let i={};function s(e){let t=i[e];if(void 0!==t)return t.exports;let o=i[e]={exports:{}};return r[e](o,o.exports,s),o.exports}s.n=e=>{let t=e&&e.__esModule?()=>e.default:()=>e;return s.d(t,{a:t}),t},s.d=(e,t)=>{if(Array.isArray(t))for(var r=0;r<t.length;){var i=t[r++],o=t[r++];s.o(e,i)?0===o&&r++:0===o?Object.defineProperty(e,i,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,i,{enumerable:!0,get:o})}else for(var i in t)s.o(t,i)&&!s.o(e,i)&&Object.defineProperty(e,i,{enumerable:!0,get:t[i]})},s.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t);let o={};s.d(o,{default:()=>g});var a=s(944),n=s.n(a),h=s(512),p=s.n(h);let{sma:d}=p().seriesTypes;class u extends d{getValues(e,t){let r=t.lowIndex,i=t.highIndex,s=t.deviation/100,o={low:1+s,high:1-s},a=e.xData,n=e.yData,h=n?n.length:0,p=[],d=[],u=[],g,l,f,c,y=!1,x=!1;if(!a||a.length<=1||h&&(void 0===n[0][r]||void 0===n[0][i]))return;let v=n[0][r],m=n[0][i];for(g=1;g<h;g++)n[g][r]<=m*o.high?(p.push([a[0],m]),f=[a[g],n[g][r]],c=!0,y=!0):n[g][i]>=v*o.low&&(p.push([a[0],v]),f=[a[g],n[g][i]],c=!1,y=!0),y&&(d.push(p[0][0]),u.push(p[0][1]),l=g++,g=h);for(g=l;g<h;g++)c?(n[g][r]<=f[1]&&(f=[a[g],n[g][r]]),n[g][i]>=f[1]*o.low&&(x=i)):(n[g][i]>=f[1]&&(f=[a[g],n[g][i]]),n[g][r]<=f[1]*o.high&&(x=r)),!1!==x&&(p.push(f),d.push(f[0]),u.push(f[1]),f=[a[g],n[g][x]],c=!c,x=!1);let b=p.length;return 0!==b&&p[b-1][0]<a[h-1]&&(p.push(f),d.push(f[0]),u.push(f[1])),{values:p,xData:d,yData:u}}}u.defaultOptions=(0,a.merge)(d.defaultOptions,{params:{index:void 0,period:void 0,lowIndex:2,highIndex:1,deviation:1}}),(0,a.extend)(u.prototype,{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag"}),p().registerSeriesType("zigzag",u);let g=n();return o.default})());