/*
 Highcharts JS v11.1.0 (2023-10-19)

 Bullet graph series type for Highcharts

 (c) 2010-2021 Kacper Madej

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/bullet",["highcharts"],function(f){b(f);b.Highcharts=f;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function f(b,g,k,c){b.hasOwnProperty(g)||(b[g]=c.apply(null,k),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:g,module:b[g]}})))}b=b?b._modules:
{};f(b,"Series/Bullet/BulletPoint.js",[b["Series/Column/ColumnSeries.js"]],function(b){var g=this&&this.__extends||function(){function b(c,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c])};return b(c,a)}return function(c,a){function k(){this.constructor=c}if("function"!==typeof a&&null!==a)throw new TypeError("Class extends value "+String(a)+" is not a constructor or null");
b(c,a);c.prototype=null===a?Object.create(a):(k.prototype=a.prototype,new k)}}();return function(b){function c(){var a=null!==b&&b.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}g(c,b);c.prototype.destroy=function(){this.targetGraphic&&(this.targetGraphic=this.targetGraphic.destroy());b.prototype.destroy.apply(this,arguments)};return c}(b.prototype.pointClass)});f(b,"Series/Bullet/BulletSeriesDefaults.js",[],function(){"";return{targetOptions:{width:"140%",height:3,borderWidth:0,
borderRadius:0},tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b>. Target: <b>{point.target}</b><br/>'}}});f(b,"Series/Bullet/BulletSeries.js",[b["Series/Bullet/BulletPoint.js"],b["Series/Bullet/BulletSeriesDefaults.js"],b["Series/Column/ColumnSeries.js"],b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,g,f,c,a){var k=this&&this.__extends||function(){function b(a,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,
a){b.__proto__=a}||function(b,a){for(var e in a)Object.prototype.hasOwnProperty.call(a,e)&&(b[e]=a[e])};return b(a,e)}return function(a,e){function c(){this.constructor=a}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");b(a,e);a.prototype=null===e?Object.create(e):(c.prototype=e.prototype,new c)}}(),u=a.extend,m=a.isNumber,v=a.merge,q=a.pick,x=a.relativeLength;a=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||
this;a.data=void 0;a.options=void 0;a.points=void 0;a.targetData=void 0;return a}k(a,b);a.prototype.drawPoints=function(){var a=this.chart,c=this.options,f=c.animationLimit||250;b.prototype.drawPoints.apply(this,arguments);for(var g=0,k=this.points;g<k.length;g++){var d=k[g],w=d.options,r=d.target,t=d.y,h=d.targetGraphic;if(m(r)&&null!==r){var l=v(c.targetOptions,w.targetOptions);var u=l.height;var n=d.shapeArgs;d.dlBox&&n&&!m(n.width)&&(n=d.dlBox);var p=x(l.width,n.width);var y=this.yAxis.translate(r,
!1,!0,!1,!0)-l.height/2-.5;p=this.crispCol.apply({chart:a,borderWidth:l.borderWidth,options:{crisp:c.crisp}},[n.x+n.width/2-p/2,y,p,u]);h?(h[a.pointCount<f?"animate":"attr"](p),m(t)&&null!==t?h.element.point=d:h.element.point=void 0):d.targetGraphic=h=a.renderer.rect().attr(p).add(this.group);a.styledMode||h.attr({fill:q(l.color,w.color,this.zones.length&&(d.getZone.call({series:this,x:d.x,y:r,options:{}}).color||this.color)||void 0,d.color,this.color),stroke:q(l.borderColor,d.borderColor,this.options.borderColor),
"stroke-width":l.borderWidth,r:l.borderRadius});m(t)&&null!==t&&(h.element.point=d);h.addClass(d.getClassName()+" highcharts-bullet-target",!0)}else h&&(d.targetGraphic=h.destroy())}};a.prototype.getExtremes=function(a){a=b.prototype.getExtremes.call(this,a);var c=this.targetData;c&&c.length&&(c=b.prototype.getExtremes.call(this,c),m(c.dataMin)&&(a.dataMin=Math.min(q(a.dataMin,Infinity),c.dataMin)),m(c.dataMax)&&(a.dataMax=Math.max(q(a.dataMax,-Infinity),c.dataMax)));return a};a.defaultOptions=v(f.defaultOptions,
g);return a}(f);u(a.prototype,{parallelArrays:["x","y","target"],pointArrayMap:["y","target"]});a.prototype.pointClass=b;c.registerSeriesType("bullet",a);return a});f(b,"masters/modules/bullet.src.js",[],function(){})});
//# sourceMappingURL=bullet.js.map