/*
 Highcharts JS v11.1.0 (2023-09-22)

 ColorAxis module

 (c) 2012-2021 Pawel Potaczek

 License: www.highcharts.com/license
*/
'use strict';(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/color-axis",["highcharts"],function(m){c(m);c.Highcharts=m;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function m(c,h,x,r){c.hasOwnProperty(h)||(c[h]=r.apply(null,x),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:h,module:c[h]}})))}c=c?c._modules:
{};m(c,"Core/Axis/Color/ColorAxisComposition.js",[c["Core/Color/Color.js"],c["Core/Utilities.js"]],function(c,h){var p=c.parse,r=h.addEvent,m=h.extend,z=h.merge,v=h.pick,E=h.splat,t;(function(c){function t(){var a=this,b=this.options;this.colorAxis=[];b.colorAxis&&(b.colorAxis=E(b.colorAxis),b.colorAxis.forEach(function(b){new l(a,b)}))}function x(a){function b(b){b=a.allItems.indexOf(b);-1!==b&&(d.destroyItem(a.allItems[b]),a.allItems.splice(b,1))}var d=this,f=[],k,l;(this.chart.colorAxis||[]).forEach(function(a){(k=
a.options)&&k.showInLegend&&(k.dataClasses&&k.visible?f=f.concat(a.getDataClassLegendSymbols()):k.visible&&f.push(a),a.series.forEach(function(a){if(!a.options.showInLegend||k.dataClasses)"point"===a.options.legendType?a.points.forEach(function(a){b(a)}):b(a)}))});for(l=f.length;l--;)a.allItems.unshift(f[l])}function A(a){a.visible&&a.item.legendColor&&a.item.legendItem.symbol.attr({fill:a.item.legendColor})}function B(a){var b;null===(b=this.chart.colorAxis)||void 0===b?void 0:b.forEach(function(b){b.update({},
a.redraw)})}function y(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function q(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]}function C(a){var b=this,d=a?"show":"hide";b.visible=b.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(b[a])b[a][d]()});this.series.buildKDTree()}function e(){var a=this,b=this.options.nullColor,d=this.colorAxis,f=this.colorKey;(this.data.length?this.data:
this.points).forEach(function(l){var e=l.getNestedProperty(f);(e=l.options.color||(l.isNull||null===l.value?b:d&&"undefined"!==typeof e?d.toColor(e,l):l.color||a.color))&&l.color!==e&&(l.color=e,"point"===a.options.legendType&&l.legendItem&&l.legendItem.label&&a.chart.legend.colorizeItem(l,l.visible))})}function b(a){var b=a.prototype.createAxis;a.prototype.createAxis=function(a,d){if("colorAxis"!==a)return b.apply(this,arguments);var f=new l(this,z(d.axis,{index:this[a].length,isX:!1}));this.isDirtyLegend=
!0;this.axes.forEach(function(a){a.series=[]});this.series.forEach(function(a){a.bindAxes();a.isDirtyData=!0});v(d.redraw,!0)&&this.redraw(d.animation);return f}}function a(){this.elem.attr("fill",p(this.start).tweenTo(p(this.end),this.pos),void 0,!0)}function f(){this.elem.attr("stroke",p(this.start).tweenTo(p(this.end),this.pos),void 0,!0)}var d=[],l;c.compose=function(k,c,g,u,w){l||(l=k);h.pushUnique(d,c)&&(k=c.prototype,k.collectionsWithUpdate.push("colorAxis"),k.collectionsWithInit.colorAxis=
[k.addColorAxis],r(c,"afterGetAxes",t),b(c));h.pushUnique(d,g)&&(c=g.prototype,c.fillSetter=a,c.strokeSetter=f);h.pushUnique(d,u)&&(r(u,"afterGetAllItems",x),r(u,"afterColorizeItem",A),r(u,"afterUpdate",B));h.pushUnique(d,w)&&(m(w.prototype,{optionalAxis:"colorAxis",translateColors:e}),m(w.prototype.pointClass.prototype,{setVisible:C}),r(w,"afterTranslate",y,{order:1}),r(w,"bindAxes",q))};c.pointSetVisible=C})(t||(t={}));return t});m(c,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,
minPadding:0,maxPadding:0,gridLineColor:"#ffffff",gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{distance:8,overflow:"justify",rotation:0},minColor:"#e6e9ff",maxColor:"#0022ff",tickLength:5,showInLegend:!0}});m(c,"Core/Axis/Color/ColorAxis.js",[c["Core/Axis/Axis.js"],c["Core/Color/Color.js"],c["Core/Axis/Color/ColorAxisComposition.js"],c["Core/Axis/Color/ColorAxisDefaults.js"],c["Core/Legend/LegendSymbol.js"],
c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,h,m,r,D,z,v){var p=this&&this.__extends||function(){function c(e,b){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])};return c(e,b)}return function(e,b){function a(){this.constructor=e}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");c(e,
b);e.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),t=h.parse,x=z.series,F=v.extend,G=v.fireEvent,A=v.isArray,B=v.isNumber,y=v.merge,q=v.pick;h=function(c){function e(b,a){var f=c.call(this,b,a)||this;f.beforePadding=!1;f.chart=void 0;f.coll="colorAxis";f.dataClasses=void 0;f.options=void 0;f.stops=void 0;f.visible=!0;f.init(b,a);return f}p(e,c);e.compose=function(b,a,f,d){m.compose(e,b,a,f,d)};e.prototype.init=function(b,a){var f=b.options.legend||{},d=a.layout?"vertical"!==
a.layout:"vertical"!==f.layout,l=a.visible;f=y(e.defaultColorAxisOptions,a,{showEmpty:!1,title:null,visible:f.enabled&&!1!==l});this.side=a.side||d?2:1;this.reversed=a.reversed||!d;this.opposite=!d;c.prototype.init.call(this,b,f,"colorAxis");this.userOptions=a;A(b.userOptions.colorAxis)&&(b.userOptions.colorAxis[this.index]=a);a.dataClasses&&this.initDataClasses(a);this.initStops();this.horiz=d;this.zoomEnabled=!1};e.prototype.initDataClasses=function(b){var a=this.chart,f=this.legendItem=this.legendItem||
{},d=b.dataClasses.length,c=this.options,e,n=0,g=a.options.chart.colorCount;this.dataClasses=e=[];f.labels=[];(b.dataClasses||[]).forEach(function(b,f){b=y(b);e.push(b);if(a.styledMode||!b.color)"category"===c.dataClassColor?(a.styledMode||(f=a.options.colors,g=f.length,b.color=f[n]),b.colorIndex=n,n++,n===g&&(n=0)):b.color=t(c.minColor).tweenTo(t(c.maxColor),2>d?.5:f/(d-1))})};e.prototype.hasData=function(){return!!(this.tickPositions||[]).length};e.prototype.setTickPositions=function(){if(!this.dataClasses)return c.prototype.setTickPositions.call(this)};
e.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=t(b[1])})};e.prototype.setOptions=function(b){c.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker};e.prototype.setAxisSize=function(){var b=this.legendItem&&this.legendItem.symbol,a=this.chart,f=a.options.legend||{},d,c;b?(this.left=f=b.attr("x"),this.top=d=b.attr("y"),this.width=c=b.attr("width"),this.height=b=b.attr("height"),
this.right=a.chartWidth-f-c,this.bottom=a.chartHeight-d-b,this.len=this.horiz?c:b,this.pos=this.horiz?f:d):this.len=(this.horiz?f.symbolWidth:f.symbolHeight)||e.defaultLegendLength};e.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)};e.prototype.toColor=function(b,a){var f=this.dataClasses,d=this.stops,c;if(f)for(c=f.length;c--;){var e=f[c];var n=e.from;d=e.to;if(("undefined"===typeof n||b>=n)&&("undefined"===typeof d||
b<=d)){var g=e.color;a&&(a.dataClass=c,a.colorIndex=e.colorIndex);break}}else{b=this.normalizedValue(b);for(c=d.length;c--&&!(b>d[c][0]););n=d[c]||d[c+1];d=d[c+1]||n;b=1-(d[0]-b)/(d[0]-n[0]||1);g=n.color.tweenTo(d.color,b)}return g};e.prototype.getOffset=function(){var b=this.legendItem&&this.legendItem.group,a=this.chart.axisOffset[this.side];if(b){this.axisParent=b;c.prototype.getOffset.call(this);var f=this.chart.legend;f.allItems.forEach(function(a){a instanceof e&&a.drawLegendSymbol(f,a)});f.render();
this.chart.getMargins(!0);this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width);this.chart.axisOffset[this.side]=a}};e.prototype.setLegendColor=function(){var b=this.reversed,a=b?1:0;b=b?0:1;a=this.horiz?[a,0,b,0]:[0,b,0,a];this.legendColor={linearGradient:{x1:a[0],y1:a[1],x2:a[2],y2:a[3]},stops:this.stops}};e.prototype.drawLegendSymbol=function(b,a){var f;a=a.legendItem||{};var d=b.padding,c=b.options,k=this.options.labels,n=q(c.itemDistance,10),g=this.horiz,h=q(c.symbolWidth,g?
e.defaultLegendLength:12),w=q(c.symbolHeight,g?12:e.defaultLegendLength),m=q(c.labelPadding,g?16:30);this.setLegendColor();a.symbol||(a.symbol=this.chart.renderer.symbol("roundedRect",0,b.baseline-11,h,w,{r:null!==(f=c.symbolRadius)&&void 0!==f?f:3}).attr({zIndex:1}).add(a.group));a.labelWidth=h+d+(g?n:q(k.x,k.distance)+this.maxLabelLength);a.labelHeight=w+d+(g?m:0)};e.prototype.setState=function(b){this.series.forEach(function(a){a.setState(b)})};e.prototype.setVisible=function(){};e.prototype.getSeriesExtremes=
function(){var b=this.series,a=b.length,c;this.dataMin=Infinity;for(this.dataMax=-Infinity;a--;){var d=b[a];var e=d.colorKey=q(d.options.colorKey,d.colorKey,d.pointValKey,d.zoneAxis,"y");var k=d.pointArrayMap;var h=d[e+"Min"]&&d[e+"Max"];if(d[e+"Data"])var g=d[e+"Data"];else if(k){g=[];k=k.indexOf(e);var u=d.yData;if(0<=k&&u)for(c=0;c<u.length;c++)g.push(q(u[c][k],u[c]))}else g=d.yData;h?(d.minColorValue=d[e+"Min"],d.maxColorValue=d[e+"Max"]):(g=x.prototype.getExtremes.call(d,g),d.minColorValue=g.dataMin,
d.maxColorValue=g.dataMax);"undefined"!==typeof d.minColorValue&&(this.dataMin=Math.min(this.dataMin,d.minColorValue),this.dataMax=Math.max(this.dataMax,d.maxColorValue));h||x.prototype.applyExtremes.call(d)}};e.prototype.drawCrosshair=function(b,a){var f=this.legendItem||{},d=a&&a.plotX,e=a&&a.plotY,k=this.pos,h=this.len;if(a){var g=this.toPixels(a.getNestedProperty(a.series.colorKey));g<k?g=k-2:g>k+h&&(g=k+h+2);a.plotX=g;a.plotY=this.len-g;c.prototype.drawCrosshair.call(this,b,a);a.plotX=d;a.plotY=
e;this.cross&&!this.cross.addedToColorAxis&&f.group&&(this.cross.addClass("highcharts-coloraxis-marker").add(f.group),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};e.prototype.getPlotLinePath=function(b){var a=this.left,f=b.translatedValue,d=this.top;return B(f)?this.horiz?[["M",f-4,d-6],["L",f+4,d-6],["L",f,d],["Z"]]:[["M",a,f],["L",a-6,f+6],["L",a-6,f-6],["Z"]]:c.prototype.getPlotLinePath.call(this,b)};e.prototype.update=
function(b,a){var f=this.chart.legend;this.series.forEach(function(a){a.isDirtyData=!0});(b.dataClasses&&f.allItems||this.dataClasses)&&this.destroyItems();c.prototype.update.call(this,b,a);this.legendItem&&this.legendItem.label&&(this.setLegendColor(),f.colorizeItem(this,!0))};e.prototype.destroyItems=function(){var b=this.chart,a=this.legendItem||{};if(a.label)b.legend.destroyItem(this);else if(a.labels){var c=0;for(a=a.labels;c<a.length;c++)b.legend.destroyItem(a[c])}b.isDirtyLegend=!0};e.prototype.destroy=
function(){this.chart.isDirtyLegend=!0;this.destroyItems();c.prototype.destroy.apply(this,[].slice.call(arguments))};e.prototype.remove=function(b){this.destroyItems();c.prototype.remove.call(this,b)};e.prototype.getDataClassLegendSymbols=function(){function b(b){return a.series.reduce(function(a,c){a.push.apply(a,c.points.filter(function(a){return a.dataClass===b}));return a},[])}var a=this,c=a.chart,d=a.legendItem&&a.legendItem.labels||[],e=c.options.legend,h=q(e.valueDecimals,-1),n=q(e.valueSuffix,
""),g;d.length||a.dataClasses.forEach(function(e,f){var k=e.from,l=e.to,m=c.numberFormatter,p=!0;g="";"undefined"===typeof k?g="< ":"undefined"===typeof l&&(g="> ");"undefined"!==typeof k&&(g+=m(k,h)+n);"undefined"!==typeof k&&"undefined"!==typeof l&&(g+=" - ");"undefined"!==typeof l&&(g+=m(l,h)+n);d.push(F({chart:c,name:g,options:{},drawLegendSymbol:D.rectangle,visible:!0,isDataClass:!0,setState:function(a){for(var c=0,d=b(f);c<d.length;c++)d[c].setState(a)},setVisible:function(){this.visible=p=
a.visible=!p;for(var d=[],e=0,g=b(f);e<g.length;e++){var h=g[e];h.setVisible(p);-1===d.indexOf(h.series)&&d.push(h.series)}c.legend.colorizeItem(this,p);d.forEach(function(a){G(a,"afterDataClassLegendClick")})}},e))});return d};e.defaultColorAxisOptions=r;e.defaultLegendLength=200;e.keepProps=["legendItem"];return e}(c);Array.prototype.push.apply(c.keepProps,h.keepProps);"";return h});m(c,"masters/modules/coloraxis.src.js",[c["Core/Globals.js"],c["Core/Axis/Color/ColorAxis.js"]],function(c,h){c.ColorAxis=
h;h.compose(c.Chart,c.Fx,c.Legend,c.Series)})});
//# sourceMappingURL=coloraxis.js.map