/*
 Highcharts JS v11.0.0 (2023-04-26)

 (c) 2009-2022

 License: www.highcharts.com/license
*/
'use strict';(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/flowmap",["highcharts"],function(t){e(t);e.Highcharts=t;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function t(g,c,l,a){g.hasOwnProperty(c)||(g[c]=a.apply(null,l),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:c,module:g[c]}})))}e=e?e._modules:
{};t(e,"Series/FlowMap/FlowMapPoint.js",[e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(g,c){var l=this&&this.__extends||function(){var d=function(a,f){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,a){d.__proto__=a}||function(d,a){for(var b in a)Object.prototype.hasOwnProperty.call(a,b)&&(d[b]=a[b])};return d(a,f)};return function(a,f){function h(){this.constructor=a}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+
" is not a constructor or null");d(a,f);a.prototype=null===f?Object.create(f):(h.prototype=f.prototype,new h)}}(),a=c.pick,f=c.isString,d=c.isNumber;return function(h){function c(){var a=null!==h&&h.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}l(c,h);c.prototype.isValid=function(){var h=!(!this.options.to||!this.options.from);[this.options.to,this.options.from].forEach(function(c){h=!!(h&&c&&(f(c)||d(a(c[0],c.lat))&&d(a(c[1],c.lon))))});return h};return c}(g.seriesTypes.mapline.prototype.pointClass)});
t(e,"Series/ColorMapComposition.js",[e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(g,c){var l=g.seriesTypes.column.prototype,a=c.addEvent,f=c.defined,d;(function(d){function h(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})}var g=[];d.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};d.seriesMembers=
{colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(a){var d={};!f(a.color)||a.state&&"normal"!==a.state||(d[this.colorProp||"fill"]=a.color);return d},pointAttribs:l.pointAttribs};d.compose=function(d){var f=d.prototype.pointClass;c.pushUnique(g,f)&&a(f,"afterSetState",h);return d}})(d||(d={}));return d});t(e,"Maps/MapSymbols.js",[e["Core/Renderer/SVG/SVGRenderer.js"]],
function(g){var c=g.prototype.symbols;c.bottombutton=function(l,a,f,d,h){if(h){var g=(null===h||void 0===h?void 0:h.r)||0;h.brBoxY=a-g;h.brBoxHeight=d+g}return c.roundedRect(l,a,f,d,h)};c.topbutton=function(l,a,f,d,h){h&&(h.brBoxHeight=d+((null===h||void 0===h?void 0:h.r)||0));return c.roundedRect(l,a,f,d,h)};return c});t(e,"Core/Chart/MapChart.js",[e["Core/Chart/Chart.js"],e["Core/Defaults.js"],e["Core/Renderer/SVG/SVGRenderer.js"],e["Core/Utilities.js"]],function(g,c,l,a){var f=this&&this.__extends||
function(){var a=function(d,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,k){b.__proto__=k}||function(b,k){for(var a in k)Object.prototype.hasOwnProperty.call(k,a)&&(b[a]=k[a])};return a(d,f)};return function(d,f){function b(){this.constructor=d}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+" is not a constructor or null");a(d,f);d.prototype=null===f?Object.create(f):(b.prototype=f.prototype,new b)}}(),d=c.getOptions,h=a.merge,e=a.pick;
g=function(a){function c(){return null!==a&&a.apply(this,arguments)||this}f(c,a);c.prototype.init=function(f,b){var k=d().credits;f=h({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:e(k.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:e(k.mapTextFull,"{geojson.copyright}")},mapView:{},tooltip:{followTouchMove:!1}},f);a.prototype.init.call(this,f,b)};return c}(g);(function(a){a.maps={};a.mapChart=function(f,d,b){return new a(f,d,b)};a.splitPath=
function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));return l.prototype.pathToSegments(a)}})(g||(g={}));return g});t(e,"Maps/MapUtilities.js",[],function(){return{boundsFromPath:function(g){var c=-Number.MAX_VALUE,l=Number.MAX_VALUE,a=-Number.MAX_VALUE,f=Number.MAX_VALUE,d;g.forEach(function(h){var g=h[h.length-2];h=h[h.length-1];"number"===typeof g&&"number"===typeof h&&
(l=Math.min(l,g),c=Math.max(c,g),f=Math.min(f,h),a=Math.max(a,h),d=!0)});if(d)return{x1:l,y1:f,x2:c,y2:a}},pointInPolygon:function(g,c){var l,a=!1,f=g.x,d=g.y;g=0;for(l=c.length-1;g<c.length;l=g++){var h=c[g][1]>d;var e=c[l][1]>d;h!==e&&f<(c[l][0]-c[g][0])*(d-c[g][1])/(c[l][1]-c[g][1])+c[g][0]&&(a=!a)}return a}}});t(e,"Series/Map/MapPoint.js",[e["Series/ColorMapComposition.js"],e["Maps/MapUtilities.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(g,c,l,a){var f=this&&this.__extends||
function(){var a=function(f,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var k in a)Object.prototype.hasOwnProperty.call(a,k)&&(b[k]=a[k])};return a(f,b)};return function(f,b){function k(){this.constructor=f}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");a(f,b);f.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),d=c.boundsFromPath,h=a.extend,
e=a.isNumber,n=a.pick;c=function(c){function g(){var b=null!==c&&c.apply(this,arguments)||this;b.options=void 0;b.path=void 0;b.series=void 0;return b}f(g,c);g.getProjectedPath=function(b,k){b.projectedPath||(k&&b.geometry?(k.hasCoordinates=!0,b.projectedPath=k.path(b.geometry)):b.projectedPath=b.path);return b.projectedPath||[]};g.prototype.applyOptions=function(b,k){var a=this.series;b=c.prototype.applyOptions.call(this,b,k);k=a.joinBy;a.mapData&&a.mapMap&&(k=c.prototype.getNestedProperty.call(b,
k[1]),(k="undefined"!==typeof k&&a.mapMap[k])?h(b,k):-1!==a.pointArrayMap.indexOf("value")&&(b.value=b.value||null));return b};g.prototype.getProjectedBounds=function(b){b=g.getProjectedPath(this,b);b=d(b);var k=this.properties,a=this.series.chart.mapView;if(b){var f=k&&k["hc-middle-lon"],c=k&&k["hc-middle-lat"];if(a&&e(f)&&e(c)){if(k=a.lonLatToProjectedUnits({lon:f,lat:c}))b.midX=k.x,b.midY=k.y}else a=k&&k["hc-middle-x"],k=k&&k["hc-middle-y"],b.midX=b.x1+(b.x2-b.x1)*n(this.middleX,e(a)?a:.5),k=n(this.middleY,
e(k)?k:.5),this.geometry||(k=1-k),b.midY=b.y2-(b.y2-b.y1)*k;return b}};g.prototype.onMouseOver=function(b){a.clearTimeout(this.colorInterval);if(!this.isNull&&this.visible||this.series.options.nullInteraction)c.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)};g.prototype.setVisible=function(b){var a=b?"show":"hide";this.visible=this.options.visible=!!b;if(this.dataLabel)this.dataLabel[a]();this.graphic&&this.graphic.attr(this.series.pointAttribs(this))};g.prototype.zoomTo=function(b){var a=
this.series.chart,f=a.mapView,d=this.bounds;if(f&&d){var c=e(this.insetIndex)&&f.insets[this.insetIndex];if(c){var h=c.projectedUnitsToPixels({x:d.x1,y:d.y1});d=c.projectedUnitsToPixels({x:d.x2,y:d.y2});h=f.pixelsToProjectedUnits({x:h.x,y:h.y});d=f.pixelsToProjectedUnits({x:d.x,y:d.y});d={x1:h.x,y1:h.y,x2:d.x,y2:d.y}}f.fitToBounds(d,void 0,!1);this.series.isDirty=!0;a.redraw(b)}};return g}(l.seriesTypes.scatter.prototype.pointClass);h(c.prototype,{dataLabelOnNull:g.pointMembers.dataLabelOnNull,moveToTopOnHover:g.pointMembers.moveToTopOnHover,
isValid:g.pointMembers.isValid});return c});t(e,"Maps/MapViewOptionsDefault.js",[],function(){return{center:[0,0],fitToGeometry:void 0,maxZoom:void 0,padding:0,projection:{name:void 0,parallels:void 0,rotation:void 0},zoom:void 0}});t(e,"Maps/MapViewInsetsOptionsDefault.js",[],function(){return{borderColor:"#cccccc",borderWidth:1,center:[0,0],padding:"10%",relativeTo:"mapBoundingBox",units:"percent"}});t(e,"Extensions/GeoJSON.js",[e["Core/Chart/Chart.js"],e["Core/FormatUtilities.js"],e["Core/Globals.js"],
e["Core/Utilities.js"]],function(g,c,e,a){function f(b,a){a||(a=Object.keys(b.objects)[0]);a=b.objects[a];if(a["hc-decoded-geojson"])return a["hc-decoded-geojson"];var k=b.arcs;if(b.transform){var f=b.transform,d=f.scale,c=f.translate;k=b.arcs.map(function(b){var a=0,k=0;return b.map(function(b){b=b.slice();b[0]=(a+=b[0])*d[0]+c[0];b[1]=(k+=b[1])*d[1]+c[1];return b})})}var h=function(b){return"number"===typeof b[0]?b.reduce(function(b,a,f){var d=0>a?k[~a]:k[a];0>a?(d=d.slice(0,0===f?d.length:d.length-
1),d.reverse()):f&&(d=d.slice(1));return b.concat(d)},[]):b.map(h)};f=a.geometries.map(function(b){return{type:"Feature",properties:b.properties,geometry:{type:b.type,coordinates:b.coordinates||h(b.arcs)}}});b={type:"FeatureCollection",copyright:b.copyright,copyrightShort:b.copyrightShort,copyrightUrl:b.copyrightUrl,features:f,"hc-recommended-mapview":a["hc-recommended-mapview"],bbox:b.bbox,title:b.title};return a["hc-decoded-geojson"]=b}function d(b,a,d){void 0===a&&(a="map");var k=[];b="Topology"===
b.type?f(b):b;b.features.forEach(function(b){var d=b.geometry||{},f=d.type;d=d.coordinates;b=b.properties;var c;"map"!==a&&"mapbubble"!==a||"Polygon"!==f&&"MultiPolygon"!==f?"mapline"!==a||"LineString"!==f&&"MultiLineString"!==f?"mappoint"===a&&"Point"===f&&d.length&&(c={geometry:{coordinates:d,type:f}}):d.length&&(c={geometry:{coordinates:d,type:f}}):d.length&&(c={geometry:{coordinates:d,type:f}});if(c){f=b&&(b.name||b.NAME);d=b&&b.lon;var h=b&&b.lat;k.push(u(c,{lat:"number"===typeof h?h:void 0,
lon:"number"===typeof d?d:void 0,name:"string"===typeof f?f:void 0,properties:b}))}});d&&b.copyrightShort&&(d.chart.mapCredits=h(d.chart.options.credits.mapText,{geojson:b}),d.chart.mapCreditsFull=h(d.chart.options.credits.mapTextFull,{geojson:b}));return k}var h=c.format,l=e.win,n=a.error,u=a.extend,w=a.merge;c=a.wrap;"";g.prototype.transformFromLatLon=function(b,a){var d=this.options.chart.proj4||l.proj4;if(d){var f=a.jsonmarginX;f=void 0===f?0:f;var k=a.jsonmarginY;k=void 0===k?0:k;var c=a.jsonres;
c=void 0===c?1:c;var h=a.scale;h=void 0===h?1:h;var g=a.xoffset;g=void 0===g?0:g;var e=a.xpan;e=void 0===e?0:e;var m=a.yoffset;m=void 0===m?0:m;var p=a.ypan;p=void 0===p?0:p;b=d(a.crs,[b.lon,b.lat]);d=a.cosAngle||a.rotation&&Math.cos(a.rotation);var r=a.sinAngle||a.rotation&&Math.sin(a.rotation);a=a.rotation?[b[0]*d+b[1]*r,-b[0]*r+b[1]*d]:b;return{x:((a[0]-g)*h+e)*c+f,y:-(((m-a[1])*h+p)*c-k)}}n(21,!1,this)};g.prototype.transformToLatLon=function(b,a){var d=this.options.chart.proj4||l.proj4;if(!d)n(21,
!1,this);else if(null!==b.y){var f=a.jsonmarginX,k=a.jsonmarginY,c=a.jsonres;c=void 0===c?1:c;var h=a.scale;h=void 0===h?1:h;var g=a.xoffset,e=a.xpan,m=a.yoffset,p=a.ypan;b={x:((b.x-(void 0===f?0:f))/c-(void 0===e?0:e))/h+(void 0===g?0:g),y:((b.y-(void 0===k?0:k))/c+(void 0===p?0:p))/h+(void 0===m?0:m)};f=a.cosAngle||a.rotation&&Math.cos(a.rotation);k=a.sinAngle||a.rotation&&Math.sin(a.rotation);a=d(a.crs,"WGS84",a.rotation?{x:b.x*f+b.y*-k,y:b.x*k+b.y*f}:b);return{lat:a.y,lon:a.x}}};g.prototype.fromPointToLatLon=
function(b){return this.mapView&&this.mapView.projectedUnitsToLonLat(b)};g.prototype.fromLatLonToPoint=function(b){return this.mapView&&this.mapView.lonLatToProjectedUnits(b)};c(g.prototype,"addCredits",function(b,a){a=w(!0,this.options.credits,a);this.mapCredits&&(a.href=null);b.call(this,a);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})});e.geojson=d;e.topo2geo=f;return{geojson:d,topo2geo:f}});t(e,"Core/Geometry/PolygonClip.js",[],function(){var g=function(a,f,
d){return(f[0]-a[0])*(d[1]-a[1])>(f[1]-a[1])*(d[0]-a[0])},c=function(a,f,d,c){var h=[a[0]-f[0],a[1]-f[1]],g=[d[0]-c[0],d[1]-c[1]];a=a[0]*f[1]-a[1]*f[0];d=d[0]*c[1]-d[1]*c[0];c=1/(h[0]*g[1]-h[1]*g[0]);h=[(a*g[0]-d*h[0])*c,(a*g[1]-d*h[1])*c];h.isIntersection=!0;return h},e;(function(a){a.clipLineString=function(f,d){var c=[];f=a.clipPolygon(f,d,!1);for(d=1;d<f.length;d++)f[d].isIntersection&&f[d-1].isIntersection&&(c.push(f.splice(0,d)),d=0),d===f.length-1&&c.push(f);return c};a.clipPolygon=function(a,
d,h){void 0===h&&(h=!0);for(var f=d[d.length-1],e,l,w=a,b=0;b<d.length;b++){var k=w;a=d[b];w=[];e=h?k[k.length-1]:k[0];for(var D=0;D<k.length;D++)l=k[D],g(f,a,l)?(g(f,a,e)||w.push(c(f,a,e,l)),w.push(l)):g(f,a,e)&&w.push(c(f,a,e,l)),e=l;f=a}return w}})(e||(e={}));return e});t(e,"Maps/Projections/LambertConformalConic.js",[],function(){var e=Math.sign||function(a){return 0===a?0:0<a?1:-1},c=Math.PI/180,l=Math.PI/2;return function(){function a(a){var d,f=(a.parallels||[]).map(function(a){return a*c}),
g=f[0]||0;f=null!==(d=f[1])&&void 0!==d?d:g;d=Math.cos(g);"object"===typeof a.projectedBounds&&(this.projectedBounds=a.projectedBounds);a=g===f?Math.sin(g):Math.log(d/Math.cos(f))/Math.log(Math.tan((l+f)/2)/Math.tan((l+g)/2));1e-10>Math.abs(a)&&(a=1e-10*(e(a)||1));this.n=a;this.c=d*Math.pow(Math.tan((l+g)/2),a)/a}a.prototype.forward=function(a){var d=a[0]*c,f=this.c,e=this.n,g=this.projectedBounds;a=a[1]*c;0<f?a<-l+.000001&&(a=-l+.000001):a>l-.000001&&(a=l-.000001);var u=f/Math.pow(Math.tan((l+a)/
2),e);a=u*Math.sin(e*d)*63.78137;d=63.78137*(f-u*Math.cos(e*d));f=[a,d];g&&(a<g.x1||a>g.x2||d<g.y1||d>g.y2)&&(f.outside=!0);return f};a.prototype.inverse=function(a){var d=a[0]/63.78137,f=this.c,g=this.n;a=f-a[1]/63.78137;var n=e(g)*Math.sqrt(d*d+a*a),u=Math.atan2(d,Math.abs(a))*e(a);0>a*g&&(u-=Math.PI*e(d)*e(a));return[u/g/c,(2*Math.atan(Math.pow(f/n,1/g))-l)/c]};return a}()});t(e,"Maps/Projections/EqualEarth.js",[],function(){var g=Math.sqrt(3)/2;return function(){function c(){this.bounds={x1:-200.37508342789243,
x2:200.37508342789243,y1:-97.52595454902263,y2:97.52595454902263}}c.prototype.forward=function(c){var a=Math.PI/180,f=Math.asin(g*Math.sin(c[1]*a)),d=f*f,e=d*d*d;return[c[0]*a*Math.cos(f)*74.03120656864502/(g*(1.340264+3*-.081106*d+e*(7*.000893+.034164*d))),74.03120656864502*f*(1.340264+-.081106*d+e*(.000893+.003796*d))]};c.prototype.inverse=function(c){var a=c[0]/74.03120656864502;c=c[1]/74.03120656864502;var f=180/Math.PI,d=c,e;for(e=0;12>e;++e){var l=d*d;var n=l*l*l;var u=d*(1.340264+-.081106*
l+n*(.000893+.003796*l))-c;l=1.340264+3*-.081106*l+n*(7*.000893+.034164*l);d-=u/=l;if(1e-9>Math.abs(u))break}l=d*d;return[f*g*a*(1.340264+3*-.081106*l+l*l*l*(7*.000893+.034164*l))/Math.cos(d),f*Math.asin(Math.sin(d)/g)]};return c}()});t(e,"Maps/Projections/Miller.js",[],function(){var e=Math.PI/4,c=Math.PI/180;return function(){function g(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-146.91480769173063,y2:146.91480769173063}}g.prototype.forward=function(a){return[a[0]*c*63.78137,
79.7267125*Math.log(Math.tan(e+.4*a[1]*c))]};g.prototype.inverse=function(a){return[a[0]/63.78137/c,2.5*(Math.atan(Math.exp(a[1]/63.78137*.8))-e)/c]};return g}()});t(e,"Maps/Projections/Orthographic.js",[],function(){var e=Math.PI/180;return function(){function c(){this.antimeridianCutting=!1;this.bounds={x1:-63.78460826781007,x2:63.78460826781007,y1:-63.78460826781007,y2:63.78460826781007}}c.prototype.forward=function(c){var a=c[0];c=c[1]*e;c=[Math.cos(c)*Math.sin(a*e)*63.78460826781007,63.78460826781007*
Math.sin(c)];if(-90>a||90<a)c.outside=!0;return c};c.prototype.inverse=function(c){var a=c[0]/63.78460826781007;c=c[1]/63.78460826781007;var f=Math.sqrt(a*a+c*c),d=Math.asin(f),g=Math.sin(d);return[Math.atan2(a*g,f*Math.cos(d))/e,Math.asin(f&&c*g/f)/e]};return c}()});t(e,"Maps/Projections/WebMercator.js",[],function(){var e=Math.PI/180;return function(){function c(){this.bounds={x1:-200.37508342789243,x2:200.37508342789243,y1:-200.3750834278071,y2:200.3750834278071};this.maxLatitude=85.0511287798}
c.prototype.forward=function(c){var a=Math.sin(c[1]*e);a=[63.78137*c[0]*e,63.78137*Math.log((1+a)/(1-a))/2];85.0511287798<Math.abs(c[1])&&(a.outside=!0);return a};c.prototype.inverse=function(c){return[c[0]/(63.78137*e),(2*Math.atan(Math.exp(c[1]/63.78137))-Math.PI/2)/e]};return c}()});t(e,"Maps/Projections/ProjectionRegistry.js",[e["Maps/Projections/LambertConformalConic.js"],e["Maps/Projections/EqualEarth.js"],e["Maps/Projections/Miller.js"],e["Maps/Projections/Orthographic.js"],e["Maps/Projections/WebMercator.js"]],
function(e,c,l,a,f){return{EqualEarth:c,LambertConformalConic:e,Miller:l,Orthographic:a,WebMercator:f}});t(e,"Maps/Projection.js",[e["Core/Geometry/PolygonClip.js"],e["Maps/Projections/ProjectionRegistry.js"],e["Core/Utilities.js"]],function(e,c,l){var a=this&&this.__spreadArray||function(a,b,d){if(d||2===arguments.length)for(var c=0,f=b.length,e;c<f;c++)!e&&c in b||(e||(e=Array.prototype.slice.call(b,0,c)),e[c]=b[c]);return a.concat(e||Array.prototype.slice.call(b))},f=e.clipLineString,d=e.clipPolygon,
g=l.clamp,t=l.erase,n=2*Math.PI/360,u=function(a){-180>a&&(a+=360);180<a&&(a-=360);return a};return function(){function e(a){void 0===a&&(a={});this.hasGeoProjection=this.hasCoordinates=!1;this.maxLatitude=90;this.options=a;var b=a.name,d=a.projectedBounds,c=a.rotation;this.rotator=c?this.getRotator(c):void 0;if(b=b?e.registry[b]:void 0)this.def=new b(a);var f=this.def,g=this.rotator;f&&(this.maxLatitude=f.maxLatitude||90,this.hasGeoProjection=!0);g&&f?(this.forward=function(a){return f.forward(g.forward(a))},
this.inverse=function(a){return g.inverse(f.inverse(a))}):f?(this.forward=function(a){return f.forward(a)},this.inverse=function(a){return f.inverse(a)}):g&&(this.forward=g.forward,this.inverse=g.inverse);this.bounds="world"===d?f&&f.bounds:d}e.add=function(a,d){e.registry[a]=d};e.greatCircle=function(a,d,c){var b=Math.atan2,e=Math.cos,f=Math.sin,g=Math.sqrt,k=a[1]*n,h=a[0]*n,m=d[1]*n,p=d[0]*n,r=m-k,l=p-h;r=f(r/2)*f(r/2)+e(k)*e(m)*f(l/2)*f(l/2);r=2*b(g(r),g(1-r));var A=Math.round(6371E3*r/5E5);l=
[];c&&l.push(a);if(1<A)for(A=a=1/A;.999>A;A+=a){var H=f((1-A)*r)/f(r),I=f(A*r)/f(r),q=H*e(k)*e(h)+I*e(m)*e(p),z=H*e(k)*f(h)+I*e(m)*f(p);H=H*f(k)+I*f(m);H=b(H,g(q*q+z*z));q=b(z,q);l.push([q/n,H/n])}c&&l.push(d);return l};e.insertGreatCircles=function(b){for(var d=b.length-1;d--;)if(10<Math.max(Math.abs(b[d][0]-b[d+1][0]),Math.abs(b[d][1]-b[d+1][1]))){var c=e.greatCircle(b[d],b[d+1]);c.length&&b.splice.apply(b,a([d+1,0],c,!1))}};e.toString=function(a){a=a||{};var b=a.rotation;return[a.name,b&&b.join(",")].join(";")};
e.prototype.lineIntersectsBounds=function(a){var b=this.bounds||{},d=b.x2,c=b.y1,f=b.y2,e=function(a,b,d){var c=a[0];a=a[1];var e=b?0:1;if("number"===typeof d&&c[b]>=d!==a[b]>=d)return c=c[e]+(d-c[b])/(a[b]-c[b])*(a[e]-c[e]),b?[c,d]:[d,c]},g=a[0];if(b=e(a,0,b.x1))g=b,a[1]=b;else if(b=e(a,0,d))g=b,a[1]=b;if(b=e(a,1,c))g=b;else if(b=e(a,1,f))g=b;return g};e.prototype.getRotator=function(a){var b=a[0]*n,d=(a[1]||0)*n;a=(a[2]||0)*n;var c=Math.cos(d),e=Math.sin(d),f=Math.cos(a),g=Math.sin(a);if(0!==b||
0!==d||0!==a)return{forward:function(a){var d=a[0]*n+b,m=a[1]*n,p=Math.cos(m);a=Math.cos(d)*p;d=Math.sin(d)*p;m=Math.sin(m);p=m*c+a*e;return[Math.atan2(d*f-p*g,a*c-m*e)/n,Math.asin(p*f+d*g)/n]},inverse:function(a){var d=a[0]*n,m=a[1]*n,p=Math.cos(m);a=Math.cos(d)*p;d=Math.sin(d)*p;m=Math.sin(m);p=m*f-d*g;return[(Math.atan2(d*f+m*g,a*c+p*e)-b)/n,Math.asin(p*c-a*e)/n]}}};e.prototype.forward=function(a){return a};e.prototype.inverse=function(a){return a};e.prototype.cutOnAntimeridian=function(b,d){var c=
[],f=[b];b.forEach(function(a,e){var f=b[e-1];if(!e){if(!d)return;f=b[b.length-1]}var m=f[0],q=a[0];(-90>m||90<m)&&(-90>q||90<q)&&0<m!==0<q&&(q=g((180-(m+360)%360)/((q+360)%360-(m+360)%360),0,1),c.push({i:e,lat:f[1]+q*(a[1]-f[1]),direction:0>m?1:-1,previousLonLat:f,lonLat:a}))});if(c.length)if(d){if(1===c.length%2){var h=c.slice().sort(function(a,b){return Math.abs(b.lat)-Math.abs(a.lat)})[0];t(c,h)}for(var k=c.length-2;0<=k;){var l=c[k].i,n=u(180+.000001*c[k].direction),x=u(180-.000001*c[k].direction);
l=b.splice.apply(b,a([l,c[k+1].i-l],e.greatCircle([n,c[k].lat],[n,c[k+1].lat],!0),!1));l.push.apply(l,e.greatCircle([x,c[k+1].lat],[x,c[k].lat],!0));f.push(l);k-=2}if(h)for(n=0;n<f.length;n++){k=h.direction;var m=h.lat;x=f[n];l=x.indexOf(h.lonLat);if(-1<l){n=(0>m?-1:1)*this.maxLatitude;var p=u(180+.000001*k),r=u(180-.000001*k);m=e.greatCircle([p,m],[p,n],!0);for(p+=120*k;-180<p&&180>p;p+=120*k)m.push([p,n]);m.push.apply(m,e.greatCircle([r,n],[r,h.lat],!0));x.splice.apply(x,a([l,0],m,!1));break}}}else for(k=
c.length;k--;)l=c[k].i,l=b.splice(l,b.length,[u(180+.000001*c[k].direction),c[k].lat]),l.unshift([u(180-.000001*c[k].direction),c[k].lat]),f.push(l);return f};e.prototype.path=function(a){var b=this,c=this.bounds,g=this.def,h=this.rotator,l=[],n="Polygon"===a.type||"MultiPolygon"===a.type,t=this.hasGeoProjection,x=!g||!1!==g.antimeridianCutting,m=x?h:void 0,p=x?g||this:this,r;c&&(r=[[c.x1,c.y1],[c.x2,c.y1],[c.x2,c.y2],[c.x1,c.y2]]);var J=function(a){a=a.map(function(a){if(x){m&&(a=m.forward(a));var b=
a[0];.000001>Math.abs(b-180)&&(b=180>b?179.999999:180.000001);a=[b,a[1]]}return a});var g=[a];t&&(e.insertGreatCircles(a),x&&(g=b.cutOnAntimeridian(a,n)));g.forEach(function(a){if(!(2>a.length)){var b=!1,z=!1,M=function(a){b?l.push(["L",a[0],a[1]]):(l.push(["M",a[0],a[1]]),b=!0)},C=!1,v=!1,g=a.map(function(a){a=p.forward(a);a.outside?C=!0:v=!0;Infinity===a[1]?a[1]=1E10:-Infinity===a[1]&&(a[1]=-1E10);return a});if(x){n&&g.push(g[0]);if(C){if(!v)return;if(r)if(n)g=d(g,r);else if(c){f(g,r).forEach(function(a){b=
!1;a.forEach(M)});return}}g.forEach(M)}else for(var B=0;B<g.length;B++){var m=a[B],h=g[B];if(h.outside)z=!0;else{if(n&&!k){var k=m;a.push(m);g.push(h)}z&&I&&(n&&t?e.greatCircle(I,m).forEach(function(a){return M(p.forward(a))}):b=!1);M(h);var I=m;z=!1}}}})};"LineString"===a.type?J(a.coordinates):"MultiLineString"===a.type?a.coordinates.forEach(function(a){return J(a)}):"Polygon"===a.type?(a.coordinates.forEach(function(a){return J(a)}),l.length&&l.push(["Z"])):"MultiPolygon"===a.type&&(a.coordinates.forEach(function(a){a.forEach(function(a){return J(a)})}),
l.length&&l.push(["Z"]));return l};e.registry=c;return e}()});t(e,"Maps/MapView.js",[e["Maps/MapViewOptionsDefault.js"],e["Maps/MapViewInsetsOptionsDefault.js"],e["Extensions/GeoJSON.js"],e["Core/Chart/MapChart.js"],e["Maps/MapUtilities.js"],e["Maps/Projection.js"],e["Core/Utilities.js"]],function(e,c,l,a,f,d,h){var g=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,
c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),n=this&&this.__spreadArray||function(a,b,c){if(c||2===arguments.length)for(var d=0,q=b.length,e;d<q;d++)!e&&d in b||(e||(e=Array.prototype.slice.call(b,0,d)),e[d]=b[d]);return a.concat(e||Array.prototype.slice.call(b))},
t=l.topo2geo,w=a.maps,b=f.boundsFromPath,k=f.pointInPolygon,D=h.addEvent,E=h.clamp,L=h.fireEvent,F=h.isArray,G=h.isNumber,N=h.isObject,x=h.isString,m=h.merge,p=h.pick,r=h.relativeLength,J=function(a,b){return Math.log(400.979322/Math.max((a.x2-a.x1)/(b.width/256),(a.y2-a.y1)/(b.height/256)))/Math.log(2)},A=function(){function a(b,c){var q=this;this.allowTransformAnimation=!0;this.insets=[];this.padding=[0,0,0,0];this.eventsToUnbind=[];var f;if(!(this instanceof H)){var v=n([b.options.chart.map],(b.options.series||
[]).map(function(a){return a.mapData}),!0).map(function(a){return q.getGeoMap(a)}),z=[];v.forEach(function(a){a&&(f||(f=a["hc-recommended-mapview"]),a.bbox&&(a=a.bbox,z.push({x1:a[0],y1:a[1],x2:a[2],y2:a[3]})))});var g=z.length&&a.compositeBounds(z);if(g){var h=g.x1;var k=g.y1,p=g.x2;g=g.y2;h=180<p-h&&90<g-k?{name:"EqualEarth"}:{name:"LambertConformalConic",parallels:[k,g],rotation:[-(h+p)/2]}}this.geoMap=v[0]}this.userOptions=c||{};v=m(e,{projection:h},f,c);g=f&&f.insets;c=c&&c.insets;g&&c&&(v.insets=
a.mergeInsets(g,c));this.chart=b;this.center=v.center;this.options=v;this.projection=new d(v.projection);this.playingField=b.plotBox;this.zoom=v.zoom||0;this.createInsets();this.eventsToUnbind.push(D(b,"afterSetChartSize",function(){q.playingField=q.getField();if(void 0===q.minZoom||q.minZoom===q.zoom)q.fitToBounds(void 0,void 0,!1),!q.chart.hasRendered&&G(q.userOptions.zoom)&&(q.zoom=q.userOptions.zoom),q.userOptions.center&&m(!0,q.center,q.userOptions.center)}));this.setUpEvents()}a.mergeInsets=
function(a,b){var c=function(a){var b={};a.forEach(function(a,c){b[a&&a.id||"i".concat(c)]=a});return b},d=m(c(a),c(b));return Object.keys(d).map(function(a){return d[a]})};a.prototype.createInsets=function(){var a=this,b=this.options,c=b.insets;c&&c.forEach(function(c){c=new H(a,m(b.insetOptions,c));a.insets.push(c)})};a.prototype.fitToBounds=function(a,b,c,d){void 0===c&&(c=!0);var q=a||this.getProjectedBounds();if(q){var e=p(b,a?0:this.options.padding);b=this.getField(!1);e=F(e)?e:[e,e,e,e];this.padding=
[r(e[0],b.height),r(e[1],b.width),r(e[2],b.height),r(e[3],b.width)];this.playingField=this.getField();b=J(q,this.playingField);a||(this.minZoom=b);a=this.projection.inverse([(q.x2+q.x1)/2,(q.y2+q.y1)/2]);this.setView(a,b,c,d)}};a.prototype.getField=function(a){void 0===a&&(a=!0);a=a?this.padding:[0,0,0,0];return{x:a[3],y:a[0],width:this.chart.plotWidth-a[1]-a[3],height:this.chart.plotHeight-a[0]-a[2]}};a.prototype.getGeoMap=function(a){if(x(a))return w[a]&&"Topology"===w[a].type?t(w[a]):w[a];if(N(a,
!0)){if("FeatureCollection"===a.type)return a;if("Topology"===a.type)return t(a)}};a.prototype.getMapBBox=function(){var a=this.getProjectedBounds(),b=this.getScale();if(a){var c=this.padding,d=this.projectedUnitsToPixels({x:a.x1,y:a.y2});return{width:(a.x2-a.x1)*b+c[1]+c[3],height:(a.y2-a.y1)*b+c[0]+c[2],x:d.x-c[3],y:d.y-c[0]}}};a.prototype.getProjectedBounds=function(){var c=this.projection,d=this.chart.series.reduce(function(a,b){var c=b.getProjectedBounds&&b.getProjectedBounds();c&&!1!==b.options.affectsMapView&&
a.push(c);return a},[]),e=this.options.fitToGeometry;return e?(this.fitToGeometryCache||("MultiPoint"===e.type?(e=e.coordinates.map(function(a){return c.forward(a)}),d=e.map(function(a){return a[0]}),e=e.map(function(a){return a[1]}),this.fitToGeometryCache={x1:Math.min.apply(0,d),x2:Math.max.apply(0,d),y1:Math.min.apply(0,e),y2:Math.max.apply(0,e)}):this.fitToGeometryCache=b(c.path(e))),this.fitToGeometryCache):this.projection.bounds||a.compositeBounds(d)};a.prototype.getScale=function(){return 256/
400.979322*Math.pow(2,this.zoom)};a.prototype.getSVGTransform=function(){var a=this.playingField,b=a.x,c=a.y,d=a.width;a=a.height;var e=this.projection.forward(this.center),f=this.projection.hasCoordinates?-1:1,g=this.getScale();f*=g;return{scaleX:g,scaleY:f,translateX:b+d/2-e[0]*g,translateY:c+a/2-e[1]*f}};a.prototype.lonLatToPixels=function(a){if(a=this.lonLatToProjectedUnits(a))return this.projectedUnitsToPixels(a)};a.prototype.lonLatToProjectedUnits=function(a){var b=this.chart,c=b.mapTransforms;
if(c){for(var d in c)if(Object.hasOwnProperty.call(c,d)&&c[d].hitZone){var e=b.transformFromLatLon(a,c[d]);if(e&&k(e,c[d].hitZone.coordinates[0]))return e}return b.transformFromLatLon(a,c["default"])}c=0;for(d=this.insets;c<d.length;c++)if(b=d[c],b.options.geoBounds&&k({x:a.lon,y:a.lat},b.options.geoBounds.coordinates[0]))return a=b.projection.forward([a.lon,a.lat]),a=b.projectedUnitsToPixels({x:a[0],y:a[1]}),this.pixelsToProjectedUnits(a);a=this.projection.forward([a.lon,a.lat]);if(!a.outside)return{x:a[0],
y:a[1]}};a.prototype.projectedUnitsToLonLat=function(a){var b=this.chart,c=b.mapTransforms;if(c){for(var d in c)if(Object.hasOwnProperty.call(c,d)&&c[d].hitZone&&k(a,c[d].hitZone.coordinates[0]))return b.transformToLatLon(a,c[d]);return b.transformToLatLon(a,c["default"])}c=this.projectedUnitsToPixels(a);d=0;for(var e=this.insets;d<e.length;d++)if(b=e[d],b.hitZone&&k(c,b.hitZone.coordinates[0]))return a=b.pixelsToProjectedUnits(c),a=b.projection.inverse([a.x,a.y]),{lon:a[0],lat:a[1]};a=this.projection.inverse([a.x,
a.y]);return{lon:a[0],lat:a[1]}};a.prototype.redraw=function(a){this.chart.series.forEach(function(a){a.useMapGeometry&&(a.isDirty=!0)});this.chart.redraw(a)};a.prototype.setView=function(a,b,c,d){void 0===c&&(c=!0);a&&(this.center=a);"number"===typeof b&&("number"===typeof this.minZoom&&(b=Math.max(b,this.minZoom)),"number"===typeof this.options.maxZoom&&(b=Math.min(b,this.options.maxZoom)),G(b)&&(this.zoom=b));var e=this.getProjectedBounds();if(e){a=this.projection.forward(this.center);var f=this.playingField;
b=f.x;var g=f.y,m=f.width;f=f.height;var C=this.getScale(),q=this.projectedUnitsToPixels({x:e.x1,y:e.y1}),h=this.projectedUnitsToPixels({x:e.x2,y:e.y2});e=[(e.x1+e.x2)/2,(e.y1+e.y2)/2];if(!this.chart.series.some(function(a){return a.isDrilling})){var k=q.x,z=h.y;h=h.x;q=q.y;h-k<m?a[0]=e[0]:k<b&&h<b+m?a[0]+=Math.max(k-b,h-m-b)/C:h>b+m&&k>b&&(a[0]+=Math.min(h-m-b,k-b)/C);q-z<f?a[1]=e[1]:z<g&&q<g+f?a[1]-=Math.max(z-g,q-f-g)/C:q>g+f&&z>g&&(a[1]-=Math.min(q-f-g,z-g)/C);this.center=this.projection.inverse(a)}this.insets.forEach(function(a){a.options.field&&
(a.hitZone=a.getHitZone(),a.playingField=a.getField())});this.render()}L(this,"afterSetView");c&&this.redraw(d)};a.prototype.projectedUnitsToPixels=function(a){var b=this.getScale(),c=this.projection.forward(this.center),d=this.playingField;return{x:d.x+d.width/2-b*(c[0]-a.x),y:d.y+d.height/2+b*(c[1]-a.y)}};a.prototype.pixelsToLonLat=function(a){return this.projectedUnitsToLonLat(this.pixelsToProjectedUnits(a))};a.prototype.pixelsToProjectedUnits=function(a){var b=a.x;a=a.y;var c=this.getScale(),
d=this.projection.forward(this.center),e=this.playingField;return{x:d[0]+(b-(e.x+e.width/2))/c,y:d[1]-(a-(e.y+e.height/2))/c}};a.prototype.setUpEvents=function(){var a=this,b=this.chart,c,d,e,f=function(f){var g=b.pointer.pinchDown,m=a.projection,C=b.mouseDownX,h=b.mouseDownY;1===g.length&&(C=g[0].chartX,h=g[0].chartY);if("number"===typeof C&&"number"===typeof h){var v="".concat(C,",").concat(h),k=f.originalEvent;g=k.chartX;k=k.chartY;v!==d&&(d=v,c=a.projection.forward(a.center),e=(a.projection.options.rotation||
[0,0]).slice());v=(v=m.def&&m.def.bounds)&&J(v,a.playingField)||-Infinity;"Orthographic"===m.options.name&&(a.minZoom||Infinity)<1.3*v?(m=440/(a.getScale()*Math.min(b.plotWidth,b.plotHeight)),e&&(C=(C-g)*m-e[0],h=E(-e[1]-(h-k)*m,-80,80),g=a.zoom,a.update({projection:{rotation:[-C,-h]}},!1),a.fitToBounds(void 0,void 0,!1),a.zoom=g,b.redraw(!1))):G(g)&&G(k)&&(m=a.getScale(),h=a.projection.inverse([c[0]+(C-g)/m,c[1]-(h-k)/m*(a.projection.hasCoordinates?1:-1)]),a.setView(h,void 0,!0,!1));f.preventDefault()}};
D(b,"pan",f);D(b,"touchpan",f);D(b,"selection",function(c){if(c.resetSelection)a.zoomBy();else{var d=c.x-b.plotLeft,e=c.y-b.plotTop,f=a.pixelsToProjectedUnits({x:d,y:e}),g=f.y;f=f.x;d=a.pixelsToProjectedUnits({x:d+c.width,y:e+c.height});a.fitToBounds({x1:f,y1:g,x2:d.x,y2:d.y},void 0,!0,c.originalEvent.touches?!1:void 0);/^touch/.test(c.originalEvent.type)||b.showResetZoom();c.preventDefault()}})};a.prototype.render=function(){this.group||(this.group=this.chart.renderer.g("map-view").attr({zIndex:4}).add())};
a.prototype.update=function(a,b,c){void 0===b&&(b=!0);var e=a.projection;e=e&&d.toString(e)!==d.toString(this.options.projection);var f=!1;m(!0,this.userOptions,a);m(!0,this.options,a);"insets"in a&&(this.insets.forEach(function(a){return a.destroy()}),this.insets.length=0,f=!0);(e||"fitToGeometry"in a)&&delete this.fitToGeometryCache;if(e||f)this.chart.series.forEach(function(a){var b=a.transformGroups;a.clearBounds&&a.clearBounds();a.isDirty=!0;a.isDirtyData=!0;if(f&&b)for(;1<b.length;)(a=b.pop())&&
a.destroy()}),e&&(this.projection=new d(this.options.projection)),f&&this.createInsets(),a.center||!Object.hasOwnProperty.call(a,"zoom")||G(a.zoom)||this.fitToBounds(void 0,void 0,!1);a.center||G(a.zoom)?this.setView(this.options.center,a.zoom,!1):"fitToGeometry"in a&&this.fitToBounds(void 0,void 0,!1);b&&this.chart.redraw(c)};a.prototype.zoomBy=function(a,b,c,d){var e=this.chart,f=this.projection.forward(this.center);b=b?this.projection.forward(b):[];var g=b[0],m=b[1];"number"===typeof a?(a=this.zoom+
a,b=void 0,c&&(g=c[0],m=c[1],c=this.getScale(),g=g-e.plotLeft-e.plotWidth/2,e=m-e.plotTop-e.plotHeight/2,g=f[0]+g/c,m=f[1]+e/c),"number"===typeof g&&"number"===typeof m&&(c=1-Math.pow(2,this.zoom)/Math.pow(2,a),g=f[0]-g,e=f[1]-m,f[0]-=g*c,f[1]+=e*c,b=this.projection.inverse(f)),this.setView(b,a,void 0,d)):this.fitToBounds(void 0,void 0,void 0,d)};a.compositeBounds=function(a){if(a.length)return a.slice(1).reduce(function(a,b){a.x1=Math.min(a.x1,b.x1);a.y1=Math.min(a.y1,b.y1);a.x2=Math.max(a.x2,b.x2);
a.y2=Math.max(a.y2,b.y2);return a},m(a[0]))};return a}(),H=function(a){function d(d,e){var f=a.call(this,d.chart,e)||this;f.id=e.id;f.mapView=d;f.options=m(c,e);f.allBounds=[];f.options.geoBounds&&(d=d.projection.path(f.options.geoBounds),f.geoBoundsProjectedBox=b(d),f.geoBoundsProjectedPolygon=d.map(function(a){return[a[1]||0,a[2]||0]}));return f}g(d,a);d.prototype.getField=function(b){void 0===b&&(b=!0);var c=this.hitZone;if(c){var d=b?this.padding:[0,0,0,0];c=c.coordinates[0];var e=c.map(function(a){return a[0]}),
f=c.map(function(a){return a[1]});c=Math.min.apply(0,e)+d[3];e=Math.max.apply(0,e)-d[1];var g=Math.min.apply(0,f)+d[0];d=Math.max.apply(0,f)-d[2];if(G(c)&&G(g))return{x:c,y:g,width:e-c,height:d-g}}return a.prototype.getField.call(this,b)};d.prototype.getHitZone=function(){var a=this.chart,b=this.mapView,c=this.options,d=(c.field||{}).coordinates;if(d){d=d[0];if("percent"===c.units){var e="mapBoundingBox"===c.relativeTo&&b.getMapBBox()||m(a.plotBox,{x:0,y:0});d=d.map(function(a){return[r("".concat(a[0],
"%"),e.width,e.x),r("".concat(a[1],"%"),e.height,e.y)]})}return{type:"Polygon",coordinates:[d]}}};d.prototype.getProjectedBounds=function(){return A.compositeBounds(this.allBounds)};d.prototype.isInside=function(a){var b=this.geoBoundsProjectedBox,c=this.geoBoundsProjectedPolygon;return!!(b&&a.x>=b.x1&&a.x<=b.x2&&a.y>=b.y1&&a.y<=b.y2&&c&&k(a,c))};d.prototype.render=function(){var a=this.chart,b=this.mapView,c=this.options,d=c.borderPath||c.field;if(d&&b.group){var e=!0;this.border||(this.border=a.renderer.path().addClass("highcharts-mapview-inset-border").add(b.group),
e=!1);a.styledMode||this.border.attr({stroke:c.borderColor,"stroke-width":c.borderWidth});var f=Math.round(this.border.strokeWidth())%2/2,g="mapBoundingBox"===c.relativeTo&&b.getMapBBox()||b.playingField;b=(d.coordinates||[]).reduce(function(b,d){return d.reduce(function(b,d,e){var m=d[0];d=d[1];"percent"===c.units&&(m=a.plotLeft+r("".concat(m,"%"),g.width,g.x),d=a.plotTop+r("".concat(d,"%"),g.height,g.y));m=Math.floor(m)+f;d=Math.floor(d)+f;b.push(0===e?["M",m,d]:["L",m,d]);return b},b)},[]);this.border[e?
"animate":"attr"]({d:b})}};d.prototype.destroy=function(){this.border&&(this.border=this.border.destroy());this.eventsToUnbind.forEach(function(a){return a()})};d.prototype.setUpEvents=function(){};return d}(A);D(a,"afterInit",function(){this.mapView=new A(this,this.options.mapView)});return A});t(e,"Series/Map/MapSeries.js",[e["Core/Animation/AnimationUtilities.js"],e["Series/ColorMapComposition.js"],e["Series/CenteredUtilities.js"],e["Core/Globals.js"],e["Core/Legend/LegendSymbol.js"],e["Core/Chart/MapChart.js"],
e["Series/Map/MapPoint.js"],e["Maps/MapView.js"],e["Core/Series/Series.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Renderer/SVG/SVGRenderer.js"],e["Core/Utilities.js"]],function(e,c,l,a,f,d,h,t,n,u,w,b){var g=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=
b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),D=e.animObject;e=a.noop;var E=d.splitPath;d=u.seriesTypes;var L=d.column,F=d.scatter;d=b.extend;var G=b.find,N=b.fireEvent,x=b.getNestedProperty,m=b.isArray,p=b.defined,r=b.isNumber,J=b.isObject,A=b.merge,H=b.objectEach,I=b.pick,q=b.splat;b=function(b){function c(){var a=null!==b&&b.apply(this,arguments)||
this;a.chart=void 0;a.data=void 0;a.group=void 0;a.joinBy=void 0;a.options=void 0;a.points=void 0;a.processedData=[];return a}g(c,b);c.prototype.animate=function(a){var b=this.chart,c=this.group,d=D(this.options.animation);a?c.attr({translateX:b.plotLeft+b.plotWidth/2,translateY:b.plotTop+b.plotHeight/2,scaleX:.001,scaleY:.001}):c.animate({translateX:b.plotLeft,translateY:b.plotTop,scaleX:1,scaleY:1},d)};c.prototype.clearBounds=function(){this.points.forEach(function(a){delete a.bounds;delete a.insetIndex;
delete a.projectedPath});delete this.bounds};c.prototype.doFullTranslate=function(){return!(!this.isDirtyData&&!this.chart.isResizing&&this.hasRendered)};c.prototype.drawMapDataLabels=function(){n.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};c.prototype.drawPoints=function(){var a=this,b=this,c=this.chart,d=this.group,e=this.transformGroups,f=void 0===e?[]:e,g=c.mapView,m=c.renderer;g&&(this.transformGroups=f,f[0]||(f[0]=m.g().add(d)),g.insets.forEach(function(a,
b){f[b+1]||f.push(m.g().add(d))}),this.doFullTranslate()&&(this.points.forEach(function(b){var d=b.graphic,e=b.shapeArgs;b.group=f["number"===typeof b.insetIndex?b.insetIndex+1:0];d&&d.parentGroup!==b.group&&d.add(b.group);e&&c.hasRendered&&!c.styledMode&&(e.fill=a.pointAttribs(b,b.state).fill)}),L.prototype.drawPoints.apply(this),this.points.forEach(function(d){var e=d.graphic;if(e){var f=e.animate,g="";d.name&&(g+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&
(g+=" highcharts-key-"+d.properties["hc-key"].toString().toLowerCase());g&&e.addClass(g);c.styledMode&&e.css(a.pointAttribs(d,d.selected&&"select"||void 0));e.animate=function(a,d,g){var m=r(a["stroke-width"])&&!r(e["stroke-width"]),h=r(e["stroke-width"])&&!r(a["stroke-width"]);if(m||h){var k=I(b.getStrokeWidth(b.options),1)/(c.mapView&&c.mapView.getScale()||1);m&&(e["stroke-width"]=k);h&&(a["stroke-width"]=k)}return f.call(e,a,d,h?function(){e.element.removeAttribute("stroke-width");delete e["stroke-width"];
g&&g.apply(this,arguments)}:g)}}})),f.forEach(function(d,e){var f=(0===e?g:g.insets[e-1]).getSVGTransform(),h=I(a.getStrokeWidth(a.options),1),k=f.scaleX,p=0<f.scaleY?1:-1,l=function(c){(b.points||[]).forEach(function(b){var d=b.graphic,e;d&&d["stroke-width"]&&(e=a.getStrokeWidth(b.options))&&d.attr({"stroke-width":e/c})})};if(m.globalAnimation&&c.hasRendered&&g.allowTransformAnimation){var r=Number(d.attr("translateX")),v=Number(d.attr("translateY")),q=Number(d.attr("scaleX")),C=function(a,b){a=
q+(k-q)*b.pos;d.attr({translateX:r+(f.translateX-r)*b.pos,translateY:v+(f.translateY-v)*b.pos,scaleX:a,scaleY:a*p,"stroke-width":h/a});l(a)};e={};c.options.chart&&(e=A({},c.options.chart.animation));if("boolean"!==typeof e){var y=e.step;e.step=function(a){y&&y.apply(this,arguments);C.apply(this,arguments)}}d.attr({animator:0}).animate({animator:1},e,function(){"boolean"!==typeof m.globalAnimation&&m.globalAnimation.complete&&m.globalAnimation.complete({applyDrilldown:!0})})}else d.attr(A(f,{"stroke-width":h/
k})),l(k)}),this.isDrilling||this.drawMapDataLabels())};c.prototype.getProjectedBounds=function(){if(!this.bounds&&this.chart.mapView){var a=this.chart.mapView,b=a.insets,c=a.projection,d=[];(this.points||[]).forEach(function(a){if(a.path||a.geometry){"string"===typeof a.path?a.path=E(a.path):m(a.path)&&"M"===a.path[0]&&(a.path=w.prototype.pathToSegments(a.path));if(!a.bounds){var e=a.getProjectedBounds(c);if(e){a.labelrank=I(a.labelrank,(e.x2-e.x1)*(e.y2-e.y1));var f=e.midX,g=e.midY;if(b&&r(f)&&
r(g)){var h=G(b,function(a){return a.isInside({x:f,y:g})});h&&(delete a.projectedPath,(e=a.getProjectedBounds(h.projection))&&h.allBounds.push(e),a.insetIndex=b.indexOf(h))}a.bounds=e}}a.bounds&&void 0===a.insetIndex&&d.push(a.bounds)}});this.bounds=t.compositeBounds(d)}return this.bounds};c.prototype.getStrokeWidth=function(a){var b=this.pointAttrToOptions;return a[b&&b["stroke-width"]||"borderWidth"]};c.prototype.hasData=function(){return!!this.processedXData.length};c.prototype.pointAttribs=function(a,
b){var c,d=a.series.chart,e=d.mapView;d=d.styledMode?this.colorAttribs(a):L.prototype.pointAttribs.call(this,a,b);var f=this.getStrokeWidth(a.options);if(b){b=A(this.options.states[b],a.options.states&&a.options.states[b]||{});var g=this.getStrokeWidth(b);p(g)&&(f=g);d.stroke=null!==(c=b.borderColor)&&void 0!==c?c:a.color}f&&e&&(f/=e.getScale());c=this.getStrokeWidth(this.options);d.dashstyle&&e&&r(c)&&(f=c/e.getScale());a.visible||(d.fill=this.options.nullColor);p(f)?d["stroke-width"]=f:delete d["stroke-width"];
d["stroke-linecap"]=d["stroke-linejoin"]=this.options.linecap;return d};c.prototype.updateData=function(){return this.processedData?!1:b.prototype.updateData.apply(this,arguments)};c.prototype.setData=function(a,c,d,e){void 0===c&&(c=!0);delete this.bounds;b.prototype.setData.call(this,a,!1,void 0,e);this.processData();this.generatePoints();c&&this.chart.redraw(d)};c.prototype.processData=function(){var b=this.options,c=b.data,d=this.chart.options.chart,e=this.joinBy,f=b.keys||this.pointArrayMap,
g=[],k={},p=this.chart.mapView;p=p&&(J(b.mapData,!0)?p.getGeoMap(b.mapData):p.geoMap);var l=this.chart.mapTransforms;(this.chart.mapTransforms=l=d.mapTransforms||p&&p["hc-transform"]||l)&&H(l,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(m(b.mapData))var q=b.mapData;else p&&"FeatureCollection"===p.type&&(this.mapTitle=p.title,q=a.geojson(p,this.type,this));var n=this.processedData=[];c&&c.forEach(function(a,d){var g=0;if(r(a))n[d]={value:a};else if(m(a)){n[d]=
{};!b.keys&&a.length>f.length&&"string"===typeof a[0]&&(n[d]["hc-key"]=a[0],++g);for(var k=0;k<f.length;++k,++g)f[k]&&"undefined"!==typeof a[g]&&(0<f[k].indexOf(".")?h.prototype.setNestedProperty(n[d],a[g],f[k]):n[d][f[k]]=a[g])}else n[d]=c[d];e&&"_i"===e[0]&&(n[d]._i=d)});if(q){this.mapData=q;this.mapMap={};for(l=0;l<q.length;l++)d=q[l],p=d.properties,d._i=l,e[0]&&p&&p[e[0]]&&(d[e[0]]=p[e[0]]),k[d[e[0]]]=d;this.mapMap=k;if(e[1]){var I=e[1];n.forEach(function(a){a=x(I,a);k[a]&&g.push(k[a])})}if(b.allAreas){if(e[1]){var z=
e[1];n.forEach(function(a){g.push(x(z,a))})}var t="|"+g.map(function(a){return a&&a[e[0]]}).join("|")+"|";q.forEach(function(a){e[0]&&-1!==t.indexOf("|"+a[e[0]]+"|")||n.push(A(a,{value:null}))})}}this.processedXData=Array(n.length)};c.prototype.setOptions=function(a){a=n.prototype.setOptions.call(this,a);var b=a.joinBy;null===b&&(b="_i");b=this.joinBy=q(b);b[1]||(b[1]=b[0]);return a};c.prototype.translate=function(){var a=this.doFullTranslate(),b=this.chart.mapView,c=b&&b.projection;!this.chart.hasRendered||
!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints(),delete this.bounds,!b||b.userOptions.center||r(b.userOptions.zoom)||b.zoom!==b.minZoom?this.getProjectedBounds():b.fitToBounds(void 0,void 0,!1));if(b){var d=b.getSVGTransform();this.points.forEach(function(e){var f=r(e.insetIndex)&&b.insets[e.insetIndex].getSVGTransform()||d;f&&e.bounds&&r(e.bounds.midX)&&r(e.bounds.midY)&&(e.plotX=e.bounds.midX*f.scaleX+f.translateX,e.plotY=e.bounds.midY*f.scaleY+f.translateY);a&&(e.shapeType=
"path",e.shapeArgs={d:h.getProjectedPath(e,c)});e.projectedPath&&!e.projectedPath.length?e.setVisible(!1):e.setVisible(!0)})}N(this,"afterTranslate")};c.defaultOptions=A(F.defaultOptions,{affectsMapView:!0,animation:!1,dataLabels:{crop:!1,formatter:function(){var a=this.series.chart.numberFormatter,b=this.point.value;return r(b)?a(b,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},linecap:"round",marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},
turboThreshold:0,allAreas:!0,borderColor:"#e6e6e6",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:void 0,borderColor:"#666666",borderWidth:2},normal:{animation:!0},select:{color:"#cccccc"}}});return c}(F);d(b.prototype,{type:"map",axisTypes:c.seriesMembers.axisTypes,colorAttribs:c.seriesMembers.colorAttribs,colorKey:c.seriesMembers.colorKey,directTouch:!0,drawDataLabels:e,drawGraph:e,drawLegendSymbol:f.drawRectangle,forceDL:!0,getCenter:l.getCenter,getExtremesFromAll:!0,getSymbol:e,isCartesian:!1,
parallelArrays:c.seriesMembers.parallelArrays,pointArrayMap:c.seriesMembers.pointArrayMap,pointClass:h,preserveAspectRatio:!0,searchPoint:e,trackerGroups:c.seriesMembers.trackerGroups,useMapGeometry:!0});c.compose(b);u.registerSeriesType("map",b);"";return b});t(e,"Series/FlowMap/FlowMapSeries.js",[e["Series/FlowMap/FlowMapPoint.js"],e["Series/Map/MapSeries.js"],e["Core/Series/SeriesRegistry.js"],e["Core/Utilities.js"]],function(e,c,l,a){var f=this&&this.__extends||function(){var a=function(b,c){a=
Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};return a(b,c)};return function(b,c){function d(){this.constructor=b}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),d=this&&this.__spreadArray||function(a,b,c){if(c||2===arguments.length)for(var d=
0,e=b.length,f;d<e;d++)!f&&d in b||(f||(f=Array.prototype.slice.call(b,0,d)),f[d]=b[d]);return a.concat(f||Array.prototype.slice.call(b))},g=l.series.prototype.pointClass,t=l.seriesTypes,n=t.column,u=t.mapline,w=a.addEvent,b=a.arrayMax,k=a.arrayMin,D=a.defined;t=a.extend;var E=a.isArray,L=a.merge,F=a.pick,G=a.relativeLength;a=function(a){function e(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;b.smallestWeight=void 0;b.greatestWeight=void 0;b.centerOfPoints=
void 0;return b}f(e,a);e.getLength=function(a,b){return Math.sqrt(a*a+b*b)};e.normalize=function(a,b){var c=this.getLength(a,b);return[a/c,b/c]};e.markerEndPath=function(a,b,c,d){var e=G(d.width||0,this.getLength(b[0]-a[0],b[1]-a[1])),f=d.markerType||"arrow",g=this.normalize(b[0]-a[0],b[1]-a[1]);d=g[0];g=g[1];var h=[];if("arrow"===f){var k=a[0],m=a[1];h.push(["L",k-d*e,m-g*e]);h.push(["L",c[0],c[1]]);k=b[0];m=b[1];h.push(["L",k+d*e,m+g*e])}if("mushroom"===f){f=a[0];a=a[1];k=b[0];b=b[1];var l=(k-f)/
2+f;m=(b-a)/2+a;l=2*(c[0]-l)+l;c=2*(c[1]-m)+m;h.push(["L",f-d*e,a-g*e]);h.push(["Q",l,c,k+d*e,b+g*e])}return h};e.prototype.animate=function(a){var b=this.points;a||b.forEach(function(a){if(a.shapeArgs&&E(a.shapeArgs.d)&&a.shapeArgs.d.length){var b=a.shapeArgs.d,c=b[0][1],e=b[0][2];if(c&&e){for(var f=[],g=0;g<b.length;g++){f.push(d([],b[g],!0));for(var h=1;h<b[g].length;h++)f[g][h]=h%2?c:e}a.graphic&&(a.graphic.attr({d:f}),a.graphic.animate({d:b}))}}})};e.prototype.getLinkWidth=function(a){var b=
this.options.width,c=a.options.weight||this.options.weight;a.options.weight=c;if(b&&!c)return b;a=this.smallestWeight;b=this.greatestWeight;if(!D(c)||!a||!b)return 0;var d=this.options.minWidth;return(c-a)*(this.options.maxWidth-d)/(b-a||1)+d};e.prototype.autoCurve=function(a,b,c,d,e,f){var g=c-a,h=d-b;a=(c-a)/2+a-e;b=(d-b)/2+b-f;g=Math.atan2(g*b-h*a,g*a+h*b);g=180*g/Math.PI;0>g&&(g=360+g);g=g*Math.PI/180;return.7*-Math.sin(g)};e.prototype.pointAttribs=function(a,b){b=c.prototype.pointAttribs.call(this,
a,b);b.fill=F(a.options.fillColor,a.options.color,"none"===this.options.fillColor?null:this.options.fillColor,this.color);b["fill-opacity"]=F(a.options.fillOpacity,this.options.fillOpacity);b["stroke-width"]=F(a.options.lineWidth,this.options.lineWidth,1);a.options.opacity&&(b.opacity=a.options.opacity);return b};e.prototype.translate=function(){var a=this;!this.chart.hasRendered||!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints());var c=[],d=0,e=0;this.points.forEach(function(b){var f=
a.chart,h=f.mapView,k=b.options,l=function(){b.series.isDirty=!0},m=function(a){a=f.get(a);if(a instanceof g&&a.plotX&&a.plotY)return w(a,"update",l),{x:a.plotX,y:a.plotY}},p=function(a){return E(a)?{lon:a[0],lat:a[1]}:a},n,r;"string"===typeof k.from?n=m(k.from):"object"===typeof k.from&&h&&(n=h.lonLatToPixels(p(k.from)));"string"===typeof k.to?r=m(k.to):"object"===typeof k.to&&h&&(r=h.lonLatToPixels(p(k.to)));b.fromPos=n;b.toPos=r;n&&r&&(d+=(n.x+r.x)/2,e+=(n.y+r.y)/2);F(b.options.weight,a.options.weight)&&
c.push(F(b.options.weight,a.options.weight))});this.smallestWeight=k(c);this.greatestWeight=b(c);this.centerOfPoints={x:d/this.points.length,y:e/this.points.length};this.points.forEach(function(b){a.getLinkWidth(b)?(b.fromPos&&(b.plotX=b.fromPos.x,b.plotY=b.fromPos.y),b.shapeType="path",b.shapeArgs=a.getPointShapeArgs(b),b.color=F(b.options.color,b.series.color)):b.shapeArgs={d:[]}})};e.prototype.getPointShapeArgs=function(a){var b,c=a.fromPos,f=a.toPos;if(!c||!f)return{};var g=this.getLinkWidth(a)/
2,h=a.options,k=L(this.options.markerEnd,h.markerEnd),l=F(h.growTowards,this.options.growTowards),m=c.x||0,n=c.y||0;c=f.x||0;var t=f.y||0;h=F(h.curveFactor,this.options.curveFactor);var v=k&&k.enabled&&k.height||0;D(h)||(h=this.autoCurve(m,n,c,t,this.centerOfPoints.x,this.centerOfPoints.y));if(v){v=G(v,4*g);var u=.5*(c-m);var B=.5*(t-n);var y=m+u;B=e.normalize(y+B*h-c,n+B+-u*h-t);y=B[1];c+=B[0]*v;t+=y*v}u=.5*(c-m);var w=.5*(t-n);var x=m+u,K=n+w;y=u;u=w;w=-y;B=e.normalize(u,w);v=B[0];B=B[1];y=1+.25*
Math.sqrt(h*h);v*=g*y;B*=g*y;u=x+u*h;h=K+w*h;y=e.normalize(u-m,h-n);w=y[0];x=y[1];y=w;w=x*g;x=-y*g;y=e.normalize(u-c,h-t);K=y[0];var E=y[1];y=K;K=-E*g;E=y*g;l&&(w/=g,x/=g,v/=4,B/=4);g={d:[["M",m-w,n-x],["Q",u-v,h-B,c-K,t-E],["L",c+K,t+E],["Q",u+v,h+B,m+w,n+x],["Z"]]};k&&k.enabled&&g.d&&(f=e.markerEndPath([c-K,t-E],[c+K,t+E],[f.x,f.y],k),(b=g.d).splice.apply(b,d([2,0],f,!1)));k=a.options.from;f=a.options.to;b=k.lat;k=k.lon;l=f.lat;f=f.lon;b&&k&&(a.options.from="".concat(+b,", ").concat(+k));l&&f&&
(a.options.to="".concat(+l,", ").concat(+f));return g};e.defaultOptions=L(u.defaultOptions,{animation:!0,dataLabels:{enabled:!1},fillOpacity:.5,markerEnd:{enabled:!0,height:"40%",width:"40%",markerType:"arrow"},width:1,maxWidth:25,minWidth:5,lineWidth:void 0,tooltip:{headerFormat:'<span style="font-size: 0.8em">{series.name}</span><br/>',pointFormat:"{point.options.from} \u2192 {point.options.to}: <b>{point.options.weight}</b>"}});return e}(u);t(a.prototype,{pointClass:e,pointArrayMap:["from","to",
"weight"],drawPoints:n.prototype.drawPoints,useMapGeometry:!0});l.registerSeriesType("flowmap",a);"";return a});t(e,"masters/modules/flowmap.src.js",[],function(){})});
//# sourceMappingURL=flowmap.js.map