/*
 Highcharts JS v11.0.0 (2023-04-26)

 (c) 2014-2021 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+c++,d)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,b={next:function(){if(d<a.length){var f=d++;return{value:c(f,a[f]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
var $jscomp$lookupPolyfilledValue=function(a,c){var d=$jscomp.propertyToPolyfillSymbol[c];if(null==d)return a[c];d=a[d];return void 0!==d?d:a[c]};$jscomp.polyfill=function(a,c,d,b){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,d,b):$jscomp.polyfillUnisolated(a,c,d,b))};
$jscomp.polyfillUnisolated=function(a,c,d,b){d=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var f=a[b];f in d||(d[f]={});d=d[f]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,d,b){var f=a.split(".");a=1===f.length;b=f[0];b=!a&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<f.length-1;h++){var u=f[h];u in b||(b[u]={});b=b[u]}f=f[f.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?b[f]:null;c=c(d);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:c}):c!==d&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=$jscomp.propertyToPolyfillSymbol[f],
$jscomp.defineProperty(b,f,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,d){return d})}},"es8","es3");
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,b,f,h){a.hasOwnProperty(b)||(a[b]=h.apply(null,f),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:b,module:a[b]}})))}a=a?a._modules:{};c(a,
"Series/ColorMapComposition.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b){var f=a.seriesTypes.column.prototype,d=b.addEvent,c=b.defined,m;(function(a){function h(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})}var m=[];a.pointMembers={dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value&&(void 0===this.value||!isNaN(this.value))}};a.seriesMembers=
{colorKey:"value",axisTypes:["xAxis","yAxis","colorAxis"],parallelArrays:["x","y","value"],pointArrayMap:["value"],trackerGroups:["group","markerGroup","dataLabelsGroup"],colorAttribs:function(a){var e={};!c(a.color)||a.state&&"normal"!==a.state||(e[this.colorProp||"fill"]=a.color);return e},pointAttribs:f.pointAttribs};a.compose=function(a){var e=a.prototype.pointClass;b.pushUnique(m,e)&&d(e,"afterSetState",h);return a}})(m||(m={}));return m});c(a,"Series/Treemap/TreemapAlgorithmGroup.js",[],function(){return function(){function a(a,
f,d,c){this.height=a;this.width=f;this.plot=c;this.startDirection=this.direction=d;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,b){return Math.max(a/b,b/a)}}}a.prototype.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/
this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};a.prototype.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0};return a}()});c(a,"Series/DrawPointUtilities.js",[a["Core/Utilities.js"]],function(a){var b=this&&this.__assign||function(){b=Object.assign||
function(a){for(var b,f=1,d=arguments.length;f<d;f++){b=arguments[f];for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])}return a};return b.apply(this,arguments)};return{draw:function(a,d){var f=d.animatableAttribs,c=d.onComplete,h=d.css,k=d.renderer,p=a.series&&a.series.chart.hasRendered?void 0:a.series&&a.series.options.animation,e=a.graphic;d.attribs=b(b({},d.attribs),{"class":a.getClassName()})||{};if(a.shouldDraw())e||(a.graphic=e="text"===d.shapeType?k.text():k[d.shapeType](d.shapeArgs||
{}),e.add(d.group)),h&&e.css(h),e.attr(d.attribs).animate(f,d.isNew?!1:p,c);else if(e){var n=function(){a.graphic=e=e&&e.destroy();"function"===typeof c&&c()};Object.keys(f).length?e.animate(f,void 0,function(){return n()}):n()}}}});c(a,"Series/Treemap/TreemapPoint.js",[a["Series/DrawPointUtilities.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b,f){var d=this&&this.__extends||function(){var a=function(e,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,
e){a.__proto__=e}||function(a,e){for(var b in e)Object.prototype.hasOwnProperty.call(e,b)&&(a[b]=e[b])};return a(e,b)};return function(e,b){function d(){this.constructor=e}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");a(e,b);e.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}(),c=b.series.prototype.pointClass,m=b.seriesTypes;b=m.pie.prototype.pointClass;var l=f.extend,k=f.isNumber,p=f.pick;f=function(e){function b(){var a=
null!==e&&e.apply(this,arguments)||this;a.name=void 0;a.node=void 0;a.options=void 0;a.series=void 0;a.shapeType="rect";a.value=void 0;return a}d(b,e);b.prototype.draw=function(b){a.draw(this,b)};b.prototype.getClassName=function(){var a=c.prototype.getClassName.call(this),b=this.series,e=b.options;this.node.level<=b.nodeMap[b.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||p(e.interactByLeaf,!e.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";
return a};b.prototype.isValid=function(){return!(!this.id&&!k(this.value))};b.prototype.setState=function(a){c.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})};b.prototype.shouldDraw=function(){return k(this.plotY)&&null!==this.y};return b}(m.scatter.prototype.pointClass);l(f.prototype,{setVisible:b.prototype.setVisible});return f});c(a,"Series/Treemap/TreemapUtilities.js",[a["Core/Utilities.js"]],function(a){var b=a.objectEach,d;(function(a){function d(a,
b,c){void 0===c&&(c=this);a=b.call(c,a);!1!==a&&d(a,b,c)}a.AXIS_MAX=100;a.isBoolean=function(a){return"boolean"===typeof a};a.eachObject=function(a,d,c){c=c||this;b(a,function(b,e){d.call(c,b,e,a)})};a.recursive=d})(d||(d={}));return d});c(a,"Series/TreeUtilities.js",[a["Core/Color/Color.js"],a["Core/Utilities.js"]],function(a,b){function d(a,b){var e=b.before,f=b.idRoot,n=b.mapIdToNode[f],h=b.points[a.i],k=h&&h.options||{},A=[],m=0;a.levelDynamic=a.level-(!1!==b.levelIsConstant?0:n.level);a.name=
p(h&&h.name,"");a.visible=f===a.id||!0===b.visible;"function"===typeof e&&(a=e(a,b));a.children.forEach(function(e,f){var v=c({},b);c(v,{index:f,siblings:a.children.length,visible:a.visible});e=d(e,v);A.push(e);e.visible&&(m+=e.val)});e=p(k.value,m);a.visible=0<=e&&(0<m||a.visible);a.children=A;a.childrenTotal=m;a.isLeaf=a.visible&&!m;a.val=e;return a}var c=b.extend,u=b.isArray,m=b.isNumber,l=b.isObject,k=b.merge,p=b.pick;return{getColor:function(b,d){var c=d.index,e=d.mapOptionsToLevel,f=d.parentColor,
h=d.parentColorIndex,n=d.series,k=d.colors,m=d.siblings,l=n.points,G=n.chart.options.chart,v;if(b){l=l[b.i];b=e[b.level]||{};if(e=l&&b.colorByPoint){var w=l.index%(k?k.length:G.colorCount);var L=k&&k[w]}if(!n.chart.styledMode){k=l&&l.options.color;G=b&&b.color;if(v=f)v=(v=b&&b.colorVariation)&&"brightness"===v.key&&c&&m?a.parse(f).brighten(c/m*v.to).get():f;v=p(k,G,L,v,n.color)}var B=p(l&&l.options.colorIndex,b&&b.colorIndex,w,h,d.colorIndex)}return{color:v,colorIndex:B}},getLevelOptions:function(a){var b=
{};if(l(a)){var d=m(a.from)?a.from:1;var c=a.levels;var f={};var e=l(a.defaults)?a.defaults:{};u(c)&&(f=c.reduce(function(a,b){if(l(b)&&m(b.level)){var c=k({},b);var f=p(c.levelIsConstant,e.levelIsConstant);delete c.levelIsConstant;delete c.level;b=b.level+(f?0:d-1);l(a[b])?k(!0,a[b],c):a[b]=c}return a},{}));c=m(a.to)?a.to:1;for(a=0;a<=c;a++)b[a]=k({},e,l(f[a])?f[a]:{})}return b},setTreeValues:d,updateRootId:function(a){if(l(a)){var b=l(a.options)?a.options:{};b=p(a.rootNode,b.rootId,"");l(a.userOptions)&&
(a.userOptions.rootId=b);a.rootNode=b}return b}}});c(a,"Extensions/Breadcrumbs/BreadcrumbsDefaults.js",[],function(){return{lang:{mainBreadcrumb:"Main"},options:{buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},style:{color:"#334eff"}},buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",rtl:!1,position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666",fontSize:"0.8em"}},showFullPath:!0,style:{},
useHTML:!1,zIndex:7}}});c(a,"Extensions/Breadcrumbs/Breadcrumbs.js",[a["Extensions/Breadcrumbs/BreadcrumbsDefaults.js"],a["Core/Chart/Chart.js"],a["Core/FormatUtilities.js"],a["Core/Utilities.js"]],function(a,b,c,h){function d(){if(this.breadcrumbs){var a=this.resetZoomButton&&this.resetZoomButton.getBBox(),b=this.breadcrumbs.options;a&&"right"===b.position.align&&"plotBox"===b.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-a.width-b.buttonSpacing)}}function f(){this.breadcrumbs&&(this.breadcrumbs.destroy(),
this.breadcrumbs=void 0)}function l(){var a=this.breadcrumbs;if(a&&!a.options.floating&&a.level){var b=a.options,d=b.buttonTheme;d=(d.height||0)+2*(d.padding||0)+b.buttonSpacing;b=b.position.verticalAlign;"bottom"===b?(this.marginBottom=(this.marginBottom||0)+d,a.yOffset=d):"middle"!==b?(this.plotTop+=d,a.yOffset=-d):a.yOffset=void 0}}function k(){this.breadcrumbs&&this.breadcrumbs.redraw()}function p(a){!0===a.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}var e=c.format,
n=h.addEvent,K=h.defined,Q=h.extend,R=h.fireEvent,y=h.isString,D=h.merge,A=h.objectEach,E=h.pick,I=[];c=function(){function c(a,b){this.elementList={};this.isDirty=!0;this.level=0;this.list=[];b=D(a.options.drilldown&&a.options.drilldown.drillUpButton,c.defaultOptions,a.options.navigation&&a.options.navigation.breadcrumbs,b);this.chart=a;this.options=b||{}}c.compose=function(c,w){h.pushUnique(I,c)&&(n(b,"destroy",f),n(b,"afterShowResetZoom",d),n(b,"getMargins",l),n(b,"redraw",k),n(b,"selection",p));
h.pushUnique(I,w)&&Q(w.lang,a.lang)};c.prototype.updateProperties=function(a){this.setList(a);this.setLevel();this.isDirty=!0};c.prototype.setList=function(a){this.list=a};c.prototype.setLevel=function(){this.level=this.list.length&&this.list.length-1};c.prototype.getLevel=function(){return this.level};c.prototype.getButtonText=function(a){var b=this.chart,c=this.options,d=b.options.lang,f=E(c.format,c.showFullPath?"{level.name}":"\u2190 {level.name}");d=d&&E(d.drillUpText,d.mainBreadcrumb);a=c.formatter&&
c.formatter(a)||e(f,{level:a.levelOptions},b)||"";(y(a)&&!a.length||"\u2190 "===a)&&K(d)&&(a=c.showFullPath?d:"\u2190 "+d);return a};c.prototype.redraw=function(){this.isDirty&&this.render();this.group&&this.group.align();this.isDirty=!1};c.prototype.render=function(){var a=this.chart,b=this.options;!this.group&&b&&(this.group=a.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:b.zIndex}).add());b.showFullPath?this.renderFullPathButtons():this.renderSingleButton();
this.alignBreadcrumbsGroup()};c.prototype.renderFullPathButtons=function(){this.destroySingleButton();this.resetElementListState();this.updateListElements();this.destroyListElements()};c.prototype.renderSingleButton=function(){var a=this.chart,b=this.list,c=this.options.buttonSpacing;this.destroyListElements();var d=this.group?this.group.getBBox().width:c;b=b[b.length-2];!a.drillUpButton&&0<this.level?a.drillUpButton=this.renderButton(b,d,c):a.drillUpButton&&(0<this.level?this.updateSingleButton():
this.destroySingleButton())};c.prototype.alignBreadcrumbsGroup=function(a){if(this.group){var b=this.options,c=b.buttonTheme,d=b.position,f="chart"===b.relativeTo||"spacingBox"===b.relativeTo?void 0:"scrollablePlotBox",e=this.group.getBBox();b=2*(c.padding||0)+b.buttonSpacing;d.width=e.width+b;d.height=e.height+b;e=D(d);a&&(e.x+=a);this.options.rtl&&(e.x+=d.width);e.y=E(e.y,this.yOffset,0);this.group.align(e,!0,f)}};c.prototype.renderButton=function(a,b,c){var d=this,f=this.chart,e=d.options,k=D(e.buttonTheme);
b=f.renderer.button(d.getButtonText(a),b,c,function(b){var c=e.events&&e.events.click,f;c&&(f=c.call(d,b,a));!1!==f&&(b.newLevel=e.showFullPath?a.level:d.level-1,R(d,"up",b))},k).addClass("highcharts-breadcrumbs-button").add(d.group);f.styledMode||b.attr(e.style);return b};c.prototype.renderSeparator=function(a,b){var c=this.chart,d=this.options.separator;a=c.renderer.label(d.text,a,b,void 0,void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);c.styledMode||a.css(d.style);
return a};c.prototype.update=function(a){D(!0,this.options,a);this.destroy();this.isDirty=!0};c.prototype.updateSingleButton=function(){var a=this.chart,b=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(b)})};c.prototype.destroy=function(){this.destroySingleButton();this.destroyListElements(!0);this.group&&this.group.destroy();this.group=void 0};c.prototype.destroyListElements=function(a){var b=this.elementList;A(b,function(c,d){if(a||!b[d].updated)c=b[d],c.button&&
c.button.destroy(),c.separator&&c.separator.destroy(),delete c.button,delete c.separator,delete b[d]});a&&(this.elementList={})};c.prototype.destroySingleButton=function(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)};c.prototype.resetElementListState=function(){A(this.elementList,function(a){a.updated=!1})};c.prototype.updateListElements=function(){for(var a=this.elementList,b=this.options.buttonSpacing,c=this.list,d=this.options.rtl,f=d?-1:1,e=function(a,
b){return f*a.getBBox().width+f*b},k=function(a,b,c){a.translate(b-a.getBBox().width,c)},h=this.group?e(this.group,b):b,l,m,n=0,p=c.length;n<p;++n){var u=n===p-1,C=void 0;l=void 0;m=c[n];a[m.level]?(l=a[m.level],C=l.button,l.separator||u?l.separator&&u&&(l.separator.destroy(),delete l.separator):(h+=f*b,l.separator=this.renderSeparator(h,b),d&&k(l.separator,h,b),h+=e(l.separator,b)),a[m.level].updated=!0):(C=this.renderButton(m,h,b),d&&k(C,h,b),h+=e(C,b),u||(l=this.renderSeparator(h,b),d&&k(l,h,b),
h+=e(l,b)),a[m.level]={button:C,separator:l,updated:!0});C&&C.setState(u?2:0)}};c.defaultOptions=a.options;return c}();"";return c});c(a,"Series/Treemap/TreemapComposition.js",[a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapUtilities.js"],a["Core/Utilities.js"]],function(a,b,c){var d=c.addEvent,f=c.extend,m=!1;d(a.series,"afterBindAxes",function(){var a=this.xAxis,c=this.yAxis;if(a&&c)if(this.is("treemap")){var d={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,minPadding:0,max:b.AXIS_MAX,
maxPadding:0,startOnTick:!1,title:void 0,tickPositions:[]};f(c.options,d);f(a.options,d);m=!0}else m&&(c.setOptions(c.userOptions),a.setOptions(a.userOptions),m=!1)})});c(a,"Series/Treemap/TreemapNode.js",[],function(){return function(){function a(){this.childrenTotal=0;this.visible=!1}a.prototype.init=function(a,c,d,u,m,l,k){this.id=a;this.i=c;this.children=d;this.height=u;this.level=m;this.series=l;this.parent=k;return this};return a}()});c(a,"Series/Treemap/TreemapSeries.js",[a["Core/Color/Color.js"],
a["Series/ColorMapComposition.js"],a["Core/Globals.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapAlgorithmGroup.js"],a["Series/Treemap/TreemapPoint.js"],a["Series/Treemap/TreemapUtilities.js"],a["Series/TreeUtilities.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"],a["Core/Utilities.js"],a["Series/Treemap/TreemapNode.js"]],function(a,b,c,h,u,m,l,k,p,e,n,K){var d=this&&this.__extends||function(){var a=function(b,g){a=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(a,b){a.__proto__=b}||function(a,b){for(var g in b)Object.prototype.hasOwnProperty.call(b,g)&&(a[g]=b[g])};return a(b,g)};return function(b,g){function c(){this.constructor=b}if("function"!==typeof g&&null!==g)throw new TypeError("Class extends value "+String(g)+" is not a constructor or null");a(b,g);b.prototype=null===g?Object.create(g):(c.prototype=g.prototype,new c)}}(),f=a.parse;a=c.noop;var y=u.series;c=u.seriesTypes;var D=c.column,A=c.heatmap,E=c.scatter,I=p.getColor,G=p.getLevelOptions,
v=p.updateRootId,w=n.addEvent,L=n.correctFloat,B=n.defined,S=n.error,J=n.extend,T=n.fireEvent,O=n.isArray,U=n.isObject,M=n.isString,z=n.merge,x=n.pick,V=n.stableSort;p=function(a){function b(){var b=null!==a&&a.apply(this,arguments)||this;b.axisRatio=void 0;b.data=void 0;b.mapOptionsToLevel=void 0;b.nodeMap=void 0;b.nodeList=void 0;b.options=void 0;b.points=void 0;b.rootNode=void 0;b.tree=void 0;b.level=void 0;return b}d(b,a);b.prototype.algorithmCalcPoints=function(a,b,c,d){var g,q,r,e,f=c.lW,F=
c.lH,t=c.plot,h=0,l=c.elArr.length-1;if(b)f=c.nW,F=c.nH;else var k=c.elArr[c.elArr.length-1];c.elArr.forEach(function(a){if(b||h<l)0===c.direction?(g=t.x,q=t.y,r=f,e=a/r):(g=t.x,q=t.y,e=F,r=a/e),d.push({x:g,y:q,width:r,height:L(e)}),0===c.direction?t.y+=e:t.x+=r;h+=1});c.reset();0===c.direction?c.width-=f:c.height-=F;t.y=t.parent.y+(t.parent.height-c.height);t.x=t.parent.x+(t.parent.width-c.width);a&&(c.direction=1-c.direction);b||c.addElement(k)};b.prototype.algorithmFill=function(a,b,c){var g=[],
d,q=b.direction,r=b.x,e=b.y,f=b.width,h=b.height,t,l,k,m;c.forEach(function(c){d=c.val/b.val*b.height*b.width;t=r;l=e;0===q?(m=h,k=d/m,f-=k,r+=k):(k=f,m=d/k,h-=m,e+=m);g.push({x:t,y:l,width:k,height:m});a&&(q=1-q)});return g};b.prototype.algorithmLowAspectRatio=function(a,b,c){var g=[],d=this,q,e={x:b.x,y:b.y,parent:b},r=0,f=c.length-1,h=new m(b.height,b.width,b.direction,e);c.forEach(function(c){q=c.val/b.val*b.height*b.width;h.addElement(q);h.lP.nR>h.lP.lR&&d.algorithmCalcPoints(a,!1,h,g,e);r===
f&&d.algorithmCalcPoints(a,!0,h,g,e);r+=1});return g};b.prototype.alignDataLabel=function(a,b,c){var g=c.style;g&&!B(g.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:g.width+="px"});D.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})};b.prototype.calculateChildrenAreas=function(a,b){var c=this,g=c.options,d=c.mapOptionsToLevel[a.level+1],q=x(c[d&&d.layoutAlgorithm]&&d.layoutAlgorithm,g.layoutAlgorithm),
e=g.alternateStartingDirection,f=[];a=a.children.filter(function(a){return!a.ignore});d&&d.layoutStartingDirection&&(b.direction="vertical"===d.layoutStartingDirection?0:1);f=c[q](b,a);a.forEach(function(a,g){g=f[g];a.values=z(g,{val:a.childrenTotal,direction:e?1-b.direction:b.direction});a.pointValues=z(g,{x:g.x/c.axisRatio,y:k.AXIS_MAX-g.y-g.height,width:g.width/c.axisRatio});a.children.length&&c.calculateChildrenAreas(a,a.values)})};b.prototype.createList=function(a){var b=this.chart,c=[];if(b.breadcrumbs){var g=
0;c.push({level:g,levelOptions:b.series[0]});b=a.target.nodeMap[a.newRootId];for(var d=[];b.parent||""===b.parent;)d.push(b),b=a.target.nodeMap[b.parent];d.reverse().forEach(function(a){c.push({level:++g,levelOptions:a})});1>=c.length&&(c.length=0)}return c};b.prototype.drawDataLabels=function(){var a=this,b=a.mapOptionsToLevel,c,d;a.points.filter(function(a){return a.node.visible}).forEach(function(g){d=b[g.node.level];c={style:{}};g.node.isLeaf||(c.enabled=!1);d&&d.dataLabels&&(c=z(c,d.dataLabels),
a._hasPointLabels=!0);g.shapeArgs&&(c.style.width=g.shapeArgs.width,g.dataLabel&&g.dataLabel.css({width:g.shapeArgs.width+"px"}));g.dlOptions=z(c,g.options.dataLabels)});y.prototype.drawDataLabels.call(this)};b.prototype.drawPoints=function(a){void 0===a&&(a=this.points);var b=this,c=b.chart,g=c.renderer,d=c.styledMode,e=b.options,f=d?{}:e.shadow,h=e.borderRadius,k=c.pointCount<e.animationLimit,l=e.allowTraversingTree;a.forEach(function(a){var c=a.node.levelDynamic,q={},N={},r={},H="level-group-"+
a.node.level,P=!!a.graphic,m=k&&P,F=a.shapeArgs;a.shouldDraw()&&(a.isInside=!0,h&&(N.r=h),z(!0,m?q:N,P?F:{},d?{}:b.pointAttribs(a,a.selected?"select":void 0)),b.colorAttribs&&d&&J(r,b.colorAttribs(a)),b[H]||(b[H]=g.g(H).attr({zIndex:1E3-(c||0)}).add(b.group),b[H].survive=!0));a.draw({animatableAttribs:q,attribs:N,css:r,group:b[H],renderer:g,shadow:f,shapeArgs:F,shapeType:a.shapeType});l&&a.graphic&&(a.drillId=e.interactByLeaf?b.drillToByLeaf(a):b.drillToByGroup(a))})};b.prototype.drillToByGroup=function(a){var b=
!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b};b.prototype.drillToByLeaf=function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b};b.prototype.drillToNode=function(a,b){S(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)};b.prototype.drillUp=function(){var a=this.nodeMap[this.rootNode];a&&M(a.parent)&&this.setRootNode(a.parent,
!0,{trigger:"traverseUpButton"})};b.prototype.getExtremes=function(){var a=y.prototype.getExtremes.call(this,this.colorValueData),b=a.dataMax;this.valueMin=a.dataMin;this.valueMax=b;return y.prototype.getExtremes.call(this)};b.prototype.getListOfParents=function(a,b){a=O(a)?a:[];var c=O(b)?b:[];b=a.reduce(function(a,b,c){b=x(b.parent,"");"undefined"===typeof a[b]&&(a[b]=[]);a[b].push(c);return a},{"":[]});k.eachObject(b,function(a,b,g){""!==b&&-1===c.indexOf(b)&&(a.forEach(function(a){g[""].push(a)}),
delete g[b])});return b};b.prototype.getTree=function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap={};this.nodeList=[];return this.buildTree("",-1,0,a)};b.prototype.buildTree=function(a,b,c,d,e){var g=this,f=[],q=g.points[b],r=0,h;(d[a]||[]).forEach(function(b){h=g.buildTree(g.points[b].id,b,c+1,d,a);r=Math.max(h.height+1,r);f.push(h)});var k=(new g.NodeClass).init(a,b,f,r,c,g,e);f.forEach(function(a){a.parentNode=k});g.nodeMap[k.id]=k;g.nodeList.push(k);
q&&(q.node=k,k.point=q);return k};b.prototype.hasData=function(){return!!this.processedXData.length};b.prototype.init=function(a,b){var c=this,d=z(b.drillUpButton,b.breadcrumbs);var g=w(c,"setOptions",function(a){a=a.userOptions;B(a.allowDrillToNode)&&!B(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);B(a.drillUpButton)&&!B(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});y.prototype.init.call(c,a,b);delete c.opacity;c.eventsToUnbind.push(g);
c.options.allowTraversingTree&&(c.eventsToUnbind.push(w(c,"click",c.onClickDrillToNode)),c.eventsToUnbind.push(w(c,"setRootNode",function(a){var b=c.chart;b.breadcrumbs&&b.breadcrumbs.updateProperties(c.createList(a))})),c.eventsToUnbind.push(w(c,"update",function(a,b){(b=this.chart.breadcrumbs)&&a.options.breadcrumbs&&b.update(a.options.breadcrumbs)})),c.eventsToUnbind.push(w(c,"destroy",function(a){var b=this.chart;b.breadcrumbs&&(b.breadcrumbs.destroy(),a.keepEventsForUpdate||(b.breadcrumbs=void 0))})));
a.breadcrumbs||(a.breadcrumbs=new e(a,d));c.eventsToUnbind.push(w(a.breadcrumbs,"up",function(a){a=this.level-a.newLevel;for(var b=0;b<a;b++)c.drillUp()}))};b.prototype.onClickDrillToNode=function(a){var b=(a=a.point)&&a.drillId;M(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))};b.prototype.pointAttribs=function(a,b){var c=U(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{};c=this.options;var g=b&&c.states&&c.states[b]||{},e=a&&a.getClassName()||"";a={stroke:a&&
a.borderColor||d.borderColor||g.borderColor||c.borderColor,"stroke-width":x(a&&a.borderWidth,d.borderWidth,g.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||g.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==e.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==e.indexOf("highcharts-internal-node-interactive")?(b=x(g.opacity,c.opacity),a.fill=f(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==e.indexOf("highcharts-internal-node")?
a.fill="none":b&&(a.fill=f(a.fill).brighten(g.brightness).get());return a};b.prototype.setColorRecursive=function(a,b,c,d,e){var g=this,f=g&&g.chart;f=f&&f.options&&f.options.colors;if(a){var h=I(a,{colors:f,index:d,mapOptionsToLevel:g.mapOptionsToLevel,parentColor:b,parentColorIndex:c,series:g,siblings:e});if(b=g.points[a.i])b.color=h.color,b.colorIndex=h.colorIndex;(a.children||[]).forEach(function(b,c){g.setColorRecursive(b,h.color,h.colorIndex,c,a.children.length)})}};b.prototype.setPointValues=
function(){var a=this,b=a.xAxis,c=a.yAxis,d=a.chart.styledMode;a.points.forEach(function(g){var e=g.node,f=e.pointValues;e=e.visible;if(f&&e){e=f.height;var h=f.width,k=f.x,q=f.y,l=d?0:(a.pointAttribs(g)["stroke-width"]||0)%2/2;f=Math.round(b.toPixels(k,!0))-l;h=Math.round(b.toPixels(k+h,!0))-l;k=Math.round(c.toPixels(q,!0))-l;e=Math.round(c.toPixels(q+e,!0))-l;e={x:Math.min(f,h),y:Math.min(k,e),width:Math.abs(h-f),height:Math.abs(e-k)};g.plotX=e.x+e.width/2;g.plotY=e.y+e.height/2;g.shapeArgs=e}else delete g.plotX,
delete g.plotY})};b.prototype.setRootNode=function(a,b,c){a=J({newRootId:a,previousRootId:this.rootNode,redraw:x(b,!0),series:this},c);T(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})};b.prototype.setState=function(a){this.options.inactiveOtherPoints=!0;y.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1};b.prototype.setTreeValues=function(a){var b=this,c=b.options,d=b.nodeMap[b.rootNode];
c=k.isBoolean(c.levelIsConstant)?c.levelIsConstant:!0;var g=0,e=[],f=b.points[a.i];a.children.forEach(function(a){a=b.setTreeValues(a);e.push(a);a.ignore||(g+=a.val)});V(e,function(a,b){return(a.sortIndex||0)-(b.sortIndex||0)});var h=x(f&&f.options.value,g);f&&(f.value=h);J(a,{children:e,childrenTotal:g,ignore:!(x(f&&f.visible,!0)&&0<h),isLeaf:a.visible&&!g,levelDynamic:a.level-(c?0:d.level),name:x(f&&f.name,""),sortIndex:x(f&&f.sortIndex,-h),val:h});return a};b.prototype.sliceAndDice=function(a,
b){return this.algorithmFill(!0,a,b)};b.prototype.squarified=function(a,b){return this.algorithmLowAspectRatio(!0,a,b)};b.prototype.strip=function(a,b){return this.algorithmLowAspectRatio(!1,a,b)};b.prototype.stripes=function(a,b){return this.algorithmFill(!1,a,b)};b.prototype.translate=function(){var a=this,b=a.options,c=v(a);y.prototype.translate.call(a);var d=a.tree=a.getTree();var e=a.nodeMap[c];""===c||e&&e.children.length||(a.setRootNode("",!1),c=a.rootNode,e=a.nodeMap[c]);a.mapOptionsToLevel=
G({from:e.level+1,levels:b.levels,to:d.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});k.recursive(a.nodeMap[a.rootNode],function(b){var c=!1,d=b.parent;b.visible=!0;if(d||""===d)c=a.nodeMap[d];return c});k.recursive(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(d);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=c={x:0,y:0,
width:k.AXIS_MAX,height:k.AXIS_MAX};a.nodeMap[""].values=c=z(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:d.val});a.calculateChildrenAreas(d,c);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=e.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()};b.defaultOptions=z(E.defaultOptions,{allowTraversingTree:!1,animationLimit:250,
borderRadius:0,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return M(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",
borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",brightness:A?0:.1,halo:!1,opacity:.75,shadow:!1}}});return b}(E);J(p.prototype,{buildKDTree:a,colorAttribs:b.seriesMembers.colorAttribs,colorKey:"colorValue",directTouch:!0,drawLegendSymbol:h.drawRectangle,getExtremesFromAll:!0,getSymbol:a,optionalAxis:"colorAxis",parallelArrays:["x","y","value","colorValue"],pointArrayMap:["value"],pointClass:l,NodeClass:K,trackerGroups:["group","dataLabelsGroup"],utils:{recursive:k.recursive}});
b.compose(p);u.registerSeriesType("treemap",p);"";return p});c(a,"masters/modules/treemap.src.js",[a["Core/Globals.js"],a["Extensions/Breadcrumbs/Breadcrumbs.js"]],function(a,b){a.Breadcrumbs=b;b.compose(a.Chart,a.defaultOptions)})});
//# sourceMappingURL=treemap.js.map