/*
 Highcharts JS v11.1.0 (2023-10-12)

 X-range series

 (c) 2010-2021 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/xrange",["highcharts"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,b,v,c){a.hasOwnProperty(b)||(a[b]=c.apply(null,v),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:b,module:a[b]}})))}a=a?a._modules:
{};f(a,"Series/XRange/XRangeSeriesDefaults.js",[a["Core/Utilities.js"]],function(a){var b=a.correctFloat,q=a.isNumber,c=a.isObject;"";return{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;c(a)&&(a=a.amount);if(q(a)&&0<a)return b(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 0.8em">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},
borderRadius:3,pointRange:0}});f(a,"Series/XRange/XRangePoint.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,b){var q=this&&this.__extends||function(){function a(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,e){a.__proto__=e}||function(a,e){for(var c in e)Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])};return a(c,e)}return function(c,e){function b(){this.constructor=c}if("function"!==typeof e&&null!==e)throw new TypeError("Class extends value "+
String(e)+" is not a constructor or null");a(c,e);c.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),c=a.series.prototype.pointClass.prototype;b=b.extend;a=function(a){function b(){var e=null!==a&&a.apply(this,arguments)||this;e.options=void 0;e.series=void 0;return e}q(b,a);b.getColorByCategory=function(a,b){var e=a.options.colors||a.chart.options.colors;a=b.y%(e?e.length:a.chart.options.chart.colorCount);return{colorIndex:a,color:e&&e[a]}};b.prototype.resolveColor=function(){var a=
this.series;if(a.options.colorByPoint&&!this.options.color){var c=b.getColorByCategory(a,this);a.chart.styledMode||(this.color=c.color);this.options.colorIndex||(this.colorIndex=c.colorIndex)}else this.color||(this.color=a.color)};b.prototype.init=function(){c.init.apply(this,arguments);this.y||(this.y=0);return this};b.prototype.setState=function(){c.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())};b.prototype.getLabelConfig=function(){var a=c.getLabelConfig.call(this),
b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];a.key=this.category||this.name;return a};b.prototype.isValid=function(){return"number"===typeof this.x&&"number"===typeof this.x2};return b}(a.seriesTypes.column.prototype.pointClass);b(a.prototype,{ttBelow:!1,tooltipDateKeys:["x","x2"]});"";return a});f(a,"Series/XRange/XRangeSeries.js",[a["Core/Globals.js"],a["Core/Color/Color.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"],a["Series/XRange/XRangeSeriesDefaults.js"],
a["Series/XRange/XRangePoint.js"]],function(a,b,f,c,I,J){function e(){if(this.isXAxis){var a=w(this.dataMax,-Number.MAX_VALUE);for(var b=0,d=this.series;b<d.length;b++){var k=d[b];if(k.x2Data){var B=0;for(k=k.x2Data;B<k.length;B++){var c=k[B];if(c&&c>a){a=c;var K=!0}}}}K&&(this.dataMax=a)}}var q=this&&this.__extends||function(){function a(b,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,a){d.__proto__=a}||function(d,a){for(var k in a)Object.prototype.hasOwnProperty.call(a,
k)&&(d[k]=a[k])};return a(b,d)}return function(b,d){function k(){this.constructor=b}if("function"!==typeof d&&null!==d)throw new TypeError("Class extends value "+String(d)+" is not a constructor or null");a(b,d);b.prototype=null===d?Object.create(d):(k.prototype=d.prototype,new k)}}();a=a.noop;var E=b.parse,F=f.series.prototype,G=f.seriesTypes.column,v=c.addEvent,x=c.clamp,L=c.defined;b=c.extend;var H=c.find,A=c.isNumber,C=c.isObject,u=c.merge,w=c.pick,M=c.relativeLength,N=[],D=function(a){function b(){var d=
null!==a&&a.apply(this,arguments)||this;d.data=void 0;d.options=void 0;d.points=void 0;return d}q(b,a);b.compose=function(a){c.pushUnique(N,a)&&v(a,"afterGetSeriesExtremes",e)};b.prototype.init=function(){a.prototype.init.apply(this,arguments);this.options.stacking=void 0};b.prototype.getColumnMetrics=function(){function d(){for(var a=0,d=b.chart.series;a<d.length;a++){var k=d[a],c=k.xAxis;k.xAxis=k.yAxis;k.yAxis=c}}var b=this;d();var c=a.prototype.getColumnMetrics.call(this);d();return c};b.prototype.cropData=
function(a,b,c,e){b=F.cropData.call(this,this.x2Data,b,c,e);b.xData=a.slice(b.start,b.end);return b};b.prototype.findPointIndex=function(a){var d=this.cropStart,b=this.points,c=a.id;if(c)var e=(e=H(b,function(a){return a.id===c}))?e.index:void 0;"undefined"===typeof e&&(e=(e=H(b,function(d){return d.x===a.x&&d.x2===a.x2&&!d.touched}))?e.index:void 0);this.cropped&&A(e)&&A(d)&&e>=d&&(e-=d);return e};b.prototype.alignDataLabel=function(d){var b=d.plotX;d.plotX=w(d.dlBox&&d.dlBox.centerX,d.plotX);a.prototype.alignDataLabel.apply(this,
arguments);d.plotX=b};b.prototype.translatePoint=function(a){var b=this.xAxis,d=this.yAxis,c=this.columnMetrics,e=this.options,f=e.minPointLength||0,h=(a.shapeArgs&&a.shapeArgs.width||0)/2,p=this.pointXOffset=c.offset,n=w(a.x2,a.x+(a.len||0)),g=e.borderRadius,q=this.chart.plotTop,l=this.chart.plotLeft,m=a.plotX,r=b.translate(n,0,0,0,1);n=Math.abs(r-m);var y=this.chart.inverted,t=w(e.borderWidth,1)%2/2,v=c.offset,z=Math.round(c.width);f&&(f-=n,0>f&&(f=0),m-=f/2,r+=f/2);m=Math.max(m,-10);r=x(r,-10,
b.len+10);L(a.options.pointWidth)&&(v-=(Math.ceil(a.options.pointWidth)-z)/2,z=Math.ceil(a.options.pointWidth));e.pointPlacement&&A(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,e.pointPlacement));e=Math.floor(Math.min(m,r))+t;r=Math.floor(Math.max(m,r))+t-e;g=Math.min(M("object"===typeof g?g.radius:g||0,z),Math.min(r,z)/2);g={x:e,y:Math.floor(a.plotY+v)+t,width:r,height:z,r:g};a.shapeArgs=g;y?a.tooltipPos[1]+=p+h:a.tooltipPos[0]-=h+p-g.width/2;h=g.x;p=h+g.width;0>h||p>b.len?(h=x(h,0,b.len),
p=x(p,0,b.len),t=p-h,a.dlBox=u(g,{x:h,width:p-h,centerX:t?t/2:null})):a.dlBox=null;h=a.tooltipPos;p=y?1:0;t=y?0:1;c=this.columnMetrics?this.columnMetrics.offset:-c.width/2;h[p]=y?h[p]+g.width/2:x(h[p]+(b.reversed?-1:0)*g.width,b.left-l,b.left+b.len-l-1);h[t]=x(h[t]+(y?-1:1)*c,d.top-q,d.top+d.len-q-1);if(d=a.partialFill)C(d)&&(d=d.amount),A(d)||(d=0),a.partShapeArgs=u(g),m=Math.max(Math.round(n*d+a.plotX-m),0),a.clipRectArgs={x:b.reversed?g.x+n-m:g.x,y:g.y,width:m,height:g.height}};b.prototype.translate=
function(){a.prototype.translate.apply(this,arguments);for(var b=0,c=this.points;b<c.length;b++)this.translatePoint(c[b])};b.prototype.drawPoint=function(a,b){var d=this.options,c=this.chart.renderer,e=a.shapeType,k=a.shapeArgs,h=a.partShapeArgs,f=a.clipRectArgs,n=a.state,g=d.states[n||"normal"]||{},q="undefined"===typeof n?"attr":b;n=this.pointAttribs(a,n);g=w(this.chart.options.chart.animation,g.animation);var l=a.graphic,m=a.partialFill;if(a.isNull||!1===a.visible)l&&(a.graphic=l.destroy());else{if(l)l.rect[b](k);
else a.graphic=l=c.g("point").addClass(a.getClassName()).add(a.group||this.group),l.rect=c[e](u(k)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(l);h&&(l.partRect?(l.partRect[b](u(h)),l.partialClipRect[b](u(f))):(l.partialClipRect=c.clipRect(f.x,f.y,f.width,f.height),l.partRect=c[e](h).addClass("highcharts-partfill-overlay").add(l).clip(l.partialClipRect)));this.chart.styledMode||(l.rect[b](n,g).shadow(d.shadow),h&&(C(m)||(m={}),C(d.partialFill)&&(m=u(d.partialFill,m)),
a=m.fill||E(n.fill).brighten(-.3).get()||E(a.color||this.color).brighten(-.3).get(),n.fill=a,l.partRect[q](n,g).shadow(d.shadow)))}};b.prototype.drawPoints=function(){for(var a=this.getAnimationVerb(),b=0,c=this.points;b<c.length;b++)this.drawPoint(c[b],a)};b.prototype.getAnimationVerb=function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"};b.prototype.isPointInside=function(b){var c=b.shapeArgs,d=b.plotX,e=b.plotY;return c?"undefined"!==typeof d&&"undefined"!==
typeof e&&0<=e&&e<=this.yAxis.len&&0<=(c.x||0)+(c.width||0)&&d<=this.xAxis.len:a.prototype.isPointInside.apply(this,arguments)};b.defaultOptions=u(G.defaultOptions,I);return b}(G);b(D.prototype,{pointClass:J,pointArrayMap:["x2","y"],getExtremesFromAll:!0,parallelArrays:["x","x2","y"],requireSorting:!1,type:"xrange",animate:F.animate,autoIncrement:a,buildKDTree:a});f.registerSeriesType("xrange",D);return D});f(a,"masters/modules/xrange.src.js",[a["Core/Globals.js"],a["Series/XRange/XRangeSeries.js"]],
function(a,b){b.compose(a.Axis)})});
//# sourceMappingURL=xrange.js.map