/**
 * Highcharts JS v13.0.0 (2026-06-11)
 * @module highcharts/modules/bullet
 * @requires highcharts
 *
 * Bullet graph series type for Highcharts
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Kacper Madej
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */import*as t from"../highcharts.js";var e={};e.n=t=>{var r=t&&t.__esModule?()=>t.default:()=>t;return e.d(r,{a:r}),r},e.d=(t,r)=>{for(var a in r)e.o(r,a)&&!e.o(t,a)&&Object.defineProperty(t,a,{enumerable:!0,get:r[a]})},e.o=(t,e)=>Object.prototype.hasOwnProperty.call(t,e);let r=t.default;var a=e.n(r);let i=t.default.Series.types.column;var s=e.n(i);class o extends s().prototype.pointClass{destroy(){this.targetGraphic&&(this.targetGraphic=this.targetGraphic.destroy()),super.destroy.apply(this,arguments)}}let l=t.default.SeriesRegistry;var p=e.n(l);class n extends s(){drawPoints(){let t=this.chart,e=this.options,a=e.animationLimit||250;for(let i of(super.drawPoints.apply(this,arguments),this.points)){let s=i.options,o=i.target,l=i.y,p,n=i.targetGraphic,d,h,c,g;if((0,r.isNumber)(o)&&null!==o){h=(c=(0,r.merge)(e.targetOptions,s.targetOptions)).height;let u=i.shapeArgs;i.dlBox&&u&&!(0,r.isNumber)(u.width)&&(u=i.dlBox),d=(0,r.relativeLength)(c.width,u.width),g=this.yAxis.translate(o,!1,!0,!1,!0)-c.height/2-.5,p=this.crispCol.apply({chart:t,borderWidth:c.borderWidth,options:{crisp:e.crisp}},[u.x+u.width/2-d/2,g,d,h]),n?(n[t.pointCount<a?"animate":"attr"](p),(0,r.isNumber)(l)&&null!==l?n.element.point=i:n.element.point=void 0):i.targetGraphic=n=t.renderer.rect().attr(p).add(this.group),t.styledMode||n.attr({fill:(0,r.pick)(c.color,s.color,this.zones.length&&(i.getZone.call({series:this,x:i.x,y:o,options:{}}).color||this.color)||void 0,i.color,this.color),stroke:(0,r.pick)(c.borderColor,i.borderColor,this.options.borderColor),"stroke-width":c.borderWidth,r:c.borderRadius}),(0,r.isNumber)(l)&&null!==l&&(n.element.point=i),n.addClass(i.getClassName()+" highcharts-bullet-target",!0)}else n&&(i.targetGraphic=n.destroy())}}getExtremes(t){let e=super.getExtremes.call(this,t),a=this.targetData;if(a&&a.length){let t=super.getExtremes.call(this,a);(0,r.isNumber)(t.dataMin)&&(e.dataMin=Math.min((0,r.pick)(e.dataMin,1/0),t.dataMin)),(0,r.isNumber)(t.dataMax)&&(e.dataMax=Math.max((0,r.pick)(e.dataMax,-1/0),t.dataMax))}return e}}n.defaultOptions=(0,r.merge)(s().defaultOptions,{targetOptions:{width:"140%",height:3,borderWidth:0,borderRadius:0},tooltip:{pointFormat:'<span style="color:{series.color}">●</span> {series.name}: <b>{point.y}</b>. Target: <b>{point.target}</b><br/>'}}),(0,r.extend)(n.prototype,{parallelArrays:["x","y","target"],pointArrayMap:["y","target"]}),n.prototype.pointClass=o,p().registerSeriesType("bullet",n);let d=a();export{d as default};